- app/consumers/compliance_reports_consumer.rb
- app/services/safe_downloader.rb
- test/consumers/compliance_reports_consumer_test.rb
This commit sends a message back to the 'uploadvalidation' queue in
Insights. The message validates the payload whether the payload
contained a valid XCCDF Report or not.
Additionally I started storing reports in tmp/storage, as using a Ruby
Tempfile as it was doing before wasn't enough. The reason is that
Tempfiles get destroyed as soon as the garbage collector runs.
Therefore the timeline went like this:
1. Consumer creates Tempfile
2. Only the *path* is passed to ActiveJob.
3. Consumer exits. Tempfile gets thrashed
4. ActiveJob keeps on running, but the file has been destroyed
> Validate compliance reports

- Jenkinsfile
- openshift/Jenkins/Dockerfile
- openshift/Jenkins/slave_pod_template.yaml
Currently, each time when the unit tests run a preprovisioned db container is used. This PR adds the db container to the Jenkins slave pod. The slave and the db communicate with each other via unix socket.
> Jenkins slave pod should include the db container

- Gemfile
- Gemfile.lock
- app/controllers/profiles_controller.rb
- app/models/profile.rb
- app/serializers/profile_serializer.rb
This should allow API consumers, like the Dashboard, to request the top
X profiles in order of least compliant to most compliant.
E.g, to get the 3 least compliant hosts:
https://prod.foo.redhat.com:1337/r/insights/platform/compliance/profiles?per_page=3
should be enough
> Add pagination and sorting to Profile index

- app/models/user.rb
- test/models/user_test.rb
The username and the account are used to login, so the redhat_id field now is irrelevant basically. Some users are reporting problems when logging in for the first time, as currently you cannot create 2 accounts with redhat_id = null
> Remove redhat_id constraint as it was removed from header

- Gemfile.lock
- app/models/rule.rb
- app/models/schema.rb
- app/services/xccdf_report_parser.rb
- config/settings/development.yml
- test/services/xccdf_report_parser_test.rb
Before this commit, if you submitted a report containing rules which
were used in a profile before, the profile would be saved without adding
these rules to the profile, so in the UI the rules page would not show
any rules.
> Save old rules in new profiles

- app/consumers/compliance_reports_consumer.rb
- test/consumers/compliance_reports_consumer_test.rb
Before this commit, the tempfile would only be removed if the validation
succeeded and a job was enqueued.
> Remove tempfile when validation is 'failure'

- app/services/xccdf_report_parser.rb
- test/services/xccdf_report_parser_test.rb
This fixes a problem when you upload a report twice and get an error like `Consumer crashes with "ActiveRecord::RecordInvalid (Validation failed: Rule has already been taken)"`. 
It happened because the parser tried to assign a profile to a rule even if it already had that assignment. This PR ensures only the profiles that are new to each rule are assigned.
> Only new profiles are assigned to old rules

- openshift/templates/compliance-prometheus-exporter.yaml
These annotations allow platform's Prometheus to scrape our
prometheus_exporter service
> Add Prometheus scraper annotations

- Dockerfile
- docker-compose.yml
When I first implemented this, I didn't realize a few things:
- `:Z` vs. `:z` in volume mounts. The former sets SELinux context to only that single container; the latter sets the SELinux context to containers in general, allowing multiple containers to mount the same local directory (this is what we want for rails+racecar+prometheus)
- You can use `build` and `image` together in docker-compose.yml (as is done for the rails service in this PR) to build a named image which can then be used in other services in the same docker-compose.yml. This turns out to be really useful for services that require the ruby environment (i.e. `bundle exec ...`)
- The `expose` keyword in a Dockerfile is identical to the port definition in docker-compose.yml. We don't want to expose 3000 at the image level, as …
> Update docker files to use the rails image, add prometheus

- app/models/account.rb
- test/models/account_test.rb
This forces users without an Insights account number (e.g: someone who registers in redhat.com but does not have a subscription to see Insights) to logout - the frontend will get 401 and log out the user.
> Ensure account number exists

- openshift/templates/compliance-consumer.yaml
We run this on the compliance-backend which is deployed with the consumer, so there's no reason to run db:migrate twice (and it's failing for this deployment every time).
> Don't migrate the DB during consumer pre-hook

- app/consumers/compliance_reports_consumer.rb
- app/controllers/concerns/exception_notifier.rb
- app/jobs/parse_report_job.rb
- app/services/xccdf_report_parser.rb
- test/controllers/systems_controller_test.rb
- test/models/rule_test.rb
- test/services/xccdf_report_parser_test.rb
This allows us to have Sidekiq workers without sharing any volumes. The
report is send as a string over to Redis, serialized as an ActiveJob
job.
> Send report through ActionJob

- config/initializers/active_job_logger_patch.rb
Writing the report contents and b64 identity of the job clutters the logs for Sidekiq
> Remove b64 identity and report content from ActiveJob logs

- app/controllers/concerns/authentication.rb
If there are missing fields, we end up calling `:[]` on `nil`. Catching
NoMethodError allows us to display a more helpful error to users
> Handle malformed auth tokens

- Gemfile
- Gemfile.lock
This is just for development purposes. Pry in the rails console is much nicer IMO:
Vanilla IRB:
```rb
irb(main):004:0> Profile.first
Profile Load (2.0ms)  SELECT  "profiles".* FROM "profiles" ORDER BY "profiles"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> #<Profile id: "85356ce8-9a07-4dae-aead-173ba4b86660", name: "Standard System Security Profile for Red Hat Enter...", ref_id: "standard", policy_id: nil, created_at: "2019-03-04 14:16:48", updated_at: "2019-03-04 14:16:48", description: "This guide presents a catalog of security-relevant...", account_id: "8e3411a6-7a9a-4456-8a2e-b9a066ecf96a", slug: "standard">
```
With pry
```rb
[4] pry(main)> Profile.first
Profile Load (1.7ms)  SELECT  "profiles".* FROM "profiles" ORDER BY "profiles"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> …
```
> Add pry-rails for pry in the rails console

- openshift/templates/compliance-backend.yml
- openshift/templates/compliance-consumer.yaml
- openshift/templates/compliance-prometheus-exporter.yaml
- openshift/templates/compliance-sidekiq.yaml
This PR adds new label `app` with the name of the deployment config. It's required for test automation.
> Added a new label for pods

- app/services/host_inventory_api.rb
- test/services/host_inventory_api_test.rb
@dLobatog The sidekiq ParseReportJob was failing for me. It seems the response and request format has changed. Now it seems we have the ability to send and receive multiple hosts at a time.
> Update host inventory response, add tests

- docker-compose.yml
- entrypoint.sh
`db:setup` re-creates the database, dropping all tables. This isn't what we want for development use.
> Don't setup the db on every entry. Add tty for debugging

- Gemfile
- Gemfile.lock
- app/jobs/parse_report_job.rb
- app/services/concerns/xccdf_report/profiles.rb
- app/services/concerns/xccdf_report/rules.rb
- app/services/xccdf_report_parser.rb
- test/models/rule_test.rb
- test/services/concerns/xccdf_report/rules_test.rb
- test/services/xccdf_report_parser_test.rb
** WIP **
This brings the parsing and importing of rules and rule_results down to only a few queries:
1 SELECT  * FROM hosts WHERE id == report host 
1 SELECT * FROM rules WHERE rules.ref_id IN (list of ref ids from report)  
1 INSERT INTO RULES (all rules)
1 INSERT INTO RULE_RESULTS (all rule results)
In practice this brings down the parsing to around 1s for a normal report, which should hopefully lower our sidekiq load.
> Import rules and rule results in bulk

- config/environments/development.rb
@dLobatog does this break `https://ci.foo.redhat.com:1337/api/compliance/graphiql` for you?
> Set asset prefix in devel to /api/compliance/assets

- app/services/concerns/xccdf_report/rules.rb
On my laptop in development; The following tests are starting with an empty compliance DB (system doesn't exist). The second `ParseReportJob` is only adding `RuleResult` objects, not adding a new system:
Before:
```
sidekiq_1     | 2019-03-25T15:02:48.118Z 1 TID-gni3gspll ParseReportJob JID-5663a4a771325a343c025fb6 INFO: start
sidekiq_1     | 2019-03-25T15:03:16.839Z 1 TID-gni3gspll ParseReportJob JID-5663a4a771325a343c025fb6 INFO: done: 28.721 sec
sidekiq_1     | 2019-03-25T15:03:28.610Z 1 TID-gni3gspv1 ParseReportJob JID-d0f323e7ffd503b262b524f5 INFO: start
sidekiq_1     | 2019-03-25T15:03:30.754Z 1 TID-gni3gspv1 ParseReportJob JID-d0f323e7ffd503b262b524f5 INFO: done: 2.144 sec
```
After:
```
sidekiq_1     | 2019-03-25T15:01:21.677Z 1 TID-gpkug1hyh ParseReportJob …
```
> Improve import performance

- app/models/schema.rb
This allows us to retrieve the profile on the frontend for each rule. This is needed to construct the query for Remediations, which looks like this:
ssg:rhel7|standard|xccdf_org.ssgproject.content_rule_service_autofs_disabled - where `standard` is the profile for the rule with ref_id `xccdf_org....`
> Add profiles to rules response in GraphQL

- app/controllers/systems_controller.rb
- app/policies/host_policy.rb
- config/routes.rb
- test/controllers/systems_controller_test.rb
Call the API using `DELETE /systems/host-id-in-the-inventory`. It only allows to remove hosts within your account scope.
> Basic API to remove hosts

- app/jobs/parse_report_job.rb
- app/services/host_inventory_api.rb
- app/services/xccdf_report_parser.rb
- test/services/host_inventory_api_test.rb
- test/services/xccdf_report_parser_test.rb
- test/test_helper.rb
This should help with tracking down inventory API related outages/errors.
> Raise errors in sidekiq logs. Use db transactions

- app/services/host_inventory_api.rb
https://github.com/RedHatInsights/compliance-backend/pull/100 causes a bug which, on compliance report upload, the profile and rules get saved, but the Host and RuleResults don't get saved.
> Always save the host, even if it exists in the inventory

- app/services/host_inventory_api.rb
- test/services/host_inventory_api_test.rb
Hopefully this will fix the issues we've been seeing in the compliance systems table
> Always assign inventory ID to a new compliance DB host

- app/jobs/parse_report_job.rb
- app/models/host.rb
- app/services/concerns/xccdf_report/rules.rb
- app/services/concerns/xccdf_report/xml_report.rb
- app/services/xccdf_report_parser.rb
- test/services/concerns/xccdf_report/xml_report_test.rb
- test/services/xccdf_report_parser_test.rb
1. Running GC collection as soon as the job finishes. 
2. Storing the file in memory. This saves us I/O as we have to store a file in the filesystem, then read from it (Nokogiri), etc. Now `OpenScap::Source` is created from the report string, and so is Nokogiri. 
3. Using _ids rather than objects wherever possible, creating object with `host_id`, selecting only `id` form the tables.
4. In `add_profiles_to_old_rules`, I prefetch all profiles now so we can check if `rules` are in those profiles instead of fetching them for every row.
Some positive benchmarks - performance wise, the improvement is around 28%, from 1.1s on average (10 runs) to 0.72s on my computer. 
Memory wise - using memory_profiler, we create this many objects:
https://gist.github.com/dLobatog/aa20068c6dd784ea992edb35ef3b1e …
> Various performance improvements for report parsing job

- Gemfile
- Gemfile.lock
- config/initializers/sidekiq.rb
https://gitlab.com/gitlab-org/sidekiq-reliable-fetch/tree/master
I tested this strategy the following way:
```ruby
class LongRunningJob
include Sidekiq::Worker
def perform
puts('hello')
sleep 60
puts('bye')
end
end
```
Then I decided to run a job, and kill sidekiq in the middle of the `sleep`:
```
2019-04-16T07:25:42.369Z 24215 TID-gspbbki7z LongRunningJob JID-1d2eb707667a6b9e6bb31534 INFO: start
hello
^C <- SIGINT SENT
2019-04-16T07:25:45.658Z 24215 TID-gspa9msmv INFO: Shutting down
2019-04-16T07:25:45.659Z 24215 TID-gspa9msmv INFO: Terminating quiet workers
2019-04-16T07:25:45.659Z 24215 TID-gspbbknyj INFO: Scheduler exiting...
2019-04-16T07:25:45.760Z 24215 TID-gspa9msmv INFO: Pausing to allow workers to finish...
2019-04-16T07:25:53.574Z 24215 TID-gspa9msmv WARN: Terminating 1 busy …
```
> Use Sidekiq reliable fetch strategy

- app/consumers/compliance_reports_consumer.rb
- app/jobs/parse_report_job.rb
This brings the data sent over to redis and back for an example report from 2019977 bytes to 221365 bytes, one order of magnitude less. The compression/decompression speed penalty is negligible.
> Zlib (de)compress the report string

- app/consumers/compliance_reports_consumer.rb
- app/models/profile.rb
- app/models/rule.rb
- app/services/concerns/xccdf_report/profiles.rb
- app/services/image_scanner.rb
- app/services/safe_downloader.rb
- app/services/xccdf_report_parser.rb
- config/environments/test.rb
- test/controllers/concerns/metadata_test.rb
- test/policies/account_policy_test.rb
Before: 
https://gist.github.com/dLobatog/0578f5bacc66f869a871757309a9a763
https://gist.github.com/dLobatog/c3b65aa9ea4f4f81356c5ecac9846cc7
After:
https://gist.github.com/dLobatog/3274a5854dcb43682a22b51404d427d9
https://gist.github.com/dLobatog/289d5b7f12a2728d2a4e045858a8fd65
It basically turns requests that take seconds into requests that take <100ms. The difference is very noticeable. It should also alleviate the load on our web backend pods.
> Use Rails.cache for compliance results queries

- app/models/profile.rb
- app/models/rule.rb
- app/models/schema.rb
- app/serializers/rule_result_serializer.rb
- app/services/image_scanner.rb
- app/services/xccdf_report_parser.rb
- codecov.yml
- db/migrate/20190422190831_add_time_to_rule_results.rb
- test/fixtures/rule_results.yml
- test/models/profile_test.rb
- test/models/rule_test.rb
- test/services/xccdf_report_parser_test.rb
- test/test_helper.rb
- Adds the start/end time to RuleResult
- Parses start/end time from TestResult xccdf report
- Updates graphql queries to use end_time as the date of last scan
Issues:
There is currently no time zone info in the report. It appears to be the local time zone of the machine on which it was run. Perhaps we could get this from metadata? For now though, I think this is a huge improvement. You can upload a report generated yesterday, and that time difference is reflected in the DB and UI.
> Use time from xccdf report, not created_at for RuleResult

- Gemfile
- Gemfile.lock
- app/jobs/parse_report_job.rb
In my local tests, report parsing grows the memory, and this will make the memory usage go back down, since it doesn't automatically.
> Call trim after GC.start

- app/models/rule.rb
- app/services/concerns/xccdf_report/rules.rb
- app/services/xccdf_report_parser.rb
- test/services/csv_exporter_test.rb
- test/services/xccdf_report_parser_test.rb
delete! returns nil if the substring isn't found. delete always returns
the string, regardless of if the substring is found and deleted
> Use delete instead of delete! in case \n isn't found

- app/services/host_inventory_api.rb
Before: `https://ci.cloud.paas.upshift.redhat.com//api/inventory/v1/hosts`
After: `https://ci.cloud.paas.upshift.redhat.com/api/inventory/v1/hosts`
The one with two slashes returns a 404.
> Remove double slash from inventory URI

- test/controllers/concerns/authentication_test.rb
To reliably reproduce the test failure, run tests with seed 29935. This PR fixes that failure.
> Ensure User.current is nil before tests, not after

- app/models/schema.rb
Using `find` will throw an exception and make GraphQL return a 404 automatically if you don't pass a profile_id argument to the fields changed here. We just want that to be `nil` so that we find `rules_passed` and `failed` for all profiles.
> Return nil when profile not found in GraphQL

- app/models/schema.rb
While we have DB validations for `presence: true` on description, we have some old `Rule` objects in the prod DB that do have nil descriptions. This should fix the graphql response for that case.
> Allow nil Rule description in graphql

- Gemfile
- app/jobs/parse_report_job.rb
These calls are not necessary since we stopped using the openscap
library to parse reports (it has a memory leak)
> Remove GC and MallocTrim

- config/initializers/sidekiq.rb
This would leave the following setup:
* Sidekiq runs client/server (it enqueues jobs and it's sidekiq itself, so server must be enabled)
* Racecar runs client (it must enqueue jobs)
* Puma and Prometheus do NOT run neither client nor server (they don't enqueue jobs)
This means on all of the apps but Sidekiq should be saving some MBs as one of the dependencies will not even be initialized. 
Notice sidekiq client is not enabled in the consumer at the moment, which makes jobs fail to enqueue there in CI.
> Enable Sidekiq client on racecar

- app/models/schema.rb
Searching and returning the rules in bulk vs using `map` seems to return dramatically better results. Before, I could click on "Remediate with Ansible" and get a 503 because the response might take 100s. This takes around 1s for the same operation.
> Return faster rule objects failed

- config/initializers/sidekiq.rb
This is to (potentially) fix the horizontal pod autoscaler issue that metrics cannot be found.
> Add rails to the sidekiq initializer

- Dockerfile
- docker-compose.yml
add prometheus port and sidekiq env variables in docker-compose
The `MALLOC_ARENA_MAX` env variable helps keep the dev environment resources low.
The exposed prometheus port allows looking at the local exporter at `http://localhost:9394/metrics`.
The Dockerfile changes enable the ability to only install gems (not packages) when building the image with updated Gemfile[.lock].
This PR does not affect production (only docker-compose development).
> Update Dockerfile for more incremental builds

- config/initializers/sidekiq.rb
This reverts commit 96037c0d7900825cbbd7d65412bb8c23d4e23be0.
Trying to reproduce the issue in https://github.com/RedHatInsights/compliance-backend/pull/144 on CI. I tried scaling prometheus exporter to 0 pods, and the cpu metric was still available on compliance-backend, so this change really shouldn't affect the metrics API.
> Revert "Add rails to the sidekiq initializer (#144)"

- app/consumers/compliance_reports_consumer.rb
- test/consumers/compliance_reports_consumer_test.rb
As per https://projects.engineering.redhat.com/browse/RHCLOUD-516 - for now both will be supported by payload_id will be removed
> Rename payload_id to request_id

- app/models/host.rb
- test/models/host_test.rb
We should allow duplicate named hosts in our DB as well. If we don't, we
could find a host by ID in the inventory but fail to create it in our DB
because the host name already exists in our DB with a different ID.
> Host names are not unique in the inventory, even by account

- app/models/profile.rb
- test/models/profile_test.rb
- test/services/xccdf_report_parser_test.rb
This is important for the dashboard, as it's making a request to api/profiles, which returns all profiles with scores - the score displayed is an integer even if you see 1 out of 2 hosts compliant, the only options are 0 or 1. It should display 0.5 in that case.
> Profile score should return a float

- app/consumers/compliance_reports_consumer.rb
- test/consumers/compliance_reports_consumer_test.rb
We want to be backwards compatible here because messages can hang around after new code is deployed.
Related to https://github.com/RedHatInsights/compliance-backend/pull/147
> Allow payload_id or request_id as the message ID

- db/migrate/20190531075839_remove_account_id_from_account.rb
The account_id (not the ID) field from the accounts table is empty and unused in the app. It can be safely removed. From prod:
```
irb(main):009:0> Account.all.map(&:account_id).uniq
=> [nil]
```
> RHICOMPL-193 - Remove account_id from account

- app/jobs/delete_host.rb
- openshift/templates/compliance-inventory-events-consumer.yaml
Currently the job that's deleting hosts once we see the event coming from the inventory is not checking whether the Host ID is in the compliance DB. This throws an exception and causes the job to retry 3 times and prints the stacktrace to the logs.
We can avoid it by just rescuing for ActiveRecord::RecordNotFound:
> RHICOMPL-195 - Check host presence before deletion

- test/consumers/compliance_reports_consumer_test.rb
Related to https://github.com/RedHatInsights/compliance-backend/pull/158
> Test report consumer with request_id and payload_id

- app/controllers/application_controller.rb
- app/controllers/concerns/exception_notifier_custom_data.rb
- test/controllers/concerns/exception_notifier_custom_data_test.rb
We were overwriting the `ExceptionNotifier` constant, defined in [the gem](https://github.com/smartinez87/exception_notification/blob/master/lib/exception_notifier.rb#L7). Maybe this will start notifying us via Slack.
This should also finally close https://projects.engineering.redhat.com/browse/RHICOMPL-21
> Fix and add tests for exception_notifier

- app/models/rule.rb
- app/models/rule_identifier.rb
- app/models/rule_reference.rb
- app/models/rule_references_rule.rb
- app/services/concerns/xccdf_report/rules.rb
- app/services/xccdf_report_parser.rb
- db/migrate/20190517153452_create_rule_references.rb
- db/migrate/20190517153913_create_join_table_rule_reference_rules.rb
- db/migrate/20190524170042_create_rule_identifier_table.rb
- test/services/xccdf_report_parser_test.rb
Towards Aha! COMP-E-99
WIP for:
- More tests
Preliminary performance impact (tested locally with docker-compose):
Before:
```
ParseReportJob JID-1e96bb7b4f72c413dfd91b50 INFO: start
ParseReportJob JID-1e96bb7b4f72c413dfd91b50 INFO: done: 8.186 sec
ParseReportJob JID-72b589705281a3ea232e6fdd INFO: start
ParseReportJob JID-72b589705281a3ea232e6fdd INFO: done: 2.302 sec
ParseReportJob JID-6f71131a8caf4540eee9e718 INFO: start
ParseReportJob JID-6f71131a8caf4540eee9e718 INFO: done: 2.493 sec
ParseReportJob JID-fa8f9b509a16410a4185b4c5 INFO: start
ParseReportJob JID-fa8f9b509a16410a4185b4c5 INFO: done: 2.118 sec
ParseReportJob JID-4a0d0780019476f8974c2e81 INFO: start
ParseReportJob JID-4a0d0780019476f8974c2e81 INFO: done: 2.476 sec
```
After:
```
ParseReportJob JID-1a814121e1c07d9981c1b04f …
```
> Parse rule identifiers and references from report XML

- app/consumers/compliance_reports_consumer.rb
- app/services/safe_downloader.rb
- test/consumers/compliance_reports_consumer_test.rb
- test/services/safe_downloader_test.rb
Before, it seems that we were only deleting the file when the validation failed.
It should not be necessary to do this, because we use `Tempfile` in `SafeDownloader`. That should remove the file automatically once it's no longer used in the ruby process memory context. According to our reports from QE it's not, so this is a way of covering our backs and delete it for sure after `process`
> RHICOMPL-186 - Stream the report instead of writing to tempfile

- app/services/safe_downloader.rb
- test/services/safe_downloader_test.rb
If the file download fails because the file is empty, the message will
be pushed back to kafka and we will consume it endlessly, effectively
turning one of the 2 consumers idle. Instead we should just rescue that
case and invalidate that payload.
> Rescue SafeDownloader when downloaded file is empty

- app/controllers/concerns/metadata.rb
- app/controllers/concerns/search.rb
- app/controllers/profiles_controller.rb
- app/controllers/rule_results_controller.rb
- app/controllers/rules_controller.rb
- app/controllers/systems_controller.rb
- app/policies/rule_result_policy.rb
- test/controllers/concerns/metadata_test.rb
This PR fixes the policy method to retrieve rule_results on
api/compliance/rule_results. Before this PR, the policy
was iterating on all of the rule_results, which was incredibly
slow.
Aside from that, output was not paginated unless 'search' was
passed. Fixing the pagination forced me to change other controllers to
match it, as a side effect all other endpoints pagination are
now fixed.
> RHICOMPL-178 - Optimize Rule results policy fetching

- app/controllers/concerns/metadata.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-213
> Fixes RHICOMPL-213: Use controller name in meta links

- app/services/safe_downloader.rb
- test/services/safe_downloader_test.rb
`URI(...).read` returns a `StringIO` for files < 10Kb and a Tempfile otherwise. We need to handle the `StringIO` case.
> Handle small report uploads which return StringIO

- app/graphql/schema.rb
This allows easier debugging while writing tests, as it disables prometheus error messages like this:
```
Prometheus Exporter, failed to send message Connection refused - connect(2) for "localhost" port 9394
Prometheus Exporter, failed to send message Connection refused - connect(2) for "localhost" port 9394
Prometheus Exporter, failed to send message Connection refused - connect(2) for "localhost" port 9394
Prometheus Exporter, failed to send message Connection refused - connect(2) for "localhost" port 9394
```
> Disable prometheus exporter in test environment

- app/services/xccdf_report_parser.rb
- test/services/xccdf_report_parser_test.rb
The existing `zip` implementation pairs xml rule_results with database RuleResult objects in undefined order. This implementation creates a hash of database RuleResults by `{<ref_id> => <id>}` and uses xml rule_results.id to index into the hash.
This new implementation should not significantly increase runtime of a parse (locally measured: 23.638 sec initial, ~ 1.685 sec subsequent).
> Ensure rule results are associated by ref_id to rules

- Gemfile
- lib/tasks/test.rake
- test/test_helper.rb
- Moved rubocop to the dev, test group in the gemfile instead of just development.
- Don't require rubocop or create a rake task for it unless dev/test
> Only use rubocop in test/dev env

- app/models/rule_reference.rb
It's hard to imagine we'd ever want to sort by `id` or `href`.
```rb
RuleReference(id: uuid, href: string, label: string)
```
> Sort rule references by label by default

- app/models/profile.rb
- test/models/profile_test.rb
We `find_or_initialize_by` `ref_id`, `name`, and `account_id` in the
[`XCCDFReport::Profiles`](https://github.com/RedHatInsights/compliance-backend/blob/master/app/services/concerns/xccdf_report/profiles.rb#L15) module, so profiles should be unique by those
three attributes.
Easy way to test: upload the standard profile for RHEL7 (`ref_id=xccdf_org.ssgproject.content_profile_standard`) and then another for RHEL8 (`ref_id=xccdf_org.ssgproject.content_profile_standard`). The only difference is the name (i.e. "Standard System Security Profile for Red Hat Enterprise Linux 7").
> Include name in profile uniqueness scope

- app/services/concerns/xccdf_report/rules.rb
- test/services/concerns/xccdf_report/rules_test.rb
- test/services/xccdf_report_parser_test.rb
Without the relevant code change, the test fails:
```
ERROR["test_only_new_rule_references_are_saved", #<Minitest::Reporters::Suite:0x000055d2bc8ac048 @name="RulesTest">, 1.3665143339894712]
test_only_new_rule_references_are_saved#RulesTest (1.37s)
ActiveRecord::NotNullViolation:         ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, , bar).
: INSERT INTO "rule_references" ("id","href","label") VALUES ('18c74014-06a4-496f-a1f6-63092788d2b5','','foo'),(NULL,'','bar') ON CONFLICT DO NOTHING  RETURNING "id"
app/services/concerns/xccdf_report/rules.rb:48:in `save_rule_references'
test/services/concerns/xccdf_report/rules_test.rb:60:in `block (2 levels) in <class:RulesTest>' …
```
> Fixes 264: Only import new rule references

- app/models/rule_reference.rb
- app/services/concerns/xccdf_report/profiles.rb
- app/services/concerns/xccdf_report/rule_references.rb
- app/services/concerns/xccdf_report/rules.rb
- app/services/xccdf_report_parser.rb
- test/services/concerns/xccdf_report/profiles_test.rb
- test/services/concerns/xccdf_report/rule_references_test.rb
- test/services/concerns/xccdf_report/rules_test.rb
This is almost all refactoring. The only functionality change should be that saving a profile raises an exception if saving fails for some reason (i.e. model validation failure).
Built on top of https://github.com/RedHatInsights/compliance-backend/pull/195
> Refactor xccdf, pull out rule_references

- app/services/concerns/xccdf_report/rule_references.rb
- app/services/concerns/xccdf_report/rules.rb
This changes from <# of new rules> updates for rule references to 1 update. It shaves about 13 seconds off the initial import, from ~85 seconds to ~72 seconds.
> Reduce SQL statements in associate_rule_references

- app/graphql/types/base_object.rb
- app/graphql/types/profile.rb
The following is the system details graphql query with the standard RHEL7 profile for this system:
Before: 
```
Completed 200 OK in 24344ms (Views: 302.9ms | ActiveRecord: 2026.4ms)
user: root
POST /api/compliance/graphql
USE eager loading detected
Rule => [:rule_identifier]
Add to your finder: :includes => [:rule_identifier]
Call stack
/app/app/controllers/graphql_controller.rb:8:in `query'
user: root
POST /api/compliance/graphql
USE eager loading detected
Rule => [:rule_references_rules]
Add to your finder: :includes => [:rule_references_rules]
Call stack
/app/app/controllers/graphql_controller.rb:8:in `query'
user: root
POST /api/compliance/graphql
USE eager loading detected
Rule => [:rule_references]
Add to your finder: :includes => [:rule_references]
Call stack …
```
> Fixes 323: Include associations in graphql query

- docker-compose.yml
This change fixes the following errors in devel:
```
Attaching to compliance-backend_prometheus_1
prometheus_1        | failed to register metric {"type"=>"graphql", "duration"=>5.679999594576657e-05, "platform_key"=>"__Schema.queryType", "key"=>"execute_field"}
prometheus_1        | failed to register metric {"type"=>"graphql", "duration"=>2.43279937421903e-05, "platform_key"=>"__Field.type", "key"=>"execute_field"}
prometheus_1        | failed to register metric {"type"=>"graphql", "duration"=>2.346000110264868e-05, "platform_key"=>"__Type.ofType", "key"=>"execute_field"}
prometheus_1        | failed to register metric {"type"=>"graphql", "duration"=>5.343199882190675e-05, "platform_key"=>"__Field.args", "key"=>"execute_field"}
prometheus_1        | failed to register metric …
```
> Use type collector not collector with prometheus

- app/controllers/profiles_controller.rb
- app/models/profile.rb
- db/migrate/20190829162229_remove_slug_from_profiles.rb
Profile ref_id is not globally unique. Profiles are unique by ref_id,
account_id, and name, but that doesn't work well for a friendly ID.
https://projects.engineering.redhat.com/browse/RHICOMPL-236
> Fixes #236: Remove slug/friendly_id from profiles

- app/graphql/types/profile.rb
After merging #210, I noticed the following:
```
user: root
POST /api/compliance/graphql
AVOID eager loading detected
Rule => [:rule_results]
Remove from your finder: :includes => [:rule_results]
Call stack
```
It seems we used one too many includes!
> Remove unnecessary includes in graphql

- app/graphql/types/profile.rb
- app/graphql/types/rule.rb
- app/graphql/types/system.rb
From the system details graphql request:
Before:
```
Completed 200 OK in 20178ms (Views: 281.5ms | ActiveRecord: 909.9ms)
```
After:
```
Completed 200 OK in 12679ms (Views: 320.2ms | ActiveRecord: 2061.4ms)
```
At this point, I think the bulk of the time is spent creating/serializing objects rather than SQL execution. This PR trades higher SQL time for creating less objects (essentially via `pluck`). It is about a 7 second improvement in response time, but we're still at around 13 seconds total for this response. :man_shrugging: 
> Do not instantiate unnecessary objects in graphql

- config/database.yml
- docker-compose.yml
- Update docker-compose with the environment variable
I've been getting these kinds of messages with the commented version of the database.yml in master: 
```
ActiveRecord::EnvironmentMismatchError: You are attempting to modify a database that was last run in `test` environment.                                                                                           
You are running in `development` environment. If you are sure you want to continue, first set the environment using:                                                                                               
bin/rails db:environment:set RAILS_ENV=development
```
This allows passing another environment variable to specify a separate test database, but it is not required.
> Allow an environment variable for the test DB

- config/sidekiq.yml
- docker-compose.yml
Fixes the following issue:
```
WARN: ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.002 seconds); all pooled connections were in use
```
The default is 10, which I've kept if no environment variable is set, or the max database connections if that's set. Alternatively, you may specify an environment variable separate from the database variable if you so desire.
I noticed there is a mismatch in both CI and production between the max DB connections and the number of sidekiq threads. This PR should also fix the issue in both without updating the deployment config. It should also help sidekiq scale better to more pods.
Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-337
Signed-off-by: Andrew Kofink …
> Add a concurrency variable for Sidekiq

- app/graphql/types/profile.rb
- app/graphql/types/system.rb
- app/models/profile.rb
- app/models/rule.rb
- app/models/rule_result.rb
- test/graphql/queries/rule_query_test.rb
- test/models/profile_test.rb
Moved from https://github.com/RedHatInsights/compliance-backend/pull/225 
- This version does not rely on default_scope
- It should be followed by a PR that stops parsing irrelevant results (notselected)
- The response time is considerably faster as we cut down results by 90%
> RHICOMPL-216 - Show only pass/fail results

- Jenkinsfile
Reverting back changes from #224 as of RedHatInsights/insights-pipeline-lib#43  'cancelPriorBuilds' can be called more than once.
> INSIGHTSQA-1564 - Uncomment cancelPriorBuilds call

- docker-compose.yml
/tmp might get wiped unexpectedly.
> Changing postgres db volume to use rails tmp instead of systems

- lib/tasks/import_remediations.rake
```
$ bundle exec rake import_remediations JOBS_ACCOUNT_NUMBER=1212
Starting import_remediations job at 2019-09-19 18:22:56 UTC
rake aborted!
NoMethodError: undefined method `fake_identity_header' for nil:NilClass
/app/app/services/remediations_api.rb:8:in `initialize'
/app/lib/tasks/import_remediations.rake:17:in `new'
/app/lib/tasks/import_remediations.rake:17:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => import_remediations
(See full trace by running task with --trace)
$ bundle exec rake import_remediations JOBS_ACCOUNT_NUMBER=1212
Starting import_remediations job at 2019-09-19 18:26:02 UTC
rake aborted!
ActiveRecord::RecordNotFound: …
```
> Fail for missing Account in import_remediations

- app/graphql/schema.rb
Fixes the following issue after hot-reloading:
```
Completed 500 Internal Server Error in 110ms (ActiveRecord: 15.4ms)
NameError (uninitialized constant Schema::Types):
app/graphql/schema.rb:12:in `<class:Schema>'
app/graphql/schema.rb:9:in `<top (required)>'
app/controllers/graphql_controller.rb:8:in `query'
```
> Require query, mutation in graphql schema

- app/serializers/rule_serializer.rb
Currently the API is taking very long to return the number of hosts that
are compliant or not with each rule. This info is not directly relevant
to our main consumer of the Rules API.
In fact, that info is taking a long time to compute, we've seen
responses of 15s+ timing out. This causes problems in the Remediations
app, which relies on this API to show the rules.
I advocate for just removing this info and the response becomes just as
simple as
1. Checking the user is registered and has a policy with the rule
2. Returning the rule
On average this is taking 60ms total.
> RHICOMPL-397 - Remove systems count from rules API

- app/models/concerns/openscap_parser_derived.rb
- app/models/rule.rb
- app/models/rule_identifier.rb
- app/services/concerns/xccdf/rule_identifiers.rb
- app/services/concerns/xccdf/rule_references.rb
- app/services/concerns/xccdf/rules.rb
- app/services/concerns/xccdf/util.rb
- test/models/rule_identifier_test.rb
- test/services/concerns/xccdf/rule_identifiers_test.rb
No rule identifiers were being parsed. This now adds rule identifier parsing from benchmark files and results files.
> Parse rule identifiers

- app/graphql/connections/base_connection.rb
- app/graphql/resolvers/base_resolver.rb
- app/graphql/resolvers/concerns/collection.rb
- app/graphql/resolvers/concerns/record.rb
- app/graphql/resolvers/generic.rb
- app/graphql/schema.graphql
- app/graphql/types/base_object.rb
- app/graphql/types/profile.rb
- app/graphql/types/query.rb
- app/graphql/types/system.rb
- test/graphql/queries/system_query_test.rb
This allows to query connections so that:
```
{
systems(first: 10, after: "MQ", search: "example") {
totalCount
pageInfo {
startCursor
endCursor
hasNextPage
hasPreviousPage
},
edges {
cursor
node {
id
name
}
}
}
}
```
```
{
"data": {
"systems": {
"totalCount": 200,
"pageInfo": {
"startCursor": "Mg",
"endCursor": "MTE",
"hasNextPage": true,
"hasPreviousPage": false
},
"edges": [
{
"cursor": "Mg",
"node": {
"id": "QmFzZU9iamVjdC0wM2YwYTlhNS1jN2U2LTRhZTItOTIyYS00ZWNkMTE5ZmY3NmU=",
"name": "example-1"
}
},
{
"cursor": "Mw",
"node": {
"id": "QmFzZU9iamVjdC0xOWI0NDk0ZS1jYWQxLTQ1NDEtYmQ4ZS0yMzIyOGU1YWU3NGM=",
"name": "example-2"
}
},
{
"cursor": "NA",
"node": {
"id": "QmFzZU9iamVjdC0zMjE3OWFmOS03NmEwLTRjZmQtOTJjZC0wM2Y5ODZmYjE0OGM=",
"name": "example-3"
}
},
{
"cursor": "NQ",
"node": {
"id": …
```
> Relay GraphQL (pagination)

- db/migrate/20191017185340_add_unique_constraint_to_profile_by_account.rb
- test/services/xccdf_report_migration_test.rb
Currently if many threads start to upload reports with the same profile
for the first time to an account, it could happen that 6 sidekiq pods
(at the moment these are 6 threads but it could change) start processing
the report at the same time.
Since all data is saved on the database at once, the Rails uniqueness
constraints may NOT apply in this case of concurrent parsing. It will
end with multiple profiles with the same ref_id, name and account_id
which is not what is expected.
This PR introduces a DB constraint so that when this happens, only 1 of
the jobs will actually save the profile, the first one to finish
parsing. The rest of them will likely fail - which is EXPECTED. As the
job is going to retry 3 times, it will retry the parsing and the 2nd
time `Profile.find_or_initialize` will …
> RHICOMPL-363 - Make uniqueness constraint for profile account_id and name

- app/services/concerns/xccdf/rule_results.rb
Fixes this kind of warning message:
```
ArgumentError: A copy of Xccdf::RuleResults has been removed from the module tree but is still active!
```
> Use fully qualified model names in xccdf concerns

- app/models/profile.rb
- app/services/concerns/xccdf/benchmarks.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/concerns/xccdf/rule_results.rb
- app/services/concerns/xccdf/util.rb
- test/services/concerns/xccdf/benchmarks_test.rb
- test/services/xccdf_report_parser_test.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-412
Initial and subsequent parse of RHEL 7 standard profile:
```
2019-11-21T17:03:05.957Z 1 TID-gni5eoqyl ParseReportJob JID-580531214732438c34fe3e78 INFO: start
2019-11-21T17:03:52.511Z 1 TID-gni5eoqyl ParseReportJob JID-580531214732438c34fe3e78 INFO: done: 46.553 sec
2019-11-21T17:04:02.524Z 1 TID-gni5eoqyl ParseReportJob JID-0910570d946ff49f5b2d9e31 INFO: start
2019-11-21T17:04:03.860Z 1 TID-gni5eoqyl ParseReportJob JID-0910570d946ff49f5b2d9e31 INFO: done: 1.336 sec
```
TODO:
> [RHICOMPL-412] - Don't parse already parsed benchmarks

- config/application.rb
- config/environments/development.rb
Fixes this error:
> /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:105:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` 
> Disable rails asset pipeline

- app/services/datastream_importer.rb
- test/services/datastream_importer_test.rb
After importing a benchmark for the first time, we should import remediations rather than waiting until 8am the next morning.
> Import remediations after report parse

- app/graphql/types/profile.rb
- app/graphql/types/rule.rb
Fixes this sort of thing seen in devel:
```
ArgumentError (A copy of Types::Profile has been removed from the module tree but is still active!):                                                                                                                                                                                                                                                                                          
app/graphql/types/profile.rb:116:in `latest_test_result' …
```
> Use fully qualified model names in graphql types

- app/controllers/concerns/authentication.rb
- app/services/rbac_api.rb
- spec/swagger_helper.rb
There is no need to send the account fake identity header when we can send directly the request header.
> Use real X-RH-IDENTITY coming from original request

- app/services/duplicate_benchmark_resolver.rb
- db/migrate/20200106134953_add_unique_index_to_benchmarks.rb
- test/services/duplicate_benchmark_resolver_test.rb
The migration migrates a duplicate benchmark's rules and profiles and associated records (namely host_profiles and rule results) and then adds the unique benchmark DB constraint.
Test scenario ideas:
- Import 1 benchmark, duplicate it and save, run the migration
- Import 2 benchmarks of different versions, update the versions to match, run the migration
- Import 1 RHEL 7 benchmark, import 1 RHEL 6 benchmark, update ref_id and version to match, run the migration
For all cases: confirm 1 benchmark exists and no errors occurred
These counts should change: `[Xccdf::Benchmark.count, Profile.count, Rule.count, RuleIdentifier.count]`
These may or may not change: `[RuleReference.count, ProfileHost.count, ProfileRule.count]`
These should not change: `[RuleResult.count, Host.count, …
> Add a unique db constraint for benchmarks

- app/models/xccdf/benchmark.rb
- test/models/benchmark_test.rb
No use for this yet, but it sounds like we'll need it in the future.
> Infer benchmark OS from ref_id

- app/services/datastream_importer.rb
- test/services/datastream_importer_test.rb
The following happens if you try to import a datastream file without any accounts:
```
Importing ./test/fixtures/files/ssg-rhel7-ds.xml at 2020-01-21 15:57:03 UTC                                                                                                                                                                                                                                                                                                                   
rake aborted! …
```
> Allow datastream import without any accounts

- app/models/profile.rb
- app/services/xccdf_tailoring_file.rb
- db/migrate/20200120203124_add_parent_profile_id_to_profiles.rb
- test/services/xccdf_tailoring_file_test.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-308
Also adds parent_profile_id to the profiles table without any code so far to populate this field.
Compare the output of `XccdfTailoringFile.new(profile: Profile.first).to_xml` to the following tailoring generated from openscap workbench:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xccdf:Tailoring xmlns:xccdf="http://checklists.nist.gov/xccdf/1.2" id="xccdf_scap-workbench_tailoring_default">
<xccdf:benchmark href="/tmp/SCAP Workbench-zVBxUA/ssg-rhel7-ds.xml"/>
<xccdf:version time="2019-10-07T11:49:49">1</xccdf:version>
<xccdf:Profile id="xccdf_org.ssgproject.content_profile_standard_customized" extends="xccdf_org.ssgproject.content_profile_standard">
<xccdf:title xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:lang="en-US" …
```
> 308: Add tailoring file service for creating tailorings

- app/graphql/schema.graphql
- app/graphql/types/query.rb
- app/models/xccdf/benchmark.rb
- test/fixtures/benchmarks.yml
- test/models/benchmark_test.rb
This should be used by the frontend to only display the latest benchmarks available on the CreatePolicy wizard
> RHICOMPL-454 - Find latest benchmarks

- .env
- app/controllers/concerns/exception_notifier_custom_data.rb
- app/services/openshift_environment.rb
- lib/tasks/import_datastream.rake
- lib/tasks/import_remediations.rake
ExceptionNotification only notifies on 500 errors on the controllers. For Rake jobs, we have to rescue any error and send it over to Slack. We have missed some errors on jobs without this.
> Notify Slack on Rake job exception

- Jenkinsfile
- Set the same base image generated from PR source code for all
services in Compliance set.
> Set image for compliance services in  Smoke Tests

- app/services/host_inventory_api.rb
- test/services/host_inventory_api_test.rb
Finding hosts by ID has never worked correctly until this change. It has been verifying a match with the inventory only based on the fqdn returned by the insights-client metadata.
Without the change, the ID test fails:
```
FAIL["test_find_results_matches_on_ID", #<Minitest::Reporters::Suite:0x000055a0d359d5c0 @name="HostInventoryApiTest">, 0.18526139999812585]
test_find_results_matches_on_ID#HostInventoryApiTest (0.19s)
find_results did not return the expected match by ID.
Expected nil to not be nil.
test/services/host_inventory_api_test.rb:56:in `block in <class:HostInventoryApiTest>'
```
> Find inventory systems by passed ID before hostname

- app/graphql/mutations/profile/associate_systems.rb
- app/models/account.rb
- app/services/host_inventory_api.rb
- app/services/remediations_api.rb
- test/graphql/mutations/associate_systems_test.rb
Create host from the inventory on policy assocate_systems only if the host doesn't already exist in compliance.
Related to https://projects.engineering.redhat.com/browse/RHICOMPL-306
Reported at https://projects.engineering.redhat.com/browse/RHICOMPL-485
Requires https://github.com/RedHatInsights/compliance-backend/pull/319
> Create host from inventory on policy association

- spec/integration/profiles_spec.rb
- spec/integration/rule_results_spec.rb
- spec/integration/rules_spec.rb
- spec/integration/systems_spec.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
@Victoremepunto this one's for you :)
Just so we're all on the same page, the files in `spec` contain both the actual API definition as well as some tests for the API. This is just the way rswag works, but it's still an API definition first model (i.e. we're not generating the API from our controller code in `app/`, and there's no guarantee that our API behaves the way we defined it). `bundle exec rake rswag` generates the `swagger/v1/openapi.json` from what's defined in `spec`. It's much nicer to be able to define resources separately (and in Ruby) than in one big yaml or json file manually.
@Victoremepunto compare against your changes in https://github.com/RedHatInsights/compliance-backend/pull/250
> Update rswag specs to include limit/offset/search

- app/controllers/rules_controller.rb
- test/controllers/rules_controller_test.rb
- test/fixtures/rules.yml
We're seeing some problems in production because /rules/$REF_ID does not work for some users, if the rule appears in multiple benchmarks. In that case `.find` will just find the first rule, which may appear in a benchmark that the current user has no policies in (hence, the user gets a 403 unauthorized). 
To avoid this, but keep the same behavior restricting visible rules to only rules for the policies visible by the user, we can query directly within the Rules policy scope for the user.
> Check for rule within user rules scope

- app/models/profile_host.rb
- test/models/profile_host_test.rb
This doesn't really make much sense anymore now that users can create and delete policies themselves via the API and UI.
> Don't delete orphaned profiles

- app/models/profile.rb
- test/models/profile_test.rb
I think this is the last place in our code where we create a non-canonical profile and need to set its parent_profile.
> Assign parent_profile on profile clone

- app/services/host_inventory_api.rb
Using the current format, we get the error `{'stale_timestamp': ['Not a valid datetime.']}`.
I don't think this is used in reality, I only noticed because I have this script to create fake hosts in the db:
```ruby
namespace :fake_data do
task create_hosts_in_inventory: :environment do
module Platform
def self.connection
faraday = Faraday.new do |f|
f.response :raise_error
f.adapter Faraday.default_adapter # this must be the last middleware
f.basic_auth 'dlobatog@redhat.com', 'redhat'
f.ssl[:verify] = false
end
faraday
end
end
account = ::Account.where(account_number: '1460290').first
200.times do |i|
host = Host.new(name: "lobatolan-#{i}")
host.save
hostinventory = ::HostInventoryAPI.new(host.id, host.name, account, 'https://ci.cloud.redhat.com', nil)
inventory_host = …
```
> Format stale_timestamp properly

- app/services/parent_profile_associator.rb
- db/migrate/20200120203124_add_parent_profile_id_to_profiles.rb
- test/services/parent_profile_associator_test.rb
Since the parent_profile migration hasn't made it past CI and given it's the latest migration in the repo, I propose we rollback CI 1 migration and re-migrate to get this data migration in. I think it's more consistent with how we've done this in the past than to create another migration.
> Migrate profiles using account_id to parent_profile_id

- app/models/profile.rb
- test/graphql/queries/profile_query_test.rb
- test/models/profile_test.rb
- test/services/xccdf_report_parser_test.rb
With the added parent_profile_id field, we no longer need to check existence of an account to determine if a profile is canonical or not.
> Determine canonical profiles based on parent_profile presence

- app/services/xccdf_tailoring_file.rb
- test/services/xccdf_tailoring_file_test.rb
Test like this:
```rb
XccdfTailoringFile.new(
profile: Profile.where.not(parent_profile_id: nil).first,
rule_ref_ids: {'rule_ref_1' => true, 'rule_ref_2' => false}
).to_xml
```
which should return something like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xccdf:Tailoring xmlns:xccdf="http://checklists.nist.gov/xccdf/1.2" id="xccdf_csfr-compliance_tailoring_default">
<xccdf:benchmark id="xccdf_org.ssgproject.content_benchmark_RHEL-7"/>
<xccdf:version time="2020-02-19T18:16:24+00:00">1</xccdf:version>
<xccdf:Profile id="xccdf_org.ssgproject.content_profile_standard" extends="xccdf_org.ssgproject.content_profile_standard">
<xccdf:title xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:lang="en-US" override="true">Standard System Security Profile for Red Hat Enterprise Linux …
```
> Tailoring file service accepts rule selections

- Gemfile
- Gemfile.lock
- app/controllers/rules_controller.rb
- app/models/rule.rb
- app/serializers/rule_serializer.rb
- db/migrate/20200303102215_change_phony_benchmark.rb
- db/migrate/20200303102215_change_phony_benchmark_version.rb
- test/controllers/rules_controller_test.rb
Apparently our DB contains multiple slugged rules, one per benchmark. In that case, the regular `friendly.find` will not find it.  
Instead of that, when a user looks for a ref_id we can just find all of the ref_ids that look like it within the user scope. In that case, if you look for `xccdf_org-ssgproject-content_rule_sysctl_net_ipv4_tcp_syncookies` but only `xccdf_org-ssgproject-content_rule_sysctl_net_ipv4_tcp_syncookies-98d17f35-6094-4071-b099-cb4bca02615d` is in the scope, it will still be found. 
```ruby
Rule.where(ref_id: "xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_tcp_syncookies").map(&:slug)
Rule Load (3.6ms)  SELECT "rules".* FROM "rules" WHERE "rules"."ref_id" = $1  [["ref_id", "xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_tcp_syncookies"]]
=> …
```
> Find all rules by slug using LIKE

- app/controllers/profiles_controller.rb
- app/models/concerns/profile_tailoring.rb
- app/models/profile.rb
- config/routes.rb
- test/controllers/profiles_controller_test.rb
- test/models/profile_test.rb
~It works without https://github.com/RedHatInsights/compliance-backend/pull/324 (merged), but you won't be able to generate any useful tailoring file with selected/unselected rules without it.~
> Allow downloading tailoring of a profile

- app/graphql/types/query.rb
I'm not sure how this was working before, but this fixed it for me.
Here's the issue:
```
Started POST "/api/compliance/graphql" for 172.18.0.1 at 2020-03-09 18:33:54 +0000                                                                                                                                                                                                                                                                                                            
Processing by GraphqlController#query as */* …
```
> Correct latestBenchmarks pundit policy invocation

- config/initializers/sidekiq.rb
Currently sidekiq is not configured correctly for running in a `rails` process.
This causes issues when trying to create a job from the backend, since it will try to connect to the default `127.0.0.1` address. 
Since the two blocks were identical it's now one in a lambda.
> Correct sidekiq configuration

- app/graphql/mutations/profile/create.rb
- app/graphql/schema.graphql
- app/models/profile.rb
- test/graphql/mutations/create_profile_mutation_test.rb
Given a list of refIds, tailor the set of rules in the policy to it.
Enables https://github.com/RedHatInsights/compliance-frontend/pull/423
> RHICOMPL-502 - Tailoring mutation

- app/graphql/types/system.rb
- app/models/profile.rb
- app/models/rule.rb
- app/models/test_result.rb
- test/models/profile_test.rb
- test/models/rule_test.rb
I noticed this issue while trying to create REST API examples. The score for a profile is a simple average across all hosts' latest test_result scores. This PR contains a scope for latest TestResults, `TestResult.latest`, which we need for almost every TestResult query.
> RHICOMPL-515 - Calculate score from test results

- db/migrate/20191126181009_seed_test_results.rb
There seem to exist some broken ProfileHost records from what we're seeing when trying to migrate the db on QA using a prod dump. This allows the migration to safely skip and remove any broken records.
> Skip broken ProfileHost on db migration

- app/services/duplicate_benchmark_resolver.rb
- test/services/duplicate_benchmark_resolver_test.rb
This migration was so slow because of the fan out to profiles and rules. A better strategy is to allow intermediate duplicates and only resolve duplicate benchmarks in order to add the DB constraint for benchmarks. Later migrations will add uniqueness constraints for rules and profiles - duplicates will be reconciled at that point. This should keep our migrations fast.
In the UI, duplicate profiles and rules may appear, but this might happen today without this PR. Again, we need to solve this in a future PR and migration.
> Resolve only duplicate benchmarks, not rules and profiles

- app/models/profile.rb
- test/fixtures/test_results.yml
- test/graphql/queries/profile_query_test.rb
- test/graphql/queries/system_query_test.rb
- test/models/profile_test.rb
This PR updates the compliant? calculation to use the TestResult score. Hopefully there are no other locations where we're counting rule results to calculate score.
> Update more score calculations to use TestResult

- app/policies/test_result_policy.rb
- test/policies/test_result_policy_test.rb
This is meant to allow the `collection_field` TestResult GQL API
endpoint to return a set of filtered TestResults - without it, Pundit
will just return nil.
> Add Pundit policy for TestResult

- app/models/host.rb
- test/models/host_test.rb
This allows us to only display hosts with test results on certain pages, such as "Reports by system" or "Report details" - where we do not want systems that have no reports.
> RHICOMPL-292 - Filter by hosts with test results

- app/models/rule_result.rb
`notapplicable` happens, for example, when a system (i.e. RHEL7) is scanned with a mismatched benchmark (i.e. xccdf_org.ssgproject.content_benchmark_RHEL-6). We should not count these rule results as passed.
From the XCCDF spec:
> Remove notapplicable from RuleResult::PASSED

- app/services/duplicate_benchmark_resolver.rb
- app/services/parent_profile_associator.rb
- db/migrate/20200327170640_remove_empty_benchmarks.rb
Some profiles cannot be associated to parents within its own benchmark,
such as profiles that come from the phony benchmark (which has no
canonical profiles).
> Associate parent profiles outside of own benchmark

- docker-compose.yml
This is only useful when you import a prod DB dump and then try to drop the database. It hasn't always happened for me, so that may not be the complete reproducer steps.
The rake db:drop command runs this query to get the DB environment from the DB itself:
```
SELECT "ar_internal_metadata"."value" FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1  [["key", "environment"]]
```
> Disable DB environment check locally

- config/environments/development.rb
This has been really helpful while testing and debugging the database migrations locally.
> Allow pending migrations in devel

- app/models/concerns/profile_scoring.rb
- app/serializers/profile_serializer.rb
The score either gives a integer (0) or a string, but the score should be a float in the API.
Disabling `encode_big_decimal_as_string` does not work with the serializer used.
> Serialise score as float

- app/controllers/concerns/authentication.rb
- test/controllers/concerns/authentication_test.rb
User information is not guaranteed to be present in the identity header. We cannot rely on user existing, only account. This PR removes any database calls to user and only uses the User model as a proxy to access the account. It's a minimal change that should fix our problems, but we could remove all user-related code in the future; it'd be hundreds of lines of code changed, not something we want to deploy right before GA. :)
Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-560
> Remove user requrement in identity header

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
Having this available allows us to query the benchmark SSG version and title in the frontend - which we want for a tooltip in the Policies tabel
> RHICOMPL-548 - Add benchmark to Profile GQL schema

- app/services/concerns/xccdf/benchmarks.rb
- app/services/concerns/xccdf/util.rb
- test/services/concerns/xccdf/benchmarks_test.rb
Basically, for whatever reason, some benchmarks (in the JIRA card, the benchmark 0.1.43) are missing a few rules, so when we tried to save results it wasn't able to do it. Normally, when we parse a report, we do 2 big steps:
1- Parse the benchmark UNLESS the benchmark is already found in our DB
2- Parse the results
In this bug, we jump straight to Parse the results, because compliance thought that the version of the benchmark '0.1.43' already contained everything that could be on those results, but turns out that's not the case. I think we should do smarter checking and check at least the number of rules, maybe other basic stuff, and import them if they are unavailable, or else step 2 fails. 
I'm not sure yet why our SSG 0.1.43 had 8 rules less than the SSG in the report. It looks like …
> RHICOMPL-568 - Re-import benchmark if rules count isn't correct

- db/migrate/20200414144209_remove_default_benchmarks_from_rules.rb
- db/migrate/20200414144221_remove_default_benchmarks_from_profiles.rb
We've removed the phony benchmark. These defaults no longer make sense.
```rb
[1] pry(main)> Profile.new
=> #<Profile:0x0000556473172c30
id: nil,
name: nil,
ref_id: nil,
created_at: nil,
updated_at: nil,
description: nil,
account_id: nil,
compliance_threshold: 100.0,
business_objective_id: nil,
benchmark_id: "ad500579-c3e3-4d7a-b057-eba6b362509e", # wtf? lol this benchmark does not exist
parent_profile_id: nil,
external: false>
```
Caution when running `rollback` - the phony benchmark will get recreated!
> Remove default benchmark from rules and profiles

- app/models/profile.rb
- test/models/profile_test.rb
Requires https://github.com/RedHatInsights/compliance-backend/pull/389
> Profiles created during report parse are external

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- app/models/profile.rb
- app/serializers/profile_serializer.rb
- app/services/concerns/xccdf/benchmarks.rb
- app/services/concerns/xccdf/util.rb
- db/migrate/20200414143250_add_external_to_profiles.rb
- db/migrate/20200414144209_remove_default_benchmarks_from_rules.rb
- db/migrate/20200414144221_remove_default_benchmarks_from_profiles.rb
- test/models/profile_test.rb
- test/services/concerns/xccdf/benchmarks_test.rb
This PR introduces 'external' in QA and benchmark in the GQL API so we can do things like : https://github.com/RedHatInsights/compliance-frontend/pull/499
> Add benchmarks to GQL & external attributes

- app/graphql/types/system.rb
- app/models/concerns/profile_scoring.rb
- app/models/rule.rb
These values are meant to be expired during report parsing, in the
invalidate_cache method. No need to manually expire them in a week.
> Remove cache expiration date

- app/models/profile.rb
- test/models/profile_test.rb
External profiles can be associated to policies (an internal profile associated to a user account). We should get the business objective and compliance threshold from the internal policy that the user defined.
> Determine policy from a profile

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
This field is meant to return the "Policy" for a profile, so if the
profile is external, this would be any policy in the same benchmark
ref_id, same ref_id, different benchmark version, if it exists, or null.
> Add policy to GQL profile type

- lib/tasks/sync_with_inventory.rake
This rake task simply sends requests to the inventory for every host,
and checks whether the host exists in the inventory. If it doesn't
exist, it deletes it from our DB.
I'm working on an improved version that fetches hosts in batches of 50, but this allows to get us off the hook now that there are some hosts like that, and in -beta envs, they show as hosts with no name in the Systems table.
> Sync compliance DB with inventory task

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- app/graphql/types/query.rb
- app/graphql/types/rule.rb
- app/graphql/types/system.rb
- app/jobs/destroy_profiles_job.rb
- app/models/concerns/profile_policy_association.rb
- app/models/concerns/profile_scoring.rb
- app/models/profile.rb
- app/models/profile_host.rb
- app/models/rule.rb
- lib/tasks/sync_with_inventory.rake
- test/graphql/queries/benchmark_query_test.rb
- test/graphql/queries/system_query_test.rb
- test/models/profile_host_test.rb
- test/models/profile_test.rb
This adds the following changes to stable:
* There is a new task (no job runs it yet, so it's only available via manual runs) to sync the DB with the inventory, and drop any records not found in the inventory
* Cache expiration date for failed rules, compliant, and results is 'never' - we only clear this cache when a new report comes in.
* Methods to determine a Policy from a Profile, and added Policy to GQL. 
* Destroy all Profiles if the "parent" Policy is destroyed.  
In addition to that, there are 2 commits which we couldn't put into prod until we got rid of current prod-stable. These changes have been already in CI for a long time.
* Don't destroy orphaned profiles (we do this in prod-stable, but it shouldn't be necessary in the "new app")
* Remove GQL endpoints that are unused
> Find policy for profile

- test/models/profile_test.rb
@dLobatog I think you mentioned this to me - This should fix the transient failure, which was sometimes finding more than 1 job due to other profiles being deleted in other tests.
> Fix transient profile test failure

- app/controllers/benchmarks_controller.rb
- app/models/xccdf/benchmark.rb
- app/serializers/benchmark_serializer.rb
- config/routes.rb
- test/controllers/benchmarks_controller_test.rb
- test/policies/benchmark_policy_test.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-593
- New Benchmarks controller and tests
- scoped_search for benchmark and profile/rule ID
- New Benchmark serializer
- Benchmark routes for `#show` and `#index`
- New Benchmark policy tests
> Add benchmarks API endpoint

- lib/tasks/import_datastream.rake
- lib/tasks/sync_with_inventory.rake
1. `HostInventoryNotFound` isn't required in the sync_inventory task, so if it's called and fails, it'll not be able to work. 
2. Calling `.invoke` more than once on a rake task will not work, as the task will be marked the first time as `@already_invoked` (see [the source](https://github.com/ruby/rake/blob/master/lib/rake/task.rb#L205)). We could either call `.reenable` to reset the flag, or just call `.execute` which runs the task directly without the task prerequisites - which is OK in this case.
> Fixes for rake tasks 

- config/environments/production.rb
- config/settings/development.yml
- config/settings/production.yml
For now we only have one redis instance, but this change would enable us to easily switch our cache to use an LRU-cache instead of the current persistent store.
> Add specific config for cache redis

- app/consumers/compliance_reports_consumer.rb
- app/jobs/parse_report_job.rb
- app/producers/payload_tracker.rb
- test/consumers/compliance_reports_consumer_test.rb
- test/jobs/parse_report_job_test.rb
- test/producers/payload_tracker_test.rb
The Payload Tracker is transitioning to using the new "request_id" terminology instead of the legacy "payload_id." This renames that field.
> Use request_id instead of payload_id

- app/services/platform.rb
This should retry 3 times if it finds any of the expected exceptions. Unfortunately we are hitting sometimes remediations or RBAC when the pods are restarting or similar, you can see the #alerts-cloudservices-apps for an example of this. It should go:
1. Try request between 0.05+0.025 seconds
2. Try request between 0.1+0.05 seconds
3. Try request between 0.2+0.1 seconds
The goal is to have less "false alarms" in the channel and actually succeed with some requests that shouldn't fail.
> Add Faraday::Retry middleware

- app/consumers/compliance_reports_consumer.rb
- app/jobs/parse_report_job.rb
- app/producers/payload_tracker.rb
- app/services/platform.rb
- spec/integration/benchmarks_spec.rb
- spec/integration/profiles_spec.rb
- spec/integration/rules_spec.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
- test/consumers/compliance_reports_consumer_test.rb
- test/fixtures/benchmarks.yml
- test/jobs/parse_report_job_test.rb
- test/producers/payload_tracker_test.rb
- test/test_helper.rb
This PR contains the following changes:
* Adds Faraday::Retry to our middleware to make GET requests to different services. This should reduce the amount of false alerts we get for services we try to contact and are temporarily down.
* Changes PayloadTracker to use `request_id` instead of `payload_id`, as the latter is deprecated.
* Adds Benchmark REST API docs to Swagger
> Introduce Faraday::Retry, Benchmark docs to stable

- app/graphql/types/interfaces/rules_preload.rb
rule_results should be an AR relation at all times, as even if it's
empty, we call methods like 'select' on it.
> Resolve rule_results to AR relation if it's empty

- app/graphql/types/interfaces/rules_preload.rb
rule_results should be an AR relation at all times, as even if it's
empty, we call methods like 'select' on it.
> [stable] Resolve rule_results to AR relation if it's empty

- app/graphql/types/interfaces/rules_preload.rb
Resolving the query for all Rule ids before trying to get all of the
RuleReferencesRules results in a massive performance improvement.
There's a penalty on running subqueries like "IN (SELECT
"rule_results"."rule_id" FROM "rule_results" WHERE
"rule_results"."test_result_id" = $1)" - versus just resolving the call
and passing the array of rule IDs.
In this example, we have already resolved the rule_ids in line 40, on
initialize_rules_context, so using a subquery is suboptimal when the
data is already in memory.
You can see the difference on these [slow](https://gist.github.com/dLobatog/d4d4ff0e012d36a11dd372402bed3b4f) vs [fast](https://gist.github.com/dLobatog/d7c8e057a600b4dc195149e7b293b5da).
Particularly the lines to notice are:
```
RuleReferencesRule Load (9662.4ms)  SELECT DISTINCT …
```
> RHICOMPL-598 - Resolve rule_ids before querying references

- app/graphql/types/interfaces/rules_preload.rb
Resolving the query for all Rule ids before trying to get all of the
RuleReferencesRules results in a massive performance improvement.
There's a penalty on running subqueries like "IN (SELECT
"rule_results"."rule_id" FROM "rule_results" WHERE
"rule_results"."test_result_id" = $1)" - versus just resolving the call
and passing the array of rule IDs.
In this example, we have already resolved the rule_ids in line 40, on
initialize_rules_context, so using a subquery is suboptimal when the
data is already in memory.
> RHICOMPL-598 - Resolve rule_ids before querying references (#430)

- app/graphql/types/profile.rb
This should make all of the calls to this endpoint faster, according to experimentation - it reduces the allocation of RuleResults by more than 10x. It's most visible on the Reports by System page.
Before (7.5s, 3.5M allocations):
After (1.2s, 143k allocations):
> RHICOMPL-586 - Don't preload rule_results on profiles GQL

- app/graphql/types/profile.rb
This should make all of the calls to this endpoint faster, according to
the results. See https://github.com/RedHatInsights/compliance-backend/pull/434 for more details
> [stable] RHICOMPL-586 - Don't preload rule_results on profiles GQL (#434)

- app/services/external_profile_updater.rb
- db/migrate/20200414143250_add_external_to_profiles.rb
- test/services/external_profile_updater_test.rb
Any profiles created before we released policy creation changes to
prod-beta should be external. Others created after our release should
stay external=false in order to show in the SCAP policies UI.
> Migrate existing profiles during db migration

- app/controllers/concerns/exception_notifier_custom_data.rb
- app/services/openshift_environment.rb
- test/controllers/concerns/exception_notifier_custom_data_test.rb
Currently, the notifications we are getting contain the User object,
which is useless. Instead, we should get the account number to
help us understand better under which circumstances the exception
happened.
> Add account_number to Openshift info

- app/graphql/schema.graphql
- app/graphql/types/system.rb
- app/services/concerns/xccdf/util.rb
- test/graphql/queries/system_query_test.rb
Please double-check first, but these fields are not used anywhere in our frontend I believe, and some are just wrong - e.g: there's no concept of "Compliant" system, profile-names should be extracted from `profiles { name }` and same goes for rule objects failed.
> Remove unused gql fields

- db/migrate/20200428143250_add_primary_key_to_rules_references.rb
- db/migrate/20200428205535_uniqueness_rule_references_rule_index.rb
This commit removes around 63M rows from RuleReferencesRule. Even though
there is a soft-validation in ActiveRecord on rule_id/reference_id, it's
completely skipped at the only place where we insert these records (in
the parser).
This greatly speeds up the SystemDetails page query, as we need to load
all RuleReferences for all rules there. The query, a simple SELECT *
from rule_references_rules WHERE rule_id IN (list of 1600 rules) goes
from 8 seconds to miliseconds. It also allows us to remove the
"DISTINCT" from the query, which was making us lose nearly 3s
sorting the records first.
As for the code itself:
1. I *must* add a primary key in order to identify the duplicate keys.
Otherwise, you can identify them, but you cannot remove them (what
are you even removing in that case)? It …
> Remove millions of duplicates from RuleReferencesRule

- app/consumers/inventory_events_consumer.rb
- app/controllers/concerns/exception_notifier_custom_data.rb
- app/jobs/concerns/record_not_found.rb
- app/jobs/delete_host.rb
- app/jobs/inventory_host_updated_job.rb
- test/consumers/inventory_events_consumer_test.rb
- test/jobs/delete_host_test.rb
- test/jobs/inventory_host_updated_job_test.rb
On Apr 28th, there will be a new event to tell apps to update hostnames if the inventory hostname changed. On the UI, this shouldn't affect us as we already always display the inventory hostname (unless the host is unsynced for whichever reason and is only on compliance, this should not happen in prod though).
On the API, this would be visible as we don't contact the inventory for anything there. So we should update the names according to the message to serve the right name.
https://platform-docs.cloud.paas.psi.redhat.com/backend/inventory.html#host-patching for more info on the message format
> RHICOMPL-631 - Update hostnames based on 'update' message

- app/graphql/mutations/system/associate_profiles.rb
- test/graphql/mutations/associate_profiles_test.rb
Currently if you associate profiles to a host, it removes the associations to external profiles. Those associations shouldn't be removed.
> RHICOMPL-641 - Keep external profiles on associateProfiles

- db/migrate/20200428143250_add_primary_key_to_rules_references.rb
- db/migrate/20200428205535_uniqueness_rule_references_rule_index.rb
This commit removes around 63M rows from RuleReferencesRule. Even though
there is a soft-validation in ActiveRecord on rule_id/reference_id, it's
completely skipped at the only place where we insert these records (in
the parser).
This greatly speeds up the SystemDetails page query, as we need to load
all RuleReferences for all rules there. The query, a simple SELECT *
from rule_references_rules WHERE rule_id IN (list of 1600 rules) goes
from 8 seconds to miliseconds. It also allows us to remove the
"DISTINCT" from the query, which was making us lose nearly 3s
sorting the records first.
As for the code itself:
1. I *must* add a primary key in order to identify the duplicate keys.
Otherwise, you can identify them, but you cannot remove them (what
are you even removing in that case)? It …
> [stable] Remove millions of duplicates from RuleReferencesRule

- app/controllers/concerns/exception_notifier_custom_data.rb
- app/graphql/mutations/test_result/delete.rb
- test/graphql/mutations/delete_test_result_mutation_test.rb
Before this change, if you deleted a Report in the UI, external profiles
are still kept in the database. This doesn't make sense, as those
reports are only meant to exist to hold the definition of the profile
for the Report, so if the report goes away, so does the profile and the
profile host associations.
This is visible through the API but also on the UI, after removing an
external Report, the SystemsTable shows the Host still linked to the
external profile.
> RHICOMPL-622 - Deleting external profiles deletes Profile

- app/controllers/concerns/authentication.rb
- app/graphql/mutations/system/associate_profiles.rb
- app/graphql/mutations/test_result/delete.rb
- test/controllers/concerns/authentication_test.rb
- test/graphql/mutations/associate_profiles_test.rb
- test/graphql/mutations/delete_test_result_mutation_test.rb
Follow up to https://github.com/RedHatInsights/compliance-backend/pull/446, as it's failing smoke tests due to the removed GQL fields.
> [stable] External files fixes & RBAC fail returns 403

- .codecov.yml
- test/test_helper.rb
When running tests locally, the .codecov.yml is not honored because
coverage is using simplecov without the codecov formatter.
Note that the coverage doesn't change for codecov reported on this PR.
> Ignore coverage in lib for simplecov and codecov

- Gemfile
- Gemfile.lock
The -b (bind to address) option in prometheus_exporter was introduced in version 0.5.0. The current docker-compose.yml is broken because we have it locked at 0.4.16.
> Bump prometheus_exporter to >= 0.5

- test/graphql/mutations/create_profile_mutation_test.rb
They are just (rarely) sometimes out of order
```rb
[1] pry(main)> [3, 5] == [5, 3]
=> false
[2] pry(main)> Set.new([3, 5]) == Set.new([5, 3])
=> true
```
> Use sets to determine equality in profile mutation test

- app/models/rule_result.rb
- app/services/concerns/xccdf/rule_results.rb
- test/services/xccdf_report_parser_test.rb
> Adjust rule result pass/fail determination

- config/initializers/prometheus.rb
- config/initializers/sidekiq.rb
From prometheus_exporter, it doesn't make sense a lot of sense
to send metrics to itself. Similarly initializing sidekiq is also
useless from prometheus_exporter.
> Do not initialize Sidekiq client or prometheus_exporter from prometheus-exporter

- app/services/concerns/xccdf/rule_references_rules.rb
- test/services/concerns/xccdf/rule_references_rules_test.rb
If we don't find them first, we will be trying to introduce duplicates,
which with the current uniqueness index it will cause a failure.
> Find RuleReferencesRule if they're present in the db

- Gemfile
- Gemfile.lock
- config/settings/development.yml
- config/settings/test.yml
- openshift/Jenkins/slave_pod_template.yaml
These gems are currently loaded and installed with the image when they
are just cruft from when we had the requirement of scanning ImageStreams
from an Openshift cluster.
A PR in e2e will follow which removes these. Also, the Gemfile is
reorganized a bit, but only the  newrelic_rpm, tty-command, docker-api, attr_encrypted gems are removed. Everything else remains the same. 
Something else I noticed when I was reorganizing the Gemfile was that we're missing out on Puma 4, [which apparently has no breaking changes](https://github.com/puma/puma/issues/1828)
https://www.schneems.com/2019/06/26/puma-4-new-io-4-your-server/
> Remove newrelic_rpm, tty-command, docker-api, attr_encrypted

- docker-compose.yml
Rails needs redis now for async tasks in Sidekiq. Now that we have a
redis_url set, without redis we get constant errors about not being able
to connect.
> Update local dev to require redis for rails

- app/models/profile.rb
- app/models/profile_host.rb
- test/models/profile_host_test.rb
I still need to test this actually on the UI, but in theory this is all that's needed not to leave orphaned hosts around in our database when they no longer have any profile assigned.
> RHICOMPL-622 - Delete hosts when they become orphaned

- app/services/concerns/xccdf/rule_references_rules.rb
- test/services/concerns/xccdf/rule_references_rules_test.rb
This enables uploads for unknown SSG OS/versions again, right now the uniqueness constraint will break them as they'll try to introduce RRR duplicates.
> [stable] Find RuleReferencesRule if they're present in the db (#456)

- Gemfile
- Gemfile.lock
- config/settings/development.yml
- config/settings/test.yml
- openshift/Jenkins/slave_pod_template.yaml
These gems are currently loaded and installed with the image when they
are just cruft from when we had the requirement of scanning ImageStreams
from an Openshift cluster.
A PR in e2e will follow which removes these. Also, the Gemfile is
reorganized a bit better.
> [stable] Remove newrelic_rpm, tty-command, docker-api, attr_encrypted (#459)

- lib/tasks/import_datastream.rake
There's a cached field called 'latest_supported_benchmarks' to avoid
making the same SQL call always to show the latest benchmarks in the
Create Policy wizard. Notice this will NOT affect customers unless we
change the LATEST_SUPPORTED_VERSIONS. This was visible on CI because the
import-job failed (killed OOM or something), so I'm going to clear the
field before the import-latest-rhel-supported job starts.
> RHICOMPL-650 - Delete cached latest_supported_rhel benchmarks

- app/services/concerns/xccdf/test_result.rb
- test/services/concerns/xccdf/test_result_test.rb
This should help keep our DB lean until we need to implement historical results. At that point, this code should be very easily reversed. From prod:
```rb
irb(main):001:0> [TestResult.count, TestResult.latest.count]
=> [4088, 1521]
```
Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-634
> Delete old test results when new ones are saved

- app/graphql/types/interfaces/rules_preload.rb
- test/graphql/queries/system_query_test.rb
We keep on getting an alert on "undefined method 'id' for nil:NilClass"
on the #alerts-cloudservices-apps.
After investigating, this alert happens because the system details page
is visited. We try to retrieve the latest Test Results for the profiles
for the System, and some RuleResults don't have a correct rule_id FK -
they're pointing to unknown rule_ids.
> irb(main):013:0> rule_ids.count
> => 4405
> irb(main):014:0> rule_ids = RuleResult.select(:rule_id).distinct.pluck(:rule_id); rule_ids.count
> => 4405
> irb(main):015:0> Rule.where(id: rule_ids).count
> => 3283
In our GQL API code, when we try to get the results for these
rules, they're showing up as "nil" and therefore they fail to
load.
> RHICOMPL-695 - Fix 'undefined method id' error on SystemDetails

- db/migrate/20200518145454_remove_useless_rule_results.rb
Many *old* records (6m+ old) in RuleResult are simply unused
(test_result_id is nil), or broken (rule_id isn't pointing to a real Rule).
These records should be removed from the database.
```
[43] pry(main)> unfound_rule_results.max_by(&:created_at)
=> #<RuleResult:0x000055f2be789630
id: "0c945c41-6122-422d-952a-c12c373284d6",
host_id: "b4166156-a04e-4afd-90b0-d8d6df31cfe4",
rule_id: "001982c1-0c73-4ac1-bba4-f6339595a9b0",
result: "notselected",
created_at: Fri, 29 Nov 2019 10:01:30 UTC +00:00,
updated_at: Fri, 29 Nov 2019 10:01:30 UTC +00:00,
test_result_id: nil>
[44] pry(main)> unfound_rule_results.min_by(&:created_at)
=> #<RuleResult:0x000055f2af0ab638
id: "8d8938b2-0f82-4d52-bac7-64024aa9531e",
host_id: "2566a863-7052-4045-abbe-056ddc9277ad",
rule_id: …
```
> Remove useless RuleResult records

- db/migrate/20200518145454_remove_useless_rule_results.rb
Many *old* records (6m+ old) in RuleResult are simply unused
(test_result_id is nil), or broken (rule_id isn't pointing to a real Rule).
These records should be removed from the database.
```
[43] pry(main)> unfound_rule_results.max_by(&:created_at)
=> #<RuleResult:0x000055f2be789630
id: "0c945c41-6122-422d-952a-c12c373284d6",
host_id: "b4166156-a04e-4afd-90b0-d8d6df31cfe4",
rule_id: "001982c1-0c73-4ac1-bba4-f6339595a9b0",
result: "notselected",
created_at: Fri, 29 Nov 2019 10:01:30 UTC +00:00,
updated_at: Fri, 29 Nov 2019 10:01:30 UTC +00:00,
test_result_id: nil>
[44] pry(main)> unfound_rule_results.min_by(&:created_at)
=> #<RuleResult:0x000055f2af0ab638
id: "8d8938b2-0f82-4d52-bac7-64024aa9531e",
host_id: "2566a863-7052-4045-abbe-056ddc9277ad",
rule_id: …
```
> [stable] Remove useless RuleResult records

- app/graphql/types/interfaces/rules_preload.rb
- test/graphql/queries/system_query_test.rb
We keep on getting an alert on "undefined method 'id' for nil:NilClass"
on the #alerts-cloudservices-apps.
After investigating, this alert happens because the system details page
is visited. We try to retrieve the latest Test Results for the profiles
for the System, and some RuleResults don't have a correct rule_id FK -
they're pointing to unknown rule_ids.
> irb(main):013:0> rule_ids.count
> => 4405
> irb(main):014:0> rule_ids = RuleResult.select(:rule_id).distinct.pluck(:rule_id); rule_ids.count
> => 4405
> irb(main):015:0> Rule.where(id: rule_ids).count
> => 3283
In our GQL API code, when we try to get the results for these
rules, they're showing up as "nil" and therefore they fail to
load.
*update*:
From this data, the rule results without a matching rule_id are all very old. I think …
> [stable] RHICOMPL-695 - Fix 'undefined method id' error on SystemDetails

- .gitignore
- db/schema.rb
Currently our pods don't have this, and we suspect it might be causing
issues as there's no authoritative source for the schema. It's being
looked at on the fly. Committing this provides a way for Rails to look
at how the schema should be from a file. Notice the top of the file even
recommends checking in the schema into the VCS
> Commit db/schema.rb

- test/graphql/mutations/associate_profiles_test.rb
Another array comparison issue - if the arrays aren't in the same order, the test fails. There is no order for a `Set`.
Failure seen here: https://jenkins-jenkins.5a9f.insights-dev.openshiftapps.com/blue/organizations/jenkins/compliance-backend/detail/PR-477/3/pipeline/
> Fix an intermittently failing associate_profiles test

- app/controllers/concerns/authentication.rb
- app/models/identity_header.rb
- test/controllers/concerns/authentication_test.rb
- test/models/identity_header_test.rb
From [this doc](https://docs.google.com/document/d/1PAzJqcUXlxg7t5cX1lsPsQtBPT_95bZbyB9Iiv_ekGM/edit#):
> The shape of the x-rh-identity object is as such:
```
{
"identity" : {
"account_number": String,
"type": String, // User or System
"auth_type": String, // cert-auth, basic-auth or jwt-auth
"user": {}, // optional if User
"system": {}, // optional if System
"internal": {},
}
}
```
> Check auth_type directly in the identity to determine cert auth

- app/models/concerns/profile_searching.rb
- app/models/xccdf/benchmark.rb
- test/models/benchmark_test.rb
- test/models/profile_test.rb
```rb
Profile.os_major_version(7)
Profile.search_for('os_major_version = 7')
Profile.os_major_version(7, false) # negative search i.e. != 7
Profile.search_for('os_major_version != 7')
Xccdf::Benchmark.os_major_version(6) # same syntax for benchmarks
Xccdf::Benchmark.search_for('os_major_version = 6')
Xccdf::Benchmark.os_major_version(8, false) # negative search i.e. != 8
Xccdf::Benchmark.search_for('os_major_version != 8')
```
https://projects.engineering.redhat.com/browse/RHICOMPL-703
> Allow searching benchmarks and profiles by OS major version

- config/routes.rb
Probes are returning 401 on CI already because the v1 namespacing in routes.rb shouldn't include the openAPI endpoint as the openapi controller already has embedded 'v1', 'v2' or whatever version is needed
> Fix readiness/liveness probes

- spec/api/v1/openapi.rb
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/benchmarks.rb
- spec/api/v1/schemas/errors.rb
- spec/api/v1/schemas/hosts.rb
- spec/api/v1/schemas/metadata.rb
- spec/api/v1/schemas/profiles.rb
- spec/api/v1/schemas/rule_results.rb
- spec/api/v1/schemas/rules.rb
- spec/api/v1/schemas/types.rb
- spec/api/v1/schemas/util.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
This should make the API specs much easier to maintain, especially as we
create new API versions. The entire API spec exists under spec/api/vX;
openapi schemas are separated into files depending on resource; utility
functions related to API schemas are separated into their own util
class. Note that this is just a refactoring and does not change the
openapi.json (other than some example ID for some reason).
> Version API spec to V1, refactor schema into files

- test/controllers/v1/openapi_endpoint_test.rb
`api/compliance/v1/openapi.json` test works fine.
> Add tests for openapi.json endpoints

- app/controllers/v1/profiles_controller.rb
- config/routes.rb
- spec/integration/profiles_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/profiles_controller_test.rb
A user may destroy any profile that is associated to their account, both
internal or external. Destroying a profile also removes associated test
results.
Towards https://projects.engineering.redhat.com/browse/RHICOMPL-595
```json
$ http DELETE https://ci.foo.redhat.com:1337/api/compliance/profiles/e8c1675a-49a0-4ac6-aa60-b58508a5c0d6
HTTP/1.1 202 Accepted
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Requested-With,content-type
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Origin: *
cache-control: no-cache
connection: close
content-type: application/vnd.api+json
date: Mon, 08 Jun 2020 18:26:30 GMT
transfer-encoding: chunked
vary: Origin
x-request-id: be4cec94-709f-4864-a7d5-650cfadeac89
x-runtime: 0.260293
{
"data": { …
```
> Implement profiles#destroy endpoint

- app/policies/profile_policy.rb
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/queries/profile_query_test.rb
- test/policies/profile_policy_test.rb
- test/policies/test_result_policy_test.rb
This updates the pundit policy for profiles to allow users to see
canonical profiles when searching or listing profiles
Canonical profiles must be visible to any user in order to pick a parent
profile during policy creation via the API or UI.
Note: Currently the UI does not use this pundit policy to limit the scope of
profiles visible to the user.
Requires frontend changes to add `canonical = false` to profile queries:
- https://github.com/RedHatInsights/compliance-frontend/pull/624
- https://github.com/RedHatInsights/frontend-components/pull/556
> Users may view/search for canonical profiles

- test/controllers/v1/profiles_controller_test.rb
Looks like we merged https://github.com/RedHatInsights/compliance-backend/pull/497 without properly rebasing and re-testing. Anyway, this should fix it.
> Fix failing profiles_controller#index tests

- app/services/rbac_api.rb
- test/services/rbac_api_test.rb
Well, this is embarrassing. Fixed, and now with tests!
`Rails.logger.info(...)` returns `true`
Tip: hide whitespace changes for easier reviewing.
https://github.com/RedHatInsights/compliance-backend/pull/503 fixes existing tests on the master branch
> Handle RBAC errors appropriately by returning 403

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/v1/profiles_controller.rb
- app/graphql/mutations/profile/create.rb
- app/models/business_objective.rb
- app/models/profile.rb
- app/serializers/profile_serializer.rb
- config/initializers/mime_types.rb
- config/routes.rb
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/profiles.rb
- spec/api/v1/schemas/types.rb
- spec/integration/profiles_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/profiles_controller_test.rb
- test/models/business_objective_test.rb
- test/models/profile_test.rb
Any params not specified are inherited from the parent profile
Minimal params:
```js
{
"data": {
"parent_profile_id": "1007b72e-7f0f-486f-911a-5c392c724faa"
}
}
}
```
All allowable params:
```js
{
"data": {
"parent_profile_id": "1007b72e-7f0f-486f-911a-5c392c724faa",
"name": "My profile",
"description": "The best profile ever",
"compliance_threshold": 95.0,
"business_objective": "LATAM Expansion"
}
}
}
```
rswag :( I'm trying to figure out how to pass JSON like parameters, but I haven't yet figured it out (see profiles_spec.rb).
> Implement profiles#create endpoint

- spec/api/v1/schemas.rb
- spec/api/v1/schemas/profiles.rb
- spec/api/v1/schemas/types.rb
- spec/integration/profiles_spec.rb
- swagger/v1/openapi.json
Before this PR, the documentation section of Swagger UI was lacking a
proper example and response. Now it's more accurate to what it is meant
to be.
Before - these fields were just `{}`.
After:
> Fix profiles create/delete request/response schema

- app/graphql/mutations/base_mutation.rb
- app/graphql/schema.graphql
- app/graphql/types/system.rb
- app/models/host.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/host_inventory_api.rb
- db/migrate/20200610083045_add_os_major_and_os_minor_to_hosts.rb
- db/schema.rb
- lib/tasks/import_host_os_releases.rake
- lib/tasks/sync_with_inventory.rake
- test/services/host_inventory_api_test.rb
- test/services/xccdf_report_parser_test.rb
Just a draft for now. The idea is to have these fields available to us so that:
- Supportability can be quickly checked
- Filtering becomes trivial
- Showing the OS doesn't require us waiting a potentially long time for inventory to release changes
- Hosts without an OS can be quickly deemed unsupported
> RHICOMPL-668 - Import os_major/minor on report parsing

- app/services/host_inventory_api.rb
- test/services/host_inventory_api_test.rb
Currently, when someone assigns a new system that doesn't exist in compliance to a policy, if the system doesn't have a os_release (which happens often on testing environments), we get the following error:
`NoMethodError: undefined method `split' for nil:NilClass`
This PR prevents that error from happening.
> RHICOMPL-748 - Support no os_release in inventory

- app/models/profile_host.rb
- test/models/profile_host_test.rb
When the following happens:
- A host is registered and assigned to an external policy
- The host is later on removed via System culling
The host is removed, but the external policy remains. This is
not only problematic because of the unused cruft in the
database, but also if the user tries to create a new Policy now
with the same ref ID, they won't be able to do it (422 error),
and they won't be able to remove the old Policy except through
the API (which is not in prod yet)
> RHICOMPL-750 - Remove external profiles after system culling

- app/controllers/application_controller.rb
- app/controllers/concerns/parameters.rb
- app/controllers/v1/benchmarks_controller.rb
- app/controllers/v1/profiles_controller.rb
- app/graphql/mutations/profile/create.rb
- app/models/profile.rb
- app/serializers/benchmark_serializer.rb
- config/initializers/wrap_parameters.rb
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/benchmarks.rb
- spec/api/v1/schemas/types.rb
- spec/integration/benchmarks_spec.rb
- spec/integration/profiles_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/profiles_controller_test.rb
- test/models/profile_test.rb
POST body containing rules relationships:
```js
{
"data": {
"parent_profile_id": "1007b72e-7f0f-486f-911a-5c392c724faa",
"name": "My tailored profile",
"compliance_threshold": 95.0
},
"relationships": {
"rules": {
"data": [
{
"id": "cc9afa66-3536-4d2e-bc8e-10111d13ec50",
"type": "rule"
},
{
"id": "06a19f0e-5c7a-4d54-bc66-e932a96bf954",
"type": "rule"
},
{
"id": "fcd8ee29-5af4-47bf-9e29-2de12f20fe9a",
"type": "rule"
}
]
}
}
}
}
HTTP/1.1 201 Created
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Requested-With,content-type
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Origin: *
cache-control: max-age=0, private, must-revalidate
connection: close
content-type: application/vnd.api+json
date: Tue, 23 Jun 2020 …
```
> Allow rules to be tailored on profiles#create API

- app/jobs/delete_host.rb
- app/jobs/destroy_profiles_job.rb
- app/jobs/inventory_host_updated_job.rb
- app/jobs/parse_report_job.rb
- test/jobs/delete_host_test.rb
- test/jobs/inventory_host_updated_job_test.rb
Currently, it's very hard for QE to test which systems are getting deleted and which aren't in order to test https://github.com/RedHatInsights/compliance-backend/commit/0b9466cc011945326c849a60a5d5e2de65748e6d. 
This adds extra logging to all jobs, which will probably be useful in the future to figure out what is happening, particularly in production where there is no Payload Tracker.
> Add more logging to Sidekiq jobs

- app/controllers/concerns/parameters.rb
- app/controllers/v1/profiles_controller.rb
- app/models/concerns/profile_hosts.rb
- app/models/concerns/profile_rules.rb
- app/models/profile.rb
- spec/integration/profiles_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/profiles_controller_test.rb
- test/models/profile_test.rb
Works the same as the rules relationship:
```js
PATCH api/v1/profiles/{uuid}
{
"data": {
"name": "My updated tailored profile",
"compliance_threshold": 90
},
"relationships": {
"rules": {
"data": [
{
"id": "cc9afa66-3536-4d2e-bc8e-10111d13ec50",
"type": "rule"
},
{
"id": "06a19f0e-5c7a-4d54-bc66-e932a96bf954",
"type": "rule"
},
{
"id": "fcd8ee29-5af4-47bf-9e29-2de12f20fe9a",
"type": "rule"
}
]
},
"hosts": {
"data": [
{
"id": "cc9afa66-3536-4d2e-bc8e-10111d13ec50",
"type": "host"
}
]
}
}
}
}
```
Also works with POST/create.
Based on changes in https://github.com/RedHatInsights/compliance-backend/pull/510 - I will rebase this PR once 510 is merged.
> [RHICOMPL-467] Allow host/profile association via API V1

- app/controllers/v1/rule_results_controller.rb
- app/controllers/v1/rules_controller.rb
- app/graphql/types/system.rb
- app/models/concerns/system_like.rb
- app/models/host.rb
- app/serializers/host_serializer.rb
- app/serializers/rule_serializer.rb
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/hosts.rb
- spec/api/v1/schemas/rule_results.rb
- spec/api/v1/schemas/rules.rb
- spec/integration/benchmarks_spec.rb
- spec/integration/rule_results_spec.rb
- spec/integration/rules_spec.rb
- spec/integration/systems_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/rules_controller_test.rb
This revisits all controllers, serializers, specs, schemas, etc. for API V1. So far we have implemented profiles and benchmarks. This matches that work to the other V1 resources.
> Match serializers to openapi spec

- app/policies/profile_policy.rb
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/queries/profile_query_test.rb
- test/policies/profile_policy_test.rb
- test/policies/test_result_policy_test.rb
This updates the pundit policy for profiles to allow users to see
canonical profiles when searching or listing profiles
Canonical profiles must be visible to any user in order to pick a parent
profile during policy creation via the API or UI.
Note: Currently the UI does not use this pundit policy to limit the scope of
profiles visible to the user.
Related to https://projects.engineering.redhat.com/browse/RHICOMPL-595
> [stable] 595 canonical searchable

- app/models/rule.rb
- app/models/xccdf/benchmark.rb
Just some fixes for deprecations to remove warning messages - nothing should have changed logically.
> s/alias/aliases/ for scoped_search deprecation

- app/controllers/v1/systems_controller.rb
- config/routes.rb
- spec/integration/systems_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/systems_controller_test.rb
This adds parity to the systems API with our other V1 APIs
- Add a systems#show endpoint
- Allow specifying includes in the hosts API
https://projects.engineering.redhat.com/browse/RHICOMPL-763
> Add hosts#show and add includes to hosts API

- app/consumers/application_consumer.rb
- app/consumers/compliance_reports_consumer.rb
- app/consumers/inventory_events_consumer.rb
While debugging our consumers recently, I realized that not all messages are logged; sometimes validations are performed first, which makes it difficult to debug what went wrong. Shared logic like logging should be part of the ApplicationConsumer.
This is fine to merge as is, but I may add to it as I continue to debug the consumers.
> Ensure all consumers log all messages received

- app/graphql/mutations/base_mutation.rb
- app/services/concerns/xccdf/hosts.rb
- test/graphql/mutations/associate_profiles_test.rb
- test/graphql/mutations/associate_systems_test.rb
- test/services/concerns/xccdf/hosts_test.rb
- test/services/host_inventory_api_test.rb
- test/services/reports_tar_reader_test.rb
- test/services/xccdf_report_parser_test.rb
Our Host model requires a non-empty name. The display_name from
inventory is either the fqdn or the id if fqdn is null, so it's never null.
> RHICOMPL-760 Use display_name instead of fqdn from inventory

- .gitignore
The ssg:sync_rhel rake tasks lays down SSG files for RHEL 6, 7, and 8.
We won't ever want to commit them to the repo unless as part of the
tests.
> Ignore scap-security-guide content in the repo

- config/initializers/sidekiq.rb
In the sidekiq logs, constantly, is printed:
```
`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/opt/app-root/src/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/launcher.rb:105:in `block (2 levels) in ❤')
```
Sidekiq doesn't offer an updated version that fixes this deprecation yet.
> Mute sidekiq Redis.exists logs

- app/models/application_record.rb
- app/models/rule_reference.rb
- app/models/rule_references_rule.rb
- app/services/concerns/xccdf/rule_references.rb
- app/services/concerns/xccdf/rule_references_rules.rb
- app/services/concerns/xccdf/test_result.rb
- test/models/rule_reference_test.rb
- test/services/concerns/xccdf/rule_references_rules_test.rb
- test/services/concerns/xccdf/rule_references_test.rb
This change essentially boils down to removing N `selects` for N / 1000 (due to batch size). In order to accurately parse a report, we must determine if the records already exist in the DB. Before, we were using `find_or_initialize_by` for each RuleReference and RuleReferencesRule (37K records just for this table in the RHEL 7 0.1.46 SSG). Now we are executing a where query to determine existing records and only importing new records.
Importing RHEL 7 SSG, version 0.1.46, initial and subsequent imports. Initial import takes about half the time:
```
rake ssg:import DATASTREAM_FILE='./scap-security-guide-0.1.46/ssg-rhel7-ds.xml'
Importing ./scap-security-guide-0.1.46/ssg-rhel7-ds.xml at 2020-07-30 04:14:25 UTC
Finished importing ./scap-security-guide-0.1.46/ssg-rhel7-ds.xml in 86.885234702 …
```
> Improve parsing performance

- lib/tasks/import_host_os_releases.rake
`end_time` is not defined and causes an error running this task.
> Fix import_host_os_releases failing with missing end_time

- app/services/concerns/xccdf/rule_references_rules.rb
Before, new_rule_references_rules was always the entire set. This PR uses the RuleReferencesRulesStruct and subtraction rather than a loop with `reject` and `include?` which took forever to run (not sure why we didn't catch this on the first PR).
Towards https://projects.engineering.redhat.com/browse/RHICOMPL-698
> Fix finding new rule references rules in parsing

- lib/tasks/import_host_os_releases.rake
A very low-risk change that fixes the import_host_os_releases job
> [stable] Fix import_host_os_releases failing with missing end_time

- app/consumers/concerns/report_parsing.rb
- app/consumers/inventory_events_consumer.rb
- test/consumers/inventory_events_consumer_test.rb
When I implemented this, I thought it'd be good to memoize some of these things, especially `report_contents` since it pulls from S3. It turns out that racecar consumers keep a single object around the entire time, so every time we get a message, we're dealing with the exact same object with all instance variables set from the last time.
Introduced in https://github.com/RedHatInsights/compliance-backend/pull/528
Related to https://projects.engineering.redhat.com/browse/RHICOMPL-765
> Un-memoize instance variables in inventory-consumer

- app/services/concerns/xccdf/benchmarks.rb
- test/services/concerns/xccdf/benchmarks_test.rb
`benchmark.profiles` includes non-canonical profiles. When parsing, only canonical profiles are created for a benchmark, so we can skip parsing the benchmark if the canonical profiles match the existing report.
> Benchmarks have been parsed if canonical profiles match

- config/racecar.rb
Consumer group IDs of all services should be unique and the service easily identifiable. Now, our consumer group IDs will have the format `compliance.inventory-events-consumer`
https://projects.engineering.redhat.com/browse/RHICOMPL-827
> [RHICOMPL-827] Add 'compliance' kafka group prefix

- app/controllers/concerns/inventory_service_helper.rb
- app/controllers/v1/profiles_controller.rb
- app/graphql/mutations/base_mutation.rb
- app/graphql/mutations/profile/associate_systems.rb
- app/graphql/mutations/system/associate_profiles.rb
- spec/integration/profiles_spec.rb
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/mutations/associate_systems_test.rb
When a profile and host are associated but the host only exists in the
inventory, we must create the host from the inventory in our own
database. We must handle this in both REST and graphql. This change
consolidates the two code paths to use the same InventoryServiceHelper.
> [RHICOMPL-467] Consolidate REST and graphql inventory logic

- docker-compose.yml
https://projects.engineering.redhat.com/browse/RHICOMPL-844
Debugging with 5 concurrent job workers is tough, and there is no real load locally, so it makes sense to only allow 1 job at a time.
> [RHICOMPL-844] Set sidekiq concurrency to 1 in devel

- app/controllers/concerns/inventory_service_helper.rb
- app/jobs/inventory_host_updated_job.rb
- app/models/host.rb
- app/services/concerns/xccdf/hosts.rb
- test/models/host_test.rb
Now, every time we update our host record from the inventory (3 places
total), we update the host's name and OS information. Updates happen
during report parsing, InventoryHostUpdatedJob, and when we initially
create the host from an existing inventory record.
> [RHICOMPL-574] Update host OS info from inventory

- lib/tasks/sync_with_inventory.rake
- test/tasks/sync_with_inventory_test.rb
I'm not sure how this ever worked without saving the host to the DB. Now with a test!
https://projects.engineering.redhat.com/browse/RHICOMPL-574
> [RHICOMPL-574] sync_with_inventory actually saves host

- app/services/remediations_api.rb
- config/initializers/exception_notification.rb
- lib/tasks/import_datastream.rake
- test/services/remediations_api_test.rb
- test/tasks/import_datastream_test.rb
This change adds connection errors to the list of rescued errors when
importing remediations. It also ensures that any exceptions that are
raised cause the entire rake task to fail (ssg:import_latest_supported).
It also updates the slack channel for exception notifications to
forum-cloudservices-compliance.
https://projects.engineering.redhat.com/browse/RHICOMPL-838
> [RHICOMPL-838] Rescue remediations errors, bubble errors on import

- app/models/host.rb
- app/services/host_inventory_api.rb
- test/models/host_test.rb
- test/services/host_inventory_api_test.rb
JSON always comes in as string keys, not symbols, in hashes from the
inventory API.
To test:
Start with a host that doesn't have OS information in the Compliance DB
```rb
[11] pry(main)> Host.find('73050cfc-52bb-4f8a-87d5-ba2b1b1be4be')
Host Load (0.4ms)  SELECT  "hosts".* FROM "hosts" WHERE "hosts"."id" = $1 LIMIT $2  [["id", "73050cfc-52bb-4f8a-87d5-ba2b1b1be4be"], ["LIMIT", 1]]
=> #<Host:0x0000564284446e80
id: "73050cfc-52bb-4f8a-87d5-ba2b1b1be4be",
name: "rhel7-insights-client.virbr0.akofink-desktop",
created_at: Tue, 01 Sep 2020 13:54:46 UTC +00:00,
updated_at: Tue, 01 Sep 2020 15:18:06 UTC +00:00,
account_id: "a8477b45-60f1-4ccf-8f64-0934ca2e2aab",
os_major_version: nil,
os_minor_version: nil>
```
Run sync_with_inventory:
```
podman exec -it  compliance-backend_rails_1 bundle exec …
```
> [RHICOMPL-574] Ensure host inventory API uses string hashes

- app/models/host.rb
- app/services/host_inventory_api.rb
- test/models/host_test.rb
- test/services/host_inventory_api_test.rb
JSON always comes in as string keys, not symbols, in hashes from the
inventory API.
> [stable][RHICOMPL-574] Ensure host inventory API uses string hashes

- app/models/profile.rb
- test/models/profile_test.rb
- test/services/xccdf_report_parser_test.rb
When parsing a test result upload, rules of existing profiles should
never be updated.
https://projects.engineering.redhat.com/browse/RHICOMPL-778
> [RHICOMPL-778] Rule updates never happen to existing profiles

- docker-compose.yml
Remove duplicate `links` declarations, and leave only `rails` service having SDIN opened.
(RHICOMPL-875)
> [RHICOMPL-875] Docker-compose: Clean up duplicate params and sdin

- app/models/profile.rb
- test/models/profile_test.rb
- test/services/xccdf_report_parser_test.rb
When parsing a test result upload, rules of existing profiles should
never be updated.
https://projects.engineering.redhat.com/browse/RHICOMPL-778
> [stable][RHICOMPL-778] Rule updates never happen to existing profiles

- config/application.rb
Environment variables from `.env` (dotenv-rails) are loaded too late, after `Settings` are already set up. They should be evaluated before the settings.
To test:
```
export SETTINGS__REDIS_URL=redis_from_dotenv
```
```shell
DISABLE_SPRING=true bundle exec rails c
> Settings.redis_url
=> "redis_from_dotenv"
```
> [RHICOMPL-890] Load dotenv before Settings are initialized

- app/services/platform.rb
- config/settings/development.yml
This is required for local development. In deployed environments, 3Scale
generates the X_RH_IDENTITY header from different auth types (basic,
jwt, etc); locally, we must pass the header directly. For platform
services that are running in CI behind 3Scale (rbac, remediations, etc.),
the header will not work, so basic auth must be set.
> [RHICOMPL-922] Allow setting platform basic auth

- app/services/concerns/xccdf/hosts.rb
- app/services/host_inventory_api.rb
This was not caught by our tests because Xccdf::Hosts was referenced and loaded. You can check it in the console:
```rb
[1] pry(main)> InventoryHostNotFound
NameError: uninitialized constant InventoryHostNotFound
from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
Caused by NameError: uninitialized constant InventoryHostNotFound
from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
[2] pry(main)> Xccdf::Hosts
=> Xccdf::Hosts
[3] pry(main)> InventoryHostNotFound
=> InventoryHostNotFound
[1] pry(main)> InventoryHostNotFound
NameError: uninitialized constant InventoryHostNotFound
from …
```
> [RHICOMPL-904] Move InventoryHostNotFound back to HostInventoryAPI

- config/settings/development.yml
- docker-compose.yml
Expect redis to be listening on localhost in development environment.
This allows to have redis running locally or in container with bounded
port.
> Dev: Bind redis to localhost

- app/jobs/parse_report_job.rb
- app/models/concerns/rule_remediation.rb
- app/models/rule.rb
- app/producers/remediation_updates.rb
- app/services/concerns/xccdf/rule_results.rb
- app/services/remediations_api.rb
- docker-compose.yml
- test/jobs/parse_report_job_test.rb
- test/producers/remediation_updates_test.rb
- test/services/xccdf_report_parser_test.rb
Reports issues from failed IDs on every report parse to the Remediation
service via Kafka.  The used topic is
`platform.remediation-updates.compliance`.
Also refactors generation of remediation issue ids.
> [RHICOMPL-759] Issue updates to Remediation service

- app/serializers/benchmark_serializer.rb
- spec/api/v1/schemas/benchmarks.rb
- swagger/v1/openapi.json
```json
GET /compliance/api/v1/benchmarks
{
"data": [
{
"id": "8036e3a9-9e97-4658-ac1f-5a0c03daac5d",
"type": "benchmark",
"attributes": {   
"ref_id": "xccdf_org.ssgproject.content_benchmark_RHEL-6",
"title": "Guide to the Secure Configuration of Red Hat Enterprise Linux 6",
"version": "0.1.28",
"description": "This guide presents a catalog of security-relevant configuration settings for Red Hat Enterprise Linux 6. It is a rendering of content structured in the eXtensible Configuration          
Checklist Description Format (XCCDF) in order to support security automation.  The SCAP content is is available in the scap-security-guide package which is developed at http://fedorahosted.org/scap-security-guid
e. Providing system administrators with such guidance informs them how to securely …
```
> [RHICOMPL-840] Include os_major_version in benchmarks API

- app/jobs/parse_report_job.rb
- app/models/concerns/rule_remediation.rb
- app/services/remediations_api.rb
- test/models/rule_test.rb
Generation of `remediation_issue_id`s dependent on having a rule with
a canonical profile.  This expectation has been broken, and this fix
allows the generation of issue ids without needing a canonical profile
for a rule.
> [RHICOMPL-965] Fix remediation import for rules w/o canonical profile

- app/models/profile_host.rb
- test/models/profile_host_test.rb
Before this change, deleting a profile with hosts associated may have
deleted the hosts as well if they were not associated with any other
profiles. After this change, we will only remove hosts from our database
during an Inventory culling message in kafka.
> [RHICOMPL-987] Do not delete orphaned hosts

- app/jobs/parse_report_job.rb
- app/models/concerns/rule_remediation.rb
- app/models/profile.rb
- app/services/remediations_api.rb
- test/models/profile_test.rb
- test/models/rule_test.rb
Generate remediation issue id's OS part based on its profile/benchmark. Do not hardcode the "rhel7" value, in order to support different major OS versions.
> [RHICOMPL-991] Major OS ver for remediation issue id

- app/jobs/parse_report_job.rb
- app/services/concerns/xccdf/util.rb
- app/services/xccdf_report_parser.rb
- test/fixtures/files/xccdf_report.xml
- test/services/xccdf_report_parser_test.rb
Raise `OSVersionMismatch` if the major OS version does not match benchmark's.
Example error:
```
ERROR: Cannot parse report: OS major version (7) does not match with benchmark xccdf_org.ssgproject.content_benchmark_RHEL-8 (8)
```
> [RHICOMPL-544] Validate OS major version of uploaded report

- app/controllers/v1/supported_ssgs_controller.rb
- app/models/supported_ssg.rb
- app/serializers/supported_ssg_serializer.rb
- config/routes.rb
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/supported_ssgs.rb
- spec/integration/supported_ssgs_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/supported_ssgs_controller_test.rb
- test/models/supported_ssg_test.rb
Mapping of RHEL minor version release to a supported SSG version package available on REST API.
Example of one record:
```
{
"id": "RHEL-7.3",
"type": "supported_ssg",
"package": "scap-security-guide-0.1.30-5.el7_3",
"version": "0.1.30",
"os_major_version": "7",
"os_minor_version": "3",
"profiles": [
"C2S",
"cjis-rhel7-server",
"common",
"nist-cl-il-al",
"ospp-rhel7-server",
"pci-dss",
"rht-ccp",
"standard",
"stig-rhel7-server-gui-upstream",
"stig-rhel7-server-upstream",
"stig-rhel7-workstation-upstream"
]
}
}
```
> [RHICOMPL-927] REST API for supported RHEL and SSG version

- app/models/account.rb
- app/models/business_objective.rb
- app/models/concerns/profile_hosts.rb
- app/models/concerns/profile_policy_association.rb
- app/models/concerns/profile_searching.rb
- app/models/host.rb
- app/models/policy.rb
- app/models/policy_host.rb
- app/models/profile.rb
- test/fixtures/policies.yml
- test/models/account_test.rb
- test/models/business_objective_test.rb
- test/models/host_test.rb
- test/models/policy_host_test.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
- test/models/test_result_test.rb
Adapted all non-breaking model changes from https://github.com/RedHatInsights/compliance-backend/pull/572
Smoke test result run locally (3 failures related to rbac that also exist on master):
```
3 failed, 85 passed, 1 skipped, 126 deselected, 333 warnings in 329.08s (0:05:29)
```
> [RHICOMPL-1042] Add policy related non-breaking model changes

- app/models/concerns/profile_searching.rb
Profile's policy association is temporarily named `policy_object`
therefore the previous scope with `policy` did not work.  Lets use the
field name `policy_id` so it works also after the temporary name is
changed back.
> [RHICOMPL-1042] Fix Profile scope with_policy

- app/models/profile.rb
- test/models/profile_test.rb
Having a profile unique by a policy before the policy model is fully
used breaks creation of new internal profiles that already have an
`external: true` variant.
Response with the constraint:
```
Response not successful: Received status code 422
<ActiveRecord::RecordInvalid: Validation failed: Ref has already been taken>
```
References: https://github.com/RedHatInsights/compliance-backend/pull/604#discussion_r505419339
> [RHICOMPL-1042] Profile is not yet uniq by a policy

- app/models/policy.rb
Policy names can be the same across account.
> [RHICOMPL-1042] Fix Policy to allow duplicate names

- app/services/copy_profiles_to_policies.rb
- db/migrate/20201015174517_copy_data_to_policy_first_pass.rb
- db/schema.rb
- test/services/copy_profiles_to_policies_test.rb
Creates a service for copying profiles into Policies.
The service creates new Policy models for Profiles that are internal and
that do not have a Policy.  It copies some of the attributes from the
profile.  It assigns the same host set from the internal profile.
The first pass for migration of profile data to policies is mostly intended for testing the migration.
Production should be migrated only when the whole feature is complete.
**IMPORTANT**
We first need to decide whether to do a simpler migration (this PR) or migrate it by using a virtual policy.
Original virtual policy lookup for external profiles:
```
Profile.includes(:benchmark)
.older_than(created_at)
.find_by(account: account_id, external: false, ref_id: ref_id,
benchmarks: { ref_id: benchmark.ref_id })
```
> [RHICOMPL-662] Migration of old profile data into new policy records

- app/controllers/concerns/rendering.rb
- test/controllers/concerns/rendering_test.rb
This is in support of RHICOMPL-661 and is a non-breaking change. It will allow rendering the errors of multiple models instead of just one. The ProfilesController will require this when creating multiple different records in one HTTP request.
> [RHICOMPL-1048] Allow rendering multiple model errors

- test/services/copy_profiles_to_policies_test.rb
As the business_objective is going to be delegated to Policy from a Profile.
> [RHICOMPL-1042] Use BO id on Profile test setup

- app/models/profile.rb
- db/migrate/20201021083148_change_uniq_on_profiles.rb
- db/schema.rb
- test/models/profile_test.rb
To support the new Policy model, the db unique constraint must be changed to include `policy_id`. Policies can have the same profiles (ref_id and benchmark), but need a different rule set.
It adds a validation, to ensure that a policy has only one profile for an SSG (ref_id and benchmark) regardless of an `external` boolean field value.
To keep the previous uniqueness by `external` field, there is a validation added for profiles that are outside of a policy. This is an intermid solution, before the Policy model is fully used. All internal profiles are expected to have a policy. Note, that the `external` field will be deprecated soon.
/cc @Victoremepunto to check the assumptions/conditions (ty!)
> [RHICOMPL-1049] Profile uniqueness in a policy

- app/models/profile.rb
- app/services/copy_profiles_to_policies.rb
- test/models/profile_test.rb
The external uniqueness for profiles outside of a policy has to include the validation condition also in the duplicate/relation lookup.
Ensure that profile data migration validates policy assignment.
> [RHICOMPL-1049] Fix external Profile uniqueness outside of a policy

- app/models/profile.rb
- test/models/profile_test.rb
There should not be two internal profiles with the same ref_id, benchmark and account.
This keeps the constraint/expectation as it was before Policy model.
> [RHICOMPL-1049] Internal profiles should be unique for an account

- app/models/concerns/profile_policy_association.rb
- app/models/profile.rb
- test/models/profile_test.rb
Lookup policy based on the host(s). Assign newly created profile into the found policy.
For Profile.clone_to it first finds the policy of the passed account.
The policy lookup up starts with the internal profile.
The internal profile:
* must have a policy that have the host assigned
* must be part of the account
* must match the ref_id of the (canonical) profile being cloned
* must match the benchmark ref_id of the profile being cloned
The last benchmark condition is there to ensure that the internal profile is
for the same major OS version.
The policy object is then retrieved from the internal profile.
The second step of the clone_to is to find an existing profile on that
policy.  The existing profile has to match the benchmark id.
> [RHICOMPL-1051] Lookup policy on profile clone

- app/models/concerns/system_like.rb
- app/models/host.rb
- test/models/host_test.rb
The REST API should return a host's assigned profiles (via its policies)
not profiles via test_results.
Validate by running `test_rest_api.py::test_associate_systems_policy` smoke test
> fix(RHICOMPL-1054): Host profiles are assigned_profiles

- app/serializers/host_serializer.rb
This is how this API behaved before we removed the ProfileHost
relationship. It's not super useful IMO, but it keeps the API
expectations unbroken.
> [RHICOMPL-1054] Hosts API returns assigned and test_result profiles

- app/controllers/application_controller.rb
- app/controllers/concerns/default_headers.rb
- test/controllers/concerns/default_headers_test.rb
Default headers were not being set for an API only controllers. This
issue has been fixed in Rails 6.0.
References:
https://github.com/rails/rails/commit/f22bc41a92e8f51d6f6da5b840f3364474d6aaba
https://github.com/rails/rails/pull/32484
> [RHICOMPL-1037] Use default headers also on API controllers

- app/graphql/types/profile.rb
- app/models/concerns/profile_policy_association.rb
- app/models/policy.rb
- test/graphql/queries/profile_query_test.rb
The GraphQL Profile.policy will return the initial profile of the associated policy.
See also: https://github.com/RedHatInsights/compliance-backend/pull/622#discussion_r510953270
> [RHICOMPL-1062] GraphQL to use profile policy association

- app/graphql/types/profile.rb
- test/graphql/queries/profile_query_test.rb
The pseudo-policy returned on the GraphQL for a profile should inherint
name and description from the policy.
The database records of profiles are keeping the original names and
descriptions (from their parent profiles).
This allows to use the `Profile.name` as policy/profile type, and
`Profile.policy.name` as the policy title (user defined).
Note, that REST API returns name and description of profiles from their
policies.  The policy/profile type on the REST API can be retrieved by
requesting canonical profiles based using the `parent_profile_id`.
> [RHICOMPL-1035] GraphQL: Pseudo-policy should inherit name and desc

- app/graphql/schema.graphql
- app/graphql/types/concerns/profile_pseudo_policy.rb
- app/graphql/types/profile.rb
- test/graphql/queries/profile_query_test.rb
Policy profiles are to be queried on a profile's policy.
All policy profiles are returned including the internal/initial profile.
Recommended way of querying:
```
query Profile($anyPolicyProfileId: String!){
profile(id: $anyPolicyProfileId) {
policy {
profiles {
id
ssgVersion  # to be added
rules {
id
}
}
}
}
}
```
Note, that there can be a case when an internal profile would be the same
as its policy (since there is no Policy GraphQL type, yet) and would be
also found in the list of policy profiles.
> [RHICOMPL-1053] Return policy profiles on GraphQL

- app/graphql/types/system.rb
- app/models/host.rb
- app/serializers/host_serializer.rb
- test/graphql/queries/system_query_test.rb
- test/models/host_test.rb
GraphQL will return all system profiles, consisting of assigned profiles (through a policy) and profiles from test results. 
This should fix showing failed rules on external reports.
Redundant `Host.profiles` association is being dropped in favor of `associated_profiles`, `test_result_profiles` and combined
`all_profiles`.
> [RHICOMPL-1063] Return all system's profiles on GraphQL

- app/models/host.rb
- test/models/host_test.rb
Search supports lookup either by policy id or by a profile id that the host is assigned to through its policy.
This would allow SystemsTable to query the systems on any of the policy profiles.
> [RHICOMPL-1069] Host scope search by policy

- app/models/concerns/profile_policy_association.rb
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/mutations/delete_profile_mutation_test.rb
- test/models/profile_test.rb
**Option 1** (via callback)
Removal of an internal/main profile (`external=false`) of a policy would
remove its policy with all dependent profiles (`external=true`).
The callback is used to guarantee data sanity, eg. when a benchmark is destroyed.
Pros:
* no change needed for UI
* other SSG profiles (with tailoring) on a policy could be removed individually
Cons:
* more than one (same-type) REST resource would be removed
* IQE would need to know which profiles are part of which policy (RHICOMPL-1078)
* main policy profile/SSG could not be removed individually without removing all policy profiles
* this behavior would likely change if the v2 API would be created with real policy type/resource
> [RHICOMPL-1074] Internal/main policy profile deletes whole policy via callback

- app/graphql/mutations/profile/edit.rb
- test/graphql/mutations/edit_policy_mutation_test.rb
via GraphQL. Sending null as the business_objective_id will now unset
the business objective from the profile's policy.
> [RHICOMPL-1070] Allow unsetting the business objective via GQL

- app/models/concerns/profile_policy_association.rb
- test/models/profile_test.rb
- test/services/copy_profiles_to_policies_test.rb
- test/services/duplicate_benchmark_resolver_test.rb
A new validation that happens only on create that ensures no other policy exists in the same account with the same policy type. Policy type is currently just the associated profiles' ref_ids. To test:
1. Create a RHEL 7 HIPAA policy in the UI
2. Import another RHEL 7 benchmark with a different SSG version
3. Create another policy via the REST API and select the new benchmark's HIPAA canonical profile as the parent profile
Before:
The API allows the action, and the policies UI displays two HIPAA policies
After:
The API detects a duplicate policy type and errors
> [RHICOMPL-841] Prevent creating policies with duplicate types

- app/models/host.rb
- test/graphql/queries/system_query_test.rb
- test/models/host_test.rb
This fixes a bug for the frontend, where the policy_id is used to
retrieve hosts for an external profile.
> [RHICOMPL-1083] Host policy_id filter finds external profile via results 

- app/services/concerns/xccdf/test_result.rb
- test/services/concerns/xccdf/test_result_test.rb
Old test results that are within the same policy for a host will now be
removed when new test results are imported for that host. The same will
happen outside of a policy (i.e. with external reports). The old
behavior would not clean up test reports across SSG versions, but this
new version does.
> feat(RHICOMPL-1086): Delete old test results within a policy

- app/serializers/profile_serializer.rb
- test/controllers/v1/profiles_controller_test.rb
REST v1 for profiles would return hosts for an external profile, if the
host uploaded a report.
> [RHICOMPL-1090] Hosts for external profile from test results on REST

- app/models/concerns/profile_policy_association.rb
- app/serializers/profile_serializer.rb
- spec/api/v1/schemas/profiles.rb
- swagger/v1/openapi.json
- test/controllers/v1/profiles_controller_test.rb
- test/models/profile_test.rb
For both graphql and REST. The policy profile is the initial profile on
a policy. Profiles without policies will return their own ID as the
policy profile ID to support 'external policies'.
> feat(RHICOMPL-1078): Expose policy profile ID on profile

- app/models/xccdf/benchmark.rb
CIS is introduced in 0.1.50 both downstream and upstream for RHEL 8. See https://docs.google.com/spreadsheets/d/1erpNef7jVedqTN8x64N50Z4gFIYPUtiAbD28nHJB6fs/edit#gid=0.
> feat(RHICOMPL-1088): Bump RHEL 8 to SSG 0.1.50

- app/graphql/schema.graphql
- app/graphql/types/system.rb
- app/models/concerns/profile_searching.rb
- app/models/host.rb
- test/graphql/queries/system_query_test.rb
- test/models/profile_test.rb
First, it introduces scope `in_policy` on Profile for querying profiles under a policy, by providing:
* the exact profile id
* any policy profile id (returns/scopes all policy profiles)
* policy id (returns/scopes all policy profiles)
Adds possibility to custom scoping of Host.all_profiles by returning an `ActiveRecord::Relation`.
And finally it adds an argument `policyId` on field `profiles` of `Systems` GraphQL type.
Provided `policyId` would filter system's assigned profiles and profiles from test results.
The behavior of filtering is the same as for the scope `policy_bunch` (on `Profile` model).
Review Recommendation: go by commits.
> [RHICOMPL-1027] Filter System profiles by policyId on GraphQL

- README.md
Re-deployment is needed due to a possible race condition with migrations
and already initiated backend containers.
Got exception:
ActiveModel::MissingAttributeError
can't write unknown attribute 'policy_id'
app/graphql/mutations/profile/create.rb:28:in `block in resolve'
> [RHICOMPL-1081] Redeployment & README migration note

- app/graphql/mutations/test_result/delete.rb
- test/graphql/mutations/delete_test_result_mutation_test.rb
The test we had for this case relied on `external=true` rather than the
policy association existing, thus not catching the bug. I've updated the
test and the code to delete the profile only if no policy exists; for
internal policies, deleting the test results for the initial profile
deletes test results for the entire policy's profiles.
> fix(Test result deletion): RHICOMPL-1109 keeps policy profile

- app/models/supported_ssg.rb
- config/supported_ssg.yaml
- lib/tasks/import_datastream.rake
- test/models/supported_ssg_test.rb
Syncs uptream SSGs from the supported matrix mapped to RHEL minor version.
Note, that downstream might backport rules to the older versions of SSGs. Currently this app handles/syncs SSGs from upstream, therefore it needs to store both versions.  Downstream version for checking supportability and upstream for syncing benchmarks.
> [RHICOMPL-948] Sync SSGs out of supported matrix 

- lib/tasks/sync_with_inventory.rake
- test/tasks/sync_with_inventory_test.rb
We're getting `Faraday::ForbbidenError`s in the sync_with_inventory job in prod. It's most likely related to the new RBAC changes and some accounts that don't have inventory:read access. In any case, we should handle this and any other Faraday errors (any issue related to the inventory request) by just skipping over the account and continuing the job to completion. Hopefully rescuing [`Faraday::Error`](https://www.rubydoc.info/github/lostisland/faraday/Faraday/Error) will accomplish this for good. It includes the following direct known subclasses: `ClientError, ConnectionFailed, ParsingError, RetriableResponse, SSLError, ServerError`
> fix(sync_with_inventory): RHICOMPL-1126 handle all Faraday errors

- app/graphql/types/concerns/profile_pseudo_policy.rb
- test/graphql/queries/profile_query_test.rb
Initial (main) policy profile should return name and the description
from the policy on GraphQL, which are user defined.
Profile and pseudo policy (profile) would return same name and the
description on GraphQL, if they are the same objects.
This will fix the problem of caching on UI, where the same GQL objects
(identified by id) had a different values depending on context.
It should also improve and fix filtering and displaying in UI.
> fix(Profile): RHICOMPL-1077 RHICOMPL-1116 RHICOMPL-1115 GraphQL to return policy name and desc

- app/graphql/types/profile.rb
- app/models/profile.rb
- app/models/supported_ssg.rb
- app/services/concerns/xccdf/test_result.rb
- db/migrate/20201116160531_add_supported_to_test_results.rb
- db/schema.rb
- test/models/supported_ssg_test.rb
- test/services/concerns/xccdf/test_result_test.rb
For each test result that we save, we will compare the host's OS to the
supported SSG matrix and appropriately mark the test result as supported
or not.
Old test results will be shown as supported (see DB migration default).
Reports associated to a host with valid OS information and a matching SSG
version in the report's profile will be marked as supported.
For hosts without OS information or for mismatched OS/SSG, the test
result is marked as unsupported.
> feat: RHICOMPL-724 Mark test results as (un)supported

- app/graphql/types/concerns/profile_pseudo_policy.rb
- test/graphql/queries/profile_query_test.rb
- test/graphql/queries/system_query_test.rb
Aligns GraphQL with REST API in regards to returning name and
description of profiles that are under a policy.  Both now take the
fields from its policy.
This fixes frontend Systems table and details, where reported
profiles and rules are listed.  On System details cards will
list correct user-defined name, and the rules table will show
correct value on the Policy column.
To get the original profile name consumer can request `policyType`
(or retrieve it from a corresponding canonical profile).
> fix(Profile): RHICOMPL-1140 policy name and description on GQL

- lib/tasks/import_datastream.rake
Fixes unzipping error/warning:
```
Archive:  scap-security-guide-0.1.28.zip
inflating: scap-security-guide-0.1.28/ssg-rhel6-ds.xml
caution: filename not matched:  scap-security-guide-0.1.28/ssg-rhel6-ds.xml
caution: filename not matched:  scap-security-guide-0.1.28/ssg-rhel6-ds.xml
```
unzip returned non-zero exit code, which resulted in skipped datastream file for import.
The reason is this command that is being issued:
```
unzip -o scap-security-guide-0.1.28.zip scap-security-guide-0.1.28/ssg-rhel6-ds.xml scap-security-guide-0.1.28/ssg-rhel6-ds.xml scap-security-guide-0.1.28/ssg-rhel6-ds.xml
```
> fix(ssg:import_rhel_supported): RHICOMPL-1142 RHEL-6 SSG imports

- app/controllers/application_controller.rb
- app/controllers/concerns/rendering.rb
- app/controllers/v1/profiles_controller.rb
- swagger/v1/openapi.json
- test/controllers/concerns/rendering_test.rb
- test/controllers/v1/profiles_controller_test.rb
Errors from validation coming from `ActiveRecord::RecordInvalid` are now rendered on all controller endpoints.
Example:
```
{"errors":["Profile policy type must be unique. Another policy with this policy type already exists."]}
```
This also fixes error `Unexpected token < in JSON at position 0` in the frontend happening if a user tried to create the same type of a policy as an existing policy for a major OS version (e.g. when the latest benchmark changed).
Here is the result in frontend with this change:
`render_error` refactored to accept string messages.
Error messages in the response JSON are now always an array.
> fix(ApplicationController): RHICOMPL-1129 handle validation errors

- app/graphql/schema.graphql
- app/graphql/types/concerns/system_profiles.rb
- app/graphql/types/system.rb
- test/graphql/queries/system_query_test.rb
Extends System GraphQL type:
* `testResultProfiles` 
* `policies` (initial policy profiles out of assigned profiles, where `external=false`)
The GraphQL fields have the option to filter by `policyId` argument, which filters by any policy profile ID. On `testResultProfiles` the `policyId` filter works even if the host/system is disassociated from its policy.
Note that there is an original `profiles` on both APIs, that returns combined result of test result profiles and associated result. It is kept for compatibility. ~~Changing it into `testResultProfiles` might be up for a question.~~ (Edit: having only test result profiles on `profiles` field would break the API, as it won't include assigned profiles if the host system have not had a report).
Rationale:
The consumer can pick any type of …
> feat(System): RHICOMPL-1139 test result profiles and policies on APIs 

- app/jobs/parse_report_job.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/xccdf_report_parser.rb
- config/settings.yml
- test/services/xccdf_report_parser_test.rb
Like other handled exceptions encountered during parsing, this error will be logged to Sidekiq:
```
2020-12-02T02:32:49.235Z 1 TID-govnpna8l ParseReportJob JID-49dd70ddf6e070a2fa899067 INFO: start
2020-12-02T02:32:49.235Z 1 TID-govnpna8l ParseReportJob JID-49dd70ddf6e070a2fa899067 INFO: Parsing report for account 1212729, system a5258d2d-90cf-4fcd-a7c5-e838ffa8b18b
2020-12-02T02:32:49.966Z 1 TID-govnpna8l ParseReportJob JID-49dd70ddf6e070a2fa899067 ERROR: Cannot parse report: No policy found matching benchmark xccdf_org.ssgproject.content_benchmark_RHEL-7 (RHEL-7) and profile xccdf_org.ssgproject.content_profile_pci-dss with host rhel7-insights-client.virbr0.akofink-laptop assigned for account 1212729. - {"ip_addresses":["192.168.121.24"],"insights_id":"b6bb4df7-9b7a-4f7a-81ec-eb1d9e9603b3 …
```
> feat: RHICOMPL-1149 Stop parsing external reports

- app/graphql/schema.graphql
- app/graphql/types/concerns/profile_scoring.rb
- app/graphql/types/concerns/test_results.rb
- app/graphql/types/profile.rb
- app/graphql/types/test_result.rb
- app/models/test_result.rb
- test/graphql/queries/profile_query_test.rb
- test/graphql/queries/system_query_test.rb
Changes to support https://github.com/RedHatInsights/compliance-frontend/pull/845
RHICOMPL-1114: Expose supported information in GraphQL
RHICOMPL-681: Only score supported reports
> feat(graphql): RHICOMPL-1114 RHICOMPL-681 supported and scoring

- app/models/supported_ssg.rb
- app/models/xccdf/benchmark.rb
- lib/tasks/import_datastream.rake
- test/graphql/queries/benchmark_query_test.rb
- test/models/benchmark_test.rb
- test/models/supported_ssg_test.rb
Return latest supported benchmarks, one each per OS major version. Benchmarks are matched from the SSG supported matrix, picked by latest minor version.
Drops caching of latest supported benchmarks, as it refactors it into a single SQL query within a scope.
Please note, that due to the use of upstream SSG packages, the benchmarks are being matched with the upstream version.
Review suggestion: go by commits.
RHICOMPL-1121
> feat(Benchmark): RHICOMPL-1121 latest supported from SSG matrix 

- docker-compose.yml
Ingress uses port 3000, and second port 8080 as metrics port.
The env variable INGRESS_PORT seems to be undocumented (not read?) and
its value conflicts with the metrics port.
Instead, it maps the port 3000 to be accessible via 8080 from outside.
See also Ingress README:
https://github.com/RedHatInsights/insights-ingress-go/blob/27a929894e645ddae9afb055495e4e823098ab17/README.md
and dev compose:
https://github.com/RedHatInsights/insights-ingress-go/blob/61330931ee5f684f54293be049b05d1648cca7ca/development/local-dev-start.yml
> fix(compose): ingress port use

- app/models/concerns/host_searching.rb
- app/models/host.rb
- test/models/host_test.rb
Add a scoped search for filtering hosts to those with test results for a
given profile or policy ID. This filter will be used on the report
details page for the systems table to show hosts with reports for a
policy, even if the host is not currently assigned to the policy.
Test with https://github.com/RedHatInsights/compliance-frontend/pull/865
> feat(Host): RHICOMPL-1138 Search by policy results

- app/models/supported_ssg.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/concerns/xccdf/rule_results.rb
- app/services/xccdf_report_parser.rb
- test/services/xccdf_report_parser_test.rb
This changes the xccdf report parser to not save unknown benchmarks (those that are either not yet imported or have an SSG version that matches no supported SSG version). If a benchmark does not already exist, the report will fail to parse with an appropriate message logged. The only way to import benchmarks into Compliance after this change will be to run the SSG import job.
> feat(parsing): RHICOMPL-722 Stop parsing unknown benchmarks

- test/test_helper.rb
Coverage has been misreported for quite some time without us knowing
why. The codecov documentation doesn't say anything about this 'rails'
option we were passing in. It was doing some weird things with some
files, like xccdf/hosts.rb not being covered at all, despite having
tests that cover it. Now it seems to be working as expected and shows
valid coverage deficiencies.
The new coverage number without the false negatives is 98.72% reported
from a local test run. Hopefully the codecov service will report a
similar result.
> fix(coverage): RHICOMPL-847 Correct coverage

- app/jobs/parse_report_job.rb
- app/services/host_inventory_api.rb
- app/services/xccdf_report_parser.rb
- lib/tasks/sync_with_inventory.rake
- test/jobs/parse_report_job_test.rb
- test/services/host_inventory_api_test.rb
- test/services/xccdf_report_parser_test.rb
If benchmark, profile, or rules are missing from a test result upload,
we should never retry parsing those uploads.
> fix(parsing): RHICOMPL-722 No retry for Missing*Errors

- docker-compose.yml
This essentially reverts #679 but uses the new env variables. I did not
properly test #679 at the time, but it breaks podman-compose, which runs all
containers in the same pod. That means ports cannot conflict internally
or externally because they are mapped from the pod, not each container.
> fix(docker-compose): Remove conflicting ports

- app/models/profile.rb
- db/migrate/20201216190051_add_policy_id_foreign_key_on_profiles.rb
- db/schema.rb
- test/models/profile_test.rb
Add a foreign key to profiles.policy_id. This means that a policy cannot
be removed from the database while some profile references it.
This also adds a validation for the same case so we can detect and
report a nice error for it, if it ever happens.
> fix(profiles migration): RHICOMPL-1045 policy_id foreign key

- app/models/concerns/profile_policy_association.rb
- app/models/policy.rb
- app/models/profile.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/concerns/xccdf/util.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
- test/services/concerns/xccdf/hosts_test.rb
- test/services/xccdf_report_parser_test.rb
Introduce `Policy.with_hosts` scope and refactor `profile.clone_to` to use it for policy object lookup.
~`BusinessObjective.in_account` now uses `includes` rather than `joins`+`distinct`, same as `Policy.with_hosts`.~
Remove `Profile#find_policy` altogether by introducing `Policy.with_ref_ids` scope.
> refactor(Policy): RHICOMPL-1057 with_hosts scope 

- app/models/policy.rb
- app/services/copy_profiles_to_policies.rb
- app/services/external_profile_updater.rb
- db/migrate/20201222134736_remove_threshold_business_objective_from_profiles.rb
- db/schema.rb
- test/graphql/mutations/edit_policy_mutation_test.rb
- test/models/profile_test.rb
- test/services/copy_profiles_to_policies_test.rb
- test/services/external_profile_updater_test.rb
Remove business_objective and compliance_threshold columns from the
profiles table.
> refactor(Profile): RHICOMPL-999 remove BO and threshold columns

- app/models/concerns/profile_searching.rb
- app/serializers/profile_serializer.rb
- spec/api/v1/schemas/profiles.rb
- swagger/v1/openapi.json
- test/models/profile_test.rb
Add ssg_version attribute to the profiles REST API and enable searching
by ssg_version in both graphql and REST.
> feat(Profile): RHICOMPL-1034 ssg_version attribute

- docker-compose.yml
The ingress:latest image doesn't accept local uploads at the moment. I think most of us are keeping this change stashed right now, so it makes sense to commit it until ingress is patched.
> devel(compose): use ingress:stable image

- docker-compose.yml
Missed this on the last change :see_no_evil: 
This only breaks with podman because everything is run in the same
network namespace. Using the old stable image requires this env
variable. I'm keeping the new variables there for when we can use latest
again.
> devel(compose): Use old ingress port env var

- app/services/concerns/xccdf/hosts.rb
- test/services/xccdf_report_parser_test.rb
This fixes an oversight where policies are found only by account and
host association while never checking ref_id. This changes it so
policies are matched on exact ref_id of the uploaded test result
profile.
> fix(report parse): RHICOMPL-1295 Find Policy by test_result_profile ref_id

- app/services/incorrect_profile_remover.rb
- db/migrate/20210107151954_remove_incorrect_profiles_from_policies.rb
- db/schema.rb
- test/services/incorrect_profile_remover_test.rb
A bug introduced in RHICOMPL-1295 caused some profiles to be incorrectly
associated to policies. The initial profile on a policy essentially
determines the policy's policy type. If any profile ref_id does not
match this initial profile's ref_id, it does not belong on the policy
and will be removed along with any test results.
> fix(data): RHICOMPL-1301 remove incorrect profiles from policies

- app/models/concerns/profile_hosts.rb
- app/models/rule_result.rb
- app/services/external_policy_remover.rb
- db/migrate/20210107161848_remove_external_policies.rb
- db/schema.rb
- test/models/profile_test.rb
- test/models/rule_result_test.rb
- test/services/external_policy_remover_test.rb
Remove all external policies from the perspective of the UI. This means
removing all profiles that are not associated to a policy that have the
external attribute set to true. Note: canonical profiles are marked as
external=false and are not affected by this migration.
> feat(external policies): RHICOMPL-1151 remove them all

- db/migrate/20210107151954_remove_incorrect_profiles_from_policies.rb
- db/schema.rb
We will need to create a new migration when we fix this. This migration
is now just a no-op but must stay in place to keep deployed schemas
versions consistent.
> revert: RHICOMPL-1301 remove incorrect profiles from policies

- db/migrate/20210107151954_remove_incorrect_profiles_from_policies.rb
This partially reverts commit 220bea2f7acdac477d7f94ce2ed0fb88dd235467.
This would be used for testing on stage and later on updated
accordingly.
> chore(migrations): RHICOMPL-1301 activate remove incorrect profiles from policies

- app/models/concerns/profile_hosts.rb
- app/models/policy.rb
- app/models/profile_host.rb
- app/models/test_result.rb
- test/models/test_result_test.rb
Intermediate tables and child tables of high volume should be deleted
right away without invoking destroy callbacks.  An examples is a removal
of a Policy that has a few Profiles but has a high volume of hosts
attached.  Note, that the hosts are attached via intermediate tables
(PolicyHost and ProfileHost) and via TestResults.
When there is a high removal of Policies/Profiles the destroy callbacks
are called for each intermediate/connecting record slowing down the
delete operation.  The destroy callbacks should only be run from the
other hand, from hosts side in this case.
Hence the change from `dependent: destroy` to `dependent: delete_all`.
It might be possible to keep the destroy if there is a possibility to
know the direction in the callback.
Drops destroy_orphaned_external_profiles …
> fix: RHICOMPL-1335 high volume removal of Policy/Profile

- config/supported_ssg.yaml
RHEL 7.9 would get two SSG versions (branches) supported.
> chore(supported_ssg): RHICOMPL-1309 SSG 0.1.52 supported for RHEL 7.9

- app/models/account.rb
This is a new field within the identity that the Inventory service is
now checking for and fails if it does not exist.
> fix(Account): RHICOMPL-1342 Add auth_type to fake_identity_header

- README.md
- config/environments/production.rb
- config/initializers/sidekiq.rb
- config/settings.yml
Option to use SSL for Redis by using `redis_ssl` and `redis_cache_ssl` setting,
also settable via envs `SETTINGS__REDIS_SSL` and
`SETTINGS__REDIS_CACHE_SSL`.
Option to set password for Redis by using `redis_password` and `redis_cache_password` setting,
also settable via envs `SETTINGS__REDIS_PASSWORD` and
`SETTINGS__REDIS_CACHE_PASSWORD`.
> feat(conf): RHICOMPL-1238 option to use SSL and auth for Redis

- db/schema.rb
This only affects places where we use `db:schema:load` (currently nowhere afaik).
> chore(devel): Update DB schema to match migrations

- README.md
- db/cyndi_setup.sql
- docker-compose.yml
This PR just creates the inventory schema for cyndi and creates a view that comes directly from the local inventory database (using [dblink](https://www.postgresql.org/docs/9.3/contrib-dblink-function.html)). We won't need to run any kind of app-connector here to keep it in sync, since it's just a view of the inventory database. Thanks to beav for the help figuring this out :) This shouldn't break any existing devel workflows. 
> feat(Cyndi): RHICOMPL-1374 create cyndi schema in compose

- app/controllers/concerns/authentication.rb
- app/controllers/concerns/inventory_service_helper.rb
- app/jobs/parse_report_job.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/host_inventory_api.rb
- lib/tasks/import_host_os_releases.rake
- lib/tasks/sync_with_inventory.rake
- test/controllers/concerns/authentication_test.rb
- test/graphql/mutations/associate_profiles_test.rb
- test/graphql/mutations/associate_systems_test.rb
- test/services/host_inventory_api_test.rb
- test/tasks/import_datastream_test.rb
- test/tasks/sync_with_inventory_test.rb
For cert-auth, the identity.system.cn must match the system's owner_id
in the system_profile, otherwise the request is unauthorized. In this
implementation, we simply pass cert-auth identity headers through to
inventory, and the response is filtered by identity.system.cn matching
owner_id in the system_profile. If nothing is returned, the identity
header is invalid for that host.
> feat(cert-auth): RHICOMPL-1080 Validate cert-auth

- config/supported_ssg.yaml
Similar to RHEL 7.9, 8.1 will now support multiple SSG versions
See also https://gitlab.cee.redhat.com/security-compliance/ssg-profiles-state/-/merge_requests/7
> feat(RHEL 8.1): RHICOMPL-1371 Add support for SSG 0.1.47

- app/services/host_inventory_api.rb
- test/services/host_inventory_api_test.rb
This is a regression introduced with RHICOMPL-1080. The HostInventoryApi
gets a nil b64_identity during report parse and must use the
fake_identity from the account.
See https://github.com/RedHatInsights/compliance-backend/pull/719/files#r566446351
> fix(HostInventoryApi): RHICOMPL-1383 handles nil b64_identity

- README.md
- docker-compose.yml
When using the docker-compose, it would first check the db version and
run db:migrate or db:setup.  The check needs to be in place, because the
db:setup (precisely db:schema:load) would drop the data.
> chore: update db setup on dev to use db:setup

- app/models/concerns/host_searching.rb
- test/models/host_test.rb
Similar to the scope and search term within the profiles API, this scope and search provide a way to show only hosts that are a member of some compliance policy. This is necessary to filter hosts after Cyndi, in which all inventory hosts are visible in our APIs.
> feat(Hosts): RHICOMPL-1397 with_policy scope / has_policy search

- app/controllers/v1/systems_controller.rb
- test/controllers/v1/systems_controller_test.rb
This adds a default search to only show hosts with test results or those
associated to a policy. The search may be overridden with any other
search or simply left empty to return all inventory hosts.
Similar to https://github.com/RedHatInsights/compliance-backend/pull/496
> feat(REST systems): RHICOMPL-1413 defaults to compliance systems

- Gemfile
- Gemfile.lock
- lib/audit_log/audit_log.rb
- lib/audit_log/audit_log/formatter.rb
- lib/audit_log/audit_log/middleware.rb
- test/lib/audit_log/audit_log_test.rb
- test/lib/audit_log/formatter_test.rb
- test/lib/audit_log/middleware_test.rb
Introduction of a middleware and utility to add entries to an audit log.  By default it logs them to STDOUT, but eventually it can be tied into CloudWatch. Log entries are formatted into JSON, split by a new-line.
Originally posted at https://github.com/RedHatInsights/insights-api-common-rails/pull/217
TODO:
> feat(logging): RHICOMPL-1217 introduce audit logging 

- README.md
- app/services/platform.rb
- config/settings/development.yml
- test/services/platform_test.rb
Changes platform_basic_auth config option to a Hash (from an array) to
be able to be settable via env variables.
Note, that this option is only being used in dev env.
> refactor: platform_basic_auth to be settable via env

- config/environments/development.rb
- lib/audit_log/audit_log.rb
- lib/audit_log/audit_log/formatter.rb
- lib/audit_log/audit_log/middleware.rb
- lib/audit_log/audit_log/wrapped_logger.rb
- test/lib/audit_log/audit_log_test.rb
- test/lib/audit_log/formatter_test.rb
- test/lib/audit_log/middleware_test.rb
- test/lib/audit_log/wrapped_logger_test.rb
Reworks the AuditLog to provide audit capabilities by wrapping a base
logger.  This allows to configure any logger (e.g. Rails.logger) to have
an audit method.
The AuditLog Middleware requires the `Rails.logger` to be wapped,
otherwise it falls back to an info logging.
Audit logs can be sent through `audit_success` or `audit_fail` depending on the status.
Example Rails configuration:
```
config.logger = Insights::API::Common::AuditLog.new(base_logger, Logger.new('log/myaudit.log'))
config.middleware.use Insights::API::Common::AuditLog::Middleware
```
Example usage:
```
Rails.logger.audit('Audit message')
Rails.logger.audit({ controller: 'MyCtrl', message: 'with evidence' })
Rails.logger.audit_success('Success!')
Rails.logger.audit_fail('Fail!') …
```
> feat(logging): RHICOMPL-1423 AuditLog wrapper

- app/controllers/concerns/authentication.rb
- app/models/identity_header.rb
- test/controllers/concerns/authentication_test.rb
- test/controllers/concerns/default_headers_test.rb
- test/controllers/concerns/metadata_test.rb
- test/controllers/graphql_controller_test.rb
- test/controllers/v1/benchmarks_controller_test.rb
- test/controllers/v1/business_objectives_controller_test.rb
- test/controllers/v1/profiles_controller_test.rb
- test/controllers/v1/rule_results_controller_test.rb
- test/controllers/v1/rules_controller_test.rb
- test/controllers/v1/supported_ssgs_controller_test.rb
- test/controllers/v1/systems_controller_test.rb
- test/models/identity_header_test.rb
Changes `before_action` to `around_action` for `authenticate_user` to add the ensure block for resetting the current user (thread local).
>  fix(auth): RHICOMPL-1439 ensure current user reset 

- app/controllers/concerns/authentication.rb
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/audit_logging.rb
- lib/audit_log/audit_log.rb
- lib/audit_log/audit_log/middleware.rb
- test/controllers/concerns/authentication_test.rb
- test/lib/audit_log/audit_log_test.rb
- test/lib/audit_log/middleware_test.rb
Fixes AuditLog middleware to reset the audit log context (currently only account number) after the request. This ensures that it will not leak to another request.
Sets account number context in the Authentication layer, once a user is authenticated.
Reworks AuditLog's `new_to_file` into `new_file_logger` utility for greater control.
And finally it audit logging initializer that sets up the AuditLog wrapper and the middleware on all envs.
The audit logger is configured via `config.audit_logger`.  By default it
puts audit logs to "log/audit.log".  If the base (non-audit) logger
isn't explicitly configured, it would use the default Rails one.
Audit logging configured:
* development: `log/audit.log` (default)
* test: NULL (devnull)
* production: STDOUT if``RAILS_LOG_TO_STDOUT` env var is set …
> feat(logging): RHICOMPL-1438 enable audit logging on all envs

- config/initializers/audit_logging.rb
For some reason the `defined?` call responded differently on Ruby 2.6
when checking whether the Rail custom config variable existence.
> fix(init): RHICOMPL-1438 audit log initializer configuration

- app/controllers/concerns/metadata.rb
- test/controllers/concerns/metadata_test.rb
When the include parameter is given, include it in the pagination links
```
GET https://ci.foo.redhat.com:1337/api/compliance/v1/systems?include=profiles
{
"data": […],
"included": […],
"meta": {…},
"links": {  
"first": "/api/compliance/systems?limit=10&search=has_test_results=true or has_policy=true&include=profiles&offset=1",
"last": "/api/compliance/systems?limit=10&search=has_test_results=true or has_policy=true&include=profiles&offset=1"
}
}
```
> fix(REST): RHICOMPL-1458 show links with includes

- app/producers/application_producer.rb
- test/fixtures/files/test_ca.crt
- test/producers/application_producer_test.rb
Our kafka producers will now allow SSL with the same config the
consumers use to connect to kafka. This is fairly difficult to test
in devel without setting up kafka with SSL, but I intend to test this
thoroughly in stage. In any case, it should be able to use plaintext
mode with the change of the racecar environment variables if anything
goes amiss.
> feat(Kafka Producers): RHICOMPL-1242 now with SSL

- app/controllers/v1/rules_controller.rb
- app/graphql/schema.graphql
- app/graphql/types/rule.rb
- app/serializers/rule_serializer.rb
- spec/api/v1/schemas/rules.rb
- swagger/v1/openapi.json
on REST and GraphQL API.  UI can consume it to send requests to Remediation service.  It would keep the ID generation in backend, on one place.
> feat(Rules): RHICOMPL-992 expose remeditation issue ID

- app/services/safe_downloader.rb
- test/services/safe_downloader_test.rb
This have been failing in kafka consumer when an empty report was
uploaded with:
```
undefined method `map' for #<String:0x000056166eb12788>
```
After this change a report validation is done correctly and error message is printed (for an empty report):
```
Invalid Report: 1:1: FATAL: Start tag expected, '<' not found
```
> fix(reports): RHICOMPL-1491 parsing empty and non-archive reports

- app/services/concerns/xccdf/rule_references_rules.rb
- test/consumers/inventory_events_consumer_test.rb
- test/controllers/v1/profiles_controller_test.rb
- test/fixtures/policies.yml
- test/fixtures/profiles.yml
- test/graphql/queries/system_query_test.rb
- test/jobs/delete_host_test.rb
- test/jobs/parse_report_job_test.rb
- test/models/policy_test.rb
- test/producers/application_producer_test.rb
- test/services/datastream_importer_test.rb
- test/services/duplicate_benchmark_resolver_test.rb
- test/services/duplicate_profile_resolver_test.rb
- test/services/duplicate_rule_reference_resolver_test.rb
- test/services/duplicate_rule_resolver_test.rb
- test/services/duplicate_rule_result_resolver_test.rb
- test/services/duplicate_test_result_resolver_test.rb
- test/services/external_policy_remover_test.rb
- test/services/incorrect_profile_remover_test.rb
- test/tasks/cleanup_db_test.rb
- test/tasks/import_datastream_test.rb
- test/tasks/import_remediations_test.rb
The test output contained a lot of warnings and puts/logging output. I went through all of these and cleaned them up, see the commit messages for more details. There are still two deprecation warnings coming from GraphQL but they will probably need modifications outside the test folder, so I will try to tackle that in a separate PR.
> RHICOMPL-1482: make the test output more readable

- app/graphql/mutations/profile/associate_rules.rb
- app/graphql/mutations/profile/associate_systems.rb
Wrapped the `AssociateSystems` and `AssociateRules` mutations with AR transactions. 
Followup on https://github.com/RedHatInsights/compliance-backend/pull/768#discussion_r590632135
> fix(Profile): wrap associate gql mutations into transactions

- app/models/concerns/host_searching.rb
- app/models/concerns/profile_searching.rb
Due to the bad namespacing in activerecord concerns, code reloading was not really functional. By putting `::` before AR class calls inside concerns we are bridging this problem as the autoloader will not try to load a namespaced version of the AR classes.
> devel(reload): explicit namespacing for AR fixes code reloads

- app/models/concerns/host_searching.rb
- app/models/concerns/profile_policy_association.rb
- app/models/concerns/profile_rules.rb
- app/models/concerns/profile_scoring.rb
- app/models/concerns/profile_searching.rb
I still found some problems with reloading after [de-namespacing](https://github.com/RedHatInsights/compliance-backend/pull/780) everything in the `ClassMethods` modules under model concerns. I basically added the `::` for any class called in the concerns. It might be an overkill, but it was necessary under `ClassMethods` as well to use it on stuff coming from external gems and not our codebase.
> devel(reload): explicit de-namespacing in all model concerns

- app/services/concerns/xccdf/hosts.rb
- app/services/concerns/xccdf/util.rb
- test/services/concerns/xccdf/hosts_test.rb
We should never be updating the rule set or any other aspect of a
policy's profile on report upload. This doesn't seem to affect anything
in the reports page, even if the report rule set differs from its
profile rule set.
> fix(parse): RHICOMPL-1508 never update existing profile rules

- test/controllers/v1/profiles_controller_test.rb
Another nil-to-nil assert comparison cleaned up :broom:
> chore(tests): remove deprecation warning from profiles controller

- app/models/policy.rb
- app/serializers/profile_serializer.rb
- config/settings.yml
- config/settings/development.yml
- test/controllers/v1/profiles_controller_test.rb
- test/models/policy_test.rb
Currently the flag only disables setting the os_minor_version on a
policy, and it also disables the os_minor_version attribute from being
serialized in our REST API.
Please test with https://github.com/RedHatInsights/insights-core/pull/2971
Later, we'll remove this flag, and it should be quite trivial to find the locations necessary by searching by the flag name, feature_comp_e_133 in our code and tests.
> feat(COMP-E-133): RHICOMPL-1520 add a feature flag

- app/graphql/mutations/profile/associate_systems.rb
- app/graphql/schema.graphql
- test/graphql/mutations/associate_systems_test.rb
Adjusted the `associateSystems` mutation to also be able to return with all the profiles under the parent policy.
Request:
```graphql
mutation associateSystems($input: associateSystemsInput!) {
associateSystems(input: $input) {
profiles {
id,
osMajorVersion,
osMinorVersion,
ssgVersion,
benchmarkId,
}
}
}
```
Response:
```json
{
"data": {
"associateSystems": {
"profiles": [
{
"id": "829735bc-cf80-41bc-a502-9a49fb54567a",
"osMajorVersion": "7",
"osMinorVersion": "7",
"ssgVersion": "0.1.43",
"benchmarkId": "dd10a20c-2527-4d82-983b-d4a9e512df1a",
"__typename": "Profile"
},
{
"id": "665881a9-997b-47de-950c-a9260d52d135",
"osMajorVersion": "7",
"osMinorVersion": "9",
"ssgVersion": "0.1.52",
"benchmarkId": "0df89dd7-8f4a-4520-b06f-371047d7cf40",
"__typename": "Profile"
}
],
"__typename": …
```
> feat(EditPolicy): RHICOMPL-1542 return all associated profiles

- Gemfile.lock
See https://github.com/rails/rails/issues/41750
tl;dr: mimemagic pulled the 0.3.5 release because they updated the license from MIT to GPL. [Our repo is already licensed under GPL](https://github.com/RedHatInsights/compliance-backend/blob/master/LICENSE), so we shouldn't be affected by this change legally. Any gem licensed as GPL must be used/modified under GPL. Anyone using rails (licensed as MIT) right now with an MIT license cannot update this gem, but we already use GPL.
> chore: Bump mimemagic to 0.3.6

- Dockerfile
- Gemfile.lock
0.3.5, 0.3.6, and 0.3.7 have been pulled :/
Starting with 0.3.7, mime detection uses the shared-mime-info native dependency. This PR requires https://github.com/RedHatInsights/s2i-insights-compliance/pull/28.
> chore: Bump mimemagic to 0.3.9

- app/models/concerns/host_searching.rb
- lib/prometheus/business_collector.rb
- lib/prometheus/engineering_collector.rb
- test/lib/prometheus/business_collector_test.rb
- test/lib/prometheus/engineering_collector_test.rb
- test/lib/prometheus/graphql_collector_test.rb
- test/models/host_test.rb
Joins across the entire hosts view can get very sluggish. We always want
to only count compliance hosts in our metrics. The sluggishness is caused, in part, by the lack of indices, etc. which will be addressed in future PRs. This PR just aims to limit the scope of our queries to compliance hosts only.
> fix(Prometheus): RHICOMPL-1559 Scope metrics to compliance hosts

- app/graphql/mutations/profile/create.rb
- app/graphql/schema.graphql
- test/graphql/mutations/create_profile_mutation_test.rb
Canonical rules are set if this param is not passed, thanks to the way `update_rules` works when `nil` is passed in.
> feat(createProfile): RHICOMPL-1607 no longer requires rule ref IDs

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- test/graphql/queries/profile_query_test.rb
Expose parentProfileId in GraphQL. This is already exposed in REST.
> feat(GraphQL): RHICOMPL-1609 profiles parentProfileId

- test/services/duplicate_canonical_profile_resolver_test.rb
Another annoying and useless output spamming our test results, unfortunately `capture_io` wasn't working here so I had to stub `STDOUT` explicitly.
> chore(tests): stub stdout in DuplicateCanonicalProfileResolverTest

- app/graphql/schema.graphql
- app/graphql/types/benchmark.rb
- app/graphql/types/query.rb
- test/graphql/queries/benchmark_query_test.rb
This change allows using GraphQL to query all benchmarks with an
optional filter. This type of query is used during the Edit Policy modal
and Create Policy wizard to get the latest_supported_os_minor_versions
to draw the rule tabs.
You can test this with https://github.com/RedHatInsights/compliance-frontend/pull/1151
> feat(GraphQL): RHICOMPL-1721 benchmarks collection

- app/models/concerns/profile_searching.rb
- app/models/policy.rb
- app/models/profile.rb
- app/services/concerns/xccdf/hosts.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
- test/services/xccdf_report_parser_test.rb
When a report is being parsed, its result should be placed to the
profile with matching OS minor version of same benchmark, if such exist.
This tries to fix the case of a multiple OS versions sharing the same
benchmark/SSG version.  For example within RHEL 6.
> fix(Profile): RHICOMPL-1543 prefer profile with exact OS minor ver.

- app/jobs/delete_host.rb
I was trying to run the `DeleteHost` job on 2k hosts with generated `TestResult` and `RuleResult` entities meanwhile firing 10k API requests to edit profiles. The sidekiq job was *maybe* a bit faster, but it's hard to measure properly. 
The first two spikes are the jobs processed without the wrapping transaction and the second set is with the transaction.
> performance(DeleteHostJob): RHICOMPL-1785 remove the transaction

- app/controllers/v1/statuses_controller.rb
- config/routes.rb
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/status.rb
- spec/integration/statuses_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/statuses_controller_test.rb
Add a new status endpoint that returns 200 if everything is OK and 500
otherwise. We can expand the statuses if needed in the future.
It also works with HEAD requests if you're not interested in the individual json statuses.
```
GET compliance/v1/status
HTTP/1.1 200 OK
{
"data": {
"api": true
}
}
```
```
GET compliance/v1/status
HTTP/1.1 500 Internal Server Error
{
"data": {
"api": false
}
}
```
> feat(REST): RHICOMPL-1563 status API endpoint

- docker-compose.yml
This port conflicts with the minikube dashboard by default and is not
even used by the Compliance team in development.
See https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
> dev: remove puptoo prometheus port

- app/models/concerns/profile_scoring.rb
This line is dead code for all the cases when this method is called.
I've added safe navigation so it doesn't raise an exception if called on
a canonical profile, even though that doesn't really make sense to do.
I think this coverage dropped slightly with the FactoryBot changes, but I'm not 100% sure.
Counterintuitively, local test coverage drops from 2469 / 2525 LOC (97.78%) -> 2467 / 2524 LOC (97.74%) because I removed more lines than covered.
The not-covered line in codecov, brought to my attention with the [last stable PR](https://github.com/RedHatInsights/compliance-backend/pull/826):
> test: Remove vestigial external policy code for coverage++

- test/factories/host.rb
I don't expect this to stay super stable, since it depends on the inventory's hosts table, which could change at any time, but for devel, this is still very useful to be able to create thousands of fake hosts, optionally in your own account.
```rb
User.current = User.new(account: Account.find_by(account_number: '123456')) # optional
FactoryBot.create(:host)
FactoryBot.create_list(:host, 1000)
```
> devel: Adjust host factory for development

- test/factories/host.rb
Makes the OS version in the host factory fixed to 7.9 and introduces a new trait to have the version randomly selected for future use. This should unblock us from the random CI failures.
> fix(tests): RHICOMPL-1857 make random OS version picking optional

- lib/tasks/import_datastream.rake
```
Tasks: TOP => ssg:import_rhel_supported
(See full trace by running task with --trace)
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
2021-05-20T14:50:07.244Z 1 TID-cat INFO: GitLab reliable fetch activated!
Fetching scap-security-guide-0.1.54.zip
Fetching scap-security-guide-0.1.52.zip
Fetching scap-security-guide-0.1.50.zip
Fetching scap-security-guide-0.1.48.zip
Fetching scap-security-guide-0.1.47.zip
Fetching scap-security-guide-0.1.46.zip
Fetching scap-security-guide-0.1.43.zip
Fetching scap-security-guide-0.1.42.zip
Fetching scap-security-guide-0.1.40.zip
Fetching scap-security-guide-0.1.36.zip
Fetching …
```
> feat(import-ssg): RHICOMPL-1558 sync newest SSGs first

- app/services/datastream_importer.rb
- lib/tasks/import_datastream.rake
Update available remediations on rules after all SSGs have been imported
to avoid a PG deadlock.
The remediations where being imported on every single SSG that has been
imported.  It has been updating all existing rules regardless of the
current SSG being imported.
That could have been one of the reasons for the deadlock.  Another fact
to consider here that it waited on the API response from the remediation
service within a transaction.
> fix(SSG): RHICOMPL-1863 import remediatons after SSG import

- app/models/concerns/benchmark_searching.rb
Use where(...).limit(1) instead of find_by(...) to reduce the number of
queries from 4 to 1 for Xccdf::Benchmark.latest_supported. Thanks @vkrizan 
for pointing this out!
> refactor(latest_supported): RHICOMPL-1773 single query

- lib/tasks/import_remediations.rake
When not providing JOBS_ACCOUNT_NUMBER, we used to fall back to just any new account. This adds that behavior back.
See https://github.com/RedHatInsights/compliance-backend/pull/844/files#diff-6aa5378d9c24177aba76fd391d9a51792d0d1b289be2a00a9bcbc0af24637ee0L27
This is required to unblock the smoke tests here: https://github.com/RedHatInsights/compliance-backend/pull/846
> fix(import_remediations): RHICOMPL-1863 fall back to new Account

- Dockerfile
Use chown within the COPY statement to reduce duplication of layers.
A build from my local code-base reduced the size by ~1G.
> fix(Dockerfile): RHICOMPL-1890 reduce layer duplication

- app/controllers/concerns/metadata.rb
- test/controllers/concerns/metadata_test.rb
Leverages ActiveSupport's `.to_query` on a Hash.
> fix(controllers): RHICOMPL-1465 escape values in links metadata

- app/models/policy.rb
- app/serializers/profile_serializer.rb
- config/settings.yml
- config/settings/development.yml
- test/controllers/v1/profiles_controller_test.rb
- test/models/policy_test.rb
I was about to add a new feature flag for downstream SSG sync and noticed this 133 flag still exists! :scissors: 
> refactor(COMP-E-133): RHICOMPL-1761 Remove the feature flag

- docker-compose.yml
I noticed this crashing when the DB connection is lost. I suspect that's
how it works in prod, too. Anyway, this is just a quality of life
improvement so you don't need to manually restart the inventory.
> devel: Restart inventory on failure

- app/consumers/concerns/validation.rb
- app/consumers/inventory_events_consumer.rb
- test/consumers/inventory_events_consumer_test.rb
The PG:Error-s have been absorbed within the report validation.  Now
they are reraised to upper levels.
Any database error within the InventoryConsumer will:
a) fail the message
b) clear existing db connections for the next iteration to reconnect
Failing the message, by reraising it to the Racecar framework, would
have a side effect of keeping the message offset.  The message will be
repeated/resend by Kafka for next processing.  The drawback is that the
messages and their offsets are linear, therefore no other messages would
be processed until the database errors will disappear.
> fix(consumer): RHICOMPL-751 reconnect db within kafka consumer

- README.md
- app/producers/application_producer.rb
- config/racecar.rb
- config/racecar.yml
- config/settings.yml
- docker-compose.yml
- test/producers/application_producer_test.rb
Read Kafka configuration from `Settings` for ease of Clowder config addition.
> refactor(config): RHICOMPL-1894 Kafka config read from Settings

- Dockerfile
Backend does not use mariadb nor npm.
There could be more of these removed (like kernel-headers and libX11), however with their removal it removes couple of other possibly useful packages (like gcc, libpng, ...).
References:
* https://catalog.redhat.com/software/containers/ubi8/s2i-base/5c83976a5a13464733ec6790?container-tabs=dockerfile
> build(Dockerfile): RHICOMPL-1268 remove unused packages

- devel.Dockerfile
`pry` has a weak dependency on the `less` command as it utilizes it for pagination of a long(er) output when debugging or running `rails console`. It's kinda annoying to install this every time manually and we have a separate dockerfile for development, so I guess it's safe to have this :pray: 
*;Without less:*;
```
<page break> --- Press enter to continue ( q<enter> to break ) --- <page break>
```
;*With less:*;
```
:
```
Basically provides a regular `less` session where you can use arrows to move and and search in the output.
> devel(Dockerfile): install less into the container

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
It's a pretty simple change :) The `rate` function measures counts per second. The `$interval` just represents the running average rate over that interval. i.e. 1h means the 1-hour moving average of traffic per-second. This particular graph was confusing to me because I didn't realize `rate` was per-second. Maybe in the future we will change it to use `increase` instead so it actually counts how many requests per `$interval` instead of that confusing explanation I gave previously about the moving average per-second traffic :laughing: 
Before:
After:
> feat(metrics): Label y axis of Traffic graph

- app/producers/test_producer.rb
- config/settings.yml
- docker-compose.yml
- lib/tasks/status.rake
- test/tasks/status_test.rb
These rake tasks can be used to check database, kafka, or redis availability for non-web ruby
services in a readiness or liveness probe.
```sh
bundle exec rake db:status
bundle exec rake redis:status
bundle exec rake kafka:status
```
Readiness/liveness probes can chain together multiple rake status invocations, depending on what services they depend on. So, inventory-consumer might run something like `rake db:status kafka:status redis:status`, and none should abort.
> feat(rake): RHICOMPL-56 db:status redis:status kafka:status tasks

- docker-compose.yml
So apparently when `db:test:prepare` runs in any other environment, it messes up stuff :laughing: who would think that :see_no_evil: 
> fix(devel): RHICOMPL-1947 run the test db prepare in the test env

- db/migrate/20210609081621_add_score_to_profiles.rb
There's no need to run the query when there are no scores are available, also it would fail as the SQL is invalid without data.
> fix(migration): RHICOMPL-1956 score profiles only when available

- app/graphql/types/concerns/system_profiles.rb
- app/graphql/types/system.rb
- app/models/host.rb
This reintroduces the [previously](https://github.com/RedHatInsights/compliance-backend/pull/895) reverted [collection loader](https://github.com/RedHatInsights/compliance-backend/pull/845) for systems' child entities. The problem with the original PR was the lack of scoping in an asynchronous environment, that has been solved by using [`context.scoped_set`](https://github.com/rmosolgo/graphql-ruby/pull/2634) for setting the parent object's ID.
> perf(GraphQL): preload collections under systems with scoped context

- clowdapp.yaml
- config/database.yml
- config/initializers/0_clowder-config.rb
- devel.json
- docker-compose.yml
UPDATE - I've modified the `docker-compose` file to read the configuration as if it was on a Clowder environment. In order to do so, I've added the `devel.json` file, which would be added to each pod's volume, and I've added the variable `ACG_CONFIG` to each of Compliance's pods. This should emulate the "clowder config injection" that happens on a Clowder deployed app. The Clowder_config::isClowderEnabled? function now returns true and uses the values from the JSON file to provide the mocked config values that are pretended to be provided by Clowder.
If you wanna test this, you should be able to do a podman-compose up and see the application working normally. Please test thoroughly and provide feedback.
> Add Initializer for Clowder config for settings

- .gitignore
- app/models/supported_ssg.rb
- app/services/ssg_config_downloader.rb
- config/settings.yml
- spec/swagger_helper.rb
- test/models/supported_ssg_test.rb
- test/services/ssg_config_downloader_test.rb
In addition to fetching the supported datastream config from compliance-ssg, this adds a ConfigDownloader which leverages the SafeDownloader to download config files. During failure to download, the backend still requires some kind of valid config, so the ConfigDownloader provides a fallback file fixture. This is also leveraged in our test environment, where no compliance-ssg service exists.
> feat: RHICOMPL-1933 get datastream config from compliance-ssg

- app/controllers/concerns/authentication.rb
Remediations needs to request the /rules endpoint via cert auth with the
new RHC client.
> feat(auth): RHICOMPL-2035 Allow /rules endpoint via cert auth

- app/models/host.rb
- test/graphql/queries/system_query_test.rb
When requesting profiles through test results under hosts, it is possible that the JOIN between the two tables produces duplicate profiles between the results if there are outdated test results for a given profile. All the other fields, like score are taken from the latest test result, so these values will be correct. As a solution I passed a `distinct` into the `scope` that resolves this problem.
> fix(Host): RHICOMPL-2063 deduplicate Host#test_result_profiles

- README.md
- app/controllers/concerns/collection.rb
- app/controllers/concerns/metadata.rb
- app/controllers/concerns/tag_filtering.rb
- config/application.rb
- lib/adjust_tags/middleware.rb
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/metadata.rb
- spec/integration/systems_spec.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
- test/controllers/concerns/tag_filtering_test.rb
- test/controllers/v1/systems_controller_test.rb
- test/lib/adjust_tags/middleware_test.rb
I traced back how Rails and Rack handle the parsing of the query string and found that the `Rack::Request::Env#query_parser` method holds the reference to their parser. So I am monkeypatching this single method in an initializer to hold our parser, which is just a delegation to the original parser with the addition of overriding the already parsed tags with our correct values.
> feat(REST): RHICOMPL-1284 implemented filtering by tags for systems

- app/controllers/concerns/authentication.rb
- test/controllers/v1/rules_controller_test.rb
Turn off rules#index via cert auth in favor of rules#show. The index
endpoint was added due to a misunderstanding on RHICOMPL-2035 of what
was needed by the remediations team.
CC @aleccohan
> fix: RHICOMPL-2035 Expose rules#show via cert-auth

- app/controllers/concerns/collection.rb
- app/controllers/concerns/metadata.rb
- app/controllers/concerns/tag_filtering.rb
- app/graphql/resolvers/concerns/collection.rb
- app/graphql/schema.graphql
- test/graphql/queries/system_query_test.rb
I (more or less) kept the same format as for the REST API, but here we can use proper arrays :wink: 
```
{
"operationName": "getSystems",
"query": "query getSystems($perPage: Int, $page: Int, $tags: [String!]) {
systems(limit: $perPage, offset: $page, tags: $tags) {
totalCount
edges {
node {
id
name
osMajorVersion
osMinorVersion
__typename
}
__typename
}
__typename
}
}",
"variables": {
"perPage": 50,
"page": 1, "tags": ["foo/bar=baz"]
}
}
```
> feat(GraphQL): RHICOMPL-2037 allow filtering results by tags

- Gemfile
- Gemfile.lock
- app/models/concerns/host_searching.rb
- test/graphql/queries/system_query_test.rb
- test/models/host_test.rb
When searching for hosts with a certain profile score we were calculating this score based on the number of passing rules, however, this is incorrect and also slow. Instead we should rely the score that is already set in the latest test results.
So this change should not just correct the searching, but also speed up the process when having a lot of records.
Closes https://github.com/RedHatInsights/compliance-backend/pull/910
> fix(score): RHICOMPL-2026 search hosts based on the correct scoring

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
There's actually 2 pie charts, one for the total and one for the client systems. I guess we don't care that much about the trend of this graph, but I can add that one in a followup PR as well.
Depends on: https://github.com/RedHatInsights/compliance-backend/pull/957
> feat(grafana): RHICOMPL-2097 piechart of systems by OS version

- app/controllers/concerns/collection.rb
- app/controllers/concerns/sorting.rb
- test/controllers/concerns/collection_test.rb
- test/graphql/resolvers/collection_test.rb
Ordering database resources by a field that contains duplicate
values with a queried set does not give deterministic result to
paginate.
This should fix pagination within REST API by adding unique id into the
ORDER BY.
> fix(REST): RHICOMPL-2109 deterministic pagination

- pr_check.sh
Just the image building parts of https://github.com/RedHatInsights/compliance-backend/pull/921. This helps development by building the image on each PR so it can be specified for testing in bonfire deployments.
> devel: RHICOMPL-2160 Build and push the image during pr_check

- spec/integration/benchmarks_spec.rb
- spec/integration/business_objectives_spec.rb
- spec/integration/profiles_spec.rb
- spec/integration/rule_results_spec.rb
- spec/integration/rules_spec.rb
- spec/integration/systems_spec.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
:shrug: not sure about the validity of this spec if the sort_by isn't passed as an array, but I guess it should be fine :thinking:
> fix(api): RHICOMPL-2175 display the sortable fields in openapi.json

- README.md
- docker-compose_nonclowder.yml
This helps testing compatibility of old non-clowder deployments. We can
remove it after fully migrating to clowder.
```sh
docker-compose -f docker-compose_nonclowder.yml ...
```
This uses env variables per container instead of the shared devel.json and ACG_CONFIG variable. (Un)setting the ACG_CONFIG env variable toggles all clowder config logic within Compliance.
Used to help debug/test https://github.com/RedHatInsights/compliance-backend/pull/945
> devel: Temporarily add back the non-clowder compose

- README.md
- app/graphql/schema.rb
- app/services/openshift_environment.rb
- clowdapp.yaml
- config/initializers/0_clowder-config.rb
- config/initializers/prometheus.rb
- config/initializers/sidekiq.rb
- config/puma.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/production.yml
- config/settings/test.yml
- devel.json
- docker-compose.yml
- entrypoint.sh
- lib/prometheus/graphql_collector.rb
To test, spin up an ephemeral environment against this IMAGE_TAG and template ref:
```sh
IMAGE_TAG=$(git rev-parse --short=7 HEAD);
TEMPLATE_REF=$(git rev-parse HEAD)
bonfire deploy -sappsre --no-remove-resources compliance -i quay.io/cloudservices/compliance-backend=$IMAGE_TAG --single-replicas --set-template-ref compliance=$TEMPLATE_REF compliance
```
Check in each of the three pods (backend, sidekiq, consumer) that metrics are exposed:
```sh
oc rsh <pod>
$ curl localhost:9000/metrics | less
```
Sidekiq should report sidekiq metrics (only once at least one job is processed), the backend should be the only pod containing DB related metrics (i.e. `complianceclient_policies_by_os_major`), and all pods should have process related metrics (memory/cpu usage, etc).
Signed-off-by: Andrew Kofink …
> feat: RHICOMPL-2076 Export metrics on each pod

- app/models/rule.rb
- app/services/concerns/xccdf/benchmarks.rb
- app/services/concerns/xccdf/rules.rb
- db/migrate/20210830070917_add_upstream_for_rules.rb
- db/schema.rb
This is the mark phase of the non-invasive cleanup of unused upstream rules from our database. I'm initially marking every rule as an upstream and during the SSG import, all the imported rules will set the `upstream` field to be `false`. This way we will know which rules should be kept in a future cleanup.
> feat(rules): RHICOMPL-2081 mark upstream rules with a new field

- app/controllers/concerns/authentication.rb
- app/models/account.rb
- app/models/identity_header.rb
- app/services/xccdf_report_parser.rb
- db/migrate/20210830130754_rename_internal_in_accounts.rb
- db/schema.rb
- test/controllers/concerns/authentication_test.rb
- test/services/reports_tar_reader_test.rb
- test/services/xccdf_report_parser_test.rb
I moved around the `account_from_header` method and generalized it into `Account.from_identity_header`. The method now tries to look up for both the account number and the `user.is_internal` boolean and if the latter one isn't set, an exception happens, the handler looks for the account by the number only, updates the `is_internal` field and retries. This way any user interaction will keep the information about the account being internal or not.
> fix(Accounts): RHICOMPL-2114 set is_internal from the identity header

- app/controllers/v1/business_objectives_controller.rb
This is some legacy stuff that doesn't allow to override the default sort in business objectives. Replacing it with *The Right Way&trade;* :wink:
> fix(sort): RHICOMPL-2179 overridable default sort of business objectives

- lib/prometheus/business_collector.rb
- test/lib/prometheus/business_collector_test.rb
If the account has the `is_internal` not set to true, i.e. `nil` or `false` it is treated as a client (non-employee) account.
> fix(metrics): RHICOMPL-2114 adjust metrics to non-internal accounts

- README.md
- app/graphql/schema.rb
- config/initializers/prometheus.rb
- config/initializers/sidekiq.rb
- config/puma.rb
Reverts changes, after Prometheus running along side main processes, to
have Prometheus disableable by clearing the settings constant.
This is useful when developing locally, especially when Spring holds the
processes.
> dev(prometheus): RHICOMPL-2251 disableable Prometheus Exporter

- app/graphql/schema.rb
Closes RHICOMPL-2254.
See : https://github.com/rmosolgo/graphql-ruby/blob/master/guides/schema/introspection.md#disabling-introspection
> fix(GraphQL): RHICOMPL-2254 Disable GraphQL introspection on prod

- app/consumers/concerns/report_parsing.rb
- app/services/xccdf_report_parser.rb
- test/consumers/inventory_events_consumer_test.rb
- test/services/xccdf_report_parser_test.rb
Two different jiras solved here:
- fix(ReportParser): RHICOMPL-2266 Handle nil identities
- fix(parsing): RHICOMPL-2114 Inject b64_identity into metadata
> fix(parsing): RHICOMPL-2114 Inject b64_identity into metadata

- app/models/concerns/host_searching.rb
- test/models/host_test.rb
Relying on the `RequestStore` once again for narrowing down the search
> perf(reports): RHICOMPL-2210 speed up filtering hosts by compliant

- app/policies/rule_result_policy.rb
:runner: :racehorse: :zap: 
**Before:**
Completed 200 OK in 13276ms (Views: 3579.5ms | ActiveRecord: 3986.8ms)
**After:**
Completed 200 OK in 5632ms (Views: 56.7ms | ActiveRecord: 5537.0ms)
> perf(REST): RHICOMPL-2249 use a subquery for RuleResults by hosts

- app/controllers/concerns/metadata.rb
- app/controllers/concerns/parameters.rb
- app/controllers/concerns/rendering.rb
- app/serializers/application_serializer.rb
- swagger/v1/openapi.json
- test/controllers/concerns/metadata_test.rb
- test/controllers/concerns/parameters_test.rb
Introduce a new param in our REST API to disable relationships in the
response entirely. Simply provide relationships=false to disable
relationships. The default is true and does not change existing API
functionality.
> feat(REST): RHICOMPL-1979 Allow disabling relationships

- app/serializers/rule_identifier_serializer.rb
- test/controllers/v1/rules_controller_test.rb
Adding the `system` and `label` attributes to the rule identifier serializer so that they are available via REST API under "included" in the response. 
To test: Add `include==rule_identifier` to the end of the REST API call. Also, use the `/api/compliance/v1/rules` or `/api/compliance/v1/rules/{id}` path in the URL of the API call.
Current response: 
```
"included": [
{
"id": "87b9a20b-3f3b-4889-8db6-219b5e167b73",
"type": "rule_identifier"
}
]
```
Response after this update:
```
"included": [
{
"label": "CCE-27012-4",
"system": "https://nvd.nist.gov/cce/index.cfm"
},
"id": "87b9a20b-3f3b-4889-8db6-219b5e167b73",
"type": "rule_identifier"
}
]
```
> feat(REST): RHICOMPL-2374 Add attributes to rule identifier serializer

- app/services/upstream_profile_remover.rb
- db/migrate/20211104070445_delete_upstream_profiles.rb
- test/services/upstream_profile_remover_test.rb
Also removing any possible dangling account that has been created during the process.
> cleanup(db): RHICOMPL-2440 remove upstream profiles with test results

- config/initializers/0_clowder-config.rb
I guess the original author wanted text mode for writing but that's redundant in Ruby.
> fix(clowder): RHICOMPL-2473 open the kafkaCaFile for write only

- config/racecar.rb
The `config.security_protocol` should and will be a symbol...
> fix(racecar): RHICOMPL-2496 explicit symbolization for config

- app/services/dangling_account_remover.rb
- test/services/dangling_account_remover_test.rb
Sometimes cyndi is not available on initial setups and in this case not even needed (ephemeral, development, ci) and it fails on this migration. I'm adding a safeguard to return with an empty relation so the migration can continue. If there are no inventory hosts, this service should not do anything anyway.
> fix(DanglingAccountRemover): RHICOMPL-2537 do not depend on cyndi

- app/graphql/mutations/base_mutation.rb
- app/graphql/mutations/profile/associate_systems.rb
- app/graphql/mutations/profile/create.rb
- app/graphql/mutations/system/associate_profiles.rb
Making the host lookup in mutations analogous to profile lookups and narrowing down profile querying in policy creation for speed.
> fix(GraphQL): RHICOMPL-2257 narrow down querying for profiles/hosts

- app/services/concerns/xccdf/benchmarks.rb
- db/migrate/20211203100649_add_package_name_to_benchmarks.rb
- db/migrate/20211211074855_clear_revisions.rb
- db/schema.rb
- test/services/concerns/xccdf/benchmarks_test.rb
- test/services/xccdf_report_parser_test.rb
I'm adding a new column for benchmarks that stores the SSG package name, if there's a difference between the imported vs current, the benchmark should be reimported on its own.
> feat(Benchmark): RHICOMPL-1896 allow reimports for backport versions

- clowdapp.yaml
Racecar had it, I don't see why sidekiq shouldn't. Hopefully it fixes the livenessProbe triggered restarts under heavy loads.
> fix(clowder): RHICOMPL-2553 livenessProbe timeout for sidekiq

- clowdapp.yaml
Rake task output looks better with `--trace` which was missing from two readiness probes (sidekiq, racecar).
> feat(clowder): RHICOMPL-2568 add tracing for readiness probes

- README.md
- db/schema.rb
- docker-compose.yml
The `bin/rails db` command now required a `-p` argument if we want to avoid interactive password input (idk why) and I also added some tracing to the rake tasks in the compose file for better debugging.
> fix(rails): RHICOMPL-2569 fixed db setup in development for rails61

- Gemfile.lock
- app/graphql/mutations/profile/associate_rules.rb
- app/services/safe_downloader.rb
- test/controllers/concerns/authentication_test.rb
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
> chore(rails6): RHICOMPL-2540 get rid of the remaining deprecations

- app/models/profile.rb
Non-canonical profiles should have an account assigned, however, the validation of this was tied to a profile having an assigned host instead of a parent profile, which triggered validation during SSG imports. As the SSG import in a clean DB can happen before the inventory is available, this can slow down the deployment process in ephemeral and docker-compose. The fix also addresses the wrong validation for the `policy` tied to itself.
> fix(profiles): RHICOMPL-2574 decouple validation from inventory

- docker-compose.yml
Renaming the `import-ssg` job to follow the clowder namings. Also adjusting some of the dependencies for smoother setup.
> dev(compose): improve dependency management in the compose file

- app/consumers/concerns/report_parsing.rb
- app/jobs/parse_report_job.rb
- test/jobs/parse_report_job_test.rb
This should reduce the memory footprint of Redis as we would be no longer channel the reports through it. The racecar task pushes the URL to the job and Sidekiq consumes it directly from the S3. It's a bit less efficient as it does N+1 downloads (each report once + validation in racecar) though, but it's fully compatible with the old setup, i.e. 1 job for 1 report if N reports are in an upload. Also it's capable of draining old jobs from sidekiq, so we should clean that up later...
> fix(ParseReportJob): RHICOMPL-1021 read reports from S3, not redis

- Gemfile.lock
Hoping that this will fix our LeaderNotAvailable issues in development :pray:
> chore(deps): RHICOMPL-2632 update racecar and ruby-kafka

- app/services/concerns/xccdf/rule_references.rb
- app/services/concerns/xccdf/rule_references_rules.rb
There were a lot of unnecessary `Array#[]` calls in the SSG importing process. The `RuleReferences#existing_href_labels` method was being called multiple times and even though the ActiveRecord result was cached there, the `pluck` operation was repetitive. In the `RuleReferencesRules` module the `rule_references_for` and `rule_for` modules were having slow and repetitive `select` and `find` calls which I replaced with a lookup hash generated by `index_by`.
Based on my benchmarks on an empty DB, the original code did the SSG import process in 17:46 and with my changes this went down to 3:33 so we're 5 times faster. This should significantly speed up the deployment process in ephemeral environments and the results should be also visible on the CI below.
- …
> perf(DatastreamImporter) RHICOMPL-2539 less array operations in import

- app/models/concerns/sortable.rb
- app/models/xccdf/benchmark.rb
Apparently calling `.to_sql` on an Arel node in a model constant crashes if the database is not available, which also crashes a ` rake db:setup` call. Ideally we would not need the `to_sql` conversion, but [Rails can't deal with Arel nodes in an order hash](https://github.com/rails/rails/issues/44282) and until the [fix](https://github.com/rails/rails/pull/44284) gets in, we need to compensate somehow. So as a solution I moved the conversion from the constant to a bit deeper.
I know it's ugly, but we have to deal with it for some time :disappointed: 
> fix(db:setup): RHICOMPL-2645 do not convert Arel to SQL on startup

- app/services/concerns/xccdf/profiles.rb
- app/services/concerns/xccdf/rules.rb
All the new rules and profiles are imported automatically as downstream, no need to update the existing ones over and over again. This also hopefully resolves a deadlock in prod.
> fix(deadlock): RHICOMPL-2694 remove downstream marking in ssg_import

- app/models/supported_ssg.rb
- app/services/datastream_downloader.rb
- test/services/datastream_downloader_test.rb
As discussed with the OpenSCAP team, we are safe with importing only the latest revision for each benchmark version per OS major. This should prevent the pingponging of rule changes between revisions that should not happen but they actually do.
> fix(ssgs): RHICOMPL-2649 only import the latest revision for OS major

- .codecov.yml
> We no longer need them as we always have the latest master's coverage report at hand.
https://docs.codecov.com/docs/comparing-commits#pseudo-comparison
> fix(codecov): RHICOMPL-2701 Disable coverage offsets

- app/models/concerns/profile_tailoring.rb
- test/models/profile_test.rb
Not sure if it's really needed but it was mentioned in the JIRA ticket. Also the order in a hash is only maintainable safely if we treat it as immutable, which we do. 
> feat(ProfileTailoring): RHICOMPL-1736 order rules by precedence

- app/models/policy_host.rb
- app/models/rule_result.rb
- app/models/test_result.rb
- test/models/policy_host_test.rb
- test/models/rule_result_test.rb
- test/models/test_result_test.rb
Host links can be sometimes orphaned and transitive validation coming from SSG import might crash on this. As a solution I am proposing to limit the validation to the `host_id` and keep the stricter one when creating records only.
> fix(ActiveRecord): RHICOMPL-2718 weaken links with host validation

- app/jobs/parse_report_job.rb
- test/jobs/parse_report_job_test.rb
Systems without results are marked as non-compliant, but we need to notify them if their first report coming in is also non-compliant.
> fix(Notification): RHICOMPL-2563 always notify if system has no reports

- app/jobs/parse_report_job.rb
- app/producers/notification.rb
Referring to just `EVENT_TYPE` without the `self` doesn't play well with inheritance. Also the `@account` variable was never properly set.
> fix(Notification): RHICOMPL-2563 two minor fixes for missing payload fields

- app/services/orphaned_links_remover.rb
When running migrations and the inventory service is not available yet, the migration fails on the `OrphanedLinksRemover` as it depends on the inventory. The only case this can happen is a deployment to ephemeral so this can cause slower CI. 
> chore(OrphanedLinksRemover): RHICOMPL-2781 relax dependency on inventory

- app/services/playbook_downloader.rb
- test/services/playbook_downloader_test.rb
Instead of downloading each playbook one-by-one, we can simply download the newly provided JSON autoindex from the right folder and match against the existing files. The performance increase is significant, the original import takes :sloth: ~70 seconds :sloth: on my local machine and the new one requires :drum: :drum:  only :zap: 2-3 seconds :zap: 
Note that for testing this you'd need to pull the latest SSG container from quay.
1. Clear the revisions from rails console
```ruby
Revision.find_by(name: 'remediations')&.delete
```
2. Import the remediations
```bash
time bin/rake import_remediations
```
> perf(SSG): RHICOMPL-2793 determine playbook existence from autoindex

- app/models/rule.rb
- app/services/concerns/xccdf/rules.rb
- db/migrate/20220310135223_reset_revisions_march_tenth.rb
- db/schema.rb
- test/services/concerns/xccdf/rules_test.rb
When creating AR objects, a `precedence` inferred from the order of the rules in the XML is passed. For newly created rules, this gets stored immediately, for rules that already existed the `Rule.import` call updates the `precedence` without calling any validations.
> feat(SSG): RHICOMPL-1736 set precedence on rules upon SSG import

- app/jobs/concerns/notifications.rb
- test/jobs/parse_report_job_test.rb
In case a host has ben unassigned from a policy, it should not fail when emitting notifications.
> fix(Notifications): RHICOMPL-2798 handle missing policy for reports

- app/consumers/concerns/report_parsing.rb
- app/consumers/inventory_events_consumer.rb
- test/consumers/inventory_events_consumer_test.rb
The `@msg_value['account']` is being used in our jobs, but it is not consistent with what we have in the kafka consumer. The correct location for the account is under `@msg_value['platform_metadata']['account']` that can be deducted from the fact that the inventory consumer passes the [`metadata`](https://github.com/RedHatInsights/compliance-backend/blob/4061c4a56ffdf43160d76e74c6dc2e69a307565b/app/consumers/concerns/report_parsing.rb#L96-L102) object that lives in Sidekiq as `@msg_value` further (different from the same variable name in the consumer). 
This caused our audit logging to omit the account information in inventory-consumer messages and that the account and host information in notifications was incorrect. Our tests of course were also incorrectly setting the account number at …
> fix(racecar): RHICOMPL-2801 retrieve account from the right location

- db/migrate/20220312143550_reset_remediations_syslog.rb
- db/schema.rb
- lib/tasks/import_remediations.rake
- test/tasks/import_remediations_test.rb
This is a very ugly hack and it should be refactored, but IMO we should not even have this complex logic in rake tasks. Therefore, we should first move logic from the rake tasks to classes and just invoke those. I'll create a ticket for this...
> hack(Remediations): RHICOMPL-2385 never import rsyslog_remote_loghost

- lib/tasks/import_datastream.rake
- test/tasks/import_datastream_test.rb
This is a comfort extra for deployments, right now we do need the environment variable AND the migration to do a forced import. With this change only the migration will be necessary, but the support for the variable will be still around if needed.
> feat(SSG): RHICOMPL-2767 force SSG import if datastream rev is nil

- app/graphql/types/system.rb
- app/serializers/host_serializer.rb
- test/controllers/v1/systems_controller_test.rb
- test/graphql/queries/system_query_test.rb
Unit tests are simple, if the parsed and converted timestamps equal to the original, the timestamp is in the right format.
> fix(Systems): RHICOMPL-2805 return all timestamps in ISO-8601 format

- Gemfile
- Gemfile.lock
- app/services/concerns/xccdf/profile_rule_groups.rb
- test/factories/rule.rb
- test/factories/rule_group.rb
This is going to fail until the [openscap parser changes](https://github.com/OpenSCAP/openscap_parser/pull/37) are merged and deployed and then we can update the gem version in our Gemfile.
I tested locally with the `openscap_parser` gem pointing to the commit in the PR and everything worked correctly.
> fix(import): RHICOMPL-2833 - Update ProfileRuleGroups import

- .commitlint.yml
- .github/workflows/ci.yml
Since we're using ticket ID where subject is expected in default configuration, our commits seem to fail on commitlint rule by being upper-case.
```
Error: You have commit messages with errors
⧗   input: feat(PolicyHost): RHICOMPL-2830 Check if host is supported
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```
_(see https://commitlint.js.org/#/reference-rules?id=subject-case)_
By using the regex it is defined where does the subject start.
_(see https://commitlint.js.org/#/reference-configuration?id=parser-presets)_
> ci(commitlint): RHICOMPL-2850 define parser options

- entrypoint.sh
- scripts/set_cgroup_limits.sh
Original implementation is [here](https://github.com/sclorg/container-common-scripts/blob/master/shared-scripts/core/usr/bin/cgroup-limits), this is intended for use in the ubi8-minimal container.
> refactor(entrypoint): RHICOMPL-2858 rewrite cgroup-limits to bash

- Gemfile.lock
Closes #1260 
Bumps [nokogiri](https://github.com/sparklemotion/nokogiri) from 1.13.3 to 1.13.4.
- [Release notes](https://github.com/sparklemotion/nokogiri/releases)
- [Changelog](https://github.com/sparklemotion/nokogiri/blob/v1.13.4/CHANGELOG.md)
- [Commits](https://github.com/sparklemotion/nokogiri/compare/v1.13.3...v1.13.4)
---
updated-dependencies:
- dependency-name: nokogiri
dependency-type: indirect
...
Signed-off-by: dependabot[bot] <support@github.com>
> chore(deps): bump nokogiri from 1.13.3 to 1.13.4

- entrypoint.sh
Executing the script doesn't set the ENV variables, calling `source` does...
> fix(entrypoint): RHICOMPL-2858 source the cgroup-limits for ENV

- scripts/set_cgroup_limits.sh
My bad, checking against the wrong var :see_no_evil: 
> fix(entrypoint): RHICOMPL-2858 use the correct variable for memlimit

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- app/models/concerns/profile_fields.rb
We don't need both, the `majorOsVersion` is being cleaned up in the frontend soon.
> cleanup(GraphQL): RHICOMPL-2895 replace the majorOsVersion

- clowdapp.yaml
- lib/tasks/import_remediations.rake
- test/services/datastream_importer_test.rb
Seems like this is not being used, so deleting.
> cleanup(env): RHICOMPL-2968 drop the JOBS_ACCOUNT_NUMBER param

- app/services/rbac.rb
- test/controllers/concerns/authentication_test.rb
- adding limit 1000 to exclude a possibility of the limit defaulting to lower number
- 1000 is max limit on RBAC API side: https://github.com/RedHatInsights/insights-rbac/blob/d511fffb50772489c009dcc1aa7ed00651eda256/rbac/api/common/pagination.py#L35
- setting empty auth_names to prevent setting Basic auth
- https://github.com/RedHatInsights/insights-rbac-api-client-ruby/blob/40abb3042dd6ea79d0b4e9b035d19449ac1725eb/lib/insights-rbac-api-client/api/access_api.rb#L88
without setting `auth_names` with empty string, `Authorization` header is being set:
```
GET /api/rbac/v1/access/?application=compliance%2Cinventory HTTP/1.1
Host: rbac:8080
User-Agent: OpenAPI-Generator/1.0.0/ruby
Content-Type: application/json
X_RH_IDENTITY: ...
Accept: application/json
Authorization: Basic Og==
```
after …
> fix(RBAC): RHICOMPL-2955 adjust request on RBAC API

- app/services/concerns/xccdf/rule_groups.rb
- db/migrate/20220511212358_clear_revisions_may_eleventh.rb
- test/services/concerns/xccdf/rule_groups_test.rb
Reverts RedHatInsights/compliance-backend#1286
> Revert "fix(RuleGroups): RHICOMPL-2956 update ancestry for rule groups correctly"

- app/graphql/types/profile.rb
The `where` clause in the `RecordLoader` gets called on the query every time, therefore having it more static causes more cache hits. As there are usually more hosts than profiles, it should speed up things if we swap these two.
> perf(GraphQL): RHICOMPL-3025 reverse querying of Profile#test_results

- clowdapp.yaml
- config/environments/production.rb
Should allow us to use a different secret (primary redis) in ephemeral environments. The default value would be the current secret.
> fix(Clowder): RHICOMPL-3068 optional fallback to primary redis

- app/graphql/types/query.rb
- test/graphql/queries/profile_query_test.rb
Instead of pre-authourizing against a specific profile, we can just scope the query against the user's account in order to get a 404 if the entity is not accessible.
> fix(GraphQL): RHICOMPL-721 scope profiles instead of pre-auth

- app/controllers/concerns/collection.rb
- app/models/concerns/benchmark_searching.rb
- app/models/rule.rb
- app/models/rule_result.rb
- app/serializers/supported_ssg_serializer.rb
- test/controllers/v1/business_objectives_controller_test.rb
- test/controllers/v1/profiles_controller_test.rb
* Only string-based fields should have implicit search, anything else doesn't really make sense
* If search is not supported for a model, we should fail with 422 instead of 500
* Null characters in a string should be handled with 422 instead of 500
* Serializer library has a bug for validating includes when having 0 relationships
For reproducing these issues, see the JIRA ticket
> Make parameter handling for searching and includes more robust

- build_deploy.sh
- pr_check.sh
- scripts/deploy/build-deploy-common.sh
- Refactor build-deploy-common deployment library
- Deprecate backwards compatibility tags (qa, latest tags no longer used)
- Update naming format of temporary image tags to match bonfire's build script
- Enforce usage of `docker` where available, fallback to `podman` when it's not.
- Detect and fail if it can't build the image
> RHICOMPL-3021 use same build logic for pr_check and build_deploy

- config/environments/development.rb
- docker-compose.yml
- lib/tasks/import_datastream.rake
- lib/tasks/import_remediations.rake
- test/tasks/import_datastream_test.rb
https://issues.redhat.com/browse/RHICOMPL-2808
Replacing the `puts` calls in the rake tasks with logging pushes these messages into the logfile in development. By extending the `RAILS_LOG_TO_STDOUT` to development and imposing it on the `import-ssg` container, this can be fixed. As a side-effect we will have much more logging info during the SSG import process with the default loglevel, i.e. DB queries that should motivate us to optimize even more :wink: 
> Fix unbuffered logging when importing SSG content in production

- app/models/supported_ssg.rb
Refactored the cache fetching part and added some expiry, which is just for safety. Also fixed the condition for forcing the download of the content to `tmp`. It doesn't fix the bug as the cache is still storing the bad values, but it is necessary.
> fix(ssg): RHICOMPL-2627 adjusted cache expiry and forced download

- config/initializers/exception_notification.rb
We actually don't have influence on the name of the channel, I just changed it for semantics. So if someone in the future is not falling into the same pit as I did with looking for notifications on the wrong channel :see_no_evil: 
> fix(slack): RHICOMPL-2648 adjust the channel for error notifications

- app/models/concerns/profile_fields.rb
- app/models/os_major_version.rb
- app/models/profile.rb
Should improve the performance of the GQL request on the create profile. Do more benchmarks than one as the first one can be slower due to cache setup if ran locally.
> perf(OsMajorVersion): RHICOMPL-3194 pass the OS version to profiles

- app/graphql/types/benchmark.rb
- app/graphql/types/rule.rb
- app/models/rule.rb
- app/models/rule_identifier.rb
- test/graphql/queries/benchmark_query_test.rb
Using GQL lookahead, we can preload the rule identifiers for rules under benchmarks which speeds up the loading significantly and also reduces the amount of allocated objects. My benchmark says that without optimization loading takes 2.5 seconds and when optimized it's around 850 milliseconds, which is more or less the same as we would not request the identifiers.
```
query benchmarkQuery($id: String!) {
benchmark(id: $id) {
id
osMajorVersion
rules {
id
title
severity
rationale
refId
description
remediationAvailable
identifier
__typename
}
__typename
}
}
```
> perf(Benchmarks): RHICOMPL-3176 preload rule identifiers if needed

- app/models/supported_ssg.rb
Dropping the revision from the cache key reduces the number of allocations by ~100k and the latency by 200ms for this query:
```
time curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XPOST -d '{
"operationName": "supportedProfilesByOSMajor",
"variables": {},
"query": "query supportedProfilesByOSMajor {
osMajorVersions {
edges {
node {
osMajorVersion
profiles {
id
name
refId
description
complianceThreshold
supportedOsVersions
benchmark {
id
refId
osMajorVersion
}
}
}
}
}
profiles(search: \"external = false and canonical = false\") {
edges {
node {
id
refId
benchmark {
refId
}
}
}
}
}"
}' "http://localhost:3000/api/compliance/graphql" | jq
```
@vkrizan any objections? 
> perf(SupportedSsg): RHICOMPL-3200 drop Revision from cache key

- config/initializers/sidekiq.rb
Should reduce the number of forked threads in the puma/rails container.
> fix(Sidekiq): RHICOMPL-3217 load the reliable-fetch only for sidekiq

- clowdapp.yaml
Turning this on for the puma pods, leaving everything else alone for now. This is just an experiment that I hope reduces overall memory usage even more.
https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
> perf(puma): RHICOMPL-3218 reduce the number of malloc arenas to 2

- config/puma.cfg
- config/puma.rb
Yabeda doesn't collect any rails/gql metrics after [disabling the puma collector](https://github.com/RedHatInsights/compliance-backend/pull/1426). 
> revert(metrics): RHICOMPL-3232 re-enable puma metrics collection

- clowdapp.yaml
This was done by mistake as we thought that the report upload performance was dropped, but actually the REST API was not responsive.
This reverts commit 7a74942ee5c07e251415e8d9574a45251064fea6.
> perf(clowder): RHICOMPL-3220 re-enable MALLOC_ARENA_MAX for racecar

- clowdapp-minimal.yaml
- clowdapp.yaml
This should make the pr_check runs start using current Clowder supported PostgreSQL ver. 13 , currently 13.3 
> feat(db update): RHICOMPL-2467 bump DB used in ephemeral to 13

- app/graphql/types/base_connection.rb
- test/graphql/queries/system_query_test.rb
When having 2 systems, this query before the change returns just 1 in totalCount. Using `#size` on a relation just counts the already loaded entities, scoped to the pagination.
```bash
time curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XPOST -d '{
"operationName": "getSystems",
"variables": {},
"query": "query getSystems {
systems(limit: 1) { 
edges {
node {
id
}
}
totalCount
}
}"
}' "http://localhost:3000/api/compliance/graphql" | jq
```
> fix(GQL): RHICOMPL-3225 provide the totalCount using #count

- app/controllers/concerns/exception_notifier_custom_data.rb
Sometimes if an error happens during the controller hooks (e.g. RBAC checks) the data section of the exception notification is not set properly. In some of these cases the current user is not even set up, therefore, I split it up into two hooks. One that runs as the very first in each controller, and another one that sets the current user after the user is authorized via RBAC.
> fix(ExcNotify): RHICOMPL-3227 set the data segment as first hook

- app/graphql/resolvers/concerns/collection.rb
- app/graphql/types/system_connection.rb
- app/models/host.rb
- test/graphql/queries/system_query_test.rb
Should fix the problem of non-scoped tags, depends on https://github.com/RedHatInsights/compliance-backend/pull/1437
> fix(GraphQL): RHICOMPL-3244 make tags a named scope for systems

- app/models/concerns/profile_searching.rb
- config/initializers/override_scoped_search_escaping.rb
- test/controllers/concerns/metadata_test.rb
- test/controllers/v1/profiles_controller_test.rb
Used this to test the time/efficiency of the old `name` scoped_search and the new version implemented here: 
`http --meta --verify no GET http://0.0.0.0:3000/api/compliance/v1/profiles search==name~"ANSSI" X-RH-IDENTITY:$ID_HEADER`
Old version: `Completed 200 OK in 361ms (Views: 253.5ms | ActiveRecord: 91.0ms | Allocations: 83467) `
Old version timed with httpie: 0.447715618s 
New version: `Completed 200 OK in 325ms (Views: 214.0ms | ActiveRecord: 90.5ms | Allocations: 83458)`
New version timed with httpie: 0.452380513s
Efficiency is about the same and this new `name` scoped_search for profiles is searching profiles and policies. It was only searching profiles before.
> fix(REST): RHICOMPL-1612 fix scope_search on profile name

- app/controllers/concerns/authentication.rb
The `User`'s object id has been changing with each request, therefore `@rbac_permissions` kept re-initializing as `nil`.
> fix(RBAC): RHICOMPL-3230 preserve user instance

- app/models/rule_result.rb
Scoped search doesn't like if there's no implicit search field on a model.
> fix(search): RHICOMPL-3246 set implicit searchable field on RuleResult

- Dockerfile
Temporary workaround for a bug that was introduced in 2.3.23 to unblock future work on compliance.
> fix(Dockerfile): RHICOMPL-3335 lock the version of bundler to 2.3.22

- app/models/concerns/sortable.rb
- app/models/rule_result.rb
When requesting a set of rule results contextualized under a specific user, the hosts table is being used in a subquery to filter them for a given user. This collides with the default sort of rule results by `id` and produces SQL queries that run for 6-10 seconds. After a few experiments we determined that sorting by `host_id` improves the performance the most. Therefore, I implemented a declarative way to prepend a default sort column for rule results before sorting by `id`. 
This is unfortunately something we cannot reproduce, but the query plans coming back from Gabi show that the changes make production 10x faster for this query
> perf(RuleResults): RHICOMPL-3332 order rule results by host_id

- Gemfile
- Gemfile.lock
- app/services/concerns/xccdf/profile_rule_groups.rb
- db/migrate/20221014125732_clear_revisions_oct_fourteenth.rb
- db/schema.rb
- test/services/concerns/xccdf/profile_rule_groups_test.rb
This PR relies on this [openscap_parser PR](https://github.com/OpenSCAP/openscap_parser/pull/39) being merged and released but I tested locally with the gem updates and the import worked correctly and the tests passed. 
To get the tests to pass locally: 
Checkout this branch locally and then update the openscap_parser line in the Gemfile to:
`gem 'openscap_parser', git: 'https://github.com/OpenSCAP/openscap_parser.git', branch: 'master'`
(Tests will continue to fail with `NoMethodError: undefined method `unselected_group_ids' `until openscap_parser changes are released)
> fix(import): RHICOMPL-3331 import selected groups correctly

- app/models/concerns/profile_fields.rb
- app/models/rule.rb
- app/models/rule_group.rb
- app/models/rule_group_relationship.rb
- test/factories/profile.rb
- test/models/profile_test.rb
- test/models/rule_group_test.rb
Here's an example of what the rules_and_rule_groups method returns: 
```
[
{
"rule_group"=>#<RuleGroup id: "29229bf4-227d-4f22-8d34-7dcd18b5dbac",ref_id: "foo_group_8b413bb7-96c3-4e74-9ea8-4b735eb74768", title: "Omnis ut ducimus vitae.", description: "Quos facilis quas. Est sequi rem. Sit veritatis id...", rationale: "Voluptas pariatur voluptate. Facilis iste rerum. M...", ancestry: nil, benchmark_id: "ffd5e1a1-09a8-4f83-9983-b3bf90bf726f", rule_id: nil>,
"group_children"=>[
{
"rule_group"=>#<RuleGroup id: "33099b35-0c74-4a1b-96bc-abbbe6e630ed", ref_id: "foo_group_47fbbe48-12ca-4da6-bbda-a7331c58b009", title: "A voluptatem eaque soluta.", description: "In optio non. Ut iusto facilis. Itaque ut soluta.", rationale: "Magnam doloribus distinctio. Et et aut. Minus quae...", ancestry: …
```
> feat(Profile): RHICOMPL-3278 get rules and groups of profile

- app/models/concerns/rules_and_rule_groups.rb
- app/models/rule_group.rb
- test/models/benchmark_test.rb
- test/models/profile_test.rb
- test/models/rule_group_test.rb
@marleystipich2 please go through this, even if it's merged by the time you check it. Took your extraction from #1273 and moved it here + renamed it to `with_relationships` as it calls the same scope on the `RuleGroupRelationship` model. You don't need the `rules` and `rule_groups` as an argument as they are available in the scope of the `Benchmark` and the `Profile`. The usage of symbols and the `x: y` (seattle-style) syntax in hashes is preferred over the hash rockets and the strings `'x' => y` when possible. Also when a method is about building a hash (or hashes) with a lot of keys, it is allowed to disable the linelength cop and move them on separate lines as it is more readable. 
> refactor(RuleGroups): RHICOMPL-3402 make the mixin more readable

- app/models/concerns/profile_tailoring.rb
- app/models/concerns/rules_and_rule_groups.rb
- app/models/rule.rb
- app/models/rule_group_relationship.rb
- test/models/profile_test.rb
Note: The XCCDF specifications says to only deselect the item that has a conflict and to not touch any other items in the Benchmark(so don't try to resolve the conflict by selecting or deselecting other items in the Benchmark)
```
Also, <xccdf:requires> and
<xccdf:conflicts> elements SHALL only change their parent item; they SHALL NOT modify
other items in the <xccdf:Benchmark>. 
```
```
Rules and Groups may contain any number of <xccdf:requires> and <xccdf:conflicts>
elements and if any of these elements do not evaluate to true, then that item SHALL become deselected. 
```
Here is an example of how conflicts are resolved: 
> feat(tailoring): RHICOMPL-2554 Add conflict resolving for rules

- Dockerfile
This is an annoying problem that only affects development, the prometheus-mmap folders start showing up when running with compose up. The fix is trivial, just moving them under [tmp](https://gitlab.com/gitlab-org/ruby/gems/prometheus-client-mmap#memory-mapped-files-storage-location)
> dev(Dockerfile): move the prometheus mmap folder under the tmp

- Dockerfile
There were some warnings about the `/tmp` folder being world-writable when running `bundle install` + I found an obsolete command of installing non-development dependencies twice in production.
> Adjustments to the first build stage in the Dockerfile

- app/models/concerns/profile_searching.rb
- test/controllers/v1/profiles_controller_test.rb
When doing implicit search with profile/policy names both, the operator is not always populated by default, which can cause errors...so setting it to `=`.
> fix(ProfileSearching): RHICOMPL-3427 implicit operator for search

- app/graphql/mutations/profile/tailor_profile.rb
- test/graphql/mutations/tailor_profile_test.rb
This should be reverted after the frontend starts sending group tailoring information via the new endpoint.
> fix(GQL): RHICOMPL-3408 fall back to default groups if not passing any

- Dockerfile
Seems like the issue has been either fixed or was never present.
> fix(Dockerfile): RHICOMPL-3337 drop the version lock from bundler

- app/models/profile.rb
- app/models/rule.rb
- app/models/rule_group.rb
- app/services/concerns/xccdf/profiles.rb
- app/services/concerns/xccdf/rule_groups.rb
- app/services/concerns/xccdf/rule_references_rules.rb
- app/services/concerns/xccdf/rules.rb
- test/services/concerns/xccdf/profile_rule_groups_test.rb
- test/services/concerns/xccdf/profile_rules_test.rb
- test/services/concerns/xccdf/rule_references_rules_test.rb
- test/services/concerns/xccdf/rules_test.rb
Extracting the `find` part of `find_or_initialize_by` in the Rule/Group/Profile models to reduce the load on the database. 
**Before:**
```
bin/rake db:truncate_all # clear DB
time bin/rake ssg:import_rhel_supported
real  3m57.819s
user  3m20.576s
sys 0m4.161s
bin/rails r "Revision.find_by(name: 'datastreams').delete" # force import
time bin/rake ssg:import_rhel_supported
real  3m2.538s
user  2m40.986s
sys 0m3.074s
```
**After:**
```
bin/rake db:truncate_all # clear DB
time bin/rake ssg:import_rhel_supported
real  3m33.509s
user  2m59.564s
sys 0m3.414s
bin/rails r "Revision.find_by(name: 'datastreams').delete" # force import
time bin/rake ssg:import_rhel_supported
real  2m47.653s
user  2m28.603s
sys 0m2.402s
```
We're faster by additional 20-30 seconds :zap: :tada: 
- …
> perf(SSG): RHICOMPL-3458 extract model initialization when importing

- Gemfile
- Gemfile.lock
- app/services/concerns/xccdf/rule_groups.rb
- test/services/concerns/xccdf/rule_groups_test.rb
Verified that openscap_parser returns the `parents_ids` of the groups in the correct order and the `ancestry` column on rule_groups is also set up in the correct order. Added tests to check this as well. 
> fix(SSG): RHICOMPL-3454 correctly set ancestry column during import

- app/controllers/v1/profiles_controller.rb
- app/models/concerns/profile_tailoring.rb
- app/services/xccdf_tailoring_file.rb
- test/models/profile_test.rb
- test/services/xccdf_tailoring_file_test.rb
Test cases covered in `profile_test.rb` :
- `rule_group_ancestor_ref_ids` returns all rule group ancestors for added rules when the rule_group depth is 4
-`rule_group_ancestor_ref_ids` returns all rule group ancestors for added rules when the rule_group depth is 1
- `rule_group_ancestor_ref_ids` does not return any rule groups that are not the parent or ancestor of an added_rule
Test cases covered in `xccdf_tailoring_file.rb`:
- all rule group ref_ids in `rule_group_ref_ids` should be added to the tailoring file with `selected='true'`
- There are no rule groups added to the tailoring file that isn't included in `rule_group_ref_ids`
> feat(Tailoring): RHICOMPL-2947 Add groups to tailoring file

- test/services/concerns/xccdf/rule_groups_test.rb
```
DEPRECATED: Use assert_nil if expecting nil from test/services/concerns/xccdf/rule_groups_test.rb:53. This will fail in Minitest 6.
```
> fix(tests): fixed deprecation for asserting nil value

- app/controllers/concerns/rendering.rb
Calling `includes` with `references` on a relation triggers `eager_load` which in case of more than 2 tables is costly. The worst performing one is the `RulesController` that works with 4 levels of joins. All the includes in other controllers are loading at least 3 tables, therefore, falling back to `preload` should improve memory usage for the price of entering multiple times into the DB instead of a single query.
The only other usage of eager loading is in the `rule_tree` where only a single table is pulled in, which is good as it is.
> perf(API): RHICOMPL-3497 disable eager loading of large relations

- app/controllers/concerns/metadata.rb
- app/models/application_record.rb
- app/models/rule_result.rb
Introducing a `count_by` method that defaults to `:id` to make counting results faster. This default value has the most significance for the `rules` (2x faster) and `systems` (15x faster) endpoint. For the `rule_results` it needed a custom column to make it even faster (~20x) as it allows PG to not enter the table at all and just use the index.
> perf(REST): RHICOMPL-3500 always count results by a specific column

- app/controllers/concerns/exception_notifier_custom_data.rb
- app/controllers/graphql_controller.rb
- config/initializers/yabeda.rb
I created a primitive regex that can parse a single operation+name from the GQL params. I intentionally made it restricted to chars+numbers up to 32 characters to avoid the injection of weird or long stuff into prometheus. This information is then being passed to the exception notifications and to Yabeda as a tag for alerting and metrics.
> feat(metrics): RHICOMPL-3501 pass the gql_op with metrics/alerts

- Gemfile
- Gemfile.lock
- app/models/profile.rb
- app/models/rule.rb
- app/models/value_definition.rb
- app/services/concerns/xccdf/profiles.rb
- app/services/concerns/xccdf/rules.rb
- app/services/concerns/xccdf/util.rb
- app/services/concerns/xccdf/value_definitions.rb
- app/services/datastream_importer.rb
- db/migrate/20221216135909_reset_revision_dec_sixteenth.rb
- db/schema.rb
- test/factories/value_definition.rb
- test/services/concerns/xccdf/profiles_test.rb
- test/services/concerns/xccdf/rule_references_containers_test.rb
- test/services/concerns/xccdf/rules_test.rb
- test/services/concerns/xccdf/value_definitions_test.rb
- test/services/xccdf_report_parser_test.rb
Purpose of this PR:
- Update openscap_parser gem to version 1.6.0
- Import Values into the `value_definitions` table
- Import `value_overrides` that holds value refinements for a Profile
- Import `value_checks` for a Rule (these are the values that are used by the Rule)
Note: I imported the `lower_bound`s and `upper_bound`s of a ValueDefinition since we are parsing the info in openscap_parser but they are not used at all in our datastreams and the openscap team said they have no plans to use them in the future.
> feat(Import): RHICOMPL-3475 import Values into the DB

- Gemfile
Upsert in Rails 7 is not sufficient to stop using `activerecord-import` gem.
> cleanup(Gemfile): remove incorrect comment for activerecord-import

- app/services/concerns/xccdf/profiles.rb
The partial index on the benchmarks/ref_ids is a bit messy for the importer, so instead we can use the primary key. This should simplify the syntax according to the [docs](https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L438-L444).
> fix(SSG): RHICOMPL-3514 use the default conflict target for profiles

- app/controllers/v1/profiles_controller.rb
- app/services/xccdf_tailoring_file.rb
- test/services/xccdf_tailoring_file_test.rb
Waiting to merge this until values are imported in the DB: https://issues.redhat.com/browse/RHICOMPL-3475
Example of what's added to the tailoring file:
`<set-value idref="foo_value_e61824be-c7a3-4701-96f6-55b21cdafd7b">testing</set-value>
<set-value idref="foo_value_62d90c6d-3cac-491d-a778-f236e7d9ddad">true</set-value>
<set-value idref="foo_value_0f821a89-4734-46d7-80d7-78dd459ad14a">3</set-value>`
> feat(Tailoring): RHICOMPL-3398 add set-value to tailoring file

- app/serializers/rule_serializer.rb
The `remediation_issue_id` is a field used for applying remediations when scoped under a profile, otherwise it does not even make sense and slows down everything as it generates N+1. Scoping it down for models where it is already available without an extra query...
> perf(REST): RHICOMPL-3531 not load rem_issue_id with benchmarks

- config/initializers/rbac.rb
It's a bit of hacky to get the schema from the URL, but it complies with how clowder works. Might be a future refactoring point for @RoamingNoMaD :wink: 
> fix(RBAC): RHINENG-101 set the URL scheme for RBAC requests

- build_deploy.sh
- scripts/deploy/build-deploy-common.sh
- Adds the `DISABLE_BUILD_CACHE` to `build-deploy-common` 
- Sets the `DISABLE_BUILD_CACHE` to true to workaround: https://github.com/containers/buildah/issues/4632
- Disable requirement to log to registries on local build mode
> fix(ci): RHCLOUD-25345 add no-cache to builds

- app/services/concerns/xccdf/profiles.rb
- db/migrate/20230503142809_reset_revisions_value_definition.rb
- db/schema.rb
There was an anomaly when we weren't specifying a conflict target upon duplicated import. This change should fix this problem @marleystipich2 
> fix(ValueDefinition): RHICOMPL-3648 adjust importing for profiles

- app/models/concerns/rule_tree.rb
- test/models/benchmark_test.rb
As discussed with @bastilian, I am reducing the amount of information requested by the ruleTree. Furthermore, instead of preloading the rules related to specific groups, we can load them for all benchmarks and do a local grouping by the group_id which reduces the allocations. In total we can free up 75% of the allocations :zap: 
> perf(API): RHICOMPL-3754 optimize and minimalize RuleTree

- app/graphql/types/base_object.rb
- app/graphql/types/benchmark.rb
This change adjusts the cache key generation to be independent from any other top-level parents than the actual object where the cached field is specified. This means that if in a query a given benchmark is wrapped in a profile, it would still resolve to the same cache key as requesting the benchmark directly. This generalization should speed up queries even more and also reduce the load on redis as each cached field should require just one entry per benchmark.
```
query Profile($id: String!) {
profile(id: $id) {
benchmark {
ruleTree
}
}
}
```
```
query Benchmark($id: String!) {
benchmark(id: $id) {
ruleTree
}
}
```
If the profile ID queried in the first query belongs to the benchmark that is queried in the second one, the cache key would resolve in both cases to the same thing, i.e. …
> perf(GraphQL): RHICOMPL-3775 generalize the cache key for fragments

- app/models/concerns/rule_tree.rb
When requesting both `rules` and `ruleTree` in a `benchmarkQuery`, we fired 2 SQL queries for the same things as one of them contained specific fields. With this change the first query will produce a cache hit for the second one.
```
query benchmarkQuery($id: String!) {
benchmark(id: $id) {
id
osMajorVersion
rules {
id
title
severity
rationale
refId
description
remediationAvailable
identifier
values
__typename
}
__typename
}
}
```
> perf(GraphQL): RHICOMPL-3770 do not request rules twice in benchmarks

- deploy/clowdapp.yaml
* Dropped the parameters for prometheus as the pod no longer exists
* Renamed the parameters to the full names of the services
* Unified the requested CPU for all services to 100m
* Increased the requested memory for the service pod from 500MB to 600MB
* Lowered the requested memory for the import job to 100MB (not applies to ephemeral)
* All the memory/CPU limits were unchanged, except the service memory has been capped to 1200MB
|          | oldCPU | oldMEM | newCPU | newMEM |
|----------|--------|--------|--------|--------|
| CONSUMER | 50     | 400    | 100    | 400    |
| SIDEKIQ  | 100    | 400    | 100    | 400    |
| SERVICE  | 400    | 500    | 100    | 600    |
| IMPORT   | 300    | 500    | 100    | 100    |
> perf(clowder): RHICOMPL-3218 adjust memory/cpu limits for services

- app/graphql/schema.rb
- deploy/clowdapp.yaml
It is allocating 50% of the memory and uses around the same CPU time based on my profiling results. Until we find a better alternative, we should suspent it.
> perf(GraphQL): RHICOMPL-3846 suspend yabeda gql metrics collection

- app/graphql/schema.graphql
- app/graphql/types/os_major_version.rb
- app/graphql/types/profile.rb
- app/models/os_major_version.rb
- test/graphql/queries/os_major_version_query_test.rb
- test/models/os_major_version_test.rb
This needed to revert the `inUse` field from the schema, which was never actually consumed by the frontend.
> perf(GraphQL): RHICOMPL-3849 enable fragment caching on OS#profiles

- Gemfile
- Gemfile.lock
- app/controllers/graphql_controller.rb
- app/graphql/schema.rb
- dashboards/grafana-dashboard-insights-compliance-general.template.yaml
- deploy/clowdapp.yaml
Replacing the GraphQL field resolve histogram with a simple request duration one combined with the GQL operation name that comes from the top-level query naming itself.
**Before:**
**After:**
> fix(Grafana): RHICOMPL-3847 measure GQL operation durations

- app/graphql/schema.rb
The `graphql-fragment-cache` gem uses a [tracer](https://github.com/DmitryTsepelev/graphql-ruby-fragment_cache/blob/master/lib/graphql/fragment_cache/schema/tracer.rb) that is only used to raise an error when dealing with connection fields. As we implement our own pagination, we do not relay on this feature. Furthermore, the tracer is using the legacy tracing API, which involves a lot of extra memory usage. Therefore, turning it off should result in better performance.
> perf(GraphQL): RHICOMPL-3848 do not use the fragment caching tracer

- app/controllers/concerns/error_handling.rb
When passing `id = 'string'` to a query, it should fail as an invalid param.
> fix(REST): RHICOMPL-3463 fail on passing invalid format to search

- .github/workflows/ruby-update.yml
I created a cronjob GH action that goes into our base container and tries to assess the version of Ruby to be installed. Then changes the version in the `.ruby-version` file itself and creates a PR. This has no effect in production, but should force our development environments (rbenv, rvm, etc) to run on the same version as the container :wink: 
> feat(devel): periodically update .ruby-version based on the package

- Dockerfile
Installing ri documentation for any gem is disabled during container buildtime, however, when running `gem update --system -V` I noticed that there is some documentation being generated that takes 1-2 minutes. This is something we don't really need.
**Before:**
```
podman build .  246.24s user 74.36s system 114% cpu 4:39.88 total
```
**After:**
```
podman build .  246.31s user 69.35s system 142% cpu 3:40.77 total
```
This should make the CI build ~~a little bit~~ significantly faster :zap: :racehorse: from 7:22 to 3:49 :racehorse: :zap: 
> perf(build): RHICOMPL-3875 do not install docs with rubygems update

- Gemfile
- Gemfile.lock
Should install less gems when running unit tests during the Jenkins pipeline :zap: 
> cleanup(Gemfile): reorganize dev/test dependencies

- Dockerfile
Nokogiri tries to install itself on aarch64 builds (when running docker on apple silicon) and it fails with an older version of glibc. Therefore, we have to force the local compilation even stronger by setting it into the bundle config.
@marleystipich2 @romanblanco @RoamingNoMaD please test this on your setup after clearing the environment
> fix(Dockerfile): force ruby platform for nokogiri in bundle config

- docker-compose.yml
The latest version of kafka support KRaft mode which allows it to operate in single node without requiring zookeeper. This should simplify our developer setup and reduce the use of resources.
> dev(compose): use single-node kafka without zookeeper

- app/controllers/concerns/v2/parameters.rb
- app/controllers/v2/application_controller.rb
- spec/controllers/v2/concerns/parameters_spec.rb
I am splitting out the parameter handling for APIv2 as we need to have different behavior for nested routes and I don't want to allow these parameters in APIv1. Rails routes allows the specification of custom parameters for resources, which I am planning to use for setting up a list of parent models in a nested resource scenario:
```ruby
resources :security_guides do
resources :profiles, parents: [SecurityGuide] do
resources :rules, parents: [SecurityGuide, Profile]
end
end
```
This list of parents will be useful for many other scenarios, but for now we will stick to using them for parameter validation only. The `StrongerParameters` gem that we use for parameter validation does not like the implicit parameters (`profile_id` and `security_guide_id` in case of the example above) of parent …
> feat(V2::Parameters): RHICOMPL-3891 allow params for nested routes

- spec/spec_helper.rb
RSpec automatically coerces all passed params to string by calling the `to_s` method on them. This is unfortunate as we are using route-level parameters to determine the nesting of a given route. To avoid this, I created a wrapper that can temporarily mock the `.to_s` method on a given list of parent classes that would be passed as a route-level parameter. After the request is called, the mocks are reset back to normal so there should be no side effects. The method yields a list of mocked parents that can be passed with the `params` in the block:
```ruby
nested(Model1, Model2) do |parents|
get :index, params: { model_1_id: 1, model_2_id: 2, parents: parents }
end
```
> feat(RSpec): helper wrapper for nested route `params[:parents]` mocking

- app/services/rbac.rb
- test/controllers/v1/profiles_controller_test.rb
- test/controllers/v1/systems_controller_test.rb
- test/graphql/mutations/associate_systems_test.rb
- test/graphql/queries/profile_query_test.rb
- test/graphql/queries/system_query_test.rb
- test/policies/host_policy_test.rb
- test/policies/policy_host_policy_test.rb
- test/services/rbac_test.rb
This was incorrectly coded, the `attributeFilter` coming from the RBAC API is converted to [`attribute_filter`](https://github.com/RedHatInsights/insights-rbac-api-client-ruby/blob/7a4462db8cb6eed30991f97aa298dcea03cbf034/docs/ResourceDefinition.md?plain=1#L7).
> fix(RBAC): RHICOMPL-3850 replace attributeFilter with attribute_filter

- app/services/rbac.rb
- test/controllers/v1/profiles_controller_test.rb
- test/controllers/v1/systems_controller_test.rb
- test/graphql/mutations/associate_systems_test.rb
- test/graphql/queries/system_query_test.rb
- test/policies/host_policy_test.rb
- test/policies/policy_host_policy_test.rb
- test/services/rbac_test.rb
There is no JSON parsing on the `ResourceDefinition#value` response...ideally it should be done by the API client, but for now we're fixing it fast.
> fix(RBAC): RHICOMPL-3850 compensate JSON parsing on RD.values

- Jenkinsfile
- config/environments/production.rb
- config/initializers/sidekiq.rb
- lib/tasks/status.rake
As clowder doesn't provide the SSL option for redis yet, we relied on the `SETTINGS__REDIS__SSL` environment variable. The latest version of the `config` gem merges settings coming from clowder in a different way and somehow ignores this environment variable. This causes a failure in starting up sidekiq in some cases, so I am working it around by directly reading the environment variable until clowder doesn't provide us this param out of the box.
> fix(Clowder): RHCLOUD-27386 workaround for REDIS_SSL

- app/models/policy.rb
- test/graphql/mutations/associate_systems_test.rb
The unassignment of systems per policy has been affecting other policies as the query for the selection of hosts to delete was not taking into account the policy ID.
> fix(PolicyHost): RHICOMPL-3949 scope down unassignment per policy

- Dockerfile
This is a temporary solution until we don't have an easy way to compile rust extensions on RHEL
> fix(Dockerfile): remove deprecation warning for prometheus rust

- app/controllers/concerns/v2/collection.rb
- app/controllers/concerns/v2/parameter_handling.rb
- app/controllers/v2/application_controller.rb
- app/controllers/v2/profiles_controller.rb
- app/controllers/v2/rules_controller.rb
- app/controllers/v2/security_guides_controller.rb
- app/controllers/v2/value_definitions_controller.rb
- app/models/v2/profile.rb
- app/models/v2/rule.rb
- app/models/v2/security_guide.rb
- app/models/v2/value_definition.rb
- config/routes.rb
- db/migrate/20230901184111_create_security_guides.rb
- db/migrate/20230901184656_create_v2_value_definitions.rb
- db/migrate/20230901184939_create_v2_rules.rb
- db/schema.rb
- db/views/security_guides_v01.sql
- db/views/v2_rules_v01.sql
- db/views/v2_value_definitions_v01.sql
- spec/controllers/v2/concerns/paginable_spec.rb
- spec/controllers/v2/concerns/parameter_handling_spec.rb
- spec/controllers/v2/concerns/searchable_spec.rb
- spec/controllers/v2/concerns/sortable_spec.rb
- spec/controllers/v2/concerns/with_metadata_spec.rb
- spec/controllers/v2/profiles_controller_spec.rb
- spec/controllers/v2/rules_controller_spec.rb
- spec/controllers/v2/security_guides_controller_spec.rb
- spec/controllers/v2/value_definitions_controller_spec.rb
- spec/spec_helper.rb
* V2 model reflections and foreign keys now match the parent IDs in nested routes
* Simplified relationships on the V2 models, less to clean up later after the remodel
* Instead of parent resources, routes now define parent reflections
* Resources are automatically joined & scoped with their parent resources in nested routes
Note that the `parents` configuration expects the reflection (`has_many`, `belongs_to`, etc) name, which is in some cases pluralized, e.g.:
```ruby
belongs_to :security_guide
has_many :profile_rules, dependent: :delete_all
has_many :profiles, through: :profile_rules, source: :profile, class_name: 'V2::Profile'
resources :security_guides, only: [:index, :show] do
resources :profiles, only: [:index, :show], parents: [:security_guide] do
resources :rules, only: [:index, …
```
> RHICOMPL-3959 make the controllers usable for multiple routes

- spec/api/v2/openapi.rb
- spec/api/v2/schemas.rb
- spec/api/v2/schemas/metadata.rb
- spec/api/v2/schemas/security_guides.rb
- spec/api/v2/schemas/types.rb
- spec/api/v2/schemas/util.rb
- spec/integration/security_guides_spec.rb
- spec/swagger_helper.rb
- swagger/v2/openapi.json
> feat(REST): RHICOMPL-3904 generate APIv2 spec

- app/services/rbac.rb
- test/graphql/queries/profile_query_test.rb
- test/services/rbac_test.rb
This is an ugly hack to compensate for the badly defined OpenAPI spec of RBAC until the type definitions get fixed.
> fix(RBAC): RHINENG-2329 compensate for badly generated swagger client

- app/models/host.rb
- test/controllers/v1/systems_controller_test.rb
The `SqlLiteral` arel object has no `or` method defined, so the ungrouped hosts only condition needs to be converted to a different node that returns with an empty collection.
> fix(Host): RHINENG-2329 return empty scope as arel node for groups

- app/models/v2/profile_rule.rb
- app/models/v2/rule.rb
- config/routes.rb
- spec/controllers/v2/concerns/collection_spec.rb
- spec/controllers/v2/rules_controller_spec.rb
- spec/factories/profile_rule.rb
- spec/factories/rule.rb
- spec/fixtures/files/searchable/rules_controller.yaml
- spec/fixtures/files/sortable/rules_controller.yaml
> feat(APIv2): RHINENG-2133 implement rules endpoint nested under profiles

- spec/delete_host_spec.rb
This sporadic error stems from the fact that the compliance score is calculated as a mean.
When one of the three created compliance scores is the average of the other two, and we delete the host associated with the compliance score that is the mean, we still get the same overall compliance score, thus the test failed.
By fixating the compliance scores of these three hosts in a manner where no combination of two scores gives us the third score, the sporadic error will not occur anymore.
> fix(test): RHINENG-2692 fix sporadic DeleteHost error

- app/controllers/concerns/v2/collection.rb
- app/controllers/v2/application_controller.rb
- spec/controllers/v2/concerns/rendering_spec.rb
- spec/controllers/v2/rules_controller_spec.rb
When requesting a nested `/index` with an existing but different root parent ID, the query returns an empty array instead of failing with a 404 error.
By joining the parents during parent validation and calling `find` we can trigger a not_found error when any of the parent hierarchy is invalid.
> fix(APIv2): RHINENG-2720 return not_found when parent ID is invalid

- Gemfile
- Gemfile.lock
- app/models/v2/policy.rb
- app/models/v2/tailoring.rb
- db/functions/tailorings_insert_v01.sql
- db/functions/v2_policies_delete_v01.sql
- db/functions/v2_policies_insert_v01.sql
- db/functions/v2_policies_update_v01.sql
- db/migrate/20231026190907_make_tailorings_writable.rb
- db/migrate/20231026194802_make_v2_policies_writable.rb
- db/schema.rb
- db/seeds.dev.rb
- db/triggers/tailorings_insert_v01.sql
- db/triggers/v2_policies_delete_v01.sql
- db/triggers/v2_policies_insert_v01.sql
- db/triggers/v2_policies_update_v01.sql
As these views are built on top of multiple tables, they are not writable by default. As a solution I created a few functions and triggers to make sure that the data gets passed correctly to the underlying tables. The `tailorings` table only required a trigger for insertion to prevent the violation of some constraints. The `v2_policies` needed more adjustments to make sure that the underlying business objective gets created/updated/deleted together with the policy. This is part of the effort of getting rid of the `business_objectives` table in the future.
> feat(DB): RHINENG-1986 make tailorings and v2_policies writable

- Jenkinsfile
- build_deploy.sh
- scripts/unit_test.sh
https://github.com/RedHatInsights/cicd-tools/tree/aeb9fe8b13b4a5524014ada4b0d324020dd04289
> fix(CI): RHCLOUD-26746 Replace build-deploy-common library 

- app/controllers/v2/application_controller.rb
- app/models/application_record.rb
- app/serializers/v2/application_serializer.rb
The idea here is to reuse the `derived_attribute` for fields joinable from 1:1 associations that aren't in the routing hierarchy of the given resource. A good example will be the `/policies` route that should display `os_major_version` of each entity that is available by joining it with the `SecurityGuide` association. 
1. Created the `ApplicationRecord.one_to_one` method to return a list of 1:1 associations on a given model
2. Adjusted the `V2::ApplicationSerializer.fields` method to additionally accept this list as an argument
3. Created `V2::ApplicationController#join_one_to_ones` method that joins the required 1:1 associations on the current scope on demand
4. Adjusted the `V2::ApplicationController#expand_resource` to include the `join_one_to_ones` in its chain
These changes should …
> feat(APIv2): RHINENG-2913 extend derived_attribute to non-parents

- app/controllers/concerns/v2/rendering.rb
- app/serializers/v2/application_serializer.rb
The dependent non-autojoined fields were ignored by default as the `one_to_one` tables were missing from the context of the serializer. Furthermore, multiple dependencies coming from the same table for two different fields were handled poorly and needed a deep(er) merging of hashes of arrays.
> Two minor fixes in handling dependent attribute serialization

- app/controllers/v2/application_controller.rb
> fix(APIv2): enforce pundit policies when resolving entities

- app/controllers/v2/application_controller.rb
This is mainly needed for pundit to make sure that records don't contain a wrong account_id. We usually don't display the account information in the API response and only a few tables contain this info, so I had to make it optional. If there are no other extra fields, I might refactor this to something more implicit.
> feat(APIv2): optionally allow the selection of additional fields

- app/policies/v2/application_policy.rb
- app/policies/v2/profile_policy.rb
- app/policies/v2/rule_policy.rb
- app/policies/v2/security_guide_policy.rb
- app/policies/v2/value_definition_policy.rb
This was never namespaced properly from the V1
> refactor(APIv2): introduce the V2::ApplicationPolicy

- app/controllers/application_controller.rb
- app/controllers/concerns/collection.rb
- app/controllers/concerns/metadata.rb
- app/controllers/concerns/parameter_handling.rb
- app/controllers/concerns/v2/collection.rb
- app/controllers/concerns/v2/metadata.rb
- app/controllers/concerns/v2/parameter_handling.rb
- app/controllers/v1/profiles_controller.rb
- app/controllers/v1/systems_controller.rb
- app/controllers/v2/application_controller.rb
- spec/controllers/v2/concerns/parameter_handling_spec.rb
No longer needed as the two namespaces got diverging enough.
> Clean up the SEARCH constant from both APIs

- app/controllers/v2/supported_profiles_controller.rb
- app/models/v2/profile.rb
- app/models/v2/supported_profile.rb
- app/policies/v2/supported_profile_policy.rb
- app/serializers/v2/supported_profile_serializer.rb
- config/routes.rb
- db/migrate/20240101101311_create_supported_profiles.rb
- db/migrate/20240105155203_reset_datastreams_new_year.rb
- db/schema.rb
- db/views/supported_profiles_v01.sql
- spec/controllers/v2/supported_profiles_controller_spec.rb
- spec/factories/profile.rb
- spec/factories/profile_os_minor_version.rb
- spec/factories/security_guide.rb
- spec/fixtures/files/searchable/supported_profiles_controller.yaml
- spec/fixtures/files/sortable/supported_profiles_controller.yaml
The idea here is to extract the complex `OsMinorVersions` query from the GQL implementation to a view, so it can be abstracted away from ActiveRecord. This might change in the future, but as long as we are in the remodelling process, we are fine like this.
The query joins `canonical_profiles` with `security_guides` and the with new `profile_os_minor_versions` table to group results by the `ref_id` and `os_major_version`. This results in a lot of redundant aggregated data, from which w need just the first entity for `id`,  `title` and `security_guide_version`, which are sorted all by the `security_guide_version` always selecting the oldest one. However, we do need all the `os_minor_versions` aggregated into an array of integers so we can construct the support matrix for the create policy …
> feat(APIv2): RHINENG-5354 implement the supported_profiles endpoint

- app/controllers/concerns/v2/collection.rb
- app/models/application_record.rb
- app/models/concerns/v2/searchable.rb
- app/models/concerns/v2/sortable.rb
- app/models/v2/application_record.rb
- app/models/v2/policy.rb
- app/models/v2/profile.rb
- app/models/v2/rule.rb
- app/models/v2/security_guide.rb
- app/models/v2/supported_profile.rb
- app/models/v2/value_definition.rb
- spec/fixtures/files/searchable/policies_controller.yaml
- spec/fixtures/files/sortable/policies_controller.yaml
The `sortable_by` helper was already available in V1, but it did additional stuff that is likely no longer required in V2. The `searchable_by` is a new wrapper around `scoped_search` that sets up our conventions regarding explicit searching and mandatory operator definitions. It also allows to define the `ext_method` as a block that should simplify custom search definitions in many cases. The second commit already utilizes this new block for searching policies by `os_major_version`.
> feat(APIv2): RHINENG-3381 introduce searchable/sortable concerns

- spec/controllers/v2/concerns/sortable_spec.rb
- spec/fixtures/files/sortable/policies_controller.yaml
- spec/fixtures/files/sortable/profiles_controller.yaml
- spec/fixtures/files/sortable/rules_controller.yaml
- spec/fixtures/files/sortable/security_guides_controller.yaml
- spec/fixtures/files/sortable/value_definitions_controller.yaml
From now on the `sortable` shared example in APIv2 specs does not return the mismatching database IDs of entities, but the indexes that we actually compare against in the YAML:
```
expected: [3, 0, 1, 5, 4, 2]
got: [0, 3, 1, 5, 4, 2]
```
It does not deal with the nested arrays, that has to be still figured out by the developer, but it definitely improves the experience when writing these YAML files.
Additionally, I dropped the explicit `:asc` and `:desc` tests that have been replaced with automatically generated tests. So from now on if you specify a sorting without a direction, both the explicit `:asc` and reverse `:desc` sorting will be automatically done without specifying it.
> test(sorting): improve experience and deduplicate definitions

- deploy/clowdapp.yaml
The readiness probe checks for the DB connection availability, in those moments the `openapi.json` via the static file middleware is definitely available. Therefore, the initial timeout for each can be safely set to the same. Furthermore the CPU bump was not necessary, the issue with deployment unavailability was because of the probes being impatient.
> perf(pods): RHINENG-8064 increase probes & revert CPU bump

- app/controllers/concerns/v2/collection.rb
- app/controllers/concerns/v2/resolver.rb
- app/controllers/v2/application_controller.rb
- app/controllers/v2/policies_controller.rb
- app/controllers/v2/profiles_controller.rb
- app/controllers/v2/rules_controller.rb
- app/controllers/v2/security_guides_controller.rb
- app/controllers/v2/supported_profiles_controller.rb
- app/controllers/v2/systems_controller.rb
- app/controllers/v2/value_definitions_controller.rb
* Renamed `resolve_collection` to `fetch_collection`
* Extracted the `V2::Resolver` concern that now contains the `expand_resource`
* Moved around with the tag filtering as it has to happen before counting the results
* Dropped one `policy_scope` call as it was duplicated in `expand_resource`
> Minor refactorings, cleanups and deduplications around resolvers

- app/controllers/concerns/v2/resolver.rb
- app/models/v2/application_record.rb
- app/models/v2/system.rb
- app/serializers/v2/application_serializer.rb
- app/serializers/v2/system_serializer.rb
- spec/controllers/v2/systems_controller_spec.rb
I created a self-join solution for aggregating self-to-many resources that can be declared using the new `aggregated_attribute` DSL method in the V2 serializers. The self-join part is done in the `V2::Resolver` concern automatically, based on what the serializer returns when requested. This allows us to combine aggregated datasets into an API response without tampering with the integrity of the rest of the returned data.
> feat(APIv2): RHINENG-2059 add aggregated list of policies to systems

- app/controllers/concerns/v2/resolver.rb
There is an [issue](https://github.com/rails/rails/pull/49047) with `ActiveRecord::Base.merge` when the left side has a table alias. Until it gets fixed, we should use this subquery as a temporary solution. 
> fix(Resolver): RHINENG-5978 temporarily use a subquery for scoping

- Gemfile
- Gemfile.lock
This should prevent the usage of RPM-provided old system gems...
> chore(deps): RHINENG-8107 make sure we don't run old system gems

- spec/controllers/v2/concerns/indexable_by_ref_id_spec.rb
- spec/controllers/v2/concerns/paginable_spec.rb
- spec/controllers/v2/concerns/rendering_spec.rb
- spec/controllers/v2/concerns/searchable_spec.rb
- spec/controllers/v2/concerns/sortable_spec.rb
- spec/controllers/v2/concerns/with_metadata_spec.rb
- spec/controllers/v2/policies_controller_spec.rb
- spec/controllers/v2/tailorings_controller_spec.rb
- spec/fixtures/files/searchable/tailorings_controller.yaml
- spec/fixtures/files/sortable/policies_controller.yaml
- spec/fixtures/files/sortable/tailorings_controller.yaml
- spec/spec_helper.rb
The `extra_params` in controller spec shared examples has a dual use:
* additional attributes for the factories
* additional parameters for the URL as `passable_params`
While the factories have no problems with consuming any kind of parameters, the `passable_params` it a bit more picky as routing often depend on what params are passed to a controller. Furthermore, sometimes we want to pass values to the factory that we don't want to see in the URL. As an initial solution, there was a simple logic implemented in the `passable_params` to omit any object that is the instance of `ActiveRecord::Base`, which allowed us to pass objects to the `extra_params` without polluting the URL. 
This solution isn't flexible enough for our needs and we already had to do some hacks when testing …
> refactor(specs): allow marking scalars to be skipped from URL params

- deploy/clowdapp.yaml
Should improve the startup speed of the service pod (tested in ephemeral) and have less pressure on the alerts when deploying. Also we can decrease the initial delays for liveness/readiness probes to a lower level.
> perf(clowder): increase RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR to 1.2

- app/controllers/concerns/v2/collection.rb
- app/controllers/concerns/v2/parameter_handling.rb
- app/controllers/concerns/v2/rendering.rb
- app/controllers/concerns/v2/resolver.rb
- app/models/concerns/v2/sortable.rb
- app/models/v2/policy.rb
- app/models/v2/system.rb
- app/policies/v2/application_policy.rb
I've added some coverage masks when copy-pasting old (and untested) code into V2 that is no longer needed. Furthermore, there were some methods that maintained compatibility with APIv1 that is now obsolete as we namespaced more V2 concerns.
> cleanup(V2): remove coverage masks and obsolete compatibility methods

- docker-compose.yml
Inventory configured an [entrypoint](https://github.com/RedHatInsights/insights-host-inventory/pull/1655) on their containers, which broke our compose-based developer setup. By resetting the entrypoint to the default one, we are back to normal behavior.
> dev(compose): reset entrypoint for inventory containers

- app/models/concerns/sortable.rb
- app/models/concerns/v2/sortable.rb
Some time ago I [fixed](https://github.com/rails/rails/pull/44284) a [bug](https://github.com/rails/rails/issues/44282) in activerecord and even [failed](https://github.com/RedHatInsights/compliance-backend/pull/1214) to clean up after it in our codebase as the changes weren't backported to the version we were running. Now that we are on 7.1, it is safe to drop the compensation.
> cleanup(sortable): drop arel hash sorting compensation

- app/controllers/concerns/v2/resolver.rb
- app/serializers/v2/application_serializer.rb
- app/serializers/v2/system_serializer.rb
There is a need to contextualize an aggregation for the `current_user` and there was also an issue with alias lookup on certain dynamically generated Arel nodes. This change deals with both issues, by moving the alias setup of an aggregation to the `V2::Resolver` and converting the last argument of `aggregated_attribute` to a lambda.
```ruby
aggregated_attribute :name, :relation, lambda do
Pundit.policy_scope(User.current, V2::System)
end
```
> feat(APIv2): allow passing context to resolver aggregations

- app/services/rbac.rb
- lib/insights/api/common/host_inventory.rb
- test/controllers/concerns/authentication_test.rb
RBAC backend no longer accepts `X_RH_IDENTITY` so we have to send `X-RH-IDENTITY` instead.
> fix(RBAC): RHINENG-9591 send identity header with hyphens

- app/controllers/concerns/v2/collection.rb
- app/graphql/types/base_connection.rb
- app/models/v2/policy.rb
- app/models/v2/tailoring.rb
Utilizing `reselect` where it was possible in APIv2, there's a few places remaining where it was still necessary to call `except`.
> cleanup(ActiveRecord): replace except+select with reselect

- app/controllers/concerns/v2/resolver.rb
- app/models/concerns/v2/merge_with_alias.rb
- app/models/v2/application_record.rb
There was an issue with merging pundit scopes with autojoined parents as they automatically get aliased based on the reflection name. I created an `Arel::Visitor` implementing BFS that can be used for both retrieving aliases from one scope and adjusting them in another. 
There were some errors around adjusting an arel AST of a cached query, so I made sure that we can opt-in construct a new AST while visiting nodes. This is ensured by the `copy` argument of the visitor and the `dup` call on each node.
If a new query shows up with which the visitor cannot deal, an exception describing this problem is displayed that should be available when running tests.
> perf(APIv2): RHINENG-8352 harmonize aliases when merging with pundit

- app/consumers/inventory_events_consumer.rb
- deploy/clowdapp.yaml
The topic has been deleted even though we did not ask for it. However, it seems to be no longer used by anyone else and as we have payload tracker, it became obsolete for us. So we can just delete it from clowder, the [logic](https://github.com/RedHatInsights/compliance-backend/blob/master/app/consumers/inventory_events_consumer.rb#L39) in our code already stops using it if isn't specified in the clowder config.
> fix(kafka): RHINENG-9805 stop using platform.upload.compliance topic

- app/controllers/v2/rules_controller.rb
- app/controllers/v2/systems_controller.rb
- app/models/v2/application_record.rb
The bulk assignment was always deleting the right side from the database when unassigning. This means that when unassigning a system from a tailoring, we didn't delete the `TailoringSystem` record, but the `System` itself. Same happened for `TailoringRule` unassignment. Furthermore, due to the dynamic evaluation of the entities to be unassigned, the unassignment itself interfered with the assignment.
So I adjusted the unassignments to deal with the linking entities and reordered the deletion to happen before the assignment. This is something we aren't really able to test in our codebase though 😞 
> fix(APIv2): bulk deletion should delete link not the entity

- spec/controllers/v2/supported_profiles_controller_spec.rb
- spec/factories/profile.rb
- spec/factories/security_guide.rb
Some `association` calls were not reflecting the ID of the entity they are associated to implicitly, therefore, they created duplicate entities that were never used. This is probably a bug in FactoryBot, but we can eliminate it by not allowing any improvisation around duplications.
> Eliminate unnecessary record generation in factory associations

- app/models/v2/policy_system.rb
- spec/controllers/v2/systems_controller_spec.rb
When assigning a system to a policy, the tailoring creation is triggered if there is no already tailoring created. In case there is a rule support mismatch between the policy's parent profile and the one that the system supports, the validation on the rule assignment fails. This caused issues when assigning systems to older policies with no longer supported parent profile. The fix is trivial, the rule cloning should always happen from the tailoring's parent and not the policy's.
> fix(APIv2): RHINENG-10037 clone rules/values from a supported profile

- db/functions/tailorings_insert_v03.sql
- db/migrate/20240522141517_update_function_tailorings_insert_to_version_3.rb
- db/schema.rb
The `ref_id` and `name` fields aren't populated by APIv2 as they are not used, but APIv1 requires them.
> fix(APIv2): RHINENG-10257 populate unused V2 fields in tailorings

- app/controllers/v2/systems_controller.rb
- app/models/v2/policy.rb
When un/assigning system/s using APIv2, the cached counters in the V1 models are not updated. This can cause that the frontend will not show the correct number of assigned/compliant/etc systems after doing V2 operations. To maintain compatibility, we have to call the `::Profile#update_counters!` V1 method upon operations. This is a temporary solution and will be deleted AFTER the old APIs are dropped.
> fix(APIv2): RHINENG-10300 update V1 counters around system assignment

- app/services/concerns/xccdf/rule_results.rb
- app/services/concerns/xccdf/test_result.rb
- db/migrate/20240527092643_test_result_failed_rule_count.rb
- db/migrate/20240527130454_update_v2_test_results_to_version_2.rb
- db/schema.rb
- db/views/v2_test_results_v02.sql
- test/services/concerns/xccdf/test_result_test.rb
Instead of creating an `aggregated_attribute` we can rely on a static field to get the number of failed rules under a policy+system combo. This number is the same for everyone who has access, so no need for scoped filtering and the number can be calculated upon parsing the report.
> feat(APIv2): RHINENG-1986 cache failed_rule_count on test results

- .rubocop.yml
- app/controllers/concerns/v2/resolver.rb
- app/models/v2/system.rb
- app/serializers/v2/application_serializer.rb
- app/serializers/v2/system_serializer.rb
- spec/controllers/v2/systems_controller_spec.rb
Weak attributes are left-outer joined with the main scope so they never limit its total count. Probably their only usage is for the `/reports/:id/systems` endpoint where some of these attributes are derived using `test_result` bindings that aren't always available. This solution brings in a ton of additional complexity and might not stick on the long run though...
> fix(APIv2): RHINENG-10379 introduce weak attributes for systems

- app/models/v2/tailoring.rb
- app/serializers/v2/tailoring_serializer.rb
- spec/api/v2/schemas/tailoring.rb
- spec/controllers/v2/tailorings_controller_spec.rb
- swagger/v2/openapi.json
> feat(APIv2): RHINENG-11782 expose security_guide version in tailorings

- app/controllers/v2/security_guides_controller.rb
- app/controllers/v2/systems_controller.rb
- spec/integration/v2/security_guides_spec.rb
- spec/integration/v2/systems_spec.rb
- swagger/v2/openapi.json
> fix(APIv2): RHINENG-11779 allow filtering entities under os_versions

- app/models/profile.rb
> fix(Policies): RHINENG-283 make validation based on the featureflag 

- spec/integration/v2/profiles_spec.rb
- spec/integration/v2/rules_spec.rb
- swagger/v2/openapi.json
> fix(APIv2): adjust docs for indexing rules/profiles by ref_id

- app/controllers/concerns/error_handling.rb
- app/controllers/concerns/v2/collection.rb
- app/models/concerns/v2/searchable.rb
- app/models/v2/policy.rb
- app/models/v2/report.rb
- app/models/v2/system.rb
- spec/integration/v2/policies_spec.rb
- spec/integration/v2/reports_spec.rb
- spec/integration/v2/systems_spec.rb
- spec/swagger_helper.rb
- swagger/v2/openapi.json
As we are heavily limited by scoped_search, I chose the validation feature to restrict searching to specific parent hierarchies. The solution uses the `except_parents` and `only_parents` keywords that we already have in our YAML-generated tests.
In order to make the validator access the list of current parents, they have been moved into a thread-current context variable. This is not the nicest way, but any other solution would unfortunately involve monkey-patching of `scoped_search`. The second hack is that the error message from the validation is regexp-replaced to make sure that the API response gets the correct message referring to the context and not the invalid value.
> fix(APIv2): RHINENG-11772 restrict search/sort to specific parents

- app/models/v2/rule.rb
- spec/controllers/v2/rules_controller_spec.rb
- spec/fixtures/files/searchable/rules_controller.yaml
- swagger/v2/openapi.json
> feat(APIv2): RHINENG-12453 enable filtering rules by rule_group_id

- app/models/v2/report.rb
**Before:**
```
SELECT "rule_results"."id", "rule_results"."rule_id", "rule_results"."result", "rule_results"."created_at", "rule_results"."updated_at", "rule_results"."test_result_id" FROM "rule_results"
INNER JOIN "v2_test_results" ON "v2_test_results"."id" = "rule_results"."test_result_id"
INNER JOIN "v2_test_results" "test_results_rule_results_join" ON "test_results_rule_results_join"."id" = "rule_results"."test_result_id"
INNER JOIN "inventory"."hosts" ON "inventory"."hosts"."id" = "test_results_rule_results_join"."system_id"
INNER JOIN "v2_rules" ON "v2_rules"."id" = "rule_results"."rule_id"
```
**After:**
```
SELECT "rule_results"."id", "rule_results"."rule_id", "rule_results"."result", "rule_results"."created_at", "rule_results"."updated_at", "rule_results"."test_result_id" FROM …
```
> fix(APIv2): RHINENG-13048 join test_results in top_failed_rules once

- app/controllers/v2/profiles_controller.rb
- app/controllers/v2/tailorings_controller.rb
- app/models/concerns/v2/rule_tree.rb
- app/models/v2/policy.rb
- app/models/v2/profile.rb
- app/models/v2/security_guide.rb
- app/models/v2/tailoring.rb
- app/policies/v2/profile_policy.rb
- app/policies/v2/tailoring_policy.rb
- config/routes.rb
- spec/controllers/v2/profiles_controller_spec.rb
- spec/controllers/v2/tailorings_controller_spec.rb
- spec/integration/v2/profiles_spec.rb
- spec/integration/v2/security_guides_spec.rb
- spec/integration/v2/tailorings_spec.rb
- swagger/v2/openapi.json
> feat(APIv2): RHINENG-13519 expose the RuleTree on profiles/tailorings

- build_deploy.sh
This update changes the following to properly generate the `SC IMAGE TAG` when building off of the `security-compliance` branch.  
> fix(ci): update build_deploy to correctly generate sc tagged images

- app/models/v2/report.rb
> fix(APIv2): RHINENG-14364 respect IGs when searching reports

- spec/integration/v2/reports_spec.rb
- spec/integration/v2/systems_spec.rb
- swagger/v2/openapi.json
only `/systems` endpoint should allow to filter by `os_version`
follow-up to 445f86bb9bc13f4202ad86eb3770213040958985
> docs(APIv2): correct searching by attributes

- spec/api/v2/openapi.rb
- spec/integration/v2/policies_spec.rb
- spec/integration/v2/profiles_spec.rb
- spec/integration/v2/reports_spec.rb
- spec/integration/v2/rule_groups_spec.rb
- spec/integration/v2/rule_results_spec.rb
- spec/integration/v2/rules_spec.rb
- spec/integration/v2/security_guides_spec.rb
- spec/integration/v2/supported_profiles_spec.rb
- spec/integration/v2/systems_spec.rb
- spec/integration/v2/tailorings_spec.rb
- spec/integration/v2/test_results_spec.rb
- spec/integration/v2/value_definitions_spec.rb
- swagger/v2/openapi.json
> docs(APIv2): RHINENG-14358 spec documentation

- app/controllers/concerns/v2/resolver.rb
- app/models/v2/system.rb
- app/policies/v2/application_policy.rb
- app/policies/v2/system_policy.rb
I am introducing the `aggregate` method on pundit scopes that allows us additional scoping of resources for aggregations. This is not for user access limitation, but for performance optimizations in SQL. User access scoping is always handled on the highest level and in FILTER calls inside aggregation. Hopefully we will only need this for the inventory, that is scoped with org_id, but this could be useful for rule results or test results if there are performance issues.
> perf(APIv2): self-joining in aggregation with a reduced (pundit) scope

- .github/workflows/checkimage.yaml
- .github/workflows/ruby-update.yml
Fixing: https://github.com/peter-evans/create-pull-request/issues/2790
> fix(Actions): upgrade create-pull-request to v6

- spec/api/v2/schemas/test_result.rb
- swagger/v2/openapi.json
> fix(OpenAPI): RHINENG-15551 revert changes and manually update OpenAPI spec

- dashboards/grafana-dashboard-insights-compliance-general.template.yaml
> refactor(Graphana): RHINENG-15507 replace kafka lag metric

- .github/workflows/ci.yml
> chore(GitHub): bump CodeCov

- app/models/v2/test_result.rb
- app/serializers/v2/test_result_serializer.rb
- spec/controllers/v2/test_results_controller_spec.rb
- swagger/v2/openapi.json
> feat(API): RHINENG-16382 provide SSG ID for Test Result

- lib/insights/api/common/satellite_compensation/middleware.rb
parameter has been excluded in https://github.com/theforeman/foreman_rh_cloud/commit/792a0d1b87a63652e29f81f94cc973f9897f8730
> cleanup(API): RHINENG-15696 remove compensation for branch_id parameter

- app/models/v2/rule.rb
- app/models/v2/rule_result.rb
- spec/factories/rule_result.rb
- spec/fixtures/files/searchable/rule_results_controller.yaml
- spec/fixtures/files/searchable/rules_controller.yaml
This PR gets back filtering rules/rule_results by identifier as it was before. See https://issues.redhat.com/browse/RHINENG-14846 or https://issues.redhat.com/browse/RHINENG-16918
1. Check if any rules endpoint and rule_results endpoint can be filtered by:
-  `identifier_label=CEE-...`
- `identifier_label !=CEE-...`
- `identifier_label ~ 'CEE-...'`
-  `identifier_label !~ 'CEE-...`
So we have separate search attribute specifically for identifier.
> fix(Rules): RHINENG-16918 search rules by identifier
