app/services/openshift_environment.rb
We should return 0 only in case the QE_ACCOUNTS is unset or empty.
=> fix(metrics): adjusted nil check for missing list of QE accounts

Gemfile, Gemfile.lock, config/puma.cfg
=> fix(deps): RHICOMPL-3380 bump Puma, Sidekiq and Yabeda versions

spec/swagger_helper.rb, swagger/v1/openapi.json
https://github.com/rswag/rswag/issues/559
=> fix(OpenAPI): RHICOMPL-3381 display response schema correctly

spec/swagger_helper.rb, swagger/v1/openapi.json
=> fix(OpenAPI): RHICOMPL-3382 remove unexpected type

Dockerfile
=> fix(Dockerfile): RHICOMPL-1892 do not run bundler as root

.github/workflows/ci.yml
=> feat(CI): RHICOMPL-3390 docker-compose building development image

app/controllers/application_controller.rb, app/controllers/concerns/tag_filtering.rb, lib/exceptions.rb, test/controllers/v1/systems_controller_test.rb
=> fix(REST): RHICOMPL-3391 fail with 4xx for invalid tags

app/models/concerns/profile_fields.rb, app/models/concerns/rules_and_rule_groups.rb, app/models/profile.rb, app/models/xccdf/benchmark.rb, test/factories/benchmark.rb, test/models/benchmark_test.rb, test/models/profile_test.rb
This PR currently conflicts with https://github.com/RedHatInsights/compliance-backend/pull/1273 so depending on which one is merged first, we'll need to resolve the conflicts at some point. 
=> feat(Benchmark): RHICOMPL-3402 get rules and groups for Benchmark

build_deploy.sh, scripts/deploy/build-deploy-common.sh
=> amend container login variable name

clowdapp-minimal.yaml, clowdapp.yaml
=> fix(clowder): RHICOMPL-3406 pass missing QE_ACCOUNTS parameter

clowdapp-minimal.yaml, clowdapp.yaml, dashboards/grafana-dashboard-insights-compliance-general.template.yaml
=> feat(clowder): RHICOMPL-3414 update openshift template apiVersion

Gemfile.lock, spec/api/v1/openapi.rb, spec/integration/benchmarks_spec.rb, spec/integration/business_objectives_spec.rb, spec/integration/profiles_spec.rb, spec/integration/rule_results_spec.rb, spec/integration/rules_spec.rb, spec/integration/statuses_spec.rb, spec/integration/supported_ssgs_spec.rb, spec/integration/systems_spec.rb, swagger/v1/openapi.json
~~Waiting for https://github.com/rswag/rswag/pull/547~~
~~Waiting for https://github.com/rswag/rswag/discussions/561~~
=> docs(OpenAPI): RHICOMPL-3199 correct link paths

Dockerfile
=> fix(Dockerfile): add missing redhat-rpm-config dev dependency

Dockerfile
Missed the `src` from the path :see_no_evil: 
=> dev(Dockerfile): fixed path for the prometheus_multiproc_dir tmp

app/services/concerns/xccdf/rule_groups.rb, app/services/concerns/xccdf/rules.rb, test/services/concerns/xccdf/rules_test.rb
=> fix(SSG): RHICOMPL-3435 update rule/group fields when importing

app/models/rule.rb, app/services/concerns/xccdf/rules.rb, db/migrate/20221122204140_add_rule_group_to_rules.rb, db/migrate/20221122204659_rule_group_cleanup_reimport.rb, db/schema.rb, test/services/concerns/xccdf/rules_test.rb, test/services/xccdf_report_parser_test.rb
=> refactor(Rule): RHICOMPL-3384 create & set the rule_group_id column

app/models/policy.rb, spec/api/v1/schemas/hosts.rb, spec/api/v1/schemas/metadata.rb, spec/api/v1/schemas/profiles.rb, spec/api/v1/schemas/status.rb, spec/integration/profiles_spec.rb, spec/integration/systems_spec.rb, spec/swagger_helper.rb, swagger/v1/openapi.json
Changes to generate OpenAPI v3.0 valid specification.
=> fix(OpenAPI): RHICOMPL-3404 fix OpenAPI v3 inconsistency

app/models/rule.rb, db/migrate/20221126093700_scoped_slug_index.rb, db/schema.rb, test/factories/rule.rb
First I scoped the index on the `slug` column in the `rules` table to the `benchmark_id`, similarly to the `ref_id` from which the `slug` is generated. Then disabled the automatic generation of slugs and explicitly set it in the import and in the factory for testing. 
For verification I ran these two lines after the migration:
```ruby
Rule.all.all? { |r| r.ref_id.parameterize == r.slug }
=> true
Rule.all.all? { |r| r.ref_id.gsub('.', '-').downcase == r.slug }
=> true
```
I tested it by calling the `time bin/rake db:truncate_all ssg:import_rhel_supported` to ensure that the data is being imported into a clean DB. Additionally I had a benchmark measurement to determine the increase of importing rules per benchmark:
```
diff --git a/app/services/concerns/xccdf/util.rb …
```
=> perf(Rule): RHICOMPL-3455 make slug generation manual upon import

app/models/concerns/profile_links.rb, app/models/rule_group.rb, app/models/xccdf/benchmark.rb, db/migrate/20221129080807_add_precedence_to_rule_groups.rb, db/schema.rb, test/models/benchmark_test.rb, test/models/profile_test.rb
Also fixing sporadic test failures with rule tree by ordering both rules and groups using precedence.
=> feat(RuleGroup): RHICOMPL-3462 add precedence column on the table

db/migrate/20221130153701_reset_revisions_for_ancestry.rb, db/schema.rb
@marleystipich2 we forgot this, need a force import to make sure things are alright everywhere.
=> chore(revisions): RHICOMPL-3454 reset datastream revisions

Dockerfile, Gemfile, Gemfile.lock
=> build(Gemfile): RHICOMPL-3403 add awesome_print into Gemfile

Gemfile, Gemfile.lock, config/initializers/sidekiq.rb
=> chore(deps): RHICOMPL-3456 bump sidekiq to the latest major version

app/models/rule_group.rb, app/services/concerns/xccdf/rule_groups.rb, db/migrate/20221202104757_reset_revision_rule_group_precedence.rb, db/schema.rb, test/services/concerns/xccdf/rule_groups_test.rb
=> feat(RuleGroup): RHICOMPL-3428 store the precedence field upon import

app/models/concerns/rules_and_rule_groups.rb, swagger/v1/openapi.json, test/factories/benchmark.rb, test/factories/profile.rb, test/models/benchmark_test.rb, test/models/profile_test.rb
=> feat(RuleTree): RHICOMPL-3449 include references and identifier

Gemfile, Gemfile.lock
=> chore(deps): bump CGI version in the gem & lockfile

Dockerfile
* Extended bundler update to the whole rubygems package
* Dropped unused variables and arguments
* Suppressed expected warnings around timezone cleanup
* Resolved warnings related to sockets
* Resolved warnings related to the tmp directory
* Fixed bundle install if nokogiri wants to compile in dev
=> cleanup(Dockerfile): tidy up both containers

app/graphql/types/interfaces/rules_preload.rb, app/graphql/types/rule.rb, app/graphql/types/rule_reference.rb, app/models/concerns/rules_and_rule_groups.rb, app/models/rule.rb, app/models/rule_reference.rb, app/models/rule_references_rule.rb, app/services/concerns/xccdf/rule_references.rb, app/services/concerns/xccdf/rule_references_rules.rb, app/services/concerns/xccdf/util.rb, app/services/datastream_importer.rb, swagger/v1/openapi.json, test/controllers/v1/rules_controller_test.rb, test/factories/rule_reference.rb, test/graphql/queries/rule_query_test.rb, test/models/benchmark_test.rb, test/models/profile_test.rb, test/models/rule_reference_test.rb, test/models/rule_references_rule_test.rb, test/models/rule_test.rb, test/services/concerns/xccdf/rule_group_relationships_test.rb, test/services/concerns/xccdf/rule_groups_test.rb, test/services/concerns/xccdf/rule_references_rules_test.rb, test/services/concerns/xccdf/rule_references_test.rb, test/services/concerns/xccdf/rules_test.rb
Should fix our performance issues with `DISTINCT` queries.
=> revert(RuleReferences): RHICOMPL-3483 use the rule_references table instead of the column again

app/models/rule.rb, app/services/concerns/xccdf/rules.rb, db/migrate/20221207113117_drop_references_column.rb, db/schema.rb, test/factories/rule.rb
=> perf(Rules): RHICOMPL-3489 remove the references column

app/models/rule_references_container.rb, app/services/concerns/xccdf/rule_references_containers.rb, app/services/concerns/xccdf/util.rb, db/migrate/20221208090957_create_rule_references_container.rb, db/migrate/20221208104648_reset_datastreams_for_rrc.rb, db/schema.rb, test/models/rule_references_container_test.rb, test/services/concerns/xccdf/rule_references_containers_test.rb
This table should eventually replace the `RuleReference` and `RuleReferencesRule` models.
=> feat(DB): RHICOMPL-3484 create&populate RuleReferencesContainers table

db/migrate/20221212124930_add_index_rule_identifier_references.rb, db/schema.rb
=> feat(DB): RHICOMPL-3496 create index on rule identifier and references

app/models/host.rb, test/controllers/v1/systems_controller_test.rb
=> fix(Hosts): RHICOMPL-3437 don't sort by SSG without policy scoping

app/graphql/types/base_connection.rb
=> perf(GQL): RHICOMPL-3500 always count results by a specific column

app/models/concerns/rule_tree.rb, app/models/rule.rb, app/models/rule_group.rb, swagger/v1/openapi.json, test/models/benchmark_test.rb
=> feat(RuleTree): RHICOMPL-3499 also display rule_references

app/services/concerns/xccdf/profiles.rb, db/migrate/20221220143030_reset_revision_dec_twentieth.rb, db/schema.rb, test/services/concerns/xccdf/profiles_test.rb
=> fix(Profile): RHICOMPL-3475 update value_overrides to use value uuids

app/controllers/concerns/v1/profile_attributes.rb, app/controllers/v1/profiles_controller.rb, app/graphql/mutations/profile/create.rb, app/graphql/mutations/profile/edit.rb, app/graphql/schema.graphql, app/graphql/types/profile.rb, app/graphql/types/rule.rb, app/models/concerns/profile_cloning.rb, app/models/concerns/rule_tree.rb, app/models/profile.rb, app/models/rule.rb, app/serializers/profile_serializer.rb, app/serializers/rule_serializer.rb, spec/api/v1/schemas/profiles.rb, spec/api/v1/schemas/rules.rb, spec/integration/profiles_spec.rb, spec/integration/rules_spec.rb, swagger/v1/openapi.json, test/controllers/v1/profiles_controller_test.rb, test/factories/profile.rb, test/graphql/mutations/create_profile_mutation_test.rb, test/graphql/mutations/edit_policy_mutation_test.rb, test/graphql/queries/profile_query_test.rb, test/models/benchmark_test.rb
=> feat(Values): RHICOMPL-3396 expose values and checks in APIs

app/services/concerns/xccdf/profiles.rb, db/migrate/20230104132131_reset_revisions_for_profile_value_overrides.rb, db/schema.rb, test/services/concerns/xccdf/profiles_test.rb, test/services/xccdf_report_parser_test.rb
=> fix(SSG): RHICOMPL-3475 overwrite existing profiles with values

app/models/concerns/benchmark_searching.rb, app/models/host.rb, app/models/profile.rb, app/models/rule.rb
=> refactor(Arel): RHICOMPL-3498 rewrite Arel.sql calls to Arel::Nodes

app/services/copy_value_overrides_to_non_canonical.rb, db/migrate/20221216171738_value_overrides_to_non_canonical_profiles.rb, test/services/copy_value_overrides_to_non_canonical_test.rb
=> chore(Profile): RHICOMPL-3503 copy value_overrides to non-canonical

app/controllers/v1/value_definitions_controller.rb, app/graphql/schema.graphql, app/graphql/types/benchmark.rb, app/graphql/types/value_definition.rb, app/models/value_definition.rb, app/policies/value_definition_policy.rb, app/serializers/benchmark_serializer.rb, app/serializers/value_definition_serializer.rb, config/routes.rb, spec/api/v1/schemas.rb, spec/api/v1/schemas/value_definitions.rb, spec/integration/value_definitions_spec.rb, swagger/v1/openapi.json, test/controllers/v1/value_definitions_controller_test.rb, test/factories/value_definition.rb, test/graphql/queries/benchmark_query_test.rb, test/policies/value_definition_policy_test.rb
=> feat(GQL): RHICOMPL-3513 expose Value Definitions in APIs

swagger/v1/openapi.json
=> feat(OpenAPI): use Markdown to make links clickable

app/policies/rule_policy.rb, app/serializers/rule_serializer.rb, spec/integration/rules_spec.rb, test/policies/rule_policy_test.rb
**Before:**
```
EXPLAIN ANALYZE SELECT COUNT(rules.id) FROM rules WHERE rules.id IN (SELECT rules.id FROM rules INNER JOIN profile_rules ON profile_rules.rule_id = rules.id INNER JOIN profiles ON profiles.id = profile_rules.profile_id WHERE (profiles.account_id = 'XY' OR profiles.id IN (SELECT profiles.id FROM profiles WHERE profiles.parent_profile_id IS NULL)))
QUERY PLAN
Finalize Aggregate  (cost=51529.28..51529.29 rows=1 width=8) (actual time=251.133..255.783 rows=1 loops=1)
->  Gather  (cost=51529.07..51529.28 rows=2 width=8) (actual time=251.125..255.777 rows=3 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Partial Aggregate  (cost=50529.07..50529.08 rows=1 width=8) (actual time=244.843..244.849 rows=1 loops=3)
->  Parallel Hash Semi Join  (cost=36561.30..50519.81 rows=3702 …
```
=> perf(Rules): RHICOMPL-3511 expose all rules to all users

app/controllers/v1/profiles_controller.rb, app/models/concerns/profile_tailoring.rb, test/models/profile_test.rb
=> fix(Tailoring): RHICOMPL-3398 use value ref_id for set-value

db/migrate/20230120125405_drop_unused_tables.rb, db/schema.rb
=> cleanup(DB): RHICOMPL-3468 remove no longer used tables

app/models/account.rb, test/models/account_test.rb
=> cleanup(Account): RHICOMPL-3607 do not update account_number anymore

docker-compose.yml
=> dev(compose): RHICOMPL-3673 fix RBAC directory mapping typo

db/seeds.dev.rb
=> fix(Arel): RHICOMPL-3672 fix Arel interpolation

app/models/profile.rb
Passed value definitions to a mutation are an instance of `ActionController::Parameters` and this class does not implement the `count` method directly, only through its `keys`.
=> fix(GraphQL): RHICOMPL-3669 count parameters based on keys

scripts/unit_test.sh
The script currently only uses the IMAGE_TAG to create names for the containers used in the `unit_test.sh` script, causing concurrent running instance using the same image to affect each other.
=> Allow concurrent runs of unit_test.sh

Dockerfile
All apps are to be on ubi8-minimal. Being on ubi8-minimal will make this transition easier. 
=> chore(Dockerfile): RHICOMPL-3599 rollback base image to ubi8-minimal

config/initializers/0_clowder-config.rb
=> fix(clowder): RHINENG-242 store kafka CA cert only once

app/controllers/concerns/tag_filtering.rb, test/controllers/v1/systems_controller_test.rb
=> fix(tags): RHICOMPL-3684 fail on tagging with unsupported \0 char

config/initializers/0_clowder-config.rb
=> chore(Clowder): RHIENG-80 use TLS on http communications

config/initializers/0_clowder-config.rb
I apologize for the hacky nature of this code. I tested the PR image on the cluster and it does work. To those reviewing: Feel free to modify this PR in anyway you see fit.
=> Combine system and clowder CA certs

Jenkinsfile
=> fix(ci): RHICOMPL-3707 add dummy Jenkinsfile

config/initializers/0_clowder-config.rb
=> refactor(clowder): RHICOMPL-3708 build combined CA in pure ruby

Gemfile.lock
=> chore(deps): bundle update --patch

db/migrate/20230403203929_reset_revisions_april_third.rb, db/schema.rb
=> chore(revisions): RHICOMPL-3648 reset datastream revisions

app/jobs/parse_report_job.rb, test/jobs/parse_report_job_test.rb
=> fix(ParseReport): RHICOMPL-2823 format the JSON output in the log

.github/workflows/ci.yml
=> feat(CI): build the final container using podman as well

config/initializers/0_clowder-config.rb, config/initializers/rbac.rb, config/settings/test.yml
=> refactor(RBAC): RHICOMPL-3690 configure rbac without url splitting

docker-compose.yml
=> fix(PG): RHICOMPL-3729 upgrade postgres to 14 in compose file

app/graphql/types/benchmark.rb, app/graphql/types/profile.rb
=> style: Remove empty lines to keep consistent separation style

Gemfile, Gemfile.lock, config/environments/production.rb, config/initializers/0_clowder-config.rb
=> feat(Logging): RHICOMPL-1382 integrate with CloudWatch logging

config/environments/production.rb
Logging needs to be loaded after clowder configuration is initialized, so moving it into an `after_initialize` hook.
=> fix(Logging): RHICOMPL-1382 load cloudwatch config after initialize

lib/logger_with_audit.rb
=> fix(Logging): RHICOMPL-3738 limit tagged logging into blocks

app/services/concerns/xccdf/profiles.rb
=> fix(import): RHICOMPL-3648 only reimport canonical profiles

config/environments/production.rb
=> fix(Logging): RHICOMPL-3741 reduce loglevel for cloudwatch

config/environments/production.rb
=> fix(logger): change log_level to level in cw logger config

db/migrate/20230503194022_copy_value_overrides.rb, db/schema.rb
Should be held back until https://github.com/RedHatInsights/compliance-backend/pull/1632 is deployed as migrations run before forced SSG imports.
=> fix(DB): RHICOMPL-3740 migrate value overrides

app/graphql/types/concerns/test_results.rb, app/models/rule_result.rb, test/services/xccdf_report_parser_test.rb
=> style: Consistent constant naming

build_deploy.sh
=> Add additional tag for security

Dockerfile
=> chore(deps): RHICOMPL-3753 upgrade ruby to v3.1

app/controllers/graphql_controller.rb
=> perf(GraphQL): garbage collect after each GQL request

app/controllers/graphql_controller.rb
=> revert(GQL): do not garbage collect on every request

docker-compose.yml
=> fix(RBAC): RHICOMPL-3756 fix path to RBAC configuration

config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, lib/insights.rb, lib/insights/api/common/adjust_tags/middleware.rb, lib/insights/api/common/logger_with_audit.rb, lib/insights/api/common/satellite_compensation/middleware.rb, test/lib/adjust_tags/middleware_test.rb
=> fix(Platform): RHICOMPL-3760 consolidate platform modules under lib

app/controllers/application_controller.rb, app/controllers/concerns/error_handling.rb
=> refactor(ApplicationController): extract error handling to a concern

.github/workflows/ci.yml, config/initializers/0_clowder-config.rb, config/settings.yml, config/settings/development.yml, config/settings/production.yml, config/settings/test.yml, github-ci.json, scripts/unit_test.sh, test.json
=> refactor(clowder): RHICOMPL-3158 consolidate legacy configuration

test/controllers/v1/profiles_controller_test.rb
=> fix(coverage): RHICOMPL-3763 cover error handlings with tests

Jenkinsfile
=> fix(ci): RHICOMPL-3773 set Ephemeral cluster to run pipeline tests

Gemfile, Gemfile.lock, app/graphql/resolvers/base_resolver.rb, app/graphql/schema.rb, app/graphql/types/base_object.rb, app/graphql/types/benchmark.rb, config/environments/production.rb, lib/tasks/import_datastream.rake
=> perf(GraphQL): RHICOMPL-3772 introduce fragment caching for benchmarks

lib/tasks/import_datastream.rake
=> fix(GraphQL): invalidate the whole GQL fragment cache upon import

app/graphql/schema.graphql, app/graphql/types/rule.rb
=> cleanup(GraphQL): RHICOMPL-3776 tidy up the rules endpoint

spec/api/v1/schemas/rules.rb, swagger/v1/openapi.json
=> fix(OpenAPI): RHICOMPL-3777 correct attribute name

config/environments/production.rb, config/initializers/0_clowder-config.rb, config/initializers/sidekiq.rb, config/settings.yml, deploy/clowdapp.yaml, lib/tasks/status.rake
=> cleanup(config): RHICOMPL-3783 consolidate Redis configuration

deploy/clowdapp.yaml
=> perf(clowder): RHICOMPL-3828 bump readiness timeout/periods

devel.json, github-ci.json, test.json
We don't use it but the clowder client warns us about it being invalid.
=> dev(clowder): RHICOMPL-3829 drop consumerGroup from local configs

deploy/clowdapp.yaml
=> perf(clowder): RHICOMPL-3831 make probing intervals consistent

app/models/host.rb, test/graphql/queries/system_query_test.rb
Tests are passing now 🎉  
Here's the SQL generated when sorting by score: 
```
Host Load (9.7ms)  SELECT "inventory"."hosts".* FROM "inventory"."hosts" LEFT OUTER JOIN "test_results" ON 
"test_results"."host_id" = "inventory"."hosts"."id" LEFT OUTER JOIN "profiles" ON "profiles"."id" = "test_results"."profile_id" 
WHERE "inventory"."hosts"."org_id" = $1 ORDER BY COALESCE("test_results"."score") ASC, "inventory"."hosts"."id" ASC 
LIMIT $2 OFFSET $3
```
=> feat(Host): RHICOMPL-3732 sort systems by compliance score

deploy/clowdapp.yaml
=> perf(GC): RHICOMPL-3218 decrease heap oldobject limit factor

Gemfile, Gemfile.lock, app/producers/application_producer.rb, app/producers/notification.rb, app/producers/payload_tracker.rb, app/producers/remediation_updates.rb, lib/tasks/status.rake, test/producers/application_producer_test.rb, test/producers/notification_test.rb, test/producers/payload_tracker_test.rb, test/producers/remediation_updates_test.rb, test/producers/report_upload_failed_test.rb, test/producers/system_non_compliant_test.rb, test/tasks/status_test.rb
=> cleanup(deps): RHICOMPL-3788 replace ruby-kafka with rdkafka-ruby

app/producers/application_producer.rb, test/producers/application_producer_test.rb
=> fix(kafka): RHICOMPL-3788 set SSL certificate path properly

Gemfile.lock
Should stop complaining about unsupported clowder config params in logs
=> chore(deps): update clowder-common-ruby to 0.2.6

deploy/clowdapp.yaml
=> perf(clowder): loosen GC configuration for service init container

scripts/deploy/build-deploy-common.sh
- Fix a bug where an image push will not make the build script to fail
- Add an error message on image push error
=> fix(ci): RHICOMPL-3837 handle image push errors

app/models/concerns/host_searching.rb, test/graphql/queries/system_query_test.rb
=>  feat(GraphQL): RHICOMPL-3542 filter systems by rule severity

app/models/host.rb, test/graphql/queries/system_query_test.rb
=> feat(Host): RHICOMPL-3731 sort systems by num of failed rules

db/cyndi_setup_devel.sql, db/cyndi_setup_test.sql
=> feat(dev): RHICOMPL-3852 implement inventory groups in dblink

deploy/clowdapp.yaml, docker-compose.yml
=> chore(devel): upgrade PostgreSQL to v15 in dev and ephemeral

app/models/os_major_version.rb
=> refactor(OsMajorVersion): drop unnecessary class around arel_table

config/devel/rbac/definitions/developer.json
=> fix(devel): RHICOMPL-3854 add an almighty RBAC role for developers

.github/workflows/ci.yml
=> ci(migrations): RHICOMPL-2519 fail the pipeline if pending migrations

app/controllers/application_controller.rb, app/controllers/concerns/collection.rb, app/controllers/concerns/metadata.rb, app/controllers/concerns/parameters.rb, app/controllers/v1/profiles_controller.rb, app/controllers/v1/systems_controller.rb
=> refactor(search): RHICOMPL-962 extract the keyword into a constant

app/models/concerns/host_searching.rb, test/graphql/queries/system_query_test.rb
=> fix(GraphQL): RHICOMPL-3542 fix selecting failed rules

app/controllers/concerns/error_handling.rb
=> fix(GQL): RHICOMPL-3856 handle parameter parsing errors

.github/workflows/ci.yml
=> dev(CI): upgrade postgres testing container in GH actions

dashboards/grafana-dashboard-insights-compliance-general.template.yaml
Kudos to @petrblaho for the SQL abuse idea :grin: 
=> feat(grafana): RHICOMPL-3340 introduce deployment annotations

.github/workflows/ruby-update.yml
=> fix(CI): wrongly copy-pasted GH action name

deploy/clowdapp.yaml
It was originally 1000/500 so moving it back.
=> fix(Clowder): bump memory limit for sidekiq

Jenkinsfile
=> perf(CI): RHICOMPL-3873 fail fast on Jenkins parallel runs

app/models/host.rb, app/models/rule_result.rb, app/models/test_result.rb, test/graphql/queries/system_query_test.rb
Still testing this but I think something like this will work.
=> fix(Host): RHICOMPL-3731 sort all failed rules including nil

.github/workflows/ruby-update.yml
https://bundler.io/blog/2022/01/23/bundler-v2-3.html
=> fix(CI): RHICOMPL-3876 make ruby/bundler version updates automated

.github/workflows/ruby-update.yml
=> feat(CI): allow dispatching github actions manually

.github/workflows/ruby-update.yml
=> fix(CI): force the bundler version update in the GitHub action

.github/workflows/ci.yml
=> feat(CI): enable manual workflow dispatch

Dockerfile
Depends on https://github.com/RedHatInsights/compliance-backend/pull/1719
=> fix(metrics): set the prometheus_multiproc_dir env variable in prod

dashboards/grafana-dashboard-insights-compliance-general.template.yaml
=> fix(grafana): adjust thresholds for GraphQL metrics to 2s red

Dockerfile, config/puma.rb
=> fix(metrics): make metrics listen on the same port for rails

Dockerfile
old        425 MB
new        376 MB
build-new  514 MB
build-old  563 MB
Depends on https://github.com/RedHatInsights/compliance-backend/pull/1719
=> fix(Dockerfile): do not include development and test gems

config/devel/rbac/definitions/developer.json
=> fix(RBAC): adjust RBAC developer role

Dockerfile, build_deploy.sh, scripts/unit_test.sh
Should make things faster by ~40 seconds as we would not need to install any packages, just some gems.
=> perf(CI): use the first stage for unit tests on Jenkins

Dockerfile
=> fix(Dockerfile): install dev dependencies when necessary

app/jobs/delete_host.rb, spec/delete_host_spec.rb, test/jobs/delete_host_test.rb
=> test(DeleteHost): RHICOMPL-3844 rewrite DeleteHost test to rspec

app/models/account.rb, db/migrate/20230707094501_remove_is_internal_from_accounts.rb, db/schema.rb, lib/insights/api/common/identity_header.rb, test/controllers/concerns/authentication_test.rb, test/models/account_test.rb
=> cleanup(db): RHICOMPL-2373 drop is_internal field from accounts table

Gemfile
=> fix(Gemfile): move the test+dev gems to a common group

test/graphql/queries/system_query_test.rb
=> docs(sorting): explain asserting two kinds of output

Gemfile
The reorg introduced more problems than it solved, preventing a ton of gems from working when debugging tests 😞 
=> Reverting the development/test gem reorganization

app/services/supported_ssg_updater.rb, config/supported_ssg.default.yaml
=> chore(SSG): update the fallback datastream file

app/models/host.rb, app/models/test_result.rb, test/graphql/queries/system_query_test.rb
=> fix(Host): RHICOMPL-3731 sort failed rules with 0 rules failed

.github/workflows/ci.yml, swagger/v1/openapi.json
=> dev(OpenAPI): RHICOMPL-3450 CI to check if the spec file has been not generated

.github/workflows/ci.yml
=> ci(OpenAPI): RHICOMPL-3450 validate OpenAPI spec

app/models/host.rb, app/policies/host_policy.rb, test/models/host_test.rb
=> feat(Hosts): RHINENG-1179 exclude edge hosts from inventory

app/models/user.rb, app/services/rbac.rb, spec/spec_helper.rb, test/models/user_test.rb, test/test_helper.rb
=> feat(RBAC): RHICOMPL-3850 get IDs of permitted inventory groups

test/services/supported_ssg_updater_test.rb
=> fix(SSG): fix typo in the SupportedSsgUpdater service

test/controllers/concerns/authentication_test.rb
=> refactor(tests): do not overwrite RBAC disablement for other tests

app/consumers/concerns/report_parsing.rb, app/jobs/concerns/notifications.rb, app/jobs/parse_report_job.rb, app/models/account.rb, app/producers/notification.rb, db/migrate/20230719150933_remove_account_number_from_accounts.rb, db/schema.rb, db/seeds.dev.rb, spec/integration/benchmarks_spec.rb, spec/integration/profiles_spec.rb, spec/integration/rule_results_spec.rb, spec/integration/systems_spec.rb, spec/swagger_helper.rb, test/consumers/inventory_events_consumer_test.rb, test/jobs/parse_report_job_test.rb, test/models/account_test.rb, test/producers/notification_test.rb, test/producers/report_upload_failed_test.rb, test/producers/system_non_compliant_test.rb
=> cleanup(db): RHICOMPL-3251 drop account_number from accounts table

app/models/application_record.rb, app/models/concerns/benchmark_searching.rb, app/models/concerns/profile_tailoring.rb, app/models/host.rb, app/models/os_major_version.rb, app/models/profile.rb, app/models/rule.rb, app/models/xccdf/benchmark.rb
=> refactor(Arel): RHICOMPL-3908 create shorthand for Arel::Nodes

app/graphql/schema.graphql, app/graphql/types/system.rb, app/models/concerns/host_searching.rb, app/serializers/host_serializer.rb, spec/api/v1/schemas/hosts.rb, spec/integration/systems_spec.rb, swagger/v1/openapi.json, test/controllers/v1/systems_controller_test.rb, test/graphql/queries/system_query_test.rb
=> feat(Hosts): RHICOMPL-3903 expose groups in gql and rest api

Gemfile, Gemfile.lock, db/migrate/20230727092330_create_canonical_profiles.rb, db/schema.rb, db/views/canonical_profiles_v01.sql
=> feat(DB): RHICOMPL-3916 introduce the canonical profiles view

.codecov.yml, app/controllers/v2/application_controller.rb, app/controllers/v2/security_guides_controller.rb, app/models/v2/security_guide.rb, app/policies/v2/security_guide_policy.rb, app/serializers/v2/application_serializer.rb, app/serializers/v2/security_guide_serializer.rb, config/environments/test.rb, config/routes.rb, spec/controllers/v2/search/security_guides_controller.yaml, spec/controllers/v2/security_guides_controller_spec.rb, spec/controllers/v2/sort/security_guides_controller.yaml, spec/factories/account.rb, spec/factories/security_guide.rb, spec/factories/user.rb, spec/models/v2/security_guide_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb, spec/support/factory_bot.rb, spec/support/shared_examples/paginable_spec.rb, spec/support/shared_examples/searchable_spec.rb, spec/support/shared_examples/sortable_spec.rb, spec/support/shared_examples/with_metadata_spec.rb
=> feat(APIv2): RHICOMPL-3786 implement Security Guides controller

spec/controllers/v2/application_controller_spec.rb
=> fix(tests): RHICOMPL-3841 V2::Application controller tests

.codecov.yml, .github/workflows/ci.yml, spec/spec_helper.rb
=> feat(CI): RHICOMPL-3786 upload coverage from rspec tests as well

spec/policies/v2/security_guide_policy_spec.rb
=> test(SecurityGuidePolicy): RHICOMPL-3842 added specs

.codecov.yml, .github/workflows/ci.yml, .simplecov, spec/spec_helper.rb, test/test_helper.rb
=>  fix(CI): RHICOMPL-3933 unify codecov configuration

spec/swagger_helper.rb, swagger/v1/openapi.json
=> fix(OpenAPI): RHICOMPL-3934 correct attribute values

Jenkinsfile
=> fix(ci): RHICOMPL-3942 add Slack notifications

Gemfile, Gemfile.lock, app/producers/application_producer.rb, app/producers/notification.rb, app/producers/payload_tracker.rb, app/producers/remediation_updates.rb, deploy/clowdapp.yaml, lib/tasks/status.rake, test/producers/application_producer_test.rb, test/producers/notification_test.rb, test/producers/payload_tracker_test.rb, test/producers/remediation_updates_test.rb, test/producers/report_upload_failed_test.rb, test/producers/system_non_compliant_test.rb, test/tasks/status_test.rb
=> cleanup(deps): RHICOMPL-3853 replace ruby-kafka with rdkafka

deploy/clowdapp.yaml
=> revert(clowdapp): RHICOMPL-3853 remove notifications from dependencies

app/services/rbac.rb, spec/spec_helper.rb, test/services/rbac_test.rb, test/test_helper.rb
=> fix(RBAC): RHICOMPL-3850 make attribute_filter a method 🤦🤦🤦

app/services/rbac.rb, spec/spec_helper.rb, test/services/rbac_test.rb, test/test_helper.rb
=> fix(RBAC): RHICOMPL-3850 use the api client for RBAC as it is intended

app/models/v2/security_guide.rb
=> fix(typo): fix doc comment typo in SG model

app/controllers/v2/profiles_controller.rb, app/models/v2/profile.rb, app/models/v2/security_guide.rb, app/policies/v2/profile_policy.rb, app/serializers/v2/profile_serializer.rb, config/routes.rb, db/migrate/20230810085607_update_canonical_profiles_to_version_3.rb, db/schema.rb, db/views/canonical_profiles_v03.sql, spec/controllers/v2/concerns/metadata_spec.rb, spec/controllers/v2/concerns/paginable_spec.rb, spec/controllers/v2/concerns/searchable_spec.rb, spec/controllers/v2/concerns/sortable_spec.rb, spec/controllers/v2/concerns/with_metadata_spec.rb, spec/controllers/v2/profiles_controller_spec.rb, spec/factories/profile.rb, spec/fixtures/files/searchable/profiles_controller.yaml, spec/fixtures/files/sortable/profiles_controller.yaml, spec/spec_helper.rb
=> feat(APIv2): RHICOMPL-3888 implement profiles controller

Gemfile, spec/spec_helper.rb, test/test_helper.rb
**Before:**
```
[root@f99bfcf63ecb src]# bin/rails c
Loading development environment (Rails 7.0.4.3)
[1] pry(main)> 
Coverage report generated for RSpec to /opt/app-root/src/coverage. 322 / 596 LOC (54.03%) covered.
[root@f99bfcf63ecb src]# 
```
**After:**
```
[root@f99bfcf63ecb src]# bin/rails c
Loading development environment (Rails 7.0.4.3)
[1] pry(main)> 
[root@f99bfcf63ecb src]# 
```
=> fix(tests): do not load test-related gems into dev/prod

Jenkinsfile
=> feat(CI): Notify QE about pr_check failures

Gemfile, test/test_helper.rb
=> fix(coverage): move&require coverage gems for testing

Jenkinsfile, config/environments/production.rb, config/initializers/sidekiq.rb, lib/tasks/status.rake
=> fix(Redis): RHICOMPL-3948 convert SSL type to boolean in config

app/models/v2/security_guide.rb, spec/models/v2/security_guide_spec.rb
=> fix(SecurityGuide): RHICOMPL-3937 fix os_major_version regex and test it

spec/controllers/v2/profiles_controller_spec.rb, spec/controllers/v2/security_guides_controller_spec.rb
=> fix(tests): tidy up the specs a little with contexts and separation

app/controllers/v2/value_definitions_controller.rb, app/models/v2/security_guide.rb, app/models/v2/value_definition.rb, app/policies/v2/value_definition_policy.rb, app/serializers/v2/value_definition_serializer.rb, config/routes.rb, spec/controllers/v2/value_definitions_controller_spec.rb, spec/factories/value_definition.rb, spec/fixtures/files/searchable/value_definitions_controller.yaml, spec/fixtures/files/sortable/value_definitions_controller.yaml
=> feat(APIv2): RHICOMPL-3890 implement ValueDefinitions controller

Gemfile.lock
=> fix(SSG): RHICOMPL-3952 bump clowder-common-ruby

app/services/xccdf_report_parser.rb, test/services/xccdf_report_parser_test.rb
=> cleanup(XCCDF): RHICOMPL-3951 do not save missing RHEL6 benchmarks

app/controllers/concerns/v2/parameter_handling.rb, app/controllers/v2/application_controller.rb, spec/controllers/v2/concerns/parameters_spec.rb
Addressing `'include Pundit' is deprecated. Please use 'include Pundit::Authorization' instead`
=> refactor(lib): update deprecated include

spec/controllers/v2/profiles_controller_spec.rb
Forgot it in https://github.com/RedHatInsights/compliance-backend/pull/1801
=> test(ProfilesController): adjust semantics for parent matching

spec/fixtures/files/sortable/profiles_controller.yaml, spec/fixtures/files/sortable/security_guides_controller.yaml, spec/fixtures/files/sortable/value_definitions_controller.yaml
=> fix(tests): consolidate sortable fixtures

app/controllers/v2/rules_controller.rb, app/models/v2/rule.rb, app/models/v2/security_guide.rb, app/policies/v2/rule_policy.rb, app/serializers/v2/rule_serializer.rb, config/routes.rb, spec/controllers/v2/rules_controller_spec.rb, spec/factories/rule.rb, spec/fixtures/files/searchable/rules_controller.yaml, spec/fixtures/files/sortable/rules_controller.yaml
=> feat(APIv2): RHICOMPL-3889 implement Rules controller

spec/controllers/v2/application_controller_spec.rb, spec/controllers/v2/profiles_controller_spec.rb, spec/controllers/v2/rules_controller_spec.rb, spec/controllers/v2/security_guides_controller_spec.rb, spec/controllers/v2/value_definitions_controller_spec.rb, spec/factories/account.rb, spec/factories/profile.rb, spec/factories/rule.rb, spec/factories/security_guide.rb, spec/factories/user.rb, spec/factories/value_definition.rb, spec/policies/v2/profile_policy_spec.rb, spec/policies/v2/rule_policy_spec.rb, spec/policies/v2/value_definition_policy_spec.rb
=> Adjusted some minor issues in specs

spec/policies/v2/globally_available_spec.rb, spec/policies/v2/profile_policy_spec.rb, spec/policies/v2/rule_policy_spec.rb, spec/policies/v2/security_guide_policy_spec.rb, spec/policies/v2/value_definition_policy_spec.rb
Should also make the tests more deterministic with the `to_set` conversion
=> test(policies): introduce the globally available shared example

app/models/host.rb, app/policies/host_policy.rb, test/models/host_test.rb
We no longer need to hide edge hosts as cyndi does not copy them for us anymore.
=> cleanup(Hosts): do not explicitly hide edge hosts

app/controllers/concerns/v2/collection.rb, app/controllers/concerns/v2/metadata.rb, app/controllers/concerns/v2/pagination.rb, app/controllers/concerns/v2/parameter_handling.rb, app/controllers/v2/application_controller.rb, spec/controllers/v2/concerns/paginable_spec.rb, spec/controllers/v2/concerns/with_metadata_spec.rb
=> feat(APIv2): RHICOMPL-3956 align offset with standard expectations

app/controllers/concerns/v2/metadata.rb
=> docs(APIv2): fix typo

Gemfile.lock
=> chore(Clowder): bump clowder-common-ruby

app/services/rbac.rb, test/services/rbac_test.rb
=> fix(RBAC): RHINENG-2322 handle invalid JSON values

app/models/host.rb, test/graphql/queries/system_query_test.rb
=> fix(Host): RHINENG-1891 sort hosts with several policies correctly

Gemfile, Gemfile.lock, app/controllers/concerns/v2/rendering.rb, app/controllers/v2/application_controller.rb, app/serializers/v2/application_serializer.rb, app/serializers/v2/profile_serializer.rb, app/serializers/v2/rule_serializer.rb, app/serializers/v2/security_guide_serializer.rb, app/serializers/v2/value_definition_serializer.rb, spec/controllers/v2/concerns/paginable_spec.rb, spec/controllers/v2/profiles_controller_spec.rb, spec/controllers/v2/rules_controller_spec.rb, spec/controllers/v2/security_guides_controller_spec.rb, spec/controllers/v2/value_definitions_controller_spec.rb, swagger/v2/openapi.json
=> refactor(APIv2): RHINENG-2271 use panko for JSON serialization

Gemfile, Gemfile.lock
=> chore(deps): update sidekiq + downgrade redis

config/routes.rb
=> feat(APIv2): RHINENG-2441 expose access via environment variable

scripts/deploy/build-deploy-common.sh
=> fix(ci): typo on docker config variable

spec/controllers/v2/concerns/collection_spec.rb, spec/controllers/v2/concerns/paginable_spec.rb, spec/controllers/v2/concerns/resource_spec.rb, spec/controllers/v2/concerns/searchable_spec.rb, spec/controllers/v2/concerns/sortable_spec.rb, spec/controllers/v2/concerns/with_metadata_spec.rb, spec/controllers/v2/profiles_controller_spec.rb, spec/controllers/v2/rules_controller_spec.rb, spec/controllers/v2/security_guides_controller_spec.rb, spec/controllers/v2/value_definitions_controller_spec.rb
=> refactor(tests): introduce collection and resource shared examples

deploy/clowdapp.yaml
=> fix(clowdapp): RHINENG-2441 expose APIV2 env variable

spec/controllers/v2/concerns/resource_spec.rb, spec/controllers/v2/profiles_controller_spec.rb, spec/controllers/v2/rules_controller_spec.rb, spec/controllers/v2/value_definitions_controller_spec.rb
=> refactor(APIv2): decouple not_found test factory generation

.rubocop.yml, Gemfile.lock, app/controllers/concerns/tag_filtering.rb, app/controllers/graphql_controller.rb, app/models/business_objective.rb, app/models/concerns/short_ref_id.rb, app/models/rule.rb, app/models/xccdf.rb, app/services/reports_tar_reader.rb, app/services/supported_ssg_updater.rb, spec/api/v2/schemas.rb, test/graphql/queries/profile_query_test.rb
=> chore(deps): update rubocop to its latest version

app/controllers/concerns/v2/metadata.rb
Should have on less call to `resolve_collection`
=> perf(APIv2): rely on resource when determining column to count by

README.md
=> cleanup(README): minor revisions in the readme

Gemfile, Gemfile.lock, app/services/rbac.rb, test/controllers/v1/profiles_controller_test.rb, test/controllers/v1/systems_controller_test.rb, test/graphql/mutations/associate_systems_test.rb, test/graphql/queries/profile_query_test.rb, test/graphql/queries/system_query_test.rb, test/policies/host_policy_test.rb, test/policies/policy_host_policy_test.rb, test/services/rbac_test.rb
To use https://github.com/RedHatInsights/insights-rbac-api-client-ruby/pull/15
=> chore: update insights-rbac-api-client gem

app/controllers/concerns/v2/rendering.rb, app/controllers/v2/application_controller.rb, app/models/v2/rule.rb, app/serializers/v2/application_serializer.rb, app/serializers/v2/rule_serializer.rb, app/serializers/v2/security_guide_serializer.rb, spec/controllers/v2/rules_controller_spec.rb, spec/factories/rule.rb, spec/models/v2/rule_spec.rb
This change introduces a `fields` method on the serializer(s) that allow the user to determine what fields are required from a given model to construct the JSON serialized result returned by the controller. Furthermore, a new `derived_attribute` is introduced to the serializer's DSL for declaring fields that depend on other models. The logic deciding what fields should be shown has been implemented using Panko's [`.filter_for`](https://panko.dev/docs/attributes#filters-for) method. Finally, the rendering is adjusted to only select & alias fields that are really required for serialization. 
The new `derived_attribute` should be used to declare a field of an ActiveRecord object that is conditionally constructed by data from the parent (joined) objects if they are available. A good example …
=> feat(APIv2): RHINENG-2198 introduce the derived_attribute serializer

app/models/policy.rb, db/migrate/20231023161508_add_profile_id_to_policies.rb, db/schema.rb
=> feat(DB): RHINENG-2705 expose profile_id on the policies table

app/controllers/concerns/v2/metadata.rb, spec/controllers/v2/concerns/with_metadata_spec.rb
=> fix(APIv2): RHINENG-2443 correct last page link of empty response

app/controllers/concerns/v2/collection.rb, app/controllers/concerns/v2/metadata.rb, app/controllers/concerns/v2/rendering.rb, spec/controllers/v2/concerns/rendering_spec.rb, spec/controllers/v2/security_guides_controller_spec.rb
=> fix(APIv2): RHINENG-1881 return not_found when parent ID is incorrect

app/models/v2/policy.rb, app/models/v2/policy_host.rb, app/models/v2/tailoring.rb, db/migrate/20231024083131_create_tailorings.rb, db/migrate/20231024113017_create_v2_policies.rb, db/schema.rb, db/views/tailorings_v01.sql, db/views/v2_policies_v01.sql
The `tailorings` view is a simplification of the non-canonical profiles with only the really necessary fields available. 
=> feat(APIv2): RHINENG-1986 create views for policies and tailorings

db/migrate/20231024145940_drop_dead_profiles.rb, db/schema.rb
=> cleanup(DB): RHINENG-2721 delete dead policies without any profile

db/migrate/20231101162444_update_tailorings_to_version_2.rb, db/schema.rb, db/views/tailorings_v02.sql
=> fix(DB): RHINENG-1986 add missing os_minor_version to tailorings

deploy/clowdapp.yaml
We already do this in stage, but ephemeral clowder had no support for cyndi's additional filters so far, so adding them now.
=> devel(ephemeral): RHINENG-1789 add support for cyndi filters

spec/controllers/v2/concerns/rendering_spec.rb
=> fix(specs): use singularize on type instead of chop

spec/controllers/v2/concerns/paginable_spec.rb, spec/controllers/v2/concerns/rendering_spec.rb, spec/controllers/v2/concerns/searchable_spec.rb, spec/controllers/v2/concerns/sortable_spec.rb, spec/controllers/v2/concerns/with_metadata_spec.rb
The `extra_params` in searchable/sortable concerns were used both in dynamically generated factories and in the params to be passed to the final testing request. However, there are cases when the factories need these entities, but the params do not. The simplest example could be the `account_id` that is never passed to any request as a param, it is always assumed from the context, however, it is essential for the creation of some records such as policies.
In order to keep both the controller and the factories happy, I am proposing to pass whole `ActiveRecord` objects in `extra_params` to be omitted from the request, but kept when creating a factory. Internally this is done by the `passable_params` variable that contains only the non-ActiveRecord objects, while the `extra_params` keeps …
=> test(APIv2): remove AR relationships from extra_params in requests

Gemfile.lock
Brings in changes between: https://github.com/RedHatInsights/clowder-common-ruby/compare/v0.5.0...v0.5.4 - specifically needed for fix in https://github.com/RedHatInsights/clowder-common-ruby/pull/57
=> chore(Clowder): Update clowder-common-ruby gem to 0.5.4

app/controllers/concerns/v2/parameter_handling.rb, app/controllers/v2/policies_controller.rb, app/models/v2/account.rb, app/models/v2/policy.rb, app/models/v2/security_guide.rb, app/models/v2/tailoring.rb, app/policies/v2/policy_policy.rb, app/serializers/v2/policy_serializer.rb, config/routes.rb, spec/controllers/v2/policies_controller_spec.rb, spec/factories/policy.rb, spec/fixtures/files/searchable/policies_controller.yaml, spec/fixtures/files/sortable/policies_controller.yaml, spec/models/v2/policy_spec.rb, spec/policies/v2/policy_policy_spec.rb
Some testing shared example stuff is missing, but they can be added as we move forward with other endpoints and we figure out how we actually want to do it.
=> feat(APIv2): RHINENG-2076 implemented the policies endpoint

app/controllers/concerns/v2/indexable_by_ref_id.rb, app/controllers/v2/profiles_controller.rb, app/controllers/v2/rules_controller.rb, spec/controllers/v2/concerns/indexable_by_ref_id_spec.rb, spec/controllers/v2/profiles_controller_spec.rb, spec/controllers/v2/rules_controller_spec.rb, spec/factories/profile.rb, spec/factories/rule.rb
=> fix(APIv2): RHINENG-2097 allow profiles and rules to be indexed by ref_id

spec/controllers/v2/concerns/rendering_spec.rb
=> test(APIv2): add case for request with nonexistent resource ID

README.md
Because of using autoloading, the test file can not be ran using usual `rspec ./spec/tested/file/test.rb` and the desired test needs to be specified in environment variable.
=> docs: running a specific Rspec test

app/models/v2/policy.rb, app/models/v2/security_guide.rb, app/serializers/v2/policy_serializer.rb, app/serializers/v2/security_guide_serializer.rb, db/migrate/20231126165548_update_security_guides_to_version_2.rb, db/schema.rb, db/views/security_guides_v02.sql, spec/factories/security_guide.rb, spec/fixtures/files/searchable/security_guides_controller.yaml, spec/models/v2/policy_spec.rb
This might seem redundant, but it removes a lot of arel-code that would be hard to maintain across models.
=> refactor(DB): RHINENG-1986 make os_major_version a column for SGs

app/models/profile_os_minor_version.rb, app/models/supported_ssg.rb, app/models/v2/profile.rb, app/models/v2/profile_os_minor_version.rb, app/services/concerns/xccdf/profile_os_minor_versions.rb, app/services/concerns/xccdf/util.rb, app/services/ssg_config_downloader.rb, db/migrate/20231128065238_create_profile_os_minor_versions.rb, db/schema.rb, test/services/concerns/xccdf/profile_os_minor_versions_test.rb
The profile support matrix essentially replaces the `SupportedSsg` "model" from the V1 world. Its seeding is part of the SSG import process that utilizes V1 models, so I also created the model there. The table should help us determine what OS minor versions are supported by which profile.
=> feat(DB): RHINENG-1986 create and seed the profile support matrix

app/controllers/v2/security_guides_controller.rb
Found this by accident, probably not needed, so dropping it before someone copypastes it 😁 
=> cleanup(API): drop the scope method from SecurityGuidesController

Jenkinsfile
=> fix(ci): add CRCD secrets

config/environments/production.rb
=> fix(logging): RHINENG-6790 make cloudwatch client global

spec/controllers/v2/concerns/with_metadata_spec.rb
=> test(APIv2): make metadata testing dynamically based on item_count

Jenkinsfile
=> fix(ci): Switch back to ephemeral for Smoke tests

app/models/v2/tailoring.rb, app/models/v2/tailoring_rule.rb
=> feat(APIv2): RHINENG-1986 tailoring rule model

app/models/v2/rule.rb
=> fix(APIv2): change delete_all to destroy in Rules model

docker-compose.yml
=> fix(devel): update xjoin to the latest in compose

spec/controllers/v2/supported_profiles_controller_spec.rb, spec/factories/security_guide.rb
=> fix(tests): move SecurityGuide with_profiles factory to a separate trait

db/migrate/20240126103711_create_v2_rule_groups.rb, db/schema.rb, db/views/v2_rule_groups_v01.sql
=> feat(APIv2): create v2_rule_groups view

scripts/unit_test.sh
=> fix(CI): RHINENG-8060 make cyndi setup SQL path absolute

deploy/clowdapp.yaml
=> perf(pods): RHINENG-8064 increase the CPU limit for faster bootup

deploy/clowdapp.yaml
=> perf(pods): RHINENG-8064 bump readiness/liveness initialDelay

deploy/clowdapp.yaml
=> perf(pods): RHINENG-8064 bump readiness/liveness initialTimeout

app/models/v2/account.rb, app/models/v2/policy.rb, app/models/v2/policy_system.rb, app/models/v2/system.rb, app/serializers/v2/policy_serializer.rb, db/migrate/20240206160452_update_v2_policies_to_version_2.rb, db/schema.rb, db/views/v2_policies_v02.sql, spec/controllers/v2/policies_controller_spec.rb, spec/factories/policy.rb
Only merge after we got PM guidance about the naming conventions!
=> feat(APIv2): RHINENG-1986 prefer systems over hosts in models

Gemfile, Gemfile.lock
=> chore(deps): RHINENG-8107 make sure CGI and time are the latest

app/models/v2/system.rb
=> fix(APIv2): RHINENG-1986 connect hosts table to systems model

app/models/v2/account.rb, app/models/v2/policy.rb, app/models/v2/system.rb, app/models/v2/tailoring.rb, spec/controllers/v2/concerns/paginable_spec.rb, spec/controllers/v2/concerns/rendering_spec.rb, spec/controllers/v2/concerns/searchable_spec.rb, spec/controllers/v2/concerns/sortable_spec.rb, spec/controllers/v2/concerns/with_metadata_spec.rb, spec/controllers/v2/policies_controller_spec.rb, spec/models/v2/policy_spec.rb, spec/policies/v2/policy_policy_spec.rb
=> fix(db): RHINENG-1986 temporarily use V1 models for users/accounts

spec/policies/v2/policy_policy_spec.rb, spec/policies/v2/profile_policy_spec.rb, spec/policies/v2/rule_policy_spec.rb, spec/policies/v2/security_guide_policy_spec.rb, spec/policies/v2/value_definition_policy_spec.rb
=> fix(tests): make policy specs use the right user factory

app/controllers/concerns/v2/rendering.rb, app/serializers/v2/application_serializer.rb
Some semantical sugar that was hurting my 👀 
=> refactor(V2): rename the serialization context variable to joined

app/policies/v2/policy_policy.rb
=> docs(APIv2): corrected wrong model in comment

app/controllers/v2/application_controller.rb, app/controllers/v2/systems_controller.rb, app/models/v2/policy_system.rb, app/models/v2/system.rb, app/policies/v2/system_policy.rb, app/serializers/v2/system_serializer.rb, config/routes.rb, db/schema.rb, spec/controllers/v2/concerns/rendering_spec.rb, spec/controllers/v2/systems_controller_spec.rb, spec/factories/system.rb, spec/fixtures/files/searchable/systems_controller.yaml, spec/fixtures/files/sortable/systems_controller.yaml, spec/policies/v2/system_policy_spec.rb
The aggregated `policies` field is missing from this PR as it needs significant changes in how we `expand_resource`s. I will address that in a follow-up PR to make the review of this one easier.
=> feat(APIv2): RHINENG-2059 introduce the systems endpoint

app/services/concerns/xccdf/profiles.rb, db/migrate/20240219092555_reset_revisions_for_name_changes.rb, db/schema.rb
=> fix(SSG): RHINENG-8323 update profile names upon reimport

Jenkinsfile
=> fix(ci): RHCLOUD-31076 add Github API secrets

deploy/clowdapp.yaml
=> feat(Clowder): RHINENG-1883 set up pulp repository in stage

deploy/clowdapp.yaml
=> chore(clowder): RHINENG-1883 invoke pulp setup clowdjob

deploy/clowdapp.yaml
=> fix(clowder): RHINENG-1883 fix baseurl for pulp setup job

deploy/clowdapp.yaml
This reverts commit 7742476d3402014bb9a357c0851f6997dfd91c92.
=> revert(clowder): RHINENG-1883 drop pulp setup clowdjob

deploy/clowdapp.yaml
=> fix(clowder): RHINENG-1883 adjust secret and job name for pulp

deploy/clowdapp.yaml
=> fix(clowder): RHINENG-1883 adjust workdir and job name for pulp

deploy/clowdapp.yaml
=> fix(clowder): RHINENG-1883 adjust baseurl for pulp and rerun job

deploy/clowdapp.yaml
=> revert(clowder): RHINENG-1883 clean up the pulp domain setup job

spec/controllers/v2/concerns/rendering_spec.rb
=> refactor(V2Resolver): replace number with attribute names

docker-compose.yml
=> dev(compose): mock service account lookup in the RBAC container

spec/policies/v2/policy_policy_spec.rb
=> docs: Correct test description

Dockerfile
This is an ugly hack to make a security scanner happy by manually deleting RPM-provided files that cause false positives...
=> fix(Dockerfile): RHINENG-8107 hack around the security scanner

app/services/concerns/xccdf/util.rb
=> fix(SSG): RHINENG-7859 temporarily disable the V2 support matrix

app/services/concerns/xccdf/util.rb
=> revert(SSG): RHINENG-7859 re-enable the V2 support matrix in import

app/controllers/v2/tailorings_controller.rb, app/models/v2/profile.rb, app/models/v2/rule.rb, app/models/v2/rule_group.rb, app/models/v2/tailoring.rb, app/models/v2/tailoring_rule.rb, app/policies/v2/tailoring_policy.rb, app/serializers/v2/tailoring_serializer.rb, app/services/v2/xccdf_tailoring_file.rb, config/routes.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/factories/profile.rb, spec/factories/profile_rule.rb, spec/factories/rule.rb, spec/factories/rule_group.rb, spec/factories/security_guide.rb, spec/factories/tailoring.rb, spec/factories/tailoring_rule.rb, spec/fixtures/files/searchable/tailorings_controller.yaml, spec/fixtures/files/sortable/tailorings_controller.yaml, spec/policies/v2/tailoring_policy_spec.rb, spec/spec_helper.rb
=> feat(APIv2): RHINENG-2875 implement tailorings endpoint

app/controllers/concerns/v2/resolver.rb, app/serializers/v2/application_serializer.rb, config/routes.rb, spec/controllers/v2/systems_controller_spec.rb, spec/factories/policy.rb, spec/factories/policy_system.rb, spec/factories/system.rb, spec/fixtures/files/searchable/systems_controller.yaml, spec/fixtures/files/sortable/systems_controller.yaml
I included some minor fixes that only make sense as a followup here (and I want to avoid rebasing) and also the filtering out of aggregations if the dependencies of the aggregation are joined as parents. 
=> feat(APIv2): RHINENG-8339 implement systems under policies

spec/factories/tailoring.rb
=> test(Tailorings): make sure that random rules are not converging

app/models/v2/report.rb, app/models/v2/system.rb, app/models/v2/tailoring.rb, db/migrate/20240302162345_create_reports.rb, db/schema.rb, db/views/reports_v01.sql
=> feat(V2): RHINENG-1986 introduce the reports model

app/models/v2/policy_system.rb, app/models/v2/system.rb, db/migrate/20240304140834_create_policy_systems.rb, db/schema.rb, db/views/policy_systems_v01.sql, spec/factories/policy_system.rb
=> feat(DB): RHINENG-1986 introduce policy_systems view

app/models/v2/policy.rb, config/routes.rb, spec/controllers/v2/policies_controller_spec.rb, spec/factories/policy.rb, spec/fixtures/files/searchable/policies_controller.yaml, spec/fixtures/files/sortable/policies_controller.yaml
Depends on https://github.com/RedHatInsights/compliance-backend/pull/1961
=> feat(APIv2): RHINENG-8556 introduce /systems/:id/policies

app/controllers/v2/application_controller.rb, app/controllers/v2/systems_controller.rb, app/models/v2/policy.rb, app/models/v2/policy_system.rb, app/models/v2/system.rb, app/policies/v2/system_policy.rb, config/routes.rb, spec/controllers/v2/concerns/searchable_spec.rb, spec/controllers/v2/concerns/sortable_spec.rb, spec/controllers/v2/policies_controller_spec.rb, spec/controllers/v2/systems_controller_spec.rb, spec/factories/policy.rb, spec/factories/system.rb, spec/fixtures/files/searchable/policies_controller.yaml, spec/fixtures/files/searchable/systems_controller.yaml, spec/fixtures/files/sortable/policies_controller.yaml, spec/fixtures/files/sortable/systems_controller.yaml, spec/spec_helper.rb
=> feat(APIv2): RHINENG-392 assigning/deassigning systems from policies

app/serializers/v2/policy_serializer.rb, db/migrate/20240306151739_update_v2_policies_to_version_3.rb, db/schema.rb, db/views/reports_v02.sql, db/views/v2_policies_v03.sql, spec/controllers/v2/policies_controller_spec.rb, spec/factories/policy.rb
=> feat(DB): RHINENG-1986 rename system_count to total_system_count

app/models/v2/policy.rb, spec/controllers/v2/policies_controller_spec.rb, spec/factories/policy.rb
Created a separate ticket for testing...
=> feat(APIv2): RHINENG-8729 sort by total_system_count in policies

spec/factories/policy.rb, spec/fixtures/files/sortable/policies_controller.yaml
=> test(APIv2): RHINENG-8734 policies sortable by total_system_count

app/controllers/concerns/tag_filtering.rb, app/controllers/concerns/v2/parameter_handling.rb, app/models/v2/application_record.rb, spec/controllers/v2/concerns/taggable_spec.rb, spec/controllers/v2/concerns/with_metadata_spec.rb, spec/controllers/v2/systems_controller_spec.rb, spec/factories/system.rb
=> feat(APIv2): RHINENG-8779 enable tagging for systems

app/controllers/v2/tailorings_controller.rb, app/models/v2/tailoring.rb, app/services/v2/xccdf_tailoring_file.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/factories/profile.rb, spec/factories/tailoring.rb
=> fix(Tailoring): RHINENG-8753 include unselected rules

spec/controllers/v2/supported_profiles_controller_spec.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/factories/profile.rb, spec/factories/security_guide.rb
=> refactor(specs): eliminate count-based traits

app/controllers/v2/rule_groups_controller.rb, app/models/v2/rule_group.rb, app/policies/v2/rule_group_policy.rb, app/serializers/v2/rule_group_serializer.rb, config/routes.rb, spec/controllers/v2/rule_groups_controller_spec.rb, spec/fixtures/files/sortable/rule_groups_controller.yaml, spec/policies/v2/rule_group_policy_spec.rb
=> feat(APIv2): RHINENG-8832 introduce the rule groups endpoint

app/controllers/v2/security_guides_controller.rb, app/models/v2/security_guide.rb, app/policies/v2/security_guide_policy.rb, config/routes.rb, spec/controllers/v2/security_guides_controller_spec.rb, spec/models/v2/security_guide_spec.rb
Returning the bare minimum structure for reconstructing a hierarchy of rules and groups. 
=> feat(APIv2): RHINENG-8831 implemented rule_tree endpoint

app/controllers/v2/tailorings_controller.rb, app/services/v2/json_tailoring_file.rb, app/services/v2/xccdf_tailoring_file.rb, config/routes.rb, spec/controllers/v2/tailorings_controller_spec.rb
Tests will come later as there is some stuff to clean up in the `tailoring_file` tests.
=> feat(Tailoring): RHINENG-8754 introduce JSON tailoring file format

spec/api/v2/schemas.rb, spec/api/v2/schemas/errors.rb, spec/api/v2/schemas/security_guide.rb, spec/integration/v2/security_guides_spec.rb, spec/swagger_helper.rb, swagger/v2/openapi.json
* Created some new helper methods for schema referencing
* Adjusted schema class names 
* Made a comment about the identity header being internal only (for v1 too)
=> feat(APIv2): RHINENG-2752 swagger specs for Security Guides

spec/api/v2/schemas.rb, spec/api/v2/schemas/profile.rb, spec/api/v2/schemas/security_guide.rb, spec/api/v2/schemas/value_definition.rb, spec/integration/v2/profiles_spec.rb, spec/integration/v2/value_definitions_spec.rb, swagger/v2/openapi.json
=> fix(OpenAPIv2): RHINENG-2752 implemented value definitions

spec/api/v2/schemas.rb, spec/api/v2/schemas/supported_profile.rb, spec/integration/v2/supported_profiles_spec.rb, swagger/v2/openapi.json
=> feat(OpenAPIv2): RHINENG-2752 implemented supported profiles

app/controllers/concerns/v2/rendering.rb, app/controllers/v2/policies_controller.rb, app/controllers/v2/systems_controller.rb, spec/controllers/v2/policies_controller_spec.rb, spec/controllers/v2/systems_controller_spec.rb
=> fix(APIv2): make CREATE/UPDATE responses semantically correct

spec/api/v2/schemas.rb, spec/api/v2/schemas/metadata.rb, spec/api/v2/schemas/policy.rb, spec/api/v2/schemas/profile.rb, spec/api/v2/schemas/rule_group.rb, spec/api/v2/schemas/security_guide.rb, spec/api/v2/schemas/supported_profile.rb, spec/api/v2/schemas/types.rb, spec/api/v2/schemas/value_definition.rb, spec/integration/v2/policies_spec.rb, spec/integration/v2/profiles_spec.rb, spec/integration/v2/rule_groups_spec.rb, spec/integration/v2/security_guides_spec.rb, spec/integration/v2/supported_profiles_spec.rb, spec/integration/v2/value_definitions_spec.rb, spec/swagger_helper.rb, swagger/v2/openapi.json
=> feat(OpenAPIv2): RHINENG-2752 implemented policies

app/policies/v2/tailoring_policy.rb, spec/api/v2/schemas.rb, spec/api/v2/schemas/tailoring.rb, spec/api/v2/schemas/tailoring_file.rb, spec/factories/policy.rb, spec/integration/v2/tailorings_spec.rb, swagger/tailoring_file.json, swagger/v2/openapi.json
=> feat(OpenAPIv2): RHINENG-2752 implemented tailorings

spec/api/v2/schemas.rb, spec/api/v2/schemas/rule.rb, spec/factories/rule.rb, spec/integration/v2/rule_groups_spec.rb, spec/integration/v2/rules_spec.rb, swagger/v1/openapi.json, swagger/v2/openapi.json
=> feat(OpenAPIv2): RHINENG-2752 implemented rules

spec/integration/v2/tailorings_spec.rb, swagger/v2/openapi.json
=> fix(OpenAPIv2): RHINENG-2752 define tailoring indexation by OS

app/controllers/v2/systems_controller.rb, spec/controllers/v2/systems_controller_spec.rb
=> fix(APIv2): adjust RBAC and responses for systems patch/delete

.rubocop.yml, spec/api/v2/schemas.rb, spec/api/v2/schemas/policy.rb, spec/api/v2/schemas/profile.rb, spec/api/v2/schemas/rule.rb, spec/api/v2/schemas/rule_group.rb, spec/api/v2/schemas/security_guide.rb, spec/api/v2/schemas/supported_profile.rb, spec/api/v2/schemas/system.rb, spec/api/v2/schemas/tailoring.rb, spec/api/v2/schemas/value_definition.rb, spec/integration/v2/systems_spec.rb, swagger/v2/openapi.json
=> feat(OpenAPIv2): RHINENG-2752 implemented systems

.github/workflows/ci.yml
=> test(CI): use RSpec doc format with colored output in GH actions

spec/controllers/v2/tailorings_controller_spec.rb
=> refactor(spec): simplify some things in the Tailorings tests

app/models/v2/security_guide.rb, spec/models/v2/security_guide_spec.rb
=> fix(APIv2): sort RuleTree nodes on the same level by precedence

spec/integration/v2/policies_spec.rb, swagger/v2/openapi.json
=> feat(OpenAPIv2): RHINENG-2752 systems/policies endpoint specs

app/controllers/concerns/v2/authentication.rb, app/controllers/v2/application_controller.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/factories/account.rb, spec/factories/user.rb
=> fix(Tailoring): RHINENG-8782 do not restrict tailoring_file to cert_auth

spec/controllers/v2/tailorings_controller_spec.rb
=> test(Tailoring): RHINENG-8856 test JSON and XML tailoring formats

app/models/v2/application_record.rb, app/models/v2/policy_system.rb, app/models/v2/profile.rb, app/models/v2/security_guide.rb, spec/controllers/v2/systems_controller_spec.rb, spec/models/v2/profile_spec.rb
=> feat(APIv2): when assigning a system, make sure it has a tailoring

app/serializers/v2/profile_serializer.rb, app/serializers/v2/tailoring_serializer.rb, spec/api/v2/schemas/profile.rb, spec/controllers/v2/profiles_controller_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): RHINENG-8907 expose value_overrides on profiles

app/controllers/v1/statuses_controller.rb
=> test(readiness): RHINENG-8803 debug the statuses controller

app/controllers/v1/statuses_controller.rb, config/environments/production.rb
=> test(readiness): RHINENG-8803 even more debugging

spec/integration/v2/systems_spec.rb
=> docs(OpenAPI): Correct description of a 404 error when unassigning System

spec/controllers/v2/systems_controller_spec.rb
=> test(Tailoring): sort values and rules by id

app/controllers/v2/rules_controller.rb, app/models/v2/policy.rb, app/models/v2/rule.rb, app/models/v2/tailoring.rb, app/models/v2/tailoring_rule.rb, app/policies/v2/rule_policy.rb, config/routes.rb, db/migrate/20240322093524_tailoring_rule_view.rb, db/schema.rb, db/views/tailoring_rules_v01.sql, spec/controllers/v2/rules_controller_spec.rb, spec/factories/rule.rb, spec/integration/v2/tailorings_spec.rb, swagger/v2/openapi.json
=> feat(Tailoring): RHINENG-2876 (un)assign rules with tailoring

scripts/unit_test.sh
=> fix(ci): update postgresql-rds image tag

public/api/compliance/v2/openapi.json
=> feat(APIv2): expose v2 OpenAPI schema in public

.github/workflows/ci.yml, swagger/v2/openapi.json
=> fix(OpenAPI): regenerate V2 schema and adjust CI to validate it

config/environments/production.rb
=> fix(cloudwatch): RHINENG-9019 re-enable cloudwatch

app/controllers/concerns/v2/rendering.rb, app/controllers/v2/rules_controller.rb, app/controllers/v2/systems_controller.rb, app/models/v2/application_record.rb, app/models/v2/system.rb, app/policies/v2/rule_policy.rb, app/policies/v2/system_policy.rb, config/routes.rb, spec/controllers/v2/rules_controller_spec.rb, spec/controllers/v2/systems_controller_spec.rb, spec/integration/v2/rules_spec.rb, spec/integration/v2/systems_spec.rb, swagger/v2/openapi.json
Depends on: https://github.com/RedHatInsights/compliance-backend/pull/2023
=> feat(APIv2): RHINENG-3746 bulk assignment of systems and rules

app/models/v2/policy.rb, spec/controllers/v2/policies_controller_spec.rb
=> feat(APIv2): RHINENG-5800 inherit default values upon policy creation

.github/workflows/ci.yml
=> chore(CI): bump codecov exporter to its latest version

spec/integration/v2/profiles_spec.rb, spec/integration/v2/value_definitions_spec.rb
=> fix(CI): eliminate sporiadic failures with spaces in titles

app/controllers/concerns/v2/authentication.rb, app/controllers/concerns/v2/resolver.rb, app/models/account.rb, app/models/user.rb, app/models/v2/application_record.rb, app/models/v2/policy.rb, app/models/v2/system.rb, app/policies/v2/system_policy.rb, lib/insights/api/common/identity_header.rb, spec/controllers/v2/policies_controller_spec.rb, spec/controllers/v2/systems_controller_spec.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/factories/account.rb, spec/factories/system.rb, spec/factories/user.rb, spec/fixtures/files/searchable/policies_controller.yaml, spec/policies/v2/system_policy_spec.rb, test/models/user_test.rb
Had to do some cleanups and extend some things around `CERTH_AUTH` which allowed me to add additional test coverage for some endpoints. Furthermore, I introduced searching profiles by `os_minor_version` to allow insights-client to look up profiles to which a system can be assigned.
=> Surprise for PM

app/consumers/concerns/report_parsing.rb, app/consumers/inventory_events_consumer.rb, app/jobs/delete_host.rb, app/jobs/parse_report_job.rb, config/environments/development.rb, config/environments/production.rb, lib/insights/api/common/logger_with_audit.rb
Tested in ephemeral, all good!
=> fix(cloudwatch): RHINENG-9019 re-enable cloudwatch without tagging

app/models/v2/test_result.rb, db/migrate/20240409085523_create_v2_test_results.rb, db/schema.rb, db/views/v2_test_results_v01.sql
=> feat(APIv2): RHINENG-1986 introduce the V2::TestResult model

app/controllers/v2/tailorings_controller.rb, app/models/v2/tailoring.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/factories/profile.rb, spec/factories/tailoring.rb, spec/models/v2/tailoring_spec.rb
=> fix(APIv2): RHINENG-9361 map ref_id of values into tailoring_file

app/controllers/concerns/v2/authentication.rb
=> fix(APIv2): do not set empty parents for root route CERT_AUTH

.github/workflows/ci.yml
https://github.com/codecov/codecov-action/issues/1368
=> fix(CI): revert codecov-actions to v4.2.0

.github/workflows/ci.yml
=> fix(CI): compatibility with codecov-action@v4

app/controllers/concerns/v2/authentication.rb, app/services/v2/json_tailoring_file.rb, spec/controllers/v2/systems_controller_spec.rb
=> Minor refactorings around APIv2

app/models/v2/application_record.rb, spec/controllers/v2/concerns/searchable_spec.rb, spec/integration/v2/profiles_spec.rb, spec/integration/v2/value_definitions_spec.rb, spec/swagger_helper.rb
=> fix(APIv2): RHINENG-9542 fail on implicit searching without fields

app/models/v2/system.rb, spec/fixtures/files/searchable/systems_controller.yaml, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-8781 allow filtering systems by assigned/scanned

app/serializers/v2/rule_serializer.rb, db/functions/v2_rules_delete_v01.sql, db/functions/v2_rules_insert_v01.sql, db/functions/v2_rules_update_v01.sql, db/migrate/20240423093616_update_v2_rules_to_version_2.rb, db/migrate/20240423105337_create_function_v2_rules_insert.rb, db/migrate/20240423110153_create_function_v2_rules_update.rb, db/migrate/20240423110737_create_function_v2_rules_delete.rb, db/migrate/20240423111001_create_trigger_v2_rules_insert.rb, db/migrate/20240423111009_create_trigger_v2_rules_update.rb, db/migrate/20240423111013_create_trigger_v2_rules_delete.rb, db/schema.rb, db/triggers/v2_rules_delete_v01.sql, db/triggers/v2_rules_insert_v01.sql, db/triggers/v2_rules_update_v01.sql, db/views/v2_rules_v02.sql, spec/controllers/v2/rules_controller_spec.rb, spec/factories/rule.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-8970 implemented missing fields on rules

spec/integration/v2/policies_spec.rb, spec/integration/v2/security_guides_spec.rb, spec/integration/v2/supported_profiles_spec.rb, spec/integration/v2/systems_spec.rb, spec/swagger_helper.rb, swagger/v2/openapi.json
=> fix(APIv2): various minor fixes around the OpenAPI spec

app/models/v2/policy.rb, app/models/v2/system.rb, app/models/v2/tailoring.rb
=> fix(APIv2): RHINENG-9765 use try when resolving derived attributes

app/consumers/concerns/report_parsing.rb, app/consumers/inventory_events_consumer.rb
=> dev(kafka): adding debug logging to figure out what's wrong

app/consumers/concerns/report_parsing.rb, app/consumers/inventory_events_consumer.rb
=> dev(kafka): adding specific debug logging to figure out what's wrong

app/controllers/concerns/v2/resolver.rb, app/serializers/v2/application_serializer.rb
The current implementation of aggregations in the `V2::Resolver` supports one aggregation per reflection. When trying to define multiple ones, the resulting `[lambda, alias]` pairs get flattened with other pairs. Furthermore, the joining for a given reflection happens multiple times, once per aggregation, which is inefficient and would require aliasing. 
I had to adjust the `V2::ApplicationSerializer#merge_dependencies` to not flatten the `[lambda, alias]` pairs when doing the aggregation. The flattening still happens in any other case (joining parents and 1:1s) as it should. I also extracted the field evaluation/aliasing + selection in the `V2::Resolver#join_aggregated` method into a single step per reflection. 
Now that different aggregations overlap and use the same `JOIN` fragment, it …
=> fix(APIv2): RHINENG-9808 optimize multiple aggregations within relation

dashboards/grafana-dashboard-insights-compliance-general.template.yaml
=> fix: updates variable syntax to get back deploy annotations

config/environments/production.rb, deploy/clowdapp.yaml
=> fix(CloudWatch): RHINENG-1973 parametrize logstream name in clowdapp

spec/api/v2/openapi.rb, swagger/v2/openapi.json
=> feat(OpenAPI): put a temporary warning about development into docs

deploy/clowdapp.yaml
=> fix(Clowder): RHINENG-6790 adjust default value for ssg import ls

app/controllers/concerns/v2/authentication.rb, spec/controllers/v2/concerns/rendering_spec.rb
=> fix(APIv2): RHINENG-8944 semantically correct unauthorized/forbidden

app/models/v2/rule_group.rb, app/models/v2/value_definition.rb, spec/fixtures/files/searchable/rule_groups_controller.yaml, swagger/v2/openapi.json
=> fix(APIv2): RHINENG-9865 adjust sorting for ValueDefs/RuleGroups

app/models/v2/system.rb
Account should be accessible via the `org_id` only
=> cleanup(remodel): RHINENG-1986 hide the account column on systems

app/graphql/schema.rb, app/jobs/parse_report_job.rb, app/models/rule_result.rb, config/application.rb, test/controllers/concerns/exception_notifier_custom_data_test.rb, test/controllers/v1/profiles_controller_test.rb, test/controllers/v1/value_definitions_controller_test.rb, test/services/concerns/xccdf/benchmarks_test.rb, test/services/concerns/xccdf/profile_os_minor_versions_test.rb, test/services/concerns/xccdf/profile_rules_test.rb, test/services/concerns/xccdf/profiles_test.rb, test/services/concerns/xccdf/rule_group_relationships_test.rb, test/services/concerns/xccdf/rule_groups_test.rb, test/services/concerns/xccdf/rule_references_containers_test.rb, test/services/concerns/xccdf/rules_test.rb, test/services/concerns/xccdf/test_result_test.rb, test/services/concerns/xccdf/value_definitions_test.rb
=> chore(rails): use 7.1 rails configuration defaults

app/models/v2/policy.rb, spec/controllers/v2/policies_controller_spec.rb
=> fix(APIv2): RHINENG-9985 not_acceptable when policy without params

app/models/v2/policy.rb, spec/controllers/v2/policies_controller_spec.rb
=> fix(APIv2): RHINENG-10010 do not allow duplicate policy creation

.github/workflows/ci.yml, Gemfile.lock
=> chore(deps): update nokogiri

app/controllers/concerns/error_handling.rb
=> fix(APIv2): RHINENG-10049 handle range errors from activerecord

app/controllers/v2/tailorings_controller.rb, app/models/v2/tailoring.rb, app/models/v2/value_definition.rb, app/policies/v2/tailoring_policy.rb, config/routes.rb, spec/api/v2/schemas/tailoring.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/factories/profile.rb, spec/factories/tailoring.rb, spec/factories/value_definition.rb, spec/integration/v2/tailorings_spec.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-10053 value editing on tailorings

.github/workflows/security-scanning-workflow.yml
Enabling the `Platform Security GitHub Workflow` - This workflow provides Red Hat ConsoleDot Teams with a way to scan the containers they create in a convenient, automated, and reliable manner within their GitHub repository. The Platform Security Github Workflow lets teams get security feedback as they open Pull Requests.
REF: https://github.com/RedHatInsights/platform-security-gh-workflow
=> chore(ci): enable platform-security github workflow

spec/spec_helper.rb
=> fix(RSpec): do not truncate diff output with matching

app/models/v2/policy_system.rb, app/models/v2/tailoring.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/factories/tailoring.rb
=> perf(APIv2): RHINENG-10041 make TailoringRule cloning faster

spec/factories/test_result.rb
@romanblanco let this be a lesson to never complicate random number generation unnecessarily 😆 
=> fix(APIv2): simplify score generation for test results

app/models/v2/tailoring.rb, app/serializers/v2/tailoring_serializer.rb, spec/api/v2/schemas/tailoring.rb, spec/controllers/v2/tailorings_controller_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): RHINENG-10239 add security_guide_id field to tailorings

app/controllers/v2/systems_controller.rb
=> cleanup(APIv2): swap a map that should have been an each

app/controllers/concerns/v2/resolver.rb
When joining with multiple parents, sometimes it happens that due to a `through` association more than one parent is joined in a single step of the iteration. This can cause multiple joins with the same association and aliasing them with weird names. These joins might result in duplications, so I am adding a mechanism to prevent them.
We can retrieve a list of already joined associations using the new `already_joined` method that lists not just the directly joined associations coming from `joins_values` but the whole chain of `through` models. Then we can decide to join or not based on this computed list.
=> fix(APIv2): RHINENG-10041 do not join with parents multiple times

.github/workflows/ci.yml
=> chore(CI): update codecov-action to the latest version

Dockerfile
=> fix(Dockerfile): only install postgres from the centos repo

config/routes.rb
=> fix(APIv2): make sure the new API is not enabled when flag unset

app/models/concerns/v2/indexable.rb
=> fix(APIv2): RHINENG-10286 make UUID validation more typesafe

.github/workflows/ci.yml, deploy/clowdapp.yaml, docker-compose.yml
=> RHINENG-10295: enable YJIT in devel/CI + expose it in clowder for parametrization

db/functions/tailorings_insert_v04.sql, db/migrate/20240523140254_update_function_tailorings_insert_to_version_4.rb, db/schema.rb
@LightOfHeaven1994 should fix the duplication of policies issue on the frontend, but you have to delete existing policies (again).
=> fix(APIv2): RHINENG-10299 set the external field on new tailorings

app/models/v2/report.rb, app/models/v2/report_system.rb, app/serializers/v2/report_serializer.rb, db/migrate/20240528141213_create_report_systems.rb, db/migrate/20240528151651_drop_reports.rb, db/schema.rb, db/views/report_systems_v01.sql, spec/api/v2/schemas/report.rb, spec/controllers/v2/reports_controller_spec.rb, spec/factories/report.rb, spec/fixtures/files/searchable/reports_controller.yaml, swagger/v2/openapi.json
We needed a few changes for the reports model, because the systems underneath should include the ones without test results:
* Dropped the reports view, we will use the policies table instead
* Created a filter to show reports that have test results (for frontend)
* Renamed `assigned_systems` to `systems` 
* Renamed `systems` to `reported_systems`
* Introduced the `report_systems` view
* Renamed `result_system_count` to `reported_system_count`
* Moved the aggregation tests into their own contexts
* Adjusted some documentation in the openapi.json
=> refactor(APIv2): remodel around reports without test results

app/serializers/v2/supported_profile_serializer.rb, db/migrate/20240529122815_update_supported_profiles_to_version_2.rb, db/schema.rb, db/views/supported_profiles_v02.sql, spec/api/v2/schemas/supported_profile.rb, spec/api/v2/schemas/tailoring_file.rb, spec/controllers/v2/supported_profiles_controller_spec.rb, spec/integration/v2/policies_spec.rb, spec/integration/v2/profiles_spec.rb, spec/integration/v2/reports_spec.rb, spec/integration/v2/rule_groups_spec.rb, spec/integration/v2/rules_spec.rb, spec/integration/v2/security_guides_spec.rb, spec/integration/v2/systems_spec.rb, spec/integration/v2/tailorings_spec.rb, spec/integration/v2/value_definitions_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): RHINENG-10366 semantic review adjustments

app/models/v2/system.rb, app/models/v2/test_result.rb, app/serializers/v2/system_serializer.rb, config/routes.rb, spec/api/v2/schemas/system.rb, spec/controllers/v2/systems_controller_spec.rb, spec/integration/v2/systems_spec.rb, swagger/v2/openapi.json
There are 3 fields that don't work yet and will be addressed separately:
* compliant
* failed_rule_count
* last_scanned
=> feat(APIv2): RHINENG-8340 implement systems endpoint under reports

app/models/v2/rule_result.rb, app/models/v2/system.rb, app/models/v2/test_result.rb
=> feat(APIv2): RHINENG-1986 introduce the V2::RuleResult model

app/services/concerns/xccdf/profile_os_minor_versions.rb
=> fix(SSG): RHINENG-9543 determing BM version from openscap object

app/models/supported_ssg.rb, app/services/concerns/xccdf/profile_os_minor_versions.rb
=> fix(SSG): RHINENG-9543 invalidate cache when importing ssgs

spec/integration/v2/systems_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): adjust operationId for reports/:id/systems/:id

Dockerfile
=> fix(Dockerfile): install postgres from Copr

spec/controllers/v2/policies_controller_spec.rb, spec/controllers/v2/security_guides_controller_spec.rb, spec/controllers/v2/supported_profiles_controller_spec.rb, spec/controllers/v2/systems_controller_spec.rb
=> remove: remove unnecessary let

app/models/v2/system.rb, db/functions/v2_test_results_insert_v01.sql, db/migrate/20240603084200_update_v2_test_results_to_version_3.rb, db/migrate/20240604142831_create_function_v2_test_results_insert.rb, db/migrate/20240604142901_create_trigger_v2_test_results_insert.rb, db/schema.rb, db/triggers/v2_test_results_insert_v01.sql, db/views/v2_test_results_v03.sql
=> feat(APIv2): RHINENG-1986 bind report_id to test_results

app/models/v2/report.rb
=> fix(APIv2): RHINENG-10549 do not allow sorting reports by hostcount

Dockerfile
=> fix(bundle): always use system libffi when bundle installing

.github/workflows/ruby-update.yml
=> fix(CI): adjust ruby-setup to use the system ffi

spec/api/v2/schemas/tailoring_file.rb, swagger/v2/tailoring_schema.json
=> fix(test): allow offline fallback for retrieving tailoring schema

app/controllers/v2/reports_controller.rb, app/models/v2/report.rb, app/policies/v2/report_policy.rb, config/routes.rb, db/functions/v2_test_results_delete_v01.sql, db/migrate/20240607103320_create_function_v2_test_results_delete.rb, db/migrate/20240607103908_create_trigger_v2_test_results_delete.rb, db/schema.rb, db/triggers/v2_test_results_delete_v01.sql, spec/controllers/v2/reports_controller_spec.rb, spec/integration/v2/reports_spec.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-10190 implement DELETE action on Reports endpoint

Gemfile.lock
=> chore(deps): update bundler

.github/workflows/ruby-update.yml
=> fix(CI): move bundler env vars one level up

app/controllers/v2/policies_controller.rb, app/controllers/v2/reports_controller.rb, app/models/v2/policy.rb, app/models/v2/report.rb, spec/controllers/v2/policies_controller_spec.rb
=> fix(APIv2): RHINENG-10538 allow policy deletion with associations

app/controllers/concerns/v2/resolver.rb, app/controllers/v2/test_results_controller.rb, app/models/v2/system.rb, app/models/v2/test_result.rb, app/policies/v2/test_result_policy.rb, app/serializers/v2/application_serializer.rb, app/serializers/v2/system_serializer.rb, app/serializers/v2/test_result_serializer.rb, config/routes.rb, spec/api/v2/schemas.rb, spec/api/v2/schemas/system.rb, spec/api/v2/schemas/test_result.rb, spec/controllers/v2/concerns/searchable_spec.rb, spec/controllers/v2/concerns/sortable_spec.rb, spec/controllers/v2/systems_controller_spec.rb, spec/controllers/v2/test_results_controller_spec.rb, spec/factories/system.rb, spec/factories/test_result.rb, spec/fixtures/files/searchable/systems_controller.yaml, spec/fixtures/files/searchable/test_results_controller.yaml, spec/fixtures/files/sortable/systems_controller.yaml, spec/fixtures/files/sortable/test_results_controller.yaml, spec/integration/v2/systems_spec.rb, spec/integration/v2/test_results_spec.rb, spec/policies/v2/system_policy_spec.rb, spec/policies/v2/test_result_policy_spec.rb, spec/spec_helper.rb, swagger/v1/openapi.json, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-10812 test result endpoint under reports

.github/workflows/ci.yml
=> fix(CI): update codecov uploader to 4.5.0

Dockerfile, deploy/clowdapp.yaml
=> chore(deps): use postgresql 16 for development/ephemeral

app/models/v2/historical_test_result.rb, app/models/v2/report.rb, app/models/v2/rule_result.rb, app/models/v2/test_result.rb, db/migrate/20240621074849_create_historical_test_results.rb, db/migrate/20240621074926_update_v2_test_results_to_version_4.rb, db/migrate/20240621081235_create_trigger_historical_test_results_delete.rb, db/schema.rb, db/triggers/historical_test_results_delete_v01.sql, db/views/historical_test_results_v01.sql, db/views/v2_test_results_v04.sql
The `V2::TestResult` model now returns only what `::TestResult.latest` is returning and the rest of test results are available under `V2::HistoricalTestResults`. For now we don't have multiple test results for a single tailoring/system combo, but the codebase always allowed it. 
This should allow us in the future to compare historical test results in a similar fashion as Drift does with system profiles.
=> feat(APIv2): RHINENG-1986 branch out historical test results

.github/workflows/ci.yml
https://github.com/containers/podman-compose/issues/980
=> fix(CI): downgrade podman-compose to compensate for a bug

deploy/clowdapp.yaml
=> feat(metrics): RHINENG-10929 add failed_rules to the floorplan

app/controllers/application_controller.rb, app/controllers/graphql_controller.rb
=> fix(metrics): RHINENG-11009 ensure path tag is empty for apiv1/gql

app/controllers/v2/systems_controller.rb, app/models/v2/policy.rb, app/models/v2/policy_system.rb, spec/controllers/v2/policies_controller_spec.rb, spec/controllers/v2/systems_controller_spec.rb
=> feat(APIv2): RHINENG-283 allow the creation of sibling policies

config/routes.rb, spec/api/v2/schemas/report.rb, spec/controllers/v2/reports_controller_spec.rb, spec/factories/report.rb, spec/fixtures/files/searchable/reports_controller.yaml, spec/fixtures/files/sortable/reports_controller.yaml, spec/integration/v2/reports_spec.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-11150 expose reports under systems endpoint

app/models/v2/test_result.rb, spec/controllers/v2/concerns/searchable_spec.rb, spec/controllers/v2/test_results_controller_spec.rb, spec/fixtures/files/searchable/test_results_controller.yaml, spec/spec_helper.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-11151 test results searchable by system_id

app/controllers/v2/rule_results_controller.rb, app/models/v2/rule.rb, app/models/v2/rule_result.rb, app/policies/v2/rule_result_policy.rb, app/serializers/v2/rule_result_serializer.rb, config/routes.rb, db/functions/v2_rules_update_v02.sql, db/migrate/20240703064538_update_function_v2_rules_update_to_version_2.rb, db/schema.rb, spec/api/v2/schemas.rb, spec/api/v2/schemas/rule_result.rb, spec/controllers/v2/rule_results_controller_spec.rb, spec/factories/policy.rb, spec/factories/rule_result.rb, spec/fixtures/files/searchable/rule_results_controller.yaml, spec/fixtures/files/sortable/rule_results_controller.yaml, spec/integration/v2/rule_results_spec.rb, spec/policies/v2/rule_result_policy_spec.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-8773 introduce the rule results endpoint

spec/integration/v2/reports_spec.rb
=> fix(OpenAPI): clarify DELETE report action

app/models/v2/system.rb, app/models/v2/test_result.rb, spec/fixtures/files/searchable/systems_controller.yaml, spec/fixtures/files/searchable/test_results_controller.yaml, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-10811 filtering systems by group_name

app/controllers/v2/reports_controller.rb, app/models/v2/report.rb, app/policies/v2/report_policy.rb, config/routes.rb, spec/api/v2/schemas.rb, spec/api/v2/schemas/report_stats.rb, spec/controllers/v2/reports_controller_spec.rb, spec/integration/v2/reports_spec.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-8784 expose top_failed_rules under reports

spec/api/v2/schemas/report_stats.rb, spec/integration/v2/policies_spec.rb, spec/integration/v2/reports_spec.rb, spec/integration/v2/tailorings_spec.rb, spec/integration/v2/value_definitions_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): semantic adjustments to the OpenAPI spec

README.md
=> docs(README): additional arguments for exemplary command

Gemfile.lock
=> chore(deps): bump rexml to 3.3.2

.github/workflows/ci.yml
=> fix(CI): call docker-compose using the new syntax

config/routes.rb
=> cleanup(routes): make the route configuration look nicer

app/models/v2/report.rb
=> fix(APIv2): RHINENG-8784 sort top_failed_rules by severity

app/controllers/v2/security_guides_controller.rb, app/controllers/v2/systems_controller.rb, app/models/v2/security_guide.rb, app/models/v2/system.rb, app/policies/v2/security_guide_policy.rb, app/policies/v2/system_policy.rb, config/routes.rb, spec/integration/v2/security_guides_spec.rb, spec/integration/v2/systems_spec.rb, spec/models/v2/security_guide_spec.rb, spec/models/v2/system_spec.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-11779 expose os_versions on systems/SGs

app/models/v2/report.rb, app/serializers/v2/report_serializer.rb, spec/controllers/v2/reports_controller_spec.rb, spec/fixtures/files/sortable/reports_controller.yaml, spec/integration/v2/reports_spec.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-10187 sorting reports by compliant percentage

app/controllers/v2/reports_controller.rb, app/controllers/v2/test_results_controller.rb, app/models/v2/report.rb, app/models/v2/system.rb, app/models/v2/test_result.rb, app/policies/test_result_policy.rb, app/policies/v2/report_policy.rb, app/policies/v2/test_result_policy.rb, app/serializers/v2/system_serializer.rb, config/routes.rb, spec/integration/v2/reports_spec.rb, spec/integration/v2/test_results_spec.rb, spec/models/v2/report_spec.rb, spec/models/v2/test_result_spec.rb, swagger/v2/openapi.json
Depends on: https://github.com/RedHatInsights/compliance-backend/pull/2178
=> feat(APIv2): RHINENG-11779 additional os_versions endpoints

app/models/profile.rb
=> fix(Policy): RHINENG-283 relax the validation for multipolicy

app/models/v2/system.rb, spec/fixtures/files/searchable/systems_controller.yaml, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-11984 allow filtering systems by profile_ref_ids

app/models/v2/system.rb
=> fix(APIv2): RHINENG-11984 swap conditions for safer checks

app/models/v2/security_guide.rb, spec/fixtures/files/searchable/security_guides_controller.yaml, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-11982 search SSGs by profile_ref_id and os_minor

spec/factories/rule.rb, swagger/v2/openapi.json
=> fix(CI): eliminate randomness in rule reference factories for rswag

spec/controllers/v2/concerns/paginable_spec.rb
Without thist, RSpec tests take 45 minutes ... expecting less.
=> test(paginable): run fewer tests for pagination+offsets in APIv2

app/models/v2/system.rb, spec/fixtures/files/searchable/systems_controller.yaml, swagger/v2/openapi.json
=> fix(APIv2): RHINENG-11984 search should be a singular field

app/models/v2/test_result.rb, spec/factories/test_result.rb, spec/fixtures/files/searchable/test_results_controller.yaml, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-11773 filter failed rules by severity

app/controllers/v2/application_controller.rb, config/routes.rb, deploy/clowdapp.yaml
=> feat(APIv2): RHINENG-10949 selective enablement of APIv2 in prod

app/controllers/concerns/v2/collection.rb, app/models/concerns/v2/merge_with_alias.rb, app/policies/v2/policy_policy.rb, app/policies/v2/report_policy.rb, app/policies/v2/tailoring_policy.rb, app/policies/v2/test_result_policy.rb, spec/controllers/v2/policies_controller_spec.rb, spec/controllers/v2/systems_controller_spec.rb
=> fix(APIv2): RHINENG-12169 adjusting merge_with_alias and scoping around inventory groups

spec/integration/v2/reports_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): correct prefix for os_versions under reports in OpenAPI

db/functions/tailorings_insert_v06.sql, db/migrate/20240902073047_update_tailorings_to_version_3.rb, db/migrate/20240903073330_update_function_tailorings_insert_to_version_6.rb, db/schema.rb, db/views/tailorings_v03.sql, spec/controllers/v2/concerns/indexable_spec.rb, spec/controllers/v2/systems_controller_spec.rb
=> fix(APIv2): RHINENG-12255 return correct type for os_minor_version

app/serializers/v2/test_result_serializer.rb, config/initializers/oj.rb, spec/api/v2/schemas/test_result.rb, spec/controllers/v2/test_results_controller_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): adds score to test results

app/models/v2/report.rb, spec/api/v2/schemas/report_stats.rb, spec/api/v2/schemas/rule.rb, swagger/v2/openapi.json
=> fix(APIv2): add missing fields to report stats and to OpenAPI

db/functions/v2_rules_insert_v02.sql, db/migrate/20240904141834_update_function_v2_rules_insert_to_version_2.rb, db/schema.rb
Tested on the current stage/prod dataset using: 
```
SELECT ref_id, slug FROM rules WHERE lower(regexp_replace(ref_id, '\.', '-', 'g')) != slug;
```
=> feat(ModelV2): store slug when inserting into the v2_rules view

dashboards/grafana-dashboard-insights-compliance-general.template.yaml
Upgrades (some) charts to new Timeseries.
Fixes RDS data source.
Moves two processing related charts from Business Metrics to main dashboard area.
=> fix(grafana): upgrade charts and fix RDS source

app/models/v2/profile.rb, app/models/v2/rule.rb
=> fix(indexable): RHINENG-12365 safe navigation when converting IDs

app/models/v2/report.rb
=> fix(APIv2): RHINENG-11772 search restriction for reports/systems

app/models/v2/system.rb, spec/fixtures/files/searchable/systems_controller.yaml, spec/integration/v2/systems_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): RHINENG-11772 restrict assigned_or_scanned search

Dockerfile
=> revert(Dockerfile): RHINENG-12526 go back to UBI9 as the base image

Jenkinsfile, README.md
=> feat(ephemeral): RHINENG-11553 enable trusted resource configuration

Gemfile.lock
=> chore(deps): RHINENG-12656 update puma

spec/integration/v2/systems_spec.rb, spec/swagger_helper.rb, swagger/v2/openapi.json
=> feat(APIv2): add tagging parameter to systems listing endpoint

app/models/v2/report.rb
=> fix(APIv2): RHINENG-13048 scope down rules to a single report

app/controllers/concerns/v2/parameter_handling.rb, app/controllers/concerns/v2/rendering.rb, spec/controllers/v2/concerns/rendering_spec.rb, spec/integration/v2/policies_spec.rb, spec/integration/v2/profiles_spec.rb, spec/integration/v2/reports_spec.rb, spec/integration/v2/rule_groups_spec.rb, spec/integration/v2/rule_results_spec.rb, spec/integration/v2/rules_spec.rb, spec/integration/v2/security_guides_spec.rb, spec/integration/v2/supported_profiles_spec.rb, spec/integration/v2/systems_spec.rb, spec/integration/v2/tailorings_spec.rb, spec/integration/v2/test_results_spec.rb, spec/integration/v2/value_definitions_spec.rb, spec/swagger_helper.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-12138 allow returning collections with IDs only

.syft.yaml
=> fix(konflux): workaround syft configuration for cachi2 and konflux

spec/api/v2/schemas/test_result.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-12395 provide timestamp of last scan for system

deploy/clowdapp.yaml
=> feat(konflux): set the image parameter to pull from konflux quay

app/controllers/v2/test_results_controller.rb
=> fix(APIv2): adjust RBAC roles for viewing test results

app/controllers/v2/rule_results_controller.rb
=> fix(APIv2): corrected permission for reading rule result

app/controllers/v2/tailorings_controller.rb, app/models/v2/tailoring.rb, config/routes.rb, spec/api/v2/schemas.rb, spec/api/v2/schemas/tailoring.rb, spec/controllers/v2/tailorings_controller_spec.rb, spec/integration/v2/tailorings_spec.rb, swagger/v2/openapi.json
This is a feature that ImageBuilder requested, they need to be able to create "empty" policies without systems.
=> feat(APIv2): RHINENG-13307 create tailorings via API explicitly

.github/workflows/ci.yml
=> fix(CI): Use pipx instead of pip

.github/workflows/checkimage.yaml
=> feat(CI): enable automatic updates for container base image

.github/workflows/checkimage.yaml
=> fix(CI): checkimage workflow to fetch the correct Digest

app/models/v2/fix.rb, app/models/v2/rule.rb, app/services/concerns/xccdf/fixes.rb, app/services/concerns/xccdf/util.rb, db/migrate/20241014100839_create_fixes.rb, db/schema.rb
=> feat(V2): import fixes for rules into our models

deploy/clowdapp.yaml
=> fix(deploy): set the IMAGE_DIGEST parameter on clowdapp

deploy/clowdapp.yaml
=> fix(clowdapp): remove unnecessary template parameter

deploy/clowdapp.yaml, entrypoint.sh, lib/tasks/db.rake
=> feat(DB): RHINENG-13738 reindex the database on a daily basis

spec/swagger_helper.rb, swagger/v2/openapi.json
=> fix(snyk): make snyk happy about false-positive error

.tekton/compliance-backend-pull-request.yaml, .tekton/compliance-backend-push.yaml
=> feat(konflux): update buildah to support subscriptions

Dockerfile
Do not merge before Monday's konflux update PR that it has to be rebased against -> will make it green.
=> revert(Dockerfile): RHINENG-13916 roll back to UBI8

app/models/v2/application_record.rb, app/models/v2/rule_result.rb, app/models/v2/system.rb, app/models/v2/test_result.rb, spec/fixtures/files/searchable/systems_controller.yaml, spec/fixtures/files/sortable/systems_controller.yaml, swagger/v2/openapi.json
=> feat(APIv2): allow sorting/searching systems by whole os_version

docker-compose.yml
=> fix(compose): adjust build-rails-db to check for DB existence

app/models/v2/policy.rb, app/models/v2/profile.rb, app/models/v2/report.rb, app/models/v2/rule.rb, app/models/v2/rule_group.rb, app/models/v2/rule_result.rb, app/models/v2/security_guide.rb, app/models/v2/system.rb, app/models/v2/test_result.rb, app/models/v2/value_definition.rb, spec/fixtures/files/searchable/policies_controller.yaml, spec/fixtures/files/searchable/profiles_controller.yaml, spec/fixtures/files/searchable/reports_controller.yaml, spec/fixtures/files/searchable/rule_groups_controller.yaml, spec/fixtures/files/searchable/rule_results_controller.yaml, spec/fixtures/files/searchable/rules_controller.yaml, spec/fixtures/files/searchable/security_guides_controller.yaml, spec/fixtures/files/searchable/systems_controller.yaml, spec/fixtures/files/searchable/test_results_controller.yaml, spec/fixtures/files/searchable/value_definitions_controller.yaml, swagger/v2/openapi.json
All searches should use the `^ (1 2 3)` form!
=> fix(APIv2): RHINENG-13974 drop unnecessary IN/NOTIN searches and make the rest consistent

app/models/v2/supported_profile.rb, spec/fixtures/files/searchable/supported_profiles_controller.yaml, swagger/v2/openapi.json
=> feat(APIv2): add search for supported_profiles by ref_id and title

.tekton/compliance-backend-pull-request.yaml, .tekton/compliance-backend-push.yaml
=> feat(konflux): add new mandatory RPM signature scan task to tekton

app/models/v2/report.rb, spec/fixtures/files/searchable/reports_controller.yaml, swagger/v2/openapi.json
=> feat(RHINENG-14055): Ability to filter Reports by percent_compliant

app/models/v2/security_guide.rb, spec/fixtures/files/searchable/security_guides_controller.yaml, swagger/v2/openapi.json
=> fix(APIv2): introduce searching security guides by supported_profile

app/controllers/v2/test_results_controller.rb, app/models/v2/test_result.rb, app/policies/v2/test_result_policy.rb, config/routes.rb, spec/integration/v2/test_results_spec.rb, swagger/v2/openapi.json
=> feat(APIv2): RHINENG-14053 expose ssg_versions on TestResults

app/controllers/concerns/tag_filtering.rb, app/models/v2/system.rb, app/models/v2/test_result.rb, spec/controllers/v2/test_results_controller_spec.rb, spec/integration/v2/test_results_spec.rb, swagger/v2/openapi.json
=> feat(V2): RHINENG-14034 filter test_results by tags

deploy/clowdapp.yaml
=> revert(konflux): use non-konflux image for deployment

app/controllers/concerns/v2/collection.rb, app/models/v2/rule_result.rb, app/serializers/v2/rule_result_serializer.rb, app/serializers/v2/rule_serializer.rb, spec/api/v2/schemas/rule.rb, spec/api/v2/schemas/rule_result.rb, spec/controllers/v2/rule_results_controller_spec.rb, spec/controllers/v2/rules_controller_spec.rb, spec/fixtures/files/searchable/rule_results_controller.yaml, swagger/v2/openapi.json
Exposing rule_group_id on both rules and rule results + making rule results searchable by it.
=> feat(APIv2): RHINENG-14356 allow RR filtering by rule_group_id

.github/workflows/ci.yml
=> fix(CI): update codecov in github actions to latest

Gemfile.lock
=> chore(deps): update bundler version

spec/api/v2/schemas/tailoring.rb, swagger/v2/openapi.json
=> fix(APIv2): RHINENG-14418 correct use of 'require' attribute

spec/integration/v2/profiles_spec.rb, spec/integration/v2/tailorings_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): mark discouraged endpoints as deprecated 

app/controllers/v2/application_controller.rb, app/models/profile.rb, deploy/clowdapp.yaml
=> feat(APIv2): RHINENG-12245 enable APIv2 for everyone

Jenkinsfile
=> Add stage for running floorist tests

app/models/v2/rule_result.rb, spec/integration/v2/rule_results_spec.rb, swagger/v2/openapi.json
=> fix(APIv2): RHINENG-14554 exclude remediation_available from searchable attributes

test/factories/host.rb
=> dev(seeds): adjust table name for inventory in development for seeding

.github/workflows/checkimage.yaml, .github/workflows/ruby-update.yml
Separate branches for each job should fix overlapping updates done by GH Actions.
=> fix(Actions): separate update branches

README.md
=> docs(APIv2): update reference to openapi.json

deploy/clowdapp.yaml
This should collect data in such format:
```
org_id | system | updated_at
org_id1 | system1 | timestamp1
org_id1 | system2 | timestamp2
org_id2 | system3 | timestamp3
```
=> feat(floorist): add HMS metrics for tested systems

deploy/clowdapp.yaml
=> fix(Floorist): deduplicate resource

config/application.rb
=> cleanup(GraphQL): remove GraphiQL related configuration

deploy/clowdapp.yaml
=> feat(floorist): add HMS metrics for assigned systems

Dockerfile
=> chore(Dockerfile): RHINENG-12549 upgrade base image to ubi9-minimal

.github/CODEOWNERS, renovate.json
This has been already implemented for all interact-team FE repos and works fine. Konflux PRs are automerged if only hash updated & all pipelines are green on PR
=> ci(Konflux): add konflux automerge (hash update)

.github/workflows/ci.yml, spec/api/v2/openapi.rb, spec/integration/v2/rule_groups_spec.rb, swagger/v2/openapi.json
https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/
=> ci(OpenAPI): RHINENG-15553 use GH action to test OpenAPI spec

app/controllers/v1/application_controller.rb, test/controllers/v1/benchmarks_controller_test.rb, test/controllers/v1/rule_results_controller_test.rb, test/controllers/v1/rules_controller_test.rb, test/controllers/v1/supported_ssgs_controller_test.rb, test/controllers/v1/systems_controller_test.rb, test/controllers/v1/value_definitions_controller_test.rb
=> docs(API): RHINENG-15809 announce APIv1 deprecation

Gemfile, Gemfile.lock
=> chore(deps): bump cgi, uri, nokogiri

deploy/clowdapp.yaml
=> fix(floorist): change to a distinct prefix

.commitlint.yml
=> ci(image): add image as an option in commitlint scope

app/models/v2/test_result.rb, app/serializers/v2/test_result_serializer.rb, spec/controllers/v2/test_results_controller_spec.rb, swagger/v2/openapi.json
This reverts commit db5640f342653951894437922f1159a44ccc4d5a.
=> revert(API): RHINENG-16382 provide SSG ID for Test Result

spec/integration/v2/rule_results_spec.rb, swagger/v2/openapi.json
=> docs(OpenAPI): RHINENG-16728 generate Rule Results example data

app/models/v2/test_result.rb, app/serializers/v2/test_result_serializer.rb, spec/controllers/v2/test_results_controller_spec.rb, swagger/v2/openapi.json
This reverts commit 378641e0f415ad6cbb5c8ff694c4f4b675b95e46.
The security_guide_id would need to be introduced to other models for consistency, adding unnecessary information to the API
=> revert(API): RHINENG-16382 remove SSG ID for Test Result

.commitlint.yml
=> ci(Kafka): add Kafka to commitlint scope

dashboards/grafana-dashboard-insights-compliance-general.template.yaml
=> ci(metrics): update datasourses

.tekton/compliance-backend-pull-request.yaml, .tekton/compliance-backend-push.yaml
https://issues.redhat.com/browse/KONFLUX-2264
Created using: 
https://github.com/simonbaird/konflux-pipeline-patcher/blob/main/specific-one-liners.md#sast-unicode-and-shell-check-tasks
=> feat(CI): RHINENG-16913 add shell and unicode sast pipeline tasks

app/models/v2/rule.rb, app/models/v2/rule_result.rb, app/serializers/v2/rule_result_serializer.rb, app/serializers/v2/rule_serializer.rb, spec/api/v2/schemas/rule.rb, spec/api/v2/schemas/rule_result.rb, spec/controllers/v2/rules_controller_spec.rb, spec/models/v2/rule_spec.rb, swagger/v2/openapi.json
=> feat(API): RHINENG-17591 expand remediation_issue_id

karafka.rb
=> fix(Kafka): setting initial offset as latest

app/consumers/application_consumer.rb, config/initializers/sidekiq.rb
=> fix(Kafka): increase retry to 3

app/producers/application_producer.rb
=> fix(Kafka): use all Kafka brokers

app/producers/application_producer.rb, karafka.rb
https://karafka.io/docs/WaterDrop-Getting-Started/ suggests to use Karafka, as it integrates WaterDrop automatically
=> fix(Kafka): use Karafka for producing

Jenkinsfile
taking back changes from f4a59b4773e23fb68fd01ca100f8cfdf0737f904 that temporarily increased IQE timeout
=> ci: decrease IQE timeout to 30 minutes

karafka.rb
=> fix(Kafka): set consumer group for inventory topic

dashboards/grafana-dashboard-insights-compliance-general.template.yaml
=> fix(Grafana): migrate to new Kafka lag metric

renovate.json
Low priority but might cause issues later.
=> fix(Renovate): RHINENG-18233 remove extension of base config

config/initializers/yabeda.rb
=> fix(metrics): run yabeda in a karafka context

app/consumers/inventory_events_consumer.rb, app/services/kafka/policy_system_importer.rb, spec/consumers/inventory_events_consumer_spec.rb, spec/services/kafka/policy_system_importer_spec.rb
=> fix(Kafka): RHINENG-18765 import updated systems also
