- Gemfile
- app/controllers/profiles_controller.rb
- config/initializers/cors.rb
- config/routes.rb
- test/controllers/profiles_controller_test.rb
This is just a way of exposing all profiles in an API endpoint that is
consumable by the frontend.
> Simplest example of Profile API

- README.md
- openshift/templates/compliance/_cfg.yml
- openshift/templates/compliance/compliance-backend.yml
Additional information in README about openshift deployment. Added `_cfg.yml`.
> Updated README

- .travis.yml
- Gemfile
- Gemfile.lock
- app/consumers/application_consumer.rb
- app/consumers/compliance_reports_consumer.rb
- app/jobs/parse_report_job.rb
- app/services/host_inventory_api.rb
- app/services/xccdf_report_parser.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/test.yml
- test/fixtures/users.yml
- test/models/rule_test.rb
- test/services/xccdf_report_parser_test.rb
Needs https://github.com/RedHatInsights/insights-host-inventory/
> Basic Host Inventory integration

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
- test/test_helper.rb
Codecov shows the coverage of the repo. I followed their guides, but it's not clear why it shows the coverage only for 5 files https://codecov.io/gh/quarckster/compliance-backend/branch/codecov.
> Added codecov

- app/controllers/profiles_controller.rb
- app/models/policy.rb
- app/models/profile.rb
- app/models/rule.rb
- app/serializers/profile_serializer.rb
- test/models/profile_test.rb
- test/models/rule_result_test.rb
To be merged after https://github.com/RedHatInsights/compliance-backend/pull/17/files
This is meant to compute compliance levels for a host/profile so that we can expose it on the API
> Compute compliance score for a profile

- Jenkinsfile
- openshift/Jenkins/Dockerfile
~Requires https://github.com/RedHatInsights/insights-pipeline-lib/pull/2~ Ready to merge.
> Optimized build of the jenkins slave

- Jenkinsfile
- README.md
- spec/spec_helper.rb
- test/test_helper.rb
* added codecov badge;
* removed redundant simplecov calls;
* coverage reports are uploaded to codecov only if the codecov token is provided.
> Codecov integration

- openshift/Jenkins/Dockerfile
Used custom `BUNDLER_PATH` with correct permissions.
> Fixed bundler permissions

- Jenkinsfile
- README.md
- app/models/profile.rb
- app/policies/rule_policy.rb
- app/serializers/profile_serializer.rb
- app/serializers/rule_serializer.rb
- app/services/concerns/xccdf_report/profiles.rb
- lib/tasks/test.rake
Without this, when it runs 'rake test', it wipes the development database
unless ran with RAILS_ENV=test
> Move validate to test namespace

- app/models/profile.rb
Before this change was implemented, retrieving the results for a profile
(RuleResults), resulted on N+1 queries. I needed to get the most recent
result every time, which meant checking each result individually. This
can be achieved with the postgres rank() function very easily, whereas I
don't think ActiveRecord provides anything else to do it.
To reproduce this, upload 10 reports, say with 500 rules each. You'll
notice retrieving 5000 rules and checking for the latest one takes a
long time using the N+1 queries method, around 20 seconds whereas this
does it in around 20ms on my machine.
> Improve retrieval performance for RuleResults

- .gitignore
- Dockerfile
- Gemfile
- Jenkinsfile
- README.md
- config/database.yml.example
- docker-compose.yml
- entrypoint.sh
~I'd like some help with the following issues:~
- ~Racecar can't communicate with kafka running in insights-upload for some reason. I'm not sure if we need to define a network or something.~
- ~Right now there are no volume mounts for the database, as I was hitting selinux issues when mounting with `-v /tmp/db:/var/lib/postgresql/data:Z`. This means you get a fresh DB every time you bring the services down and back up.~
> Add docker-compose for devel w/ postgres

- openshift/templates/compliance-backend.yml
Added simple httpGet health checks for compliance api backend.
> Added health checks for compliance backend

- Gemfile
- Gemfile.lock
- app/models/schema.rb
- config/initializers/config.rb
- config/initializers/prometheus.rb
- config/puma.rb
- config/racecar.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/production.yml
- lib/graphql_collector.rb
- openshift/templates/compliance-prometheus-exporter.yaml
Do NOT merge until we actually have a pod running `prometheus_exporter` to which we can connect.
> Prometheus instrumentation

- codecov.yml
- test/controllers/systems_controller_test.rb
This PR should significantly increase the reported test coverage.
> Add some systems_controller tests. Ignore coverage on the schema

- Gemfile
- Gemfile.lock
- config/application.rb
- config/initializers/sidekiq.rb
- config/settings.yml
- config/settings/development.yml
- docker-compose.yml
- openshift/templates/compliance-redis.yaml
- openshift/templates/compliance-sidekiq.yaml
This reverts commit c7a5929ff55070ab3104bf2dec48a59da9f3a347. It should
not be an issue to get this back again as long as we send the report
directly through the job, instead of the filepath.
> Return to Sidekiq

- test/controllers/rule_results_controller_test.rb
- test/controllers/rules_controller_test.rb
- test/services/csv_exporter_test.rb
Towards https://projects.engineering.redhat.com/browse/RHICOMPL-21
> Increase coverage, fix rubocop warning

- test/services/concerns/xccdf_report/profiles_test.rb
- test/services/concerns/xccdf_report/xml_report_test.rb
Towards https://projects.engineering.redhat.com/browse/RHICOMPL-21
> Add tests for xccdf report concerns

- app/models/profile.rb
- app/models/schema.rb
- app/policies/profile_policy.rb
- config/routes.rb
- db/migrate/20190322232315_add_compliance_threshold_to_profiles.rb
- test/models/profile_test.rb
https://github.com/RedHatInsights/compliance-frontend/pull/101
> Mutation for compliance_threshold for profiles

- Gemfile
- Gemfile.lock
- brakeman_output.markdown
- lib/tasks/brakeman.rake
- lib/tasks/test.rake
I also alphabetized the Gemfile development groups. I'm not sure if we should commit the brakeman_output.* files. We can also provide a previous output to compare results to.
> Towards RHICOMPL-13: Add brakeman

- app/controllers/application_controller.rb
- app/controllers/concerns/metadata.rb
- app/controllers/concerns/pagination.rb
- app/controllers/concerns/search.rb
- app/controllers/profiles_controller.rb
- app/controllers/rule_results_controller.rb
- app/controllers/rules_controller.rb
- app/controllers/systems_controller.rb
- app/models/profile.rb
- app/policies/rule_result_policy.rb
- test/controllers/concerns/metadata_test.rb
- test/controllers/rule_results_controller_test.rb
- test/controllers/rules_controller_test.rb
- test/controllers/systems_controller_test.rb
- test/test_helper.rb
Depends on https://github.com/RedHatInsights/compliance-backend/pull/93
> IPP 12 - Change per-page/page to limit/offset and add links 

- app/models/host.rb
- app/models/policy.rb
- app/models/profile.rb
- app/models/rule_result.rb
- app/serializers/rule_result_serializer.rb
- spec/integration/profiles_spec.rb
- spec/integration/rule_results_spec.rb
- spec/integration/rules_spec.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
- test/controllers/systems_controller_test.rb
- test/fixtures/hosts.yml
- test/fixtures/rule_results.yml
- test/fixtures/rules.yml
Depends on : 
https://github.com/RedHatInsights/compliance-backend/pull/94/files
https://github.com/RedHatInsights/compliance-backend/pull/93/files
> IPP 12 - Add Rule and RuleResult to Swagger

- app/models/concerns/system_like.rb
- app/models/host.rb
- app/models/schema.rb
- test/models/host_test.rb
Tests missing, meant to be used in the filter: https://github.com/RedHatInsights/compliance-backend/pull/103/files
> Add search by compliance and score

- app/models/host.rb
- app/models/profile_host.rb
- test/models/profile_host_test.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-134
> Fixes RHICOMPL-134: Delete the profile if it has no hosts

- config/environments/production.rb
Aims to make sidekiq perform better.
> Log level set to info for production

- app/services/image_scanner.rb
- test/fixtures/imagestreams.yml
- test/fixtures/openshift_connections.yml
- test/services/image_scanner_test.rb
This class represents the most uncovered lines of any file [at 41](https://codecov.io/gh/RedHatInsights/compliance-backend/src/master/app/services/image_scanner.rb).
> Test the image_scanner

- app/services/xccdf_report_parser.rb
This partially reverts https://github.com/RedHatInsights/compliance-backend/pull/136/
> Don't use insights_id as the host id

- app/services/xccdf_report_parser.rb
Metadata from insights-upload should contain ID. We should save our hosts with the same ID, if available.
> Set new host ID to metadata ID

- Jenkinsfile
This issue breaks default pipeline behavior https://github.com/RedHatInsights/insights-pipeline-lib/issues/22
> Workaround for incorrect withStatusContext behavior

- app/consumers/inventory_events_consumer.rb
- app/jobs/delete_host.rb
- config/settings.yml
- test/consumers/inventory_events_consumer_test.rb
https://github.com/RedHatInsights/s2i-insights-compliance/pull/12
>  RHICOMPL-181 - Delete hosts when notified by the inventory 

- app/jobs/delete_host.rb
We should handle errors as well as possible.
> Handle missing host on delete

- app/controllers/concerns/metadata.rb
- test/controllers/concerns/metadata_test.rb
[RHICOMPL-212](https://projects.engineering.redhat.com/browse/RHICOMPL-212)
> Fixes RHICOMPL-212: properly calculate last page

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- app/graphql/types/rule.rb
- app/graphql/types/rule_identifier.rb
- app/graphql/types/rule_reference.rb
- app/models/rule.rb
- test/fixtures/rule_identifiers.yml
- test/fixtures/rule_references.yml
- test/graphql/queries/rule_query_test.rb
- test/models/rule_test.rb
Built on top of https://github.com/RedHatInsights/compliance-backend/pull/171
Towards https://redhatmbu.aha.io/epics/COMP-E-99
>  Add rule identifiers/references to graphql schema

- app/services/xccdf_report_parser.rb
- test/services/xccdf_report_parser_test.rb
First try at fixing/handling https://projects.engineering.redhat.com/browse/RHICOMPL-221
> Update host name when changed in inventory

- app/jobs/parse_report_job.rb
We experienced problems with jobs taking an indefinite amount of time to run in QA. In this case, killing the job will not work, as our reliable queue will make it run until it fails 3 times (killing the pod is not a fail). I had to go to redis directly and clear the job queue. 
Instead, we can just mark the job as cancelled, and not run it in such case - as recommended on Sidekiq's guide - https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-cancel-a-sidekiq-job
> Cancellable job interface

- app/graphql/schema.rb
> Increase graphql timeout to 20 seconds

- app/jobs/parse_report_job.rb
- app/services/xccdf_report_parser.rb
- test/services/xccdf_report_parser_test.rb
In draft for now, needs testing.
> RHICOMPL-321 - Block import of xccdf.xml reports

- swagger/v1/openapi.v3.yaml
- Fix API paths
- Add missing parameters to spec
- Add missing object type
> Fix OpenAPI v3 paths spec.

- app/jobs/migrate_xccdf_reports_job.rb
- app/services/xccdf_report_migration.rb
- config/initializers/sidekiq.rb
- lib/tasks/fix_xccdf_reports.rake
- test/services/xccdf_report_migration_test.rb
Run with noop with `NOOP=true rake fix_xccdf_reports`
> RHICOMPL-364 - Migrate broken report ref IDs

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- app/models/concerns/system_like.rb
- app/models/profile.rb
- app/serializers/rule_serializer.rb
@akofink, @dLobatog  please check
> fix stable branch conflicts

- db/migrate/20190924171312_add_benchmark_id_to_profile.rb
- db/migrate/20190924171409_add_benchmark_id_to_rule.rb
- db/migrate/20190924173755_delete_policies.rb
> Add a phony default benchmark to profiles + rules

- app/services/concerns/xccdf/hosts.rb
- app/services/host_inventory_api.rb
- app/services/xccdf_report_parser.rb
- test/services/host_inventory_api_test.rb
- test/services/xccdf_report_parser_test.rb
Kind of a big oversight on my part :see_no_evil:
> Sync with inventory on import

- Jenkinsfile
Adapting pipeline to use insights-pipeline v3 library.
> Update Jenkinsfile for insights-pipeline-lib v3

- app/models/profile.rb
- test/models/profile_test.rb
Draft for now as I'm writing tests and checking other parts of the parser that can be improved.
> Add parsed host to pre-existing profile in account

- .env
- app/controllers/concerns/metadata.rb
- config/environments/development.rb
- config/initializers/rswag-ui.rb
- config/routes.rb
Mounted at both /api and /r/insights/platform
> Mount compliance app at both prefixes

- Jenkinsfile
@bsquizz could you please take a look?
> Fail when critical steps fail

- app/services/xccdf_report_parser.rb
> [RHICOMPL-442] - Validate XCCDF vs DS by benchmark ID

- app/services/concerns/xccdf/hosts.rb
- app/services/concerns/xccdf/rule_results.rb
- app/services/concerns/xccdf/util.rb
- app/services/xccdf_report_parser.rb
- test/fixtures/hosts.yml
- test/services/concerns/xccdf/hosts_test.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-444
> [RHICOMPL-444] - Handle tailored test result parsing

- config/application.rb
Related to https://github.com/RedHatInsights/compliance-backend/pull/282
> Re-enable sprockets in devel

- Gemfile
- Gemfile.lock
- app/graphql/types/profile.rb
- app/graphql/types/rule.rb
- app/graphql/types/system.rb
- app/models/host.rb
- app/models/profile.rb
- app/models/rule.rb
- app/models/rule_result.rb
- app/models/test_result.rb
- app/serializers/rule_result_serializer.rb
- app/services/concerns/xccdf/rule_results.rb
- app/services/concerns/xccdf/test_result.rb
- app/services/concerns/xccdf/util.rb
- app/services/xccdf_report_migration.rb
- db/migrate/20191126180559_create_test_results.rb
- db/migrate/20191126181009_seed_test_results.rb
- db/migrate/20191203091219_remove_time_fields_from_rule_results.rb
- test/fixtures/test_results.yml
- test/graphql/queries/profile_query_test.rb
- test/graphql/queries/rule_query_test.rb
- test/graphql/queries/system_query_test.rb
- test/models/host_test.rb
- test/models/profile_test.rb
- test/models/rule_test.rb
- test/models/test_result_test.rb
- test/policies/rule_result_policy_test.rb
- test/services/concerns/xccdf/hosts_test.rb
- test/services/xccdf_report_migration_test.rb
Still in draft - basically https://github.com/RedHatInsights/compliance-backend/pull/274 but without the graphql batching
> RHICOMPL-398 - Add TestResult model and migration

- app/models/rule.rb
- app/policies/rule_policy.rb
To search, you may use `api/compliance/rules?search=reference=4.3.3.5.4`
> RHICOMPL-420 - Add references, identifier to Rules scoped_search

- app/controllers/concerns/authentication.rb
- app/services/rbac_api.rb
- config/settings.yml
- spec/swagger_helper.rb
- test/controllers/concerns/authentication_test.rb
The SETTINGS__DISABLE_RBAC disables RBAC after this change
> Disable RBAC based on ENV variable

- Jenkinsfile
- Remove `rbac`, add new services from platform refactoring
> Update services to be deployed for Smoke tests

- app/graphql/mutations/profile/create.rb
- test/graphql/mutations/create_profile_mutation_test.rb
Towards https://projects.engineering.redhat.com/browse/RHICOMPL-308
> Populate parent profile on profile create mutation

- app/services/host_inventory_api.rb
Related to https://projects.engineering.redhat.com/browse/RHCLOUD-3824
> Add required culling params for inventory API

- app/graphql/mutations/profile/delete.rb
- app/graphql/schema.graphql
- app/jobs/delete_test_results_job.rb
- app/models/profile.rb
- test/graphql/mutations/delete_profile_mutation_test.rb
- test/jobs/delete_test_results_job_test.rb
See https://github.com/RedHatInsights/compliance-frontend/pull/392 for the UI part that uses this.
> Remove destructive dependency and remove results only optionally

- app/graphql/mutations/base_mutation.rb
- app/graphql/mutations/profile/associate_systems.rb
- app/graphql/mutations/system/associate_profiles.rb
- test/graphql/mutations/associate_profiles_test.rb
For usage with https://github.com/RedHatInsights/compliance-frontend/pull/395
> Create host if not exists on host-profile association

- app/serializers/profile_serializer.rb
> Add parent_profile_id to profiles serializer

- app/controllers/profiles_controller.rb
Follow-up from https://github.com/RedHatInsights/compliance-backend/pull/342#discussion_r387641448
> Use Pundit scope in profiles controller

- app/serializers/profile_serializer.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-506
> Add canonical and tailored to the profiles API

- app/models/rule.rb
- app/policies/rule_policy.rb
- test/models/rule_test.rb
- test/policies/rule_policy_test.rb
> Allow users to view rules from canonical profiles

- app/graphql/mutations/base_mutation.rb
- app/jobs/parse_report_job.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/host_inventory_api.rb
- app/services/xccdf_report_parser.rb
- test/services/host_inventory_api_test.rb
- test/services/reports_tar_reader_test.rb
- test/services/xccdf_report_parser_test.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-499
> Enforce metadata[fqdn] and ID presence in message

- app/graphql/schema.graphql
- app/graphql/types/query.rb
- app/graphql/types/system.rb
- app/graphql/types/test_result.rb
This is a very early version that definitely needs work.
> Add test result graphql endpoint

- app/graphql/schema.graphql
- app/graphql/types/concerns/test_results.rb
- app/graphql/types/profile.rb
We should _never_ be calculating score ourselves. We don't know how to do it (NIST 7275 r.4, section 7.3.2 Scoring Models), and we're not NIST certified.
https://projects.engineering.redhat.com/browse/RHICOMPL-515
> Profile graphql returns score

- db/migrate/20191126181009_seed_test_results.rb
* Batch size is down to 30 as it seems to be the fastest I found by manually trying different values on Openshift, it runs on underpowered pods, but the value isn't really important. 
* Host and Profile tables are not called anymore, instead we use host_id
and profile_id directly.
* TestResult inserts are wrapped in a transaction to avoid:
```
BEGIN
insert into ...
COMMIT
... repeat for as many TestResult objects as needed
```
instead we do
```
BEGIN
insert into ...
insert into ...
insert into ...
insert into ...
COMMIT
```
which is more performant and just as safe as everything is already
wrapped by an upper level nested transaction as it's a migration.
* Also I added a counter to keep track of how many HostProfile objects
are left and measure the progress.
> Performance improvements to SeedTestResults migration

- app/models/business_objective.rb
- app/policies/business_objective_policy.rb
BusinessObjective queries should be _much_ faster now.
https://projects.engineering.redhat.com/browse/RHICOMPL-434
> Use SQL only for BO pundit policy

- app/controllers/concerns/authentication.rb
- test/controllers/concerns/authentication_test.rb
Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-560
> Remove user requrement in identity header (#385)

- db/migrate/20200414143250_add_external_to_profiles.rb
> Add external to profiles

- app/jobs/destroy_profiles_job.rb
- app/models/concerns/profile_policy_association.rb
- app/models/profile.rb
- test/models/profile_test.rb
> Destroy all profiles in a policy on policy destroy

- lib/tasks/import_datastream.rake
> Task to import supported SSG benchmarks

- spec/integration/benchmarks_spec.rb
- spec/integration/profiles_spec.rb
- spec/integration/rules_spec.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
- test/fixtures/benchmarks.yml
- test/test_helper.rb
> Add benchmark REST API docs

- app/serializers/profile_serializer.rb
This information will be useful to the client for tailored policies.
> Profiles API returns parent_profile_ref_id

- app/controllers/concerns/authentication.rb
- test/controllers/concerns/authentication_test.rb
Towards https://projects.engineering.redhat.com/browse/RHICOMPL-640
UI changes are also needed.
> RBAC failure results in 403, not 401

- app/models/concerns/profile_policy_association.rb
- config/settings.yml
- db/migrate/20200106134953_add_unique_index_to_benchmarks.rb
- db/migrate/20200325185540_add_unique_index_to_profiles.rb
> Only delete policy_profiles for non-canonical profiles

- app/models/rule_result.rb
- app/services/concerns/xccdf/rule_results.rb
- test/services/xccdf_report_parser_test.rb
> [stable] Adjust rule result pass/fail determination (#451)

- Dockerfile
> Bump devel Dockerfile to Ruby 2.6

- app/consumers/inventory_events_consumer.rb
- app/controllers/concerns/exception_notifier_custom_data.rb
- app/jobs/concerns/record_not_found.rb
- app/jobs/delete_host.rb
- app/jobs/inventory_host_updated_job.rb
- app/services/openshift_environment.rb
- test/consumers/inventory_events_consumer_test.rb
- test/controllers/concerns/exception_notifier_custom_data_test.rb
- test/jobs/delete_host_test.rb
- test/jobs/inventory_host_updated_job_test.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-631
> RHICOMPL-631 in stable

- app/services/concerns/xccdf/test_result.rb
- test/services/concerns/xccdf/test_result_test.rb
Fixes https://projects.engineering.redhat.com/browse/RHICOMPL-634
> Delete old test results when new ones are saved (#467)

- app/controllers/concerns/authentication.rb
- test/controllers/concerns/authentication_test.rb
The two endpoints so far we need to allow via cert based auth are
profiles#index and profiles#tailoring_file. Cert based auth may contain
system information but does not contain user informatoin, so this should
be a good check to use to detect cert vs. user auth.
> Skip RBAC for certain endpoints with cert based auth

- app/controllers/application_controller.rb
- app/controllers/concerns/rendering.rb
- app/controllers/profiles_controller.rb
- app/models/concerns/profile_searching.rb
- app/models/profile.rb
- app/serializers/parent_profile_serializer.rb
- app/serializers/profile_serializer.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
- test/models/profile_test.rb
Separated from https://github.com/RedHatInsights/compliance-backend/pull/410 to ease reviewing.
- Adds relationships to API response
- Allows side-loaded includes of all related resources
- Allows searching profiles by `canonical`
> Fully implement V1 profiles#index

- Gemfile
- Gemfile.lock
- spec/integration/benchmarks_spec.rb
- spec/integration/profiles_spec.rb
- spec/integration/rule_results_spec.rb
- spec/integration/rules_spec.rb
- spec/integration/systems_spec.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
rswag seems to generate the examples incorrectly :( Here's a docker-based openapi validator:
```
docker run -it --rm -v $(pwd):/project:z -w /project usabillabv/openapi3-validator swagger/v1/openapi.json
```
Here's a ruby based validator before:
```rb
[37] pry(main)> Openapi3Parser.load_file('./compliance-backend/swagger/v1/openapi.json').errors.errors.map { |e| e.inspect }
=> ["Openapi3Parser::Validation::Error(message: Missing required fields: openapi, context: #/, for_type: Openapi)",
"Openapi3Parser::Validation::Error(message: Unexpected fields: swagger and definitions, context: #/, for_type: Openapi)",
"Openapi3Parser::Validation::Error(message: Unexpected fields: consumes and produces, context: #/paths/%2Fapi%2Fcompliance%2Fbenchmarks/get, for_type: Operation)", …
```
> Begin conforming to openapi 3.0.3

- app/models/profile.rb
- app/serializers/profile_serializer.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
Profiles response looks like this:
```json
{
"data": {
"business_objective": "Foo",
"canonical": false,
"compliance_threshold": 100.0,
"compliant_host_count": 0,
"description": "The HIPAA Security Rule establishes U.S. national standards to protect individuals’\nelectronic personal health information that is created, received, used, or\nmaintained by a covered entity. The Security Rule requires appropriate\nadministrative, physical and technical safeguards to ensure the\nconfidentiality, integrity, and security of electronic protected health\ninformation.\n\nThis profile configures Red Hat Enterprise Linux 7 to the HIPAA Security\nRule identified for securing of electronic protected health information.",
"external": true,
"name": "Health Insurance Portability and …
```
> Add os_major_version to the profile schema

- app/controllers/v1/profiles_controller.rb
- spec/integration/profiles_spec.rb
- spec/swagger_helper.rb
- swagger/v1/openapi.json
This adds the ability to include relationships to profiles#show
Also added: a `ref_spec` helper method. I, for one, make mistakes like `'#ref' => 'foo'` all the time (as opposed to `'$ref' => 'foo'`). Look for a refactoring PR for other resources soon.
```json
$ http https://ci.foo.redhat.com:1337/api/compliance/profiles/e8c1675a-49a0-4ac6-aa60-b58508a5c0d6 include=='benchmark'
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Requested-With,content-type
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Origin: *
cache-control: max-age=0, private, must-revalidate
connection: close
content-type: application/vnd.api+json
date: Thu, 04 Jun 2020 15:48:33 GMT
etag: W/"2dd482f37a7b094ecc980931ec865005" …
```
> profiles#show uses render_json helper

- app/controllers/concerns/authentication.rb
- app/models/identity_header.rb
- test/controllers/concerns/authentication_test.rb
- test/models/identity_header_test.rb
> [stable] Check auth_type directly in the identity to determine cert auth (#486)

- app/services/rbac_api.rb
- test/services/rbac_api_test.rb
> [stable] Handle RBAC errors appropriately by returning 403

- app/controllers/v1/business_objectives_controller.rb
- app/models/account.rb
- app/serializers/business_objective_serializer.rb
- config/routes.rb
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/business_objectives.rb
- spec/integration/business_objectives_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/business_objectives_controller_test.rb
- test/controllers/v1/profiles_controller_test.rb
- test/models/account_test.rb
- test/test_helper.rb
```js
GET /api/compliance/business_objectives
{
"data": [
{
"title": "China"
},
"id": "5b661819-3ecd-4597-9c98-e7e5e0f6ca23",
"relationships": {
"profiles": {
"data": [
{
"id": "3ad85c18-6339-4e87-ace5-44625cd1b172",
"type": "profile"
}
]
}
},
"type": "business_objective"
},
{
"title": "Foo"
},
"id": "00577e90-63ff-4e7f-8238-867f879a8605",
"relationships": {
"profiles": {
"data": [
{
"id": "35774cad-0c1b-4139-b6c7-012109798981",
"type": "profile"
}
]
}
},
"type": "business_objective"
}
],
"links": {
"first": "/api/compliance/business_objectives?limit=10&offset=1",
"last": "/api/compliance/business_objectives?limit=10&offset=1"
},
"meta": {
"limit": 10,
"offset": 1,
"search": null,
"total": 2
}
}
```
> Add business_objectives V1 API for index and show

- app/controllers/application_controller.rb
- app/controllers/v1/profiles_controller.rb
- app/models/profile.rb
- config/routes.rb
- spec/integration/profiles_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/profiles_controller_test.rb
- test/models/profile_test.rb
`PATCH profiles/<uuid>`
```js
{
"data": {
"name": "My updated tailored profile",
"compliance_threshold": 90
},
"relationships": {
"rules": {
"data": [
{
"id": "cc9afa66-3536-4d2e-bc8e-10111d13ec50",
"type": "rule"
}
]
}
}
}
}
```
> Allow updating profiles

- app/models/application_record.rb
- app/models/rule_reference.rb
- app/models/rule_references_rule.rb
- app/services/concerns/xccdf/rule_references.rb
- app/services/concerns/xccdf/rule_references_rules.rb
- app/services/concerns/xccdf/test_result.rb
- test/models/rule_reference_test.rb
- test/services/concerns/xccdf/rule_references_rules_test.rb
- test/services/concerns/xccdf/rule_references_test.rb
> [stable] [RHICOMPL-698] Improve parsing performance

- Gemfile.lock
See https://github.com/codecov/codecov-ruby#deprecation-warning
> Update codecov to latest version

- app/jobs/parse_report_job.rb
- app/models/application_record.rb
- app/models/concerns/profile_policy_association.rb
- app/models/profile.rb
- db/migrate/20200804012906_add_uniqueness_by_external_to_profiles.rb
- db/schema.rb
- test/graphql/mutations/associate_profiles_test.rb
- test/models/profile_test.rb
> Allow profiles to differ only by in/external

- app/controllers/concerns/inventory_service_helper.rb
- app/controllers/v1/profiles_controller.rb
- app/graphql/mutations/base_mutation.rb
- app/graphql/mutations/profile/associate_systems.rb
- app/graphql/mutations/system/associate_profiles.rb
- config/racecar.rb
- spec/integration/profiles_spec.rb
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/mutations/associate_systems_test.rb
[RHICOMPL-827](https://projects.engineering.redhat.com/browse/RHICOMPL-827) Add 'compliance' kafka group prefix
[RHICOMPL-467](https://projects.engineering.redhat.com/browse/RHICOMPL-467) Consolidate REST and graphql inventory logic
:no_smoking:
> [RHICOMPL-827][RHICOMPL-467][stable]

- app/graphql/mutations/profile/edit.rb
- app/graphql/schema.graphql
Required for https://github.com/RedHatInsights/compliance-frontend/pull/685
> [RHICOMPL-742] Allow editing the profile description

- app/controllers/concerns/inventory_service_helper.rb
- app/jobs/inventory_host_updated_job.rb
- app/jobs/parse_report_job.rb
- app/models/application_record.rb
- app/models/concerns/profile_policy_association.rb
- app/models/host.rb
- app/models/profile.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/remediations_api.rb
- config/initializers/exception_notification.rb
- db/migrate/20200804012906_add_uniqueness_by_external_to_profiles.rb
- db/schema.rb
- lib/tasks/import_datastream.rake
- lib/tasks/sync_with_inventory.rake
- test/graphql/mutations/associate_profiles_test.rb
- test/models/host_test.rb
- test/models/profile_test.rb
- test/services/remediations_api_test.rb
- test/tasks/import_datastream_test.rb
- test/tasks/sync_with_inventory_test.rb
https://projects.engineering.redhat.com/browse/RHICOMPL-652
https://projects.engineering.redhat.com/browse/RHICOMPL-574
:no_smoking:
> [stable][RHICOMPL-652][RHICOMPL-574]

- README.md
Adds list of dependent services and a list of components. Updates dev setup.
> [RHICOMPL-888] README: Document architecture and update dev setup

- README.md
- app/graphql/schema.rb
- app/services/openshift_environment.rb
- config/initializers/prometheus.rb
- config/initializers/sidekiq.rb
- config/puma.rb
- config/settings/test.yml
When developing the Prometheus is most of the time not needed.
(RHICOMPL-869)
> [RHICOMPL-869] Connect to Prometheus only when the hostname is configured

- app/producers/application_producer.rb
- app/producers/payload_tracker.rb
- test/producers/payload_tracker_test.rb
Refactoring of Kafka producer to allow creation of more producers.
Preparation for RHICOMPL-759.
> [RHICOMPL-759] Refactor: Kafka producer to common one

- app/producers/application_producer.rb
- app/producers/payload_tracker.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/host_inventory_api.rb
- app/services/platform.rb
- config/settings/development.yml
- docker-compose.yml
- test/producers/payload_tracker_test.rb
https://issues.redhat.com/browse/RHICOMPL-904
https://issues.redhat.com/browse/RHICOMPL-922
> [RHICOMPL-904][RHICOMPL-922] push to stable

- app/consumers/inventory_events_consumer.rb
- app/producers/payload_tracker.rb
- app/producers/remediation_updates.rb
- config/settings.yml
- test/consumers/inventory_events_consumer_test.rb
Refactored settings for Kafka topics configuration to section of consumers/subscriptions and producers. Made the consumers to use their respective settings.
> [RHICOMPL-944] Configurable Kafka Producer Topics

- README.md
> [RHICOMPL-922] Document use of platform basic auth in dev env

- app/consumers/inventory_events_consumer.rb
- app/jobs/parse_report_job.rb
- app/models/concerns/rule_remediation.rb
- app/models/rule.rb
- app/producers/payload_tracker.rb
- app/producers/remediation_updates.rb
- app/serializers/benchmark_serializer.rb
- app/services/concerns/xccdf/rule_results.rb
- app/services/remediations_api.rb
- config/settings.yml
- docker-compose.yml
- spec/api/v1/schemas/benchmarks.rb
- swagger/v1/openapi.json
- test/consumers/inventory_events_consumer_test.rb
- test/jobs/parse_report_job_test.rb
- test/producers/remediation_updates_test.rb
- test/services/xccdf_report_parser_test.rb
See https://issues.redhat.com/browse/RHICOMPL-946
:no_smoking:
> [RHICOMPL-759][RHICOMPL-840][RHICOMPL-944][RHICOMPL-946][stable]

- README.md
- app/jobs/parse_report_job.rb
- app/models/concerns/rule_remediation.rb
- app/services/remediations_api.rb
- test/models/rule_test.rb
> [RHICOMPL-965][RHICOMPL-922][stable]

- lib/tasks/import_remediations.rake
- test/tasks/import_remediations_test.rb
> [RHICOMPL-465] Do not swallow exceptions in import_remediations

- lib/tasks/import_remediations.rake
- test/tasks/import_remediations_test.rb
> [RHICOMPL-465][stable] Do not swallow exceptions in import_remediations (#586)

- config/supported_ssg.yaml
Initial configuration of SSG support matrix.
> [RHICOMPL-901] Store SSG and RHEL minor release support matrix

- lib/tasks/sync_with_inventory.rake
- test/tasks/sync_with_inventory_test.rb
> [RHICOMPL-994] Rescue inventory server errors on host sync

- app/jobs/parse_report_job.rb
- app/models/concerns/rule_remediation.rb
- app/models/profile.rb
- app/models/profile_host.rb
- app/services/remediations_api.rb
- config/supported_ssg.yaml
- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
- lib/tasks/sync_with_inventory.rake
- test/models/profile_host_test.rb
- test/models/profile_test.rb
- test/models/rule_test.rb
- test/tasks/sync_with_inventory_test.rb
> [stable][RHICOMPL-901][RHICOMPL-987][RHICOMPL-991][RHICOMPL-994]

- docker-compose.yml
> [RHICOMPL-996] Dev: fix DB mount point in docker-compose

- app/controllers/v1/supported_ssgs_controller.rb
- app/jobs/parse_report_job.rb
- app/models/supported_ssg.rb
- app/models/xccdf/benchmark.rb
- app/serializers/supported_ssg_serializer.rb
- app/services/concerns/xccdf/util.rb
- app/services/xccdf_report_parser.rb
- config/routes.rb
- docker-compose.yml
- spec/api/v1/schemas.rb
- spec/api/v1/schemas/supported_ssgs.rb
- spec/integration/supported_ssgs_spec.rb
- swagger/v1/openapi.json
- test/controllers/v1/supported_ssgs_controller_test.rb
- test/fixtures/files/xccdf_report.xml
- test/models/supported_ssg_test.rb
- test/services/xccdf_report_parser_test.rb
https://issues.redhat.com/browse/RHICOMPL-1016
:no_smoking:
> [stable][RHICOMPL-927][RHICOMPL-544][RHICOMPL-1006][RHICOMPL-996][RHICOMPL-1016]

- db/migrate/20200910153704_create_policies_and_policy_profiles.rb
- db/schema.rb
Shuffle indices, and add profile-policy reference
> [RHICOMPL-1040] Create policies, policy_hosts tables

- app/graphql/types/profile.rb
- app/models/concerns/profile_policy_association.rb
- test/controllers/concerns/metadata_test.rb
- test/controllers/v1/profiles_controller_test.rb
This PR is for the RHICOMPL-661 branch.
> [RHICOMPL-661] Cleanup, reduce test changes

- app/controllers/application_controller.rb
- app/controllers/concerns/default_headers.rb
- app/graphql/schema.graphql
- app/graphql/types/concerns/profile_pseudo_policy.rb
- app/graphql/types/profile.rb
- app/graphql/types/system.rb
- app/models/concerns/profile_policy_association.rb
- app/models/host.rb
- app/models/policy.rb
- app/serializers/host_serializer.rb
- test/controllers/concerns/default_headers_test.rb
- test/graphql/queries/profile_query_test.rb
- test/graphql/queries/system_query_test.rb
- test/models/host_test.rb
RHICOMPL-1037
RHICOMPL-1062
RHICOMPL-1035
RHICOMPL-1053
RHICOMPL-1063
:no_smoking:
> [stable] Align stable to master

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- test/graphql/queries/profile_query_test.rb
A shortcut to retrieving benchmark's version.
> [RHICOMPL-1060] Expose ssgVersion for the Profile GraphQL type

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- test/graphql/queries/profile_query_test.rb
A shortcut to retrieving benchmark's version.
> [stable][RHICOMPL-1060] Expose ssgVersion for the Profile GraphQL type

- app/graphql/mutations/profile/edit.rb
- app/models/concerns/profile_policy_association.rb
- app/models/host.rb
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/mutations/delete_profile_mutation_test.rb
- test/graphql/mutations/edit_policy_mutation_test.rb
- test/models/host_test.rb
- test/models/profile_test.rb
RHICOMPL-1069
RHICOMPL-1074
RHICOMPL-1070
:no_smoking:
> chore: Align stable to master

- app/models/concerns/profile_searching.rb
- test/models/profile_test.rb
`has_policy_test_results` should look up profiles which policy has results, meaning that at least on of policy profile has a test result.
> [RHICOMPL-1036] has_policy_test_results filter on Profile

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- app/models/profile.rb
- app/serializers/profile_serializer.rb
- spec/api/v1/schemas/profiles.rb
- swagger/v1/openapi.json
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/queries/profile_query_test.rb
For graphql and REST
Test with https://github.com/RedHatInsights/compliance-frontend/pull/822
> feat(RHICOMPL-959): Add policy_type attribute to profiles

- app/models/policy.rb
- app/services/copy_profiles_to_policies.rb
- test/models/policy_test.rb
Also ensure profile business objective associations are nullified on
profile to policy copy.
> [RHICOMPL-1093] Fix orphaned BO removal on policy deletion

- lib/tasks/import_datastream.rake
> fix(RHICOMPL-1097): invalidate latest_supported after ssg import

- README.md
> [stable] Sync with master

- app/models/host.rb
This should not affect any behavior
> refactor(RHICOMPL-1091): Delete duplicate test_result_profiles

- app/jobs/parse_report_job.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/xccdf_report_parser.rb
- config/settings.yml
- test/services/xccdf_report_parser_test.rb
> [stable] feat: RHICOMPL-1149 Stop parsing external reports

- app/models/supported_ssg.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/concerns/xccdf/rule_results.rb
- app/services/xccdf_report_parser.rb
- test/services/xccdf_report_parser_test.rb
> Align stable to master

- app/models/concerns/profile_policy_association.rb
- app/models/concerns/profile_searching.rb
- app/models/policy.rb
- app/models/profile.rb
- app/serializers/profile_serializer.rb
- app/services/concerns/xccdf/hosts.rb
- app/services/concerns/xccdf/util.rb
- app/services/copy_profiles_to_policies.rb
- app/services/external_profile_updater.rb
- db/migrate/20201216190051_add_policy_id_foreign_key_on_profiles.rb
- db/migrate/20201222134736_remove_threshold_business_objective_from_profiles.rb
- db/schema.rb
- docker-compose.yml
- spec/api/v1/schemas/profiles.rb
- swagger/v1/openapi.json
- test/graphql/mutations/edit_policy_mutation_test.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
- test/services/concerns/xccdf/hosts_test.rb
- test/services/copy_profiles_to_policies_test.rb
- test/services/external_profile_updater_test.rb
- test/services/xccdf_report_parser_test.rb
RHICOMPL-999
RHICOMPL-1034
RHICOMPL-1045
RHICOMPL-1057
> [stable] Sync with master for 2021-01-06

- app/models/supported_ssg.rb
- config/supported_ssg.yaml
- test/models/supported_ssg_test.rb
- test/services/concerns/xccdf/test_result_test.rb
Allow more than one SSG version/package for OS minor release.  The
pseudo-id has been changed to include package.
> feat(SupportedSsg): RHICOMPL-1320 more than one for OS minor

- lib/tasks/debug.rake
Creates rake task `db:debug` that would print out all subsequent SQL
queries made by other rake tasks in sequence.
> feat(rake): RHICOMPL-1330 debug SQL queries

- app/models/supported_ssg.rb
- config/supported_ssg.yaml
- db/migrate/20210107151954_remove_incorrect_profiles_from_policies.rb
- db/schema.rb
- lib/tasks/debug.rake
- test/models/supported_ssg_test.rb
- test/services/concerns/xccdf/test_result_test.rb
RHICOMPL-1330
RHICOMPL-1320 
:no_smoking:
> [stable] Align stable to master 

- app/models/concerns/profile_hosts.rb
- app/models/policy.rb
- app/models/profile_host.rb
- app/models/test_result.rb
- test/models/test_result_test.rb
> [stable] Sync stable with master

- config/supported_ssg.yaml
> [stable] Align stable with master

- .github/pull_request_template.md
> feat(FedRamp): RHICOMPL-1265 add secure coding checklist

- app/models/concerns/host_searching.rb
- app/models/concerns/system_like.rb
- db/cyndi_setup_test.sql
- spec/api/v1/schemas/hosts.rb
- swagger/v1/openapi.json
- test/models/host_test.rb
- test/services/concerns/xccdf/test_result_test.rb
> fix(Host): RHICOMPL-1415 os version search

- app/graphql/schema.graphql
- app/graphql/types/benchmark.rb
- test/graphql/queries/benchmark_query_test.rb
field is already present on REST API.
> feat(Benchmark): RHICOMPL-1420 add osMajorVersion on GQL response

- app/controllers/concerns/rendering.rb
- app/controllers/v1/systems_controller.rb
- app/graphql/schema.graphql
- app/graphql/types/system.rb
- app/models/host.rb
- app/serializers/host_serializer.rb
- spec/api/v1/schemas/hosts.rb
- swagger/v1/openapi.json
Since we added a search term, it makes sense to also add an attribute so users can know what to expect when using the search.
> feat(Host): RHICOMPL-1397 add has_policy attribute

- db/cyndi_setup_test.sql
TRUNCATE the Cyndi hosts table to be able to reinsert changed values.
> refactor: cyndi test env setup with truncate

- config/routes.rb
> refactor(routes): drop unreachable systems destroy on readonly model

- app/models/concerns/profile_rules.rb
- app/models/policy.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
required for #755 to determine changes for audit logging.
> refactor(models): RHICOMPL-1462 update_rules and update_hosts

- app/controllers/application_controller.rb
- app/controllers/concerns/v1/profile_audit.rb
- app/controllers/v1/profiles_controller.rb
- app/graphql/mutations/base_mutation.rb
- app/graphql/mutations/business_objective/create.rb
- app/graphql/mutations/profile/associate_systems.rb
- app/graphql/mutations/profile/create.rb
- app/graphql/mutations/profile/delete.rb
- app/graphql/mutations/profile/edit.rb
- app/graphql/mutations/system/associate_profiles.rb
- app/graphql/mutations/test_result/delete.rb
- app/models/business_objective.rb
- app/models/concerns/profile_policy_association.rb
- app/models/concerns/profile_rules.rb
- app/models/policy.rb
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/mutations/associate_profiles_test.rb
- test/graphql/mutations/associate_systems_test.rb
- test/graphql/mutations/create_business_objective_mutation_test.rb
- test/graphql/mutations/create_profile_mutation_test.rb
- test/graphql/mutations/delete_profile_mutation_test.rb
- test/graphql/mutations/delete_test_result_mutation_test.rb
- test/graphql/mutations/edit_policy_mutation_test.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
- test/test_helper.rb
**Depends on #759 (first two commits)**
Adds audit logging to mutating REST and GraphQL controllers, including some autoremoval hooks of business objectives and policies.
> feat(logging): RHICOMPL-1219 audit log events in controllers

- app/controllers/application_controller.rb
- app/controllers/concerns/metadata.rb
- app/controllers/concerns/v1/profile_audit.rb
- app/controllers/v1/profiles_controller.rb
- app/graphql/mutations/base_mutation.rb
- app/graphql/mutations/business_objective/create.rb
- app/graphql/mutations/profile/associate_systems.rb
- app/graphql/mutations/profile/create.rb
- app/graphql/mutations/profile/delete.rb
- app/graphql/mutations/profile/edit.rb
- app/graphql/mutations/system/associate_profiles.rb
- app/graphql/mutations/test_result/delete.rb
- app/models/business_objective.rb
- app/models/concerns/profile_policy_association.rb
- app/models/concerns/profile_rules.rb
- app/models/policy.rb
- test/controllers/concerns/metadata_test.rb
- test/controllers/v1/profiles_controller_test.rb
- test/graphql/mutations/associate_profiles_test.rb
- test/graphql/mutations/associate_systems_test.rb
- test/graphql/mutations/create_business_objective_mutation_test.rb
- test/graphql/mutations/create_profile_mutation_test.rb
- test/graphql/mutations/delete_profile_mutation_test.rb
- test/graphql/mutations/delete_test_result_mutation_test.rb
- test/graphql/mutations/edit_policy_mutation_test.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
- test/test_helper.rb
RHICOMPL-1219
RHICOMPL-1462
RHICOMPL-1458
:no_smoking: 
> Bump stable

- docker-compose.yml
This allows the`SETTINGS__PLATFORM_BASIC_AUTH_USERNAME` and `SETTINGS__PLATFORM_BASIC_AUTH_PASSWORD` environment variables mentioned in the README to be consumed from this file.
> devel(compose): consume the .env in the main rails container

- docker-compose.yml
Without hostname defined, one of the audit tests fail:
```
FAIL["test_logs_audit_with_general_evidence_included", #<Minitest::Reporters::Suite:0x0000559f06154ed8 @name="AuditLogWrappedLoggerTest">, 0.14894805600124528]                                                   
test_logs_audit_with_general_evidence_included#AuditLogWrappedLoggerTest (0.15s)                                                                                                                                  
--- expected                                                                                                                                                                                               
+++ actual …
```
> fix(audit): Add hostnames to compose for local audit tests

- app/consumers/concerns/report_parsing.rb
- app/consumers/concerns/validation.rb
- app/consumers/inventory_events_consumer.rb
- app/jobs/delete_host.rb
- test/consumers/inventory_events_consumer_test.rb
Refactoring to plug in auditing within Kafka inventory consumer.
> refactor: RHICOMPL-1474 inventory consumer incl. report download and validation

- app/consumers/concerns/report_parsing.rb
- app/consumers/inventory_events_consumer.rb
- app/jobs/delete_host.rb
- test/consumers/inventory_events_consumer_test.rb
- test/jobs/delete_host_test.rb
> feat(logging): RHICOMPL-1457 audit log consumer events

- lib/audit_log/audit_log/formatter.rb
- test/lib/audit_log/formatter_test.rb
> fix(logging): RHICOMPL-1485 sidekiq context evidence for ver <6

- app/graphql/schema.graphql
- app/graphql/types/profile.rb
- app/models/concerns/profile_searching.rb
- app/models/profile.rb
- app/serializers/profile_serializer.rb
- spec/api/v1/schemas/profiles.rb
- swagger/v1/openapi.json
- test/graphql/queries/profile_query_test.rb
Add os_minor_version and os_version to both GraphQL and REST APIs for
profiles.
~Requires https://github.com/RedHatInsights/compliance-backend/pull/778~ merged
Can be tested with https://github.com/RedHatInsights/insights-core/pull/2971
> feat(APIs): RHICOMPL-1406 add profile os_minor_version

- app/models/host.rb
- app/models/policy.rb
- app/models/policy_host.rb
- app/models/profile.rb
- app/models/supported_ssg.rb
- test/models/host_test.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
Introduced a new method on the Policy model for updating OS versions and integrated it to the `update_hosts`.
> Create policy profiles for each assigned OS minor version

- test/controllers/concerns/authentication_test.rb
> tests(authentication): RHICOMPL-1525 cleare audit context

- app/models/concerns/profile_searching.rb
- app/models/concerns/profile_tailoring.rb
- app/models/profile.rb
> RHICOMPL-1531 Audit log (pre)creation of OS profiles

- app/graphql/schema.graphql
- app/graphql/types/benchmark.rb
- app/models/supported_ssg.rb
- app/models/xccdf/benchmark.rb
- app/serializers/benchmark_serializer.rb
- spec/api/v1/schemas/benchmarks.rb
- swagger/v1/openapi.json
- test/models/benchmark_test.rb
- test/models/supported_ssg_test.rb
Adds `supported_os_minor_versions` to Benchmark APIs.
Filtering is on the way...
> feat(Benchmark): RHICOMPL-1527 add supported_os_minor_versions attribute on APIs

- app/models/concerns/benchmark_searching.rb
- app/models/xccdf/benchmark.rb
- test/models/benchmark_test.rb
Adds scope `supported_os_minor_versions` for `Benchmark` model.
Adds scoped search fitlering `supported_os_minor_version`.
Examples:
```
supported_os_minor_version = 9
supported_os_minor_version ^ (9, 10)
os_major_version = 7 and supported_os_minor_version ^ (8, 9)
```
> feat(Benchmark): RHICOMPL-1538 searching by supported_os_minor_versions

- app/graphql/schema.graphql
- app/graphql/types/benchmark.rb
- app/models/concerns/benchmark_searching.rb
- app/models/xccdf/benchmark.rb
- app/serializers/benchmark_serializer.rb
- spec/api/v1/schemas/benchmarks.rb
- swagger/v1/openapi.json
- test/models/benchmark_test.rb
supported_os_minor_version(s) -> latest_supported_os_minor_version(s)
> refactor(Benchmark): RHICOMPL-1527 rename field

- app/graphql/mutations/profile/associate_rules.rb
- app/graphql/schema.graphql
- test/graphql/mutations/associate_rules_test.rb
> feat(EditPolicy): RHICOMPL-1576 assigning rules via ruleRefIds

- config/settings.yml
> feat(flag): RHICOMPL-1540 enable the feature flag for 133

- config/supported_ssg.yaml
> chore(ssg): RHICOMPL-1539 supported SSG 0.1.54 for RHEL 7.9

- app/models/concerns/profile_fields.rb
- app/models/policy.rb
- app/models/profile.rb
- test/models/policy_test.rb
when they differ by OS minor version.  Fixes RHEL 6 cases where multiple
minor versions share the same SSG.
**Pending tests.**
> fix(Policy): RHICOMPL-1782 creation of same SSG profiles

- db/cyndi_setup_test.sql
Missed from my FactoryBot PR :see_no_evil: 
> fix(CI): RHICOMPL-1853 remove initial hosts from the test db

- config/supported_ssg.yaml
- swagger/v1/openapi.json
```
Archive:  scap-security-guide-0.1.54.zip
inflating: scap-security-guide-0.1.54/ssg-rhel7-ds.xml
inflating: scap-security-guide-0.1.54/ssg-rhel8-ds.xml
...
```
I'm seeing some timeout issues syncing remediations when trying this locally, but it could just be my internet connection to CI.
> feat(SSG): RHICOMPL-1591 Support RHEL 8.4, SSG 0.1.54

- test/models/host_test.rb
> fix(tests): RHICOMPL-1854 escape hosts when searching by name

- db/migrate/20210517182143_add_index_account_number_to_accounts.rb
- db/schema.rb
This is just a normal index for now. We will need to go back and update
it to be a unique index and clean up duplicate accounts. This is an
endeavor to speed up our pundit policies, especially when querying
hosts.
> fix(Account): RHICOMPL-1558 Add index on account_number

- app/models/concerns/benchmark_searching.rb
- app/models/profile.rb
- app/models/supported_ssg.rb
- test/factories/benchmark.rb
- test/graphql/queries/benchmark_query_test.rb
- test/models/benchmark_test.rb
- test/models/profile_test.rb
- test/models/supported_ssg_test.rb
- test/test_helper.rb
> feat(Benchmarks): RHICOMPL-1773 fallback latest from existing

- app/graphql/types/concerns/system_profiles.rb
- app/models/host.rb
> perf(GraphQL): RHICOMPL-1788 preload collections under systems

- Gemfile
- Gemfile.lock
- app/serializers/account_serializer.rb
- app/serializers/benchmark_serializer.rb
- app/serializers/business_objective_serializer.rb
- app/serializers/host_serializer.rb
- app/serializers/profile_serializer.rb
- app/serializers/rule_identifier_serializer.rb
- app/serializers/rule_reference_serializer.rb
- app/serializers/rule_result_serializer.rb
- app/serializers/rule_serializer.rb
- app/serializers/supported_ssg_serializer.rb
- app/serializers/test_result_serializer.rb
> chore(deps): RHICOMPL-1065 replace the JSON serializer

- Dockerfile
> feat(Dockerfile): RHICOMPL-1192 no EPEL needed

- .dockerignore
This should reduce the overall image size a bit.  It adds `.git`, `tmp`
and other folders and files to be ignored on COPY within a container
build.
> feat(build): RHICOMPL-1891 improve dockerignore

- README.md
- build_deploy.sh
- entrypoint.sh
- Fixes a bug using the container engine command within a variable,
refactored to use functions instead
- Add a local build option to run locally without pushing to remote
registy
> fix(build): RHICOMPL-1889 Refactor and bugfix of build_deploy.sh

- build_deploy.sh
> hotfix for small bug on build_deploy

- pr_check.sh
> fix: Make pr_check.sh just pass for now

- config/initializers/exception_notification.rb
Use `https` or otherwise do not use it at all.
> feat(config): RHICOMPL-1245 ensure that https is set on slack_webhook

- config/database.yml
> feat(RHICOMPL-1360): Add clowder config conditional for database config

- app/controllers/v1/benchmarks_controller.rb
- test/controllers/v1/benchmarks_controller_test.rb
> perf(REST): RHICOMPL-1717 allow preloading records for explicit includes

- app/producers/application_producer.rb
- config/racecar.rb
- config/settings.yml
- test/producers/application_producer_test.rb
Builds on top of #867 (merged)
> feat(kafka): RHICOMPL-1893 Kafka SASL authentication 

- config/puma.rb
Signed-off-by: Victor M <vmugicag@redhat.com>
> feat(RHICOMPL-1360): Add Puma webport config with Clowder

- app/controllers/concerns/rendering.rb
- app/controllers/v1/benchmarks_controller.rb
- app/serializers/account_serializer.rb
- app/serializers/application_serializer.rb
- app/serializers/benchmark_serializer.rb
- app/serializers/business_objective_serializer.rb
- app/serializers/host_serializer.rb
- app/serializers/profile_serializer.rb
- app/serializers/rule_identifier_serializer.rb
- app/serializers/rule_reference_serializer.rb
- app/serializers/rule_result_serializer.rb
- app/serializers/rule_serializer.rb
- app/serializers/supported_ssg_serializer.rb
- app/serializers/test_result_serializer.rb
- spec/integration/profiles_spec.rb
> Do not evaluate relationship on included records in REST

- swagger/v1/openapi.json
Missed this from #870, credit goes to @akofink for noticing it :+1: :1st_place_medal: 
> fix(openapi): RHICOMPL-1886 update the openapi.json

- app/services/safe_downloader.rb
- test/services/safe_downloader_test.rb
> feat(audit): RHICOMPL-1408 log report download

- app/services/safe_downloader.rb
- test/services/safe_downloader_test.rb
Check schema of the report download URL to be https/secured in
production.  Fail otherwise.
> feat(reports): RHICOMPL-1236 check download URL

- app/consumers/concerns/report_parsing.rb
- app/services/safe_downloader.rb
- config/settings.yml
- config/settings/production.yml
- test/consumers/inventory_events_consumer_test.rb
- test/services/safe_downloader_test.rb
>  refactor(downloader): RHICOMPL-1912 to download other files

- docker-compose.yml
> Add registry to each image from docker-compose

- deploy/build-deploy-common.sh
> feat(build-deploy-common): Always --pull during build

- deploy/build-deploy-common.sh
The script doesn't halts on login to registry error and it should.
Signed-off-by: Victor M <vmugicag@redhat.com>
> Exits on login error

- app/graphql/types/concerns/system_profiles.rb
- app/models/host.rb
This reverts commit 537527fe69c56b49d795169996d7ea7e38851ffa. 
https://github.com/RedHatInsights/compliance-backend/pull/845
> perf(GraphQL): RHICOMPL-1937 revert preloading under systems

- app/controllers/v1/profiles_controller.rb
- app/jobs/delete_host.rb
- app/models/concerns/profile_policy_scoring.rb
- app/models/profile.rb
- app/models/test_result.rb
- db/migrate/20210609081621_add_score_to_profiles.rb
- db/schema.rb
- test/controllers/v1/profiles_controller_test.rb
- test/jobs/delete_host_test.rb
> RHICOMPL-1899 Sort profiles by their cached score only when they are unsorted

- app/jobs/delete_host.rb
- app/models/concerns/profile_policy_scoring.rb
- app/models/concerns/profile_scoring.rb
- app/models/policy.rb
- app/models/test_result.rb
- db/migrate/20210609114653_add_cached_counts.rb
- db/schema.rb
- test/jobs/delete_host_test.rb
- test/models/policy_test.rb
- test/services/concerns/xccdf/test_result_test.rb
This is just a super naive implementation that somehow works :shrug: :laughing: 
> feat(cache): RHICOMPL-1706 store host count for policies in fields

- clowdapp.yaml
- config/initializers/0_clowder-config.rb
> Fix Clowder config

- app/services/datastream_downloader.rb
- config/settings.yml
- config/settings/development.yml
- docker-compose.yml
- lib/tasks/import_datastream.rake
- test/services/datastream_downloader_test.rb
- test/tasks/import_datastream_test.rb
Adds `DatastreamDownloader` service, that intends to download downstream datastream (ds) files from the
compliance-ssg server from predefined directory/URL structure.
> feat(ssg): RHICOMPL-1594 downstream datastream downloader

- deploy/build-deploy-common.sh
> feat(deploy): improve container registry login

- db/seeds.dev.rb
> fix(seeds): RHICOMPL-1763 move integer conversion one level out

- lib/prometheus/business_collector.rb
- test/lib/prometheus/business_collector_test.rb
> feat(metrics): RHICOMPL-1763 track OS major/minor version counts

- config/puma.rb
This fixes run of puma in devel enviroment.
The library is likely not preloaded.
> fix(puma): require clowder lib in puma config

- config/settings/development.yml
- spec/api/v1/openapi.rb
- spec/api/v1/schemas/hosts.rb
- swagger/v1/openapi.json
Not entirely sure when this needs to be merged :thinking: 
> update(urls): RHICOMPL-1958 replace cloud with console in URLs

- .gitignore
- Dockerfile
- clowdapp.yaml
- config/initializers/0_clowder-config.rb
- config/settings.yml
- deploy/clowder-config-main.sha256
- deploy/get-clowder-common-bash.sh
- devel.json
- entrypoint.sh
To test on ephemeral:
login to the ephemeral environment first via `oc login ...` login command copied from the web UI
Deploy:
``` 
bonfire deploy --no-remove-resources all compliance
```
> feat(clowder) - RHICOMPL-1363 - provide working Clowder template

- clowdapp.yaml
> fix(clowder): use old "backend" name for the service

- docker-compose.yml
@xmicha82 Please try this change to see if it fixes the issue you're facing with minio.
> devel: Include .env as an env_file for docker-compose

- test/graphql/queries/system_query_test.rb
> fix(test): RHICOMPL-2067 adjust tests for test result profiles

- app/graphql/schema.graphql
- app/graphql/types/system.rb
- app/graphql/types/tag.rb
- test/graphql/queries/system_query_test.rb
@bastilian FYI ths is how you can do it from the frontend:
```
{
systems {
edges {
node {
id
name
tags {
namespace
key
value
}
}
}
}
}
```
> feat(GraphQL): RHICOMPL-2038 expose tags on systems

- Jenkinsfile
- openshift/Jenkins/slave_pod_template.yaml
Naive temporary fix for Jenkins unit tests.
> build: RHICOMPL-2073 fix Jenkins unit test run

- spec/integration/systems_spec.rb
- swagger/v1/openapi.json
> fix(openapi): RHICOMPL-2075 fix swagger/openapi for tagging

- .rubocop.yml
- lib/prometheus/business_collector.rb
- lib/prometheus/engineering_collector.rb
> devel(rubocop): Ignore prometheus collectors

- lib/prometheus/business_collector.rb
- test/lib/prometheus/business_collector_test.rb
> feat(metrics): RHICOMPL-2049 track accounts with big policies

- lib/prometheus/business_collector.rb
See https://prometheus.io/docs/concepts/metric_types/#counter
> fix(metrics): RHICOMPL-1763 s/Counter/Gauge/ for systems_by_os

- lib/prometheus/business_collector.rb
- test/lib/prometheus/business_collector_test.rb
> fix(metrics): RHICOMPL-2088 calculate policies correctly

- lib/prometheus/business_collector.rb
- test/lib/prometheus/business_collector_test.rb
> feat(metrics): RHICOMPL-2050 gauge for measuring huge policies

- app/controllers/concerns/metadata.rb
- test/controllers/concerns/metadata_test.rb
> fix(metadata): RHICOMPL-2093 include tags in the metadata when set

- lib/prometheus/business_collector.rb
- test/lib/prometheus/business_collector_test.rb
> feat(metrics): RHICOMPL-2056 count policies by OS major version

- README.md
> docs(README): seeding data

- README.md
Feel free to contribute. I'll keep updating this as I'm trying this stuff out.
> docs: ephemeral deployment via bonfire

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
This should fix colliding UID and permalinking.
> fix(grafana): RHICOMPL-2104 unique id

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
This is me shooting in the dark, kinda :see_no_evil:
> feat(grafana): RHICOMPL-2054 uploaded reports per month

- app/controllers/concerns/pagination.rb
- test/controllers/concerns/metadata_test.rb
handling of limits equal to or below zero
> fix: RHICOMPL-1849 controller fix for limits <= 0 

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
:see_no_evil: my bad :see_no_evil:
> fix(grafana): RHICOMPL-2138 add missing comma to the configmap

- app/services/duplicate_account_resolver.rb
- db/migrate/20210809071351_deduplicate_accounts.rb
- db/schema.rb
- test/services/duplicate_account_resolver_test.rb
:thinking: not sure how to test this as the migration runs first and will not allow me to create non-unique accounts :thinking: we should reconsider to use rspec for migration tests that would support testing the up/down calls directly
> feat(db): RHICOMPL-1561 make account numbers unique

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
The uploads aren't showing properly due to the retention I guess, will file an issue to figure it out and fix it if possible.
>  fix(grafana): RHICOMPL-2097 create a business metrics row

- clowdapp.yaml
- config/initializers/0_clowder-config.rb
Signed-off-by: Victor M <vmugicag@redhat.com>
> feat(Clowder): Add Remediations Clowder config

- app/models/revision.rb
- db/migrate/20210819144533_create_revisions.rb
- db/schema.rb
- test/models/revision_test.rb
This table will hold the latest revision synced by our import-ssg or
import-remediations tasks to determine if a re-sync is necessary or not.
> feat: RHICOMPL-2143 Create table ssg_revisions

- clowdapp.yaml
> feat(clowder): add suffix to each clowderized component

- app/models/xccdf/benchmark.rb
- test/controllers/v1/benchmarks_controller_test.rb
> fix(sorting): RHICOMPL-2177 enable sorting for benchmarks

- app/models/business_objective.rb
- test/controllers/v1/business_objectives_controller_test.rb
> fix(sorting): RHICOMPL-2179 enable sorting for business objectives

- app/models/rule_result.rb
- test/controllers/v1/rule_results_controller_test.rb
> fix(sorting): RHICOMPL-2180 allow sorting rule results

- app/models/profile.rb
- app/services/concerns/xccdf/profiles.rb
- db/migrate/20210830080830_add_upstream_for_profiles.rb
- db/schema.rb
Analogous with https://github.com/RedHatInsights/compliance-backend/pull/982, but for profiles ...
> feat(profiles): RHICOMPL-2080 mark upstream profiles with a new field

- .gitignore
- .rubocop.yml
- app/graphql/schema.rb
- clowdapp.yaml
- config/initializers/sidekiq.rb
- pr_check.sh
- test/test_helper.rb
- unit_test.sh
> feat: RHICOMPL-1362 Run unit tests during pr_check

- app/graphql/types/base_object.rb
- test/graphql/queries/system_query_test.rb
- test/services/duplicate_canonical_profile_resolver_test.rb
Also fixing a legacy warning related to GQL
> Remove unnecessary output from tests

- clowdapp.yaml
This affects sidekiq and import-ssg.
> chore(clowder): Bump up CPU to 800m max for sidekiq/ssg pods

- app/services/dangling_account_remover.rb
- db/migrate/20210831100856_remove_dangling_accounts.rb
- db/schema.rb
- test/services/dangling_account_remover_test.rb
> chore(db): RHICOMPL-2194 remove dangling accounts

- config/initializers/prometheus.rb
This should make exported metrics have the right prefix we expect on the Grafana dashboard graphics.
> fix(metrics): Fix metrics prefix

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
> fix(grafana): Correct CPU resource limit metric name

- app/models/concerns/benchmark_searching.rb
since upstream ssg versions are longer used, we should remove their usage from the code as well
> fix(concerns): RHICOMPL-2112 removed upstream ssg from benchmarks

- unit_test.sh
> fix(clowder): Clean up containers for unit tests

- app/models/concerns/benchmark_searching.rb
- app/models/supported_ssg.rb
- config/supported_ssg.default.yaml
- test/models/benchmark_test.rb
- test/models/supported_ssg_test.rb
> refactor(upstream ssg): RHICOMPL-2267 remove usage of upstream ssgs

- clowdapp.yaml
- config/database.yml
- Sets correctly SSL mode and path to RDS CA cert
- Small refactor of Clowder template
> fix(Clowder): fix Clowder database config 

- clowdapp.yaml
It's `"false"` by default. We'll set it true from within app-interface.
> feat(clowder): RHICOMPL-2288 Parameterize FORCE_IMPORT_SSG

- unit_test.sh
> fix: Remove containers by name in unit_test.sh

- clowdapp.yaml
- pr_check.sh
> feat(Clowder) RHICOMPL-1985 Fix smoke tests

- app/models/revision.rb
- clowdapp.yaml
- lib/tasks/import_datastream.rake
- lib/tasks/import_remediations.rake
- test/models/revision_test.rb
- test/tasks/import_datastream_test.rb
Also contains https://github.com/RedHatInsights/compliance-backend/pull/1013
> feat: RHICOMPL-2145 Use revision table to skip parsing datastreams

- lib/prometheus/engineering_collector.rb
Adds LRU cache on engineering prometheus collector, that mostly
collects dangling items.
This should alleviate hits to database, and should fix database high
load.
> feat(metrics): RHICOMPL-2316 LRU cache dangling items

- clowdapp.yaml
> feat: RHICOMPL-2359 Probes for all services

- clowdapp.yaml
- config/initializers/0_clowder-config.rb
- config/racecar.rb
> feat(Clowder): RHICOMPL-2317 default Kafka settings to enforce SALS_TLS

- unit_test.sh
> fix(Clowder): Use $ghprbPullId for IMAGE_TAG

- app/services/concerns/xccdf/profile_rules.rb
- db/migrate/20211112131735_clear_datastream_revisions.rb
- test/services/concerns/xccdf/profile_rules_test.rb
Once again I'm asking for `SETTINGS__FORCE_IMPORT_SSGS` to be set to `true` in the next deployment.
> cleanup(db): RHICOMPL-2439 reconcile profile-rule relationships

- db/schema.rb
Someone probably forgot to check in the schema after running the migration :thinking:
> chore(db): update the DB schema migration date

- app/services/concerns/xccdf/profiles.rb
- app/services/concerns/xccdf/rules.rb
> fix(ssg_import): RHICOMPL-2491 wrap upstream marking in transactions

- app/models/xccdf/benchmark.rb
- test/models/benchmark_test.rb
Replaces https://github.com/RedHatInsights/compliance-backend/pull/1061
https://www.postgresql.org/docs/14/sql-select.html#SQL-DISTINCT
> feat(Benchmarks): RHICOMPL-2399 all supported profiles for OS major

- .codecov.yml
https://docs.codecov.com/docs/comparing-commits
> fix(codecov): enable coverage offsets

- app/controllers/application_controller.rb
API doesn't really like them, just to have the symmetry with the frontend
> feat(http): RHICOMPL-2389 add CSP/HSTS headers for the API

- db/migrate/20220103131739_reset_revisions_ssg.rb
- db/schema.rb
> fix(migrations): reset revisions again for force import

- Gemfile
- Gemfile.lock
- test/services/ssg_config_downloader_test.rb
- test/test_helper.rb
It should fork processes based on the number of cores on your machine.
> feat(rails): RHICOMPL-1318 enable parallel testing

- docker-compose.yml
> fix(docker): add missing ; to the compose file after echos

- Dockerfile
- Gemfile
- Gemfile.lock
- devel.Dockerfile
- test/test_helper.rb
> chore(ruby): RHICOMPL-2567 bump ruby to v3.0

- test/models/host_test.rb
> fix(tests): RHICOMPL-2584 scoped_search cannot handle negative numbers

- app/producers/notification.rb
- config/initializers/0_clowder-config.rb
- config/settings.yml
- test/producers/notification_test.rb
> feat(notifications): RHICOMPL-2565 implement kafka producer

- app/controllers/concerns/parameters.rb
> fix(REST): RHICOMPL-2585 do not run pundit on nil hosts

- app/graphql/types/system.rb
> fix(ruby3): RHICOMPL-2588 fix missed ruby3 deprecation

- app/models/concerns/host_searching.rb
> fix(hosts): RHICOMPL-2570 Fix ssg version sorting

- Gemfile
- Gemfile.lock
- lib/audit_log/audit_log/formatter.rb
- test/lib/audit_log/formatter_test.rb
> chore(deps): RHICOMPL-2587 upgrade sidekiq to its latest

- devel.json
> fix(clowder): add missing devel config for notifications topic

- .rubocop.yml
- Gemfile.lock
> chore(rubocop): RHICOMPL-2598 Update rubocop-rails to latest version

- Gemfile
- Gemfile.lock
> chore(deps): RHICOMPL-2591 upgrade puma to v5

- config/initializers/prometheus.rb
> fix(metrics): RHICOMPL-2600 increase prometheus thread priority

- app/controllers/concerns/parameters.rb
> fix(rest): RHICOMPL-2601 allow removing all assigned hosts from policy

- clowdapp.yaml
> fix(Clowder): RHICOMPL-2579 Disable liveness/readiness check for jobs

- app/graphql/schema.graphql
- app/graphql/types/os_major_version.rb
- app/graphql/types/profile.rb
- app/models/concerns/profile_cloning.rb
- app/models/os_major_version.rb
- app/models/profile.rb
- app/models/supported_ssg.rb
- app/models/xccdf/benchmark.rb
- test/graphql/queries/os_major_version_query_test.rb
- test/models/os_major_version_test.rb
```
SELECT "profiles".*, "t"."bm_versions" AS "bm_versions" FROM "profiles"
INNER JOIN "benchmarks" ON "profiles"."benchmark_id" = "benchmarks"."id"
INNER JOIN (
SELECT (array_agg("profiles"."id" ORDER BY 
CAST(string_to_array("benchmarks"."version", '.') AS int[]) DESC))[1] as "id", array_agg("benchmarks"."version" ORDER BY 
CAST(string_to_array("benchmarks"."version", '.') AS int[]) DESC) AS bm_versions, "benchmarks"."ref_id" AS bm FROM 
"profiles" INNER JOIN "benchmarks" ON "benchmarks"."id" = "profiles"."benchmark_id" WHERE 
"profiles"."parent_profile_id" IS NULL AND "profiles"."upstream" = FALSE GROUP BY "profiles"."ref_id", 
"benchmarks"."ref_id"
) t ON t.id = profiles.id
WHERE "benchmarks"."ref_id" = $1 AND "profiles"."parent_profile_id" IS NULL AND "profiles"."upstream" = $2
```
- …
> feat(GraphQL): RHICOMPL-2589 include OS versions in osmajor/profiles

- app/models/supported_ssg.rb
> fix(SSG): RHICOMPL-2589 add missing cache invalidation

- Dockerfile
> chore(Dockerfile): RHICOMPL-2623 remove vim and update all packages

- config/environments/development.rb
https://github.com/mperham/sidekiq/wiki/Monitoring#rails
https://guides.rubyonrails.org/api_app.html#using-session-middlewares
> feat(development): enable rails sessions in development for sidekiq

- config/application.rb
- lib/satellite_compensation/middleware.rb
> fix(Satellite): RHICOMPL-2633 set MIME type to nil if empty string

- Gemfile.lock
- test/jobs/delete_host_test.rb
> chore(deps): RHICOMPL-2637 bump sidekiq to 6.4.0

- config/initializers/prometheus.rb
> fix(metrics): RHICOMPL-2582 register the metrics collectors in rails

- config/initializers/prometheus.rb
This reverts commit 7b7b027b81f6efb2b251ff3f499a6d6a262102ce.
> Revert "fix(metrics): RHICOMPL-2582 register the metrics collectors in rails

- Gemfile
- Gemfile.lock
> chore(deps): RHICOMPL-2533 enforce cgi gem is >= 0.3.1

- test/test_helper.rb
> fix(codecov): RHICOMPL-2542 run codecov with GH actions

- app/services/concerns/xccdf/rule_references_rules.rb
> refactor(DatastreamImporter): cleanup rule_references_for

- .github/workflows/ci.yml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
> devel(ci): RHICOMPL-2693 trigger GitHub Actions by Pull Request

- app/services/xccdf_report_parser.rb
> fix(ParseReportJob): RHICOMPL-2702 transaction for missing benchmark

- test/test_helper.rb
- unit_test.sh
> fix(ci): do not try to upload coverage in ephemeral ci

- app/models/concerns/host_searching.rb
- app/models/host.rb
- test/models/host_test.rb
> fix(HostSearching): RHICOMPL-2189 allow ^ operator when looking for OS

- app/models/rule.rb
- app/services/concerns/xccdf/rules.rb
- db/migrate/20220207183019_add_precedence_to_rules.rb
- db/migrate/20220208085557_nullify_revisions.rb
- db/schema.rb
- test/services/concerns/xccdf/rules_test.rb
> feat(SSG): RHICOMPL-1736 record rule order for each imported profile

- Dockerfile
> chore(Dockerfile): RHICOMPL-2297 Remove libtiff and libtiff-devel

- app/graphql/schema.graphql
- app/graphql/types/rule.rb
- app/models/rule.rb
- app/serializers/rule_serializer.rb
- spec/api/v1/schemas/rules.rb
- spec/integration/rules_spec.rb
- swagger/v1/openapi.json
> feat(API): RHICOMPL-2707 expose rule precedence in REST+GQL

- clowdapp.yaml
> fix(metrics): RHICOMPL-2287: Fix Floorist config "resources" indent

- unit_test.sh
> fix(CI): RHICOMPL-2714 set the bundler with(out) via config

- db/migrate/20220210115944_reset_datastream_revisions_again.rb
- db/schema.rb
> fix(stage): reset datastream revisions before forced SSG import

- .github/workflows/ci.yml
- app/controllers/concerns/tag_filtering.rb
- app/models/application_record.rb
- app/models/host.rb
- config/environments/test.rb
Removing dependency on `CODECOV_TOKEN`.
> chore(config): RHICOMPL-2704 Remove dependency on CodeConv token

- app/models/host.rb
- test/models/host_test.rb
> fix(tagging): RHICOMPL-2717 ignore all tagless hosts for tag listing

- app/producers/notification.rb
- test/producers/notification_test.rb
@vkrizan this is to make you happy :wink: there's also a second half that should be merged first https://github.com/RedHatInsights/notifications-backend/pull/1002
> fix(notifications): RHICOMPL-2722 semantically correct messages

- app/services/orphaned_links_remover.rb
- db/migrate/20220214121624_clear_orphaned_profile_rules.rb
- db/schema.rb
- test/services/orphaned_links_remover_test.rb
> chore(db): RHICOMPL-2720 clean up orphaned profile/rule/result links

- app/jobs/parse_report_job.rb
- app/producers/notification.rb
- app/producers/system_non_compliant.rb
- app/services/concerns/xccdf/test_result.rb
- app/services/xccdf_report_parser.rb
- test/jobs/parse_report_job_test.rb
- test/producers/notification_test.rb
- test/producers/system_non_compliant_test.rb
> feat(Notification): RHICOMPL-2563 compliance below threshold email

- app/models/profile.rb
I have no idea what was in my mind when I introduced this piece of code :see_no_evil: 
> fix(Profile): RHICOMPL-2735 load canonical/downstream benchmarks only

- clowdapp.yaml
> fix(clowder): RHICOMPL-2563 request kafka topic for notifications

- clowdapp.yaml
- config/initializers/0_clowder-config.rb
- config/settings.yml
- devel.json
- test/producers/notification_test.rb
- test/producers/system_non_compliant_test.rb
> fix(Notification): RHICOMPL-2563 typo in kafka topic name

- pr_check.sh
- Reduced timeout
- Removed xjoin deploy patch
> Tweaks to pr_check

- app/producers/notification.rb
- app/producers/system_non_compliant.rb
Apparently this is necessary :see_no_evil: 
> fix(Notification): RHICOMPL-2563 double serialize payload and context

- clowdapp.yaml
Needs to be retested after app-interface changes are in to verify that it's faster 
- [x ] Database Security
> feat(clowder): RHICOMPL-2736 extract import-ssg schedule to a param

- app/models/rule.rb
- app/services/concerns/xccdf/rules.rb
- db/migrate/20220222190410_reset_revisions_again_again.rb
- db/schema.rb
- test/services/concerns/xccdf/rules_test.rb
This is a revert of https://github.com/RedHatInsights/compliance-backend/pull/1174 and a restoration of https://github.com/RedHatInsights/compliance-backend/pull/1168. As we deployed, it is safe to again have it in our codebase.
This reverts commit a746fc4b1ce9cb53596a4f19434558b9a82e66dc.
> feat(SSG): RHICOMPL-1736 import rule precedence for all rules

- app/producers/system_non_compliant.rb
> fix(Notification): RHICOMPL-2752 round the score/threshold to 2 digits

- README.md
- app/models/concerns/profile_policy_association.rb
- config/application.rb
> chore(config): RHICOMPL-2561 Enabling has_many inversing

- app/services/supported_ssg_updater.rb
- lib/tasks/import_datastream.rake
- test/fixtures/files/supported_ssg_test.yaml
- test/services/supported_ssg_updater_test.rb
> feat(rake): RHICOMPL-2513 rake task for updating supported ssg fallback

- app/producers/system_non_compliant.rb
PM asked for 1 decimal :see_no_evil: 
> fix(Notification): RHICOMPL-2752 round score/threshold to 1 decimal

- app/controllers/concerns/metadata.rb
> fix(REST): RHICOMPL-2721 Fix REST API links when using v1

- test/factories/benchmark.rb
- test/factories/test_result.rb
- test/graphql/queries/system_query_test.rb
> chore(tests): fix some sporiadic test failures

- app/jobs/concerns/notifications.rb
- app/jobs/parse_report_job.rb
- test/jobs/parse_report_job_test.rb
> fix(notifications): RHICOMPL-2770 count test results for host/profile

- app/jobs/concerns/notifications.rb
> fix(Notifications): Fix a typo in a comment

- app/models/rule.rb
- app/services/concerns/xccdf/rules.rb
- test/services/concerns/xccdf/rules_test.rb
This reverts commit d89a3f831797ed6de8409477cb6ed1031495bb03.
> Revert "feat(SSG): RHICOMPL-1736 import rule precedence for all rules"

- .github/workflows/ci.yml
> feat(CI): RHICOMPL-2781 test the migrations without inventory

- clowdapp.yaml
> fix(RHICOMPL-2787) - Configured import-ssg job specific variables

- spec/api/v1/schemas/hosts.rb
> chore(REST): add missing updated field to host schema definition

- test/services/playbook_downloader_test.rb
Fixes the sporiadic failure at `test/services/playbook_downloader_test.rb:15` by clearing the cache.
> test(PlaybookDownloader): clear the cache between tests

- db/migrate/20220311152114_reset_remediations_revision.rb
- db/schema.rb
> chore(SSG): RHICOMPL-2794 trigger a reimport of remediations

- Gemfile
- Gemfile.lock
- test/test_helper.rb
https://docs.codecov.com/docs/deprecated-uploader-migration-guide#ruby-uploader
> devel(coverage): RHICOMPL-2800 drop the deprecated codecov uploader

- app/services/concerns/xccdf/profile_rules.rb
Wins us ~15 seconds on the import, which makes it possible to run in less than 3 minutes :zap: analogous with https://github.com/RedHatInsights/compliance-backend/pull/1218
> refactor(SSG): RHICOMPL-2810 do not query ProfileRules when importing

- pr_check.sh
> config(RHICOMPL-2811): Set insights-stage as target ref_env

- app/producers/report_upload_failed.rb
Analogous with [this](https://github.com/RedHatInsights/compliance-backend/blob/9a8c6c99e946be0013a225c679246d1f21574e44/app/producers/system_non_compliant.rb#L18)
> fix(Notification): RHICOMPL-2813 add missing to_json to payload

- app/consumers/concerns/report_parsing.rb
- app/consumers/concerns/validation.rb
- test/consumers/inventory_events_consumer_test.rb
> fix(PayloadTracker): RHICOMPL-814 pass request_id to messages

- app/producers/application_producer.rb
- app/producers/payload_tracker.rb
After a discussion with the team that maintains this microservice, we determined that their expected date format is different from what any other service expects from us.
> fix(PayloadTracker): RHICOMPL-814 send the corrent date format

- app/producers/application_producer.rb
> fix(kafka): RHICOMPL-814 emit timestamps always in UTC

- app/models/concerns/host_searching.rb
- test/graphql/queries/system_query_test.rb
In order to test this you can have a seeded DB + you need to retrieve a policy_id from the address bar on the frontend:
```bash
curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XPOST -d ' 
{               
"operationName": "getSystems",
"variables": {
"perPage": 50,
"page": 1,
"filter": "(policy_id = f5a5fb55-751c-4300-bd4c-57f1e00215d0) and (ssg_version !^ (0.1.57, 0.1.68))",
"policyId": "f5a5fb55-751c-4300-bd4c-57f1e00215d0"
},
"query": "query getSystems($filter: String!, $policyId: ID, $perPage: Int, $page: Int, $sortBy: [String!], $tags: [String!]) {
systems(
search: $filter
limit: $perPage
offset: $page
sortBy: $sortBy
tags: $tags
) {
totalCount
edges {
node {
id
name
testResultProfiles(policyId: $policyId) {
id
name
}
policies(policyId: $policyId) {
id
name
}
} …
```
> feat(GraphQL): RHICOMPL-2831 implement host searching by SSG version

- app/consumers/concerns/report_parsing.rb
- test/consumers/inventory_events_consumer_test.rb
> fix(Notification): RHICOMPL-2825 removed hosts don't need notifications

- clowdapp.yaml
- pr_check.sh
- scripts/abort_if_pending_migrations.sh
- scripts/check_migration_status_and_ssg_synced.sh
> [RHICOMPL-2815] Patch clowdapp

- Gemfile.lock
> fix(dependencies): RHICOMPL-2820 update rswag-ui and rswag-api

- app/producers/system_non_compliant.rb
> fix(Notification): RHICOMPL-2782 send the pseudo policy ID to kafka

- app/services/xccdf_report_parser.rb
- test/services/xccdf_report_parser_test.rb
> perf(ReportParser): RHICOMPL-2846 import missing BMs for RHEL6 only

- pr_check.sh
After https://github.com/RedHatInsights/bonfire/commit/a5786c0d9337a8b95541e91825b77b6a1ad29d58 seems we don't need a custom timeout value anymore.
> patch(RHICOMPL-2815): Remove custom deployment timeout value

- app/models/concerns/rule_remediation.rb
- spec/api/v1/schemas/rules.rb
- swagger/v1/openapi.json
- test/controllers/v1/rules_controller_test.rb
- test/models/rule_test.rb
> fix(RHICOMPL-2851): nullify remediation_issue_id if no remediation

- clowdapp.yaml
> clowder(RHICOMPL-2776): Force Rolling Update deployment strategy

- lib/tasks/import_datastream.rake
- test/tasks/import_datastream_test.rb
> feat(SSG): RHICOMPL-2806 Abort check_synced if remediations fail

- test/models/rule_test.rb
> chore(tests): replace assert(x,nil) with assert_nil

- app/consumers/concerns/report_parsing.rb
- app/jobs/parse_report_job.rb
- app/producers/report_upload_failed.rb
- test/consumers/inventory_events_consumer_test.rb
- test/jobs/parse_report_job_test.rb
- test/producers/report_upload_failed_test.rb
This can help us in the future with tracking the uploaded report in the Payload Tracker.
> feat(RHICOMPL-2816): include request_id in notification payloads

- docker-compose.yml
Changed in https://github.com/RedHatInsights/insights-rbac/pull/660
Solves: https://issues.redhat.com/browse/RHICOMPL-2866
> fix(compose): RHICOMPL-2866 Update RBAC migration command

- .github/workflows/ci.yml
> Add commit linter

- config/devel/rbac/definitions.json
- config/devel/rbac/permissions.json
continuation of: https://github.com/RedHatInsights/compliance-backend/pull/1236
> feat(RBAC): RHICOMPL-2710 Granular RBAC permissions

- .commitlint.yml
> fix(commitlint): RHICOMPL-2850 Fix regex to support no ticket reference

- app/models/policy.rb
- app/models/policy_host.rb
- app/models/xccdf/benchmark.rb
- spec/integration/systems_spec.rb
- test/controllers/v1/profiles_controller_test.rb
- test/controllers/v1/systems_controller_test.rb
- test/graphql/mutations/associate_profiles_test.rb
- test/graphql/mutations/associate_systems_test.rb
- test/graphql/mutations/delete_test_result_mutation_test.rb
- test/graphql/mutations/edit_policy_mutation_test.rb
- test/graphql/queries/profile_query_test.rb
- test/graphql/queries/system_query_test.rb
- test/lib/prometheus/business_collector_test.rb
- test/models/benchmark_test.rb
- test/models/host_test.rb
- test/models/policy_host_test.rb
- test/models/policy_test.rb
- test/models/profile_test.rb
- test/policies/profile_policy_test.rb
- test/services/concerns/xccdf/benchmarks_test.rb
- test/services/dangling_account_remover_test.rb
- test/services/upstream_rule_bindings_remover_test.rb
- test/services/xccdf_report_parser_test.rb
> feat(PolicyHost): RHICOMPL-2830 Check if host is supported

- app/services/ssg_config_downloader.rb
> feat(SsgConfigDownloader): RHICOMPL-2856 store SSG YAMLs in tmp

- clowdapp.yaml
> perf(clowder): increase CPU limit for SSG import to 1000m

- .commitlint.yml
> ci(commitlint): allow the 'cleanup' type prefix

- pr_check.sh
> ci(pr_check): RHICOMPL-2896 - Submit pr_check runs to Ibutsu

- app/graphql/mutations/business_objective/create.rb
- app/policies/business_objective_policy.rb
- app/services/duplicate_business_objective_resolver.rb
- db/migrate/20220127054239_deduplicate_business_objectives.rb
- test/graphql/mutations/create_business_objective_mutation_test.rb
- test/services/duplicate_business_objective_resolver_test.rb
> fix(BusinessObjective): RHICOMPL-874 prevent duplications

- scripts/set_cgroup_limits.sh
> fix(entrypoint): RHICOMPL-2858 cgroups script to work locally 😅😅

- .dockerignore
- .gemrc.prod
- Dockerfile
- config/puma.cfg
- entrypoint.sh
- scripts/fix-permissions
- unit_test.sh
Old size: 1.12GB
New size: 595MB
> chore(Dockerfile): RHICOMPL-1369 use the minimal ubi8 image

- app/models/concerns/host_searching.rb
- test/controllers/v1/systems_controller_test.rb
- test/graphql/queries/system_query_test.rb
> feat(API): RHICOMPL-2934 filtering by stale timestamp

- app/graphql/types/system.rb
- test/graphql/queries/system_query_test.rb
> perf(GraphQL): RHICOMPL-2928 preload last scanned for hosts

- db/migrate/20220513090623_org_id_to_accounts.rb
- db/schema.rb
> feat(DB): RHICOMPL-2959 introduce the org_id column

- app/controllers/concerns/authentication.rb
- app/models/user.rb
- test/controllers/concerns/authentication_test.rb
> fix(rbac): RHICOMPL-2955 pass the original identity header

- app/services/concerns/xccdf/rule_groups.rb
- db/migrate/20220511212358_clear_revisions_may_eleventh.rb
- test/services/concerns/xccdf/rule_groups_test.rb
> fix(RuleGroups): RHICOMPL-2956 update ancestry for rule groups correctly

- app/models/user.rb
- test/models/user_test.rb
> cleanup(model): drop dead code from the User model

- app/models/account.rb
- test/models/account_test.rb
> feat(auth): RHICOMPL-2960 store org_id when looking up accounts

- app/graphql/types/interfaces/rules_preload.rb
- app/models/concerns/profile_rules.rb
- app/models/concerns/rule_remediation.rb
- app/models/concerns/short_ref_id.rb
- test/models/rule_test.rb
Fixes the remediation issue ID in GraphQL.
> fix(remediations): RHICOMPL-2870 pass profile_ref_id for rules

- clowdapp.yaml
> feat(db): RHICOMPL-2970 define the job for org_id translation

- app/consumers/concerns/report_parsing.rb
- app/consumers/concerns/validation.rb
- app/consumers/inventory_events_consumer.rb
- app/jobs/concerns/notifications.rb
- app/jobs/parse_report_job.rb
- app/producers/notification.rb
- app/producers/payload_tracker.rb
- test/consumers/inventory_events_consumer_test.rb
- test/factories/account.rb
- test/jobs/parse_report_job_test.rb
- test/models/account_test.rb
- test/producers/notification_test.rb
- test/producers/payload_tracker_test.rb
- test/producers/report_upload_failed_test.rb
- test/producers/system_non_compliant_test.rb
> feat(kafka): RHICOMPL-2963 forward org_id in jobs/producers/consumers

- app/services/orphaned_profiles_cleaner.rb
- db/migrate/20220525104102_cleanup_orphaned_profiles.rb
- db/schema.rb
- test/services/orphaned_profiles_cleaner_test.rb
> fix(profiles): RHICOMPL-2989 drop profiles without policy

- Dockerfile
- unit_test.sh
> chore(Dockerfile): RHICOMPL-2996 upgrade base image to ubi9-minimal

- clowdapp.yaml
https://github.com/RedHatInsights/tenant-utils/blob/65d2ec6a2f097d38ec627699d02e8a07f6ca8957/cmd/org-id-column-populator/main.go#L106
https://github.com/RedHatInsights/tenant-utils/blob/main/cmd/org-id-column-populator/README.md#possible-errors
> fix(clowder): RHICOMPL-2970 adjust timeout for EAN translation

- app/jobs/concerns/notifications.rb
- app/services/concerns/xccdf/test_result.rb
- test/jobs/parse_report_job_test.rb
> fix(notification): RHICOMPL-2994 do not emit for unsupported hosts

- app/graphql/types/query.rb
> fix(RBAC): RHICOMPL-2998 enforce read permission on GraphQL query type

- app/controllers/v1/profiles_controller.rb
- test/controllers/v1/profiles_controller_test.rb
> fix(rbac): RHICOMPL-3016 cover tailoring_file with compliance:read

- app/graphql/types/interfaces/rules_preload.rb
> perf(RuleIdentifier): RHICOMPL-3004 preload using lookahead in GQL

- README.md
> dev(README): Empty commit to bump the build of a new container image

- Dockerfile
> fix(Dockerfile): RHICOMPL-2996 make the tmp/log folders sticky

- Dockerfile
> fix(Dockerfile): RHICOMPL-2996 make tmp/log folders writable

- deploy/build-deploy-common.sh
Fixes a bug on the function that detects whether if the script is being run by the CI system.
> RHICOMPL-3020 fix detect-ci-runner 

- clowdapp.yaml
- config/environments/production.rb
> dev(logging): RHICOMPL-3004 parametrize LOG_LEVEL for Rails logging

- config/devel/rbac/definitions.json
To be up-to-date with Stage & Prod environment:
https://github.com/RedHatInsights/rbac-config/pull/285
https://github.com/RedHatInsights/rbac-config/pull/264
> feat(RBAC): RHICOMPL-2710 allow read remediation permission for all roles

- app/controllers/v1/profiles_controller.rb
- test/integration/routes_test.rb
> test(RBAC): RHICOMPL-3017 test API routes are covered with RBAC enforcement

- clowdapp.yaml
> cleanup(clowdapp): remove the obsolete org-id translation job

- app/graphql/collection_loader.rb
- app/graphql/types/interfaces/rules_preload.rb
- app/models/concerns/profile_rules.rb
- app/models/concerns/rule_remediation.rb
- app/models/concerns/short_ref_id.rb
- test/models/rule_test.rb
A little bit more speed I hope :zap: had to revert the remediation issue ID determinization in order to make this work. It is not being consumed by the frontend at this moment and I recreated the ticket for the backend part.
> fix(CollectionLoader): RHICOMPL-3025 add missing call on preloading

- app/graphql/types/interfaces/rules_preload.rb
Saves additional 2 seconds :pray: 
> perf(RulesPreload): RHICOMPL-3025 do not include rule identifiers

- app/controllers/application_controller.rb
- app/controllers/concerns/authentication.rb
- test/controllers/openapi_endopoint_test.rb
> fix(RBAC): RHICOMPL-3053 fix constant

- app/controllers/concerns/authentication.rb
- app/controllers/concerns/exception_notifier_custom_data.rb
- test/controllers/concerns/exception_notifier_custom_data_test.rb
>  feat(logging): RHICOMPL-3048 use org_id for logging 

- app/services/supported_remediations.rb
- lib/tasks/import_datastream.rake
- test/services/supported_remediations_test.rb
- test/tasks/import_datastream_test.rb
> feat(Remediations): RHICOMPL-3018 Update revision comparison 

- app/graphql/schema.graphql
- app/graphql/types/interfaces/rules_preload.rb
- app/graphql/types/profile.rb
- app/graphql/types/rule.rb
- app/models/concerns/profile_searching.rb
- app/models/rule_result.rb
- app/models/test_result.rb
- test/graphql/queries/profile_query_test.rb
```
// Listing profiles by profile/policy ID (result is always one entity, but it has to be an array for now)
query getProfiles($filter: String!, $policyId: ID!, $perPage: Int, $page: Int, $sortBy: [String!]) {
profiles(
search: $filter,
limit: $perPage
offset: $page
sortBy: $sortBy
) {
totalCount
edges {
node {
id
hosts { // listing all hosts, not just the reporting ones
id
testResultProfiles(policyId: $policyId) { // non reporting hosts have this empty
... // except rules
}
}
failingRules(policyId: $policyId) { // ordered backwards
id
title
failedCount // how many times this rule failed
identifier
}
}
}
}
}
```
> feat(GQL): RHICOMPL-3057 listing top failed rules for PDF reporting

- app/models/concerns/host_searching.rb
- test/graphql/queries/system_query_test.rb
The `getSystems` query with `testResultProfiles` can now handle filtering by `supported_ssg` or `reported` boolean values.
> feat(GQL): RHICOMPL-2995 filter by unsupported/unreported hosts

- app/graphql/types/test_result.rb
- app/services/rbac.rb
- config/devel/rbac/definitions.json
- config/devel/rbac/permissions.json
- docker-compose.yml
> cleanup(RBAC): RHICOMPL-3067 remove Compliance reporter role

- app/graphql/types/interfaces/rules_preload.rb
> fix(GraphQL): RHICOMPL-3057 load topFailedRules only for supported

- Dockerfile
> fix(Dockerfile): RHICOMPL-3064 ssg import liveness probe needs pgrep

- app/graphql/types/interfaces/rules_preload.rb
Not needed, the issue was elsewhere...
This reverts commit 1ee777aec0c083546733ece32741e61a54655ea1.
> revert(GraphQL): RHICOMPL-3057 load topFailedRules only for supported

- .github/workflows/ci.yml
> dev(CI): run zeitwerk check in gh actions static analysis

- app/controllers/application_controller.rb
- test/controllers/v1/systems_controller_test.rb
> fix(REST): RHICOMPL-380 invalid search param should return 422

- app/controllers/application_controller.rb
- app/controllers/concerns/collection.rb
- app/controllers/concerns/metadata.rb
- app/controllers/concerns/pagination.rb
- app/controllers/concerns/parameters.rb
- app/controllers/concerns/v1/profile_attributes.rb
- app/controllers/v1/benchmarks_controller.rb
- app/controllers/v1/business_objectives_controller.rb
- app/controllers/v1/profiles_controller.rb
- app/controllers/v1/rules_controller.rb
- app/controllers/v1/systems_controller.rb
- spec/integration/profiles_spec.rb
- test/controllers/v1/systems_controller_test.rb
> feat(REST): RHICOMPL-478 stricter HTTP params consumption

- clowdapp.yaml
FloorPlan is managed by Floorist Operator with dynamic schedule.
Note, that this is not intended to be tested on ephemeral environments yet.
RHICOMPL-3088
> feat(deploy): use FloorPlan CR instead of floorist

- test/policies/host_policy_test.rb
> dev(tests): RHICOMPL-3102 append missing org_id for pundit test

- pr_check.sh
> fix(CI): RHICOMPL-3109 prevent RBAC resources from being removed

- app/models/concerns/profile_searching.rb
> fix(search): RHICOMPL-1324 make profile search implicit on strings

- clowdapp.yaml
> cleanup(clowdapp): RHICOMPL-3110 clean up floorist artifacts

- clowdapp.yaml
> fix(clowdapp): RHICOMPL-2990 add ability to ignore min three replica

- config/environments/development.rb
- config/environments/test.rb
- docker-compose.yml
- lib/audit_log/audit_log.rb
https://issues.redhat.com/browse/RHICOMPL-3120
> Store Rails logfiles in tmpfs, impose a 64MB file size limit on them

- lib/satellite_compensation/middleware.rb
JIRA ticket TBD
https://github.com/theforeman/foreman_rh_cloud/blob/d995c7479152daca552960983a2aa8c330361890/app/services/foreman_rh_cloud/cloud_request_forwarder.rb#L54
> fix(REST): RHICOMPL-3124 remove branch_id parameter coming from Sat

- .github/workflows/ci.yml
- clowdapp-minimal.yaml
To test this, you should adjust your `.config/bonfire/config.yaml` according to the [documentation](https://github.com/RedHatInsights/bonfire#deploy-app-template-using-changes-youve-made-in-a-remote-git-branch) to point to your local fork of compliance-backend containing this PR, e.g.:
```yaml
apps:
- name: compliance_minimal
components:
- name: service
host: local
repo: ~/Repositories/Insights/compliance-backend
path: /clowdapp-minimal.yaml
```
Then deploy this newly defined service with bonfire:
```
bonfire deploy compliance_minimal --source=appsre --ref-env insights-stage --timeout 900 --optional-deps-method hybrid --no-remove-resources compliance 
```
You can observe that after the deployment, only the dependencies are available, pods/jobs related to compliance are missing.
- …
> feat(Clowder): RHICOMPL-3141 minified template for development

- pr_check.sh
- unit_test.sh
- add trace flag to unit_test.sh script call from pr_check
- replace docker with podman for unit_test.sh
> fix(tests): RHICOMPL-3147 unit_test.sh fix for RHEL8

- app/services/xccdf_report_parser.rb
> fix(ReportParser): RHICOMPL-3149 replace missing account# with org_id

- lib/prometheus/business_collector.rb
- test/lib/prometheus/business_collector_test.rb
> fix(Metrics): RHICOMPL-2965 dump org_id instead of account_number

- app/producers/application_producer.rb
- config/initializers/0_clowder-config.rb
- config/racecar.rb
- test/producers/application_producer_test.rb
> feat(kafka): RHICOMPL-3024 parametrize kafka auth protocol/mechanism

- config/settings.yml
> cleanup(settings): RHICOMPL-1017 CI-related entries with local ones

- clowdapp.yaml
> fix(clowder): RHICOMPL-2648 provide the secret for slack notifications

- config/puma.rb
> chore(puma): RHICOMPL-3059 add Puma restart/shutdown hooks

- clowdapp.yaml
> cleanup(clowder): RHICOMPL-1978 mark SECRET_KEY_BASE as a placeholder

- config/environments/production.rb
> fix(caching): RHICOMPL-3178 override of Rails.cache to use Redis

- clowdapp.yaml
> feat(clowder): RHICOMPL-2627 expose redis cache to all pods/jobs

- app/models/profile.rb
- config/puma.rb
- test/models/profile_test.rb
This is debug code that will only be merged to stage so that we can get a little more details in the logs when we reproduce the 502 error for this ticket: https://issues.redhat.com/browse/RHICOMPL-3059
The logs don't give much info as of now.
> fix(GraphQL): RHICOMPL-3059 Add debug code to check cached values

- app/models/supported_ssg.rb
- lib/tasks/import_datastream.rake
- test/models/supported_ssg_test.rb
> feat(caching): RHICOMPL-2627 cache SSG datastream content in redis

- app/models/supported_ssg.rb
- app/services/ssg_config_downloader.rb
This is just a temporary fix, to unblock stage from failing on 5xx errors, should be cleaned up later.
> fix(ssg): RHICOMPL-2627 download the SSG config if unavailable

- Gemfile.lock
> fix(deps): RHICOMPL-2648 update slack-notifier for ruby 3 compat

- clowdapp-minimal.yaml
- clowdapp.yaml
> feat(clowdapp): RHICOMPL-1978 consume SECRET_KEY_BASE from a secret

- app/models/profile.rb
- config/puma.rb
- test/models/profile_test.rb
> chore(cleanup): RHICOMPL-3059 remove debug code

- clowdapp.yaml
- config/puma.cfg
Let's do some benchmark with this and see how it performs on stage.
> perf(clowder): RHICOMPL-3194 reduce the count of puma workers to 2

- clowdapp-minimal.yaml
> fix(clowdapp): adjust clowdapp-minimal template to make CI happy

- clowdapp-minimal.yaml
- clowdapp.yaml
> perf(clowder): RHICOMPL-3194 increase memory limit for rails

- db/migrate/20210831100856_remove_dangling_accounts.rb
- db/migrate/20211104070445_delete_upstream_profiles.rb
Should fix the migration issues when setting up ephemeral...
> fix(migrations): comment out some org_id related migrations

- .github/pull_request_template.md
> fix(github): precheck the secure coding checklist

- app/services/openshift_environment.rb
- clowdapp.yaml
> fix(SlackNotify): RHICOMPL-3189 pass missing information to pods

- app/controllers/application_controller.rb
Throwing 422 exception if the pagination is over the bounds of a BIGINT.
> fix(pagination): RHICOMPL-3190 rescue from RangeError

- app/graphql/schema.graphql
- app/graphql/types/rule.rb
> perf(GraphQL): RHICOMPL-3176 drop unused remediationIssueId field

- app/graphql/types/profile.rb
- test/graphql/queries/profile_query_test.rb
**Before:**
```
Completed 200 OK in 723ms (Views: 0.9ms | ActiveRecord: 25.0ms | Allocations: 638229)
```
**After:**
```
Completed 200 OK in 610ms (Views: 0.9ms | ActiveRecord: 22.9ms | Allocations: 500235)
```
With the query:
```bash
time curl -k -H "Content-Type: application/json" -H "X-RH-IDENTITY: $RHI" -XPOST -d '{
"operationName": "supportedProfilesByOSMajor",
"variables": {},
"query": "query supportedProfilesByOSMajor {
osMajorVersions {
edges {
node {
osMajorVersion
profiles {
id
name
refId
description
complianceThreshold
supportedOsVersions
benchmark {
id
refId
osMajorVersion
}
}
}
}
}
profiles(search: \"external = false and canonical = false\") {
edges {
node {
id
refId
benchmark {
refId
}
}
}
}
}"
}' "http://localhost:3000/api/compliance/graphql" | jq
```
Should help with other …
> perf(GQL): RHICOMPL-3176 preload benchmarks under profiles

- .github/labeler.yml
- .github/workflows/labeler.yml
> ci(labeller): RHICOMPL-3202 label PRs that update GraphQL files

- config/puma.cfg
https://github.com/puma/puma/blob/15b079439222e489915380021b9dca7b9fa5ff65/5.0-Upgrade.md#nakayoshi_fork
https://www.rubydoc.info/gems/puma/Puma%2FDSL:preload_app!
> perf(puma): enable nakayoshi fork and CoW preloading

- clowdapp.yaml
Extending https://github.com/RedHatInsights/compliance-backend/pull/1410 to sidekiq and racecar
> perf(clowder): RHICOMPL-3220 malloc arena limit for sidekiq/racecar

- clowdapp-minimal.yaml
- clowdapp.yaml
> chore(cleanup): remove unused floorist props

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
Fixes the following metrics in our stage grafana:
> fix(metrics): RHICOMPL-3219 adjust some grafana queries

- Dockerfile
Accidentally introduced by https://github.com/RedHatInsights/compliance-backend/pull/1414
> cleanup(Dockerfile): RHICOMPL-3219 drop zlib-devel as a dependency

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
> fix(grafana): RHICOMPL-2582 fix some broken grafana widgets

- clowdapp-minimal.yaml
- clowdapp.yaml
- config/puma.rb
> perf(clowder): RHICOMPL-3222 preallocate threads for puma

- clowdapp.yaml
Hoping that this will speed up report parsing significantly. If it doesn't help, we also have to revert it for sidekiq.
@vkrizan seems like you were right :see_no_evil: 
> revert(clowder): RHICOMPL-3220 drop MALLOC_ARENA_MAX for racecar

- config/puma.cfg
- config/puma.rb
> fix(puma): RHICOMPL-3223 make the puma control socket path static

- config/puma.cfg
- config/puma.rb
> cleanup(metrics): RHICOMPL-3223 do not collect puma metrics

- clowdapp-minimal.yaml
- clowdapp.yaml
> perf(clowder): RHICOMPL-3222 reduce the number of puma threads to 3

- Gemfile
- app/consumers/application_consumer.rb
> fix(Gemfile): RHICOMPL-3217 do not load racecar when booting rails

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
Fixes Grafana dashboard expressions on Latency and GraphQL performance graphs.
> fix(grafana): latency and graphql expressions

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
> fix(grafana): pull RDS metrics properly in stage

- app/controllers/graphql_controller.rb
> dev(GraphQL): fix exception handling for requests in development

- db/seeds.dev.rb
- test/factories/host.rb
> dev(seeds): create each system with 5 random tags

- lib/audit_log/audit_log.rb
- lib/audit_log/audit_log/formatter.rb
- test/lib/audit_log/audit_log_test.rb
- test/lib/audit_log/formatter_test.rb
- test/lib/audit_log/middleware_test.rb
- test/lib/audit_log/wrapped_logger_test.rb
> cleanup(logging): RHICOMPL-2965 adjust org_id in audit logging

- docker-compose.yml
- spec/integration/benchmarks_spec.rb
- spec/integration/profiles_spec.rb
- swagger/v1/openapi.json
`podman-compose exec rails bundle exec rake rswag:specs:swaggerize`
> feat(OpenAPI): RHICOMPL-2077 rswag generator

- spec/integration/profiles_spec.rb
- swagger/v1/openapi.json
> docs(OpenAPI): RHICOMPL-3255 remove obsolete 'name' attribute

- app/producers/application_producer.rb
- config/racecar.rb
> fix(kafka): RHICOMPL-3258 allow SASL/SSL without CA certificate

- app/models/supported_ssg.rb
- lib/tasks/import_datastream.rake
- test/tasks/import_datastream_test.rb
> fix(SSG): RHICOMPL-3259 do not cache but memoize SupportedSSg.revision

- clowdapp-minimal.yaml
- clowdapp.yaml
> feat(clowder): RHICOMPL-3257 add pdf-generator as an optionalDependency

- config/initializers/0_clowder-config.rb
> fix(kafka): RHICOMPL-3258 do not create CA file when unavailable

- app/producers/application_producer.rb
> fix(kafka): RHICOMPL-3258 prefix config params for producer

- app/producers/application_producer.rb
> fix(kafka): RHICOMPL-3258 PLAIN doesn't need a mechanism

- app/producers/application_producer.rb
- test/producers/application_producer_test.rb
> fix(kafka): RHICOMPL-3258 producer to use system's CA certs

- .gitignore
> dev(gitignore): Add Pry configuration into .gitignore

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
> feat(grafana): RHICOMPL-3262 additional metrics for REST endpoints

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
> fix(grafana): RHICOMPL-3273 bump version

- app/controllers/concerns/parameters.rb
- app/graphql/resolvers/concerns/collection.rb
- test/controllers/concerns/collection_test.rb
- test/controllers/concerns/metadata_test.rb
- test/graphql/resolvers/collection_test.rb
> perf(pagination): RHICOMPL-3267 impose limit 100 on pagination

- app/graphql/resolvers/concerns/collection.rb
- test/graphql/resolvers/collection_test.rb
> revert(GraphQL): RHICOMPL-3279 do not limit pagination for GQL yet

- app/models/supported_ssg.rb
- app/services/datastream_downloader.rb
- app/services/ssg_config_downloader.rb
> fix(SSG): RHICOMPL-3277 bypass caching when downloading datastreams

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
> fix(grafana): adjust consumer lag query for managed kafka

- docker-compose.yml
> fix(Rbac): RHICOMPL-3195 fix mapping for rbac files

- lib/satellite_compensation/middleware.rb
> fix(satellite): RHICOMPL-3286 extend compensation middleware condition

- app/controllers/application_controller.rb
- app/services/rbac.rb
- test/controllers/openapi_endopoint_test.rb
> fix(RBAC): RHICOMPL-3216 handle authorization exception

- Gemfile
- Gemfile.lock
- spec/swagger_helper.rb
https://github.com/RedHatInsights/insights-rbac-api-client-ruby/pull/11
> cleanup(RBAC): Remove workaround of setting header

- app/serializers/rule_reference_serializer.rb
- app/serializers/rule_serializer.rb
- spec/api/v1/schemas/rules.rb
- swagger/v1/openapi.json
@LightOfHeaven1994 this will probably break the integration tests, but it affects our API responses just minimally by omitting something useless. However, the performance of the `/api/v1/rules` endpoint should be twice as fast at least.
> perf(REST): RHICOMPL-3315 do not serialize rule references

- app/controllers/v1/rules_controller.rb
- app/models/rule.rb
- app/policies/rule_policy.rb
> perf(RulesPolicy): RHICOMPL-3301 load authorized rules using a join

- app/controllers/application_controller.rb
- app/models/identity_header.rb
- config/initializers/yabeda.rb
> feat(metrics): RHICOMPL-3350 pass the org_id with collected metrics

- dashboards/grafana-dashboard-insights-compliance-general.configmap.yaml
> feat(grafana): RHICOMPL-3350 optional filtering of IQE-involved metrics in our charts

- dashboards/grafana-dashboard-insights-compliance-general.template.yaml
> fix(grafana): RHICOMPL-3350 adjust grafana template

- app/jobs/delete_host.rb
- app/jobs/parse_report_job.rb
Similar to https://github.com/RedHatInsights/compliance-backend/pull/1480 but for sidekiq
> feat(metrics): RHICOMPL-3350 pass the org_id with sidekiq as a tag

- dashboards/grafana-dashboard-insights-compliance-general.template.yaml
> RHICOMPL-3350: additional adjustments to the grafana dashboard

- app/controllers/concerns/rendering.rb
https://apidock.com/rails/v5.2.3/ActiveRecord/QueryMethods/references
> perf(REST): RHICOMPL-3361 preload associations more efficiently

- dashboards/grafana-dashboard-insights-compliance-general.template.yaml
> feat(grafana): RHICOMPL-3350 opt-exclude IQE stats from counters

- app/controllers/application_controller.rb
- app/jobs/delete_host.rb
- app/jobs/parse_report_job.rb
- app/services/openshift_environment.rb
- config/initializers/yabeda.rb
- dashboards/grafana-dashboard-insights-compliance-general.template.yaml
> perf(metrics): RHICOMPL-3368 mark IQE triggered requests

- app/graphql/types/concerns/test_results.rb
- app/graphql/types/profile.rb
- app/models/test_result.rb
Tried the following query with 600 systems:
```
{
"operationName": "supportedProfilesByOSMajor",
"variables": { "perPage": 500,  "page": 1, "tagsColumn": null, "filter": "(policy_id = f9d3fe39-e586-4ef8-a863-deea6e70577d)",  "policyId": "f9d3fe39-e586-4ef8-a863-deea6e70577d" },
"query": "
query getSystems(
$filter: String!
$policyId: ID
$perPage: Int
$page: Int
$sortBy: [String!]
$tags: [String!]
) {
systems(
search: $filter
limit: $perPage
offset: $page
sortBy: $sortBy
tags: $tags
) {
totalCount
edges {
node {
id
name
osMajorVersion
osMinorVersion
insightsId
testResultProfiles(policyId: $policyId) {
lastScanned
compliant
score
supported
benchmark {
version
}
rulesFailed
}
}
}
}
}"
}
```
Before:
```
Completed 200 OK in 7270ms (Views: 3.6ms | ActiveRecord: 484.2ms | Allocations: 6130762) …
```
> perf(GQL): RHICOMPL-3218 batch-load rule-result related fields

- spec/swagger_helper.rb
- swagger/v1/openapi.json
> docs(OpenAPI): RHICOMPL-3330 broader specification for tags format

- dashboards/grafana-dashboard-insights-compliance-general.template.yaml
> fix(grafana): RHICOMPL-3376 added missing parentheses in sidekiq query

- test/controllers/v1/profiles_controller_test.rb
Lorem ipsum has enough A letters to have this sporiadically :see_no_evil: 
> fix(test): RHICOMPL-3365 make profile name generation deterministic
